### ISSUE TITLE
Chart.js in pip package didn't upgraded to 2.7.2

### ISSUE THREAD

**Issue by fanthos** [home-assistant/home-assistant-polymer#1000]
I found that in some case the history chart may freeze. After some dig, found that the version of Chart.js to built is 2.7.1 instead of 2.7.2 in `bower.json`.
I tried to build the frontend with `./script/bootstrap` and check the output, the version of Chart.js is 2.7.2.

**Comment by balloob** [comment]
My bad, that means I didn't update dependencies locally. Pushing a new build to dev.
