### ISSUE TITLE
Breaking changes in material design icons

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#1003]
MDI will release in a month some breaking changes to their icon names. They are changing the names of icons that are named after brands instead of the actual product. For example, nest will be called thermostat and roomba will be renamed to robot-vacuum.

We need to:
 - figure out the changes
 - mention it in our breaking changes release notes
 - make sure our domain and state icons are not broken

**Comment by balloob** [comment]
Material Design Icons commits for the renames have just landed and will be released as 2.3. Thanks to @Templarian for the heads up.

Renames that will impact our users:

- "nest" to "thermostat"
- "nest-protect" to "smoke-detector"
- "roomba" to "robot-vacuum" (there is also a new "robot-vacuum-variant" that looks like neato)

We should update our code and list this in breaking changes for next release.

**Comment by Templarian** [comment]
You could alias them or throwing a warning or something about the rename. Not sure the best approach.

These renames are rare, but we've decided since there are too many brands for home automation products we'll only be using generic names from now on (this also means keeping the IoT icons more general).

**Comment by NovapaX** [comment]
Is there (or will there be) a summary of the (breaking) changes for that release?
I've looked around at the mdi repo but could not find one. But maybe I looked in the wrong place.

That way we can point our users to that list from the release notes, and it will also make it easier to scan our code for all 'breaking' icons.

**Comment by Templarian** [comment]
@NovapaX https://materialdesignicons.com/history (our dev site is much improved for this view, but not launched yet http://dev.materialdesignicons.com/history).

**Comment by Templarian** [comment]
http://templarian.com/2018/04/18/material-design-icons-v2-3-50/

`v2.3.50` released a few hours ago. Of the 107 new icons there are quite a few new ones.
