### ISSUE TITLE
Legend list item visible after graph update

### ISSUE THREAD

**Issue by corneyl** [home-assistant/home-assistant-polymer#1008]
The list item dots are visible on a graph, after they are updated. I then looks like this:

![image](https://user-images.githubusercontent.com/5320363/37654176-8ae90372-2c41-11e8-9373-f0455009a767.png)

Instead of:

![image](https://user-images.githubusercontent.com/5320363/37654315-f26bdc68-2c41-11e8-8cbf-116a5d79a21d.png)

So the extra black dots shouldn't be there. Looks like a missing class of the list elements.

**Comment by NovapaX** [comment]
I can not reproduce this.
What browser is that? What version of Home-Assistant are you on?

**Comment by corneyl** [comment]
HA 0.65.3, FireFox 59.0 (64-bit). The problem started since the new chart.js charts were added.

A list item that look good has the following classes: `<li class="style-scope ha-chart-base">...</li>`, but a wrongly looking list item has none: `</li>...</li>`

**Comment by balloob** [comment]
Ah, this is a because we're changing DOM without calling the Shady DOM / Shady CSS helpers to update the DOM.
