### ISSUE TITLE
Legend item onclick opens graph popover instead of removing line from graph

### ISSUE THREAD

**Issue by corneyl** [home-assistant/home-assistant-polymer#1009]
What happens: If one clicks on a label in the legend of a graph, it both removes that line from the current graph, and opens the popover with a larger version of the graph.

Expected: That only the line related to the label is removed from the graph.

**Comment by NovapaX** [comment]
I can reproduce this (in all browsers)
I'll try to do a fix before next release.

**Comment by NovapaX** [comment]
this should be fixed in the next release. Thanks for reporting it!
