### ISSUE TITLE
(History) Graphs zooming using mouse gestures wanted?

### ISSUE THREAD

**Issue by corneyl** [home-assistant/home-assistant-polymer#1010]
Environment: HA 0.65.3, FireFox 59.0 (64-bit).

I think that the current way graphs are configured is a bit annoying. When you want to move the graph, it actually zooms (y direction only). Example:
![ha-graph-pan](https://user-images.githubusercontent.com/5320363/37665754-3c62a056-2c5e-11e8-9a36-d95996f9938f.gif)
Sometimes it's almost impossible to get to the right point on the graph.

Proposal: disable zooming using mouse gestures.

**Comment by NovapaX** [comment]
I agree, the zooming/gesture behaviour of charts is bad currently (both touch and mouse.)
It just makes no sense.
I already have it on my list for a while, but that list is getting pretty long.

**Comment by NovapaX** [comment]
We're going to remove the current zooming plugin as it's really bad. (it also prevents scrolling)
We need a better solution/plugin before we can enable zooming again.
