### ISSUE TITLE
New Charts.js info box covers the chart

### ISSUE THREAD

**Issue by jorgeleitao** [home-assistant/home-assistant-polymer#1016]
When passing the cursor over the chart, the info box covers the chart. That didn't happen in Google Charts:

![image](https://user-images.githubusercontent.com/5114388/37727655-54304602-2d30-11e8-8781-00446b630acc.png)

![image](https://user-images.githubusercontent.com/5114388/37727685-6746ae02-2d30-11e8-89de-dd7a03257525.png)

**Comment by cgarwood** [comment]
Just tested on 0.81 beta and the info box is rendering below the selected point on the chart instead of over the top of the selected point on the chart.
