### ISSUE TITLE
Multiline Friendly Names In more-info card "broken"/weird in 0.66.0 beta

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/home-assistant-polymer#1033]
See this screenshot. Long friendly names look really weird in the `more-info` dialog with the latest beta and Chrome Web 65.0. 

<img width="374" alt="screen shot 2018-03-26 at 19 53 19" src="https://user-images.githubusercontent.com/6833237/37923638-e61166b6-312f-11e8-88fa-0c99eecb4fc1.png">

I didn't see this in 0.65.0 I think, so it's probably related to a recent change.

Steps to reproduce:

* Create an entity with a long friendly name, for example

```cpp
sensor:
  - platform: template
    sensors:
      solar_angle:
        friendly_name: "This is a very very long title about some weird issue in the latest polymer frontnend"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.sun.sun.attributes.elevation }}"
```

* Open more-info card.
* See the lines being split in a weird manner.

**Comment by NovapaX** [comment]
Yes I noticed that too.
(I have my dev configured with all kind of weird sensors and names to catch edge cases like this. So I've been looking at that for two weeks now and still didn't fix it.... sorry)
