### ISSUE TITLE
History chart in more info has scrollbars if too small

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1036]
![chart](https://user-images.githubusercontent.com/11984118/37992614-867317b2-320c-11e8-8452-a8b102beded0.png)

**Comment by NovapaX** [comment]
Yep. That’s a side effect of putting the history in the scrollable region. Will take a look.
The charts are nice but there are so much problems with the chart UX that I don’t know where to start....

**Comment by NovapaX** [comment]
should be fixed it the next release.
