### ISSUE TITLE
Charts are broken in 0.66

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#1057]
Hi,

After update hassio from 0.65.6 to 0.66 it's impossible to read charts for majority of numerical sensors since they are displayed partly in android chrome:
![screenshot_20180331-145319](https://user-images.githubusercontent.com/22867988/38163444-85236fc0-34f4-11e8-8b85-a6e82df07b76.png)
![screenshot_20180331-145426](https://user-images.githubusercontent.com/22867988/38163449-95f32480-34f4-11e8-8005-3685d59bdf41.png)
![screenshot_20180331-145505](https://user-images.githubusercontent.com/22867988/38163454-a6f207b0-34f4-11e8-9ac3-99474d83cf81.png)

**Comment by mike9011** [comment]
Same issue here, only on mobile. Already cleared cache etc.

**Comment by NovapaX** [comment]
Thanks for reporting. This is a known issue but discovered at the same time the release was done, so a fix couldn’t be included anymore.
See #1052

**Comment by NovapaX** [comment]
A fix for this will be included in the soon to be released 0.66.1
