### ISSUE TITLE
Subpar color picker

### ISSUE THREAD

**Issue by mxtra** [home-assistant/home-assistant-polymer#106]
This is not a real issue but rather an enhancement proposal. The current color picker for light colors is not a perfect choice.. Especially on mobile devices, it is a bit flimsy and sometimes more hit-and-miss. Also, the color palette makes not sense for lights. I'm not familiar with Polymer, but there seems to be a project over [here](https://github.com/David-Mulder/paper-color-picker) that appears like a great solution. It offers a round color picker ([demo](http://david-mulder.github.io/paper-color-picker/components/paper-color-picker/demo/)) as well, which would make a lot of sense since it reflects the color palette you can archive with lights. 

As I mentioned, I don't have experiences with polymer but at least I could give it a try, if there is interest.

**Comment by Landrash** [comment]
@mxtra 
> You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum.

**Comment by justweb1** [comment]
@mxtra Please request this on the forum. I am closing the issue for now.
