### ISSUE TITLE
add label-badge text transform to ha-style

### ISSUE THREAD

**Issue by uberflyx** [home-assistant/home-assistant-polymer#1061]
Hi, it would be great if someone could please add the ability to set text-transform to none within ha-style instead of it essentially being forced to uppercase. This would allow fancy units such as μ to render correctly as well as just a styling issue in general. I had a look to create a pull request but it looks like there is already some code part way there so I don't want to confuse the issue. Thanks!

https://github.com/home-assistant/home-assistant-polymer/blob/efa956a0b59ed0154e8fbdfa570021fabd3720aa/src/components/ha-label-badge.html#L59

**Comment by c727** [comment]
units should be lowercase in 0.66.1 ?! https://github.com/home-assistant/home-assistant-polymer/pull/1025

**Comment by uberflyx** [comment]
Ah ok cool so we are on the right track! I don't know if it's possible to
update the value from within the home assistant theme though? Sorry I
created a duplicate issue.. That said, I think that the text_transform line
in ha-state-label-badge.html
<https://github.com/home-assistant/home-assistant-polymer/pull/1025/files#diff-a453af711c7957f5be2f8fe692f9ea4b>
is duplicated and so a customized value may not be used anyway.

**Comment by NovapaX** [comment]
If you just set `ha-label-badge-label-text-transform: lowercase`  in your theme it will get used as the default text-transform for the labels. (or pick any other of the valid text-transform values: https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform)

The only thing that's currently not possible is override the units in the labels to uppercase
