### ISSUE TITLE
[element:chart] Charts are cropped on mobile

### ISSUE THREAD

**Issue by bokub** [home-assistant/home-assistant-polymer#1063]
On mobile only, when I click on a component with a line graph, the graph is cropped in the pop-in.

![image](https://user-images.githubusercontent.com/17952318/38232358-f6d96b5a-3716-11e8-8582-2898750a1f6a.png)

_____

**Note 1**: It seems that  `<paper-dialog-scrollable>` is the component causing this height limit

![Screenshot](https://user-images.githubusercontent.com/17952318/38232300-b6916534-3716-11e8-8b9e-ebc0892d2cc6.png)

_____

**Note 2**: Resizing the window of a few pixels (when using chrome dev tools) fixes the problem until the pop-in is closed.

![image](https://user-images.githubusercontent.com/17952318/38232494-8a4ade96-3717-11e8-813e-ade1c99b8375.png)

**Comment by NovapaX** [comment]
This was an issue on version 0.66.0 but should have been fixed in .066.1
What version of home assistant are you using? (there is a reason we ask for that information in the issue template, please fill that in next time, instead of removing it.)

**Comment by bokub** [comment]
Yeah, I have the 0.66.0, and I though it was the latest one because I don't have the usual 'update' notification.

I was surprised too by the absence of template

Thanks :+1:
