### ISSUE TITLE
History chart legend flexbox not working correctly

### ISSUE THREAD

**Issue by fanthos** [home-assistant/home-assistant-polymer#1070]
**Home Assistant release with the issue:**
0.66.1

**Last working Home Assistant release (if known):**
0.65 should works fine

**Browser and Operating System:**
Test on both
Vivaldi 1.14 based on Chrome/64.0.3282.189
Chrome 65

--

**Description of problem:**

Flexbox using at history chart legend not layout correctly
![image](https://user-images.githubusercontent.com/1490719/38362123-56866c32-3902-11e8-817e-23c4698a0233.png)

I think it looked like this in 0.65:
![image](https://user-images.githubusercontent.com/1490719/38362283-d4e3f1c6-3902-11e8-98ed-7a7d3b4ed351.png)

**Comment by NovapaX** [comment]
Yes, I saw that. That was just a plain invalid value for `flex:` 🤦‍♂️

**Comment by NovapaX** [comment]
fixed in #1076
