### ISSUE TITLE
Refreshing issue on Android Chrome (Web App)

### ISSUE THREAD

**Issue by flavio20002** [home-assistant/home-assistant-polymer#1087]
**Home Assistant release with the issue:** 0.66.1

**Browser and Operating System:** Chrome 65.0.3325.109 on Android 7.0

**Description of problem:**

This problem doesn't happen if I browse the site with Chrome browser, but only if i "add the application on home screen", and I start it like a Web App.
If I pull down the page in order to refresh, at the third or fourth try, I get this strange behaviour. I need two more pull to refresh, or back button and reopen to get the frontend icons back.

![screen](https://user-images.githubusercontent.com/10809301/38765914-6dde0e02-3fca-11e8-9e42-17d315525ce1.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by flavio20002** [comment]
Hi, it is possibile to force the total refresh of the Web App on Pulling? Like closing and reopening?
In addition to the issue of missing icons, sometimes the page remain white. I have no issue on Chrome browser, but I don't like the address bar.

**Comment by mvdnes** [comment]
I'm having the same issue. (See also home-assistant/home-assistant#15292) on home assistant 0.70+. When using Firefox 61.0 on Linux, or Chrome on Android 7.

When pressing one of the tabs, all icons appear. When closing and re-opening the browser, all icons disappear again.

**Comment by balloob** [comment]
Problem has been fixed in 0.73.
