### ISSUE TITLE
Switch/Boolean toggle circles are transparent when off.

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1090]
**Home Assistant release with the issue:**
0.68.0.dev0 (15/04/18)
Frontend version: 20180414.0

**Last working Home Assistant release (if known):**
Relatively recent dev build (0.67 still, but less than a week old).
Frontend version (I'm fairly sure): 20180404.0

**Browser and Operating System:**
Appears to occur on all browsers (Windows, Chrome + Firefox), iOS (Home Assistant App)

**Description of problem:**
The screenshot explains it better than I can. This is affecting all boolean toggles (lights, switches, inputs, groups).
![image](https://user-images.githubusercontent.com/24840952/38775323-8e26092c-40be-11e8-9454-e539cf9d43a9.png)

I've tried cache clearing. I'm not using any themes. I do have some custom state cards (Home Assistant Tiles and a Weather one). Neither are being used on these entities.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by NovapaX** [comment]
Thanks for reporting the issue!
Fix should be included in next build.
