### ISSUE TITLE
Heavier font-weight of badge label for non-latin characters is needed

### ISSUE THREAD

**Issue by cxlwill** [home-assistant/home-assistant-polymer#1101]
**Home Assistant release with the issue:**
0.67 

**Last working Home Assistant release (if known):**
0.67

**Browser and Operating System:**
All modern browser such as Chrome for mac, Safari for iOS.....

**Description of problem:**
The default font weight for badge is typically too light for non-latin characters. Many languages such as Japanese, Chinese, Korean..... they didn't based on latin characters. So they need heavier font-weight to render in order to be readable. The default font weight for badge-label is typical too light for non-latin characters. Here's the example:

![](http://oeoj44yho.bkt.clouddn.com/2018-04-18-font-weight.jpg)
(LtoR: Simplified Chinese, English, Japanese)

Despite of limited resolution of screenshot, you can observe that the character of badge title is barely to recognize. This screenshot is zoom-in, if we read the normal full size of HA's frontend website, this vague phenomenon would be more serious.

If I adjust it manually to `350`, then it is far better:
![](http://oeoj44yho.bkt.clouddn.com/2018-04-18-font-weight-2.jpg)

**Additional information:**
Since font weight is hard-written in the project and the change to it would influence all users, I suggest open the adjustability for this feature in the `theme`. So only non-latin speaker need to adjust it.

**Comment by NovapaX** [comment]
We currently render at font-weight 300. Are you sure that second screenshot is at a font-weight of 350?
You can set the font size by including `ha-label-badge-title-font-size: 110%` in your theme. Would that help too?

**Comment by cxlwill** [comment]
1. Yes, up 300 down 350.
2. No, the size is different from weight. No matter how you adjust the size, it is still light and vague because no every pixels get proper rendered. Besides 110% is too big and not very elegant for badge, right?

Here's 110%:
![](http://oeoj44yho.bkt.clouddn.com/2018-04-18-font-wight-110.jpg)
