### ISSUE TITLE
Binary Sensor States Not Displaying Values/States

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1103]
**Home Assistant release with the issue:**
0.68.0.dev0 (18/04/18)
Frontend: 20180417.0

**Last working Home Assistant release (if known):**
(Can't recall which dev build, very recent)
Frontend: 20180414.0

**Browser and Operating System:**
Seems to be all browsers (tested on Windows using Chrome and Firefox, and iOS using the HA app).

**Description of problem:**
Binary sensor states still show fine within the dev-state page, and function okay. Within the frontend these display as [%1$s] regardless of the state. I can't tell if this is all binary sensors or just Xiaomi ones as that's all I have displaying. I suspect this is a frontend issue as it was working in an old cached tab I had open, upon doing a full refresh the issue showed on that tab too.

![image](https://user-images.githubusercontent.com/24840952/38929944-3480d564-434d-11e8-99ac-8aa6ecc633e9.png)

![image](https://user-images.githubusercontent.com/24840952/38929760-9461563a-434c-11e8-95f6-85137d480afb.png)

**Javascript errors shown in the web inspector (if applicable):**
Nothing relevant.

**Comment by NovapaX** [comment]
This is an error in `translations/en.json`
I really don't know what happened there....  @c727

**Comment by balloob** [comment]
CC @armills 

Looks like the upload script got messed up 🤔

**Comment by balloob** [comment]
![image](https://user-images.githubusercontent.com/1444314/38933762-e79ad1f6-42e7-11e8-80b8-720bbb2ba108.png)
