### ISSUE TITLE
Configuration Panel Text Moves Up After Entering A Menu

### ISSUE THREAD

**Issue by theaquarium** [home-assistant/home-assistant-polymer#1124]
**Home Assistant release with the issue:**

0.67.1

**Last working Home Assistant release (if known):**
n/a

**Browser and Operating System:**
- Google Chrome 66.0.3359.117
- Firefox Quantum 59.0.2 on Windows 10
- Google Chrome 666.0.3359.126 on Android 8.0.0

**Description of problem:**

In the configuration panel, the text on the left moves up so the words "Configure Home Assistant" are hidden after entering one of the menus (e.g. integrations, general, customization).

Here is a screenshot of the configuration panel before entering a menu:
![image](https://user-images.githubusercontent.com/26528805/39280265-51a9b8ac-48cc-11e8-85b7-5a24ea5b3e2f.png)

Here is a screenshot of the configuration panel after entering a menu:
![image](https://user-images.githubusercontent.com/26528805/39280324-aa71a65c-48cc-11e8-9723-de6d741552d7.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by cgarwood** [comment]
Can confirm this is still an issue on 0.78
