### ISSUE TITLE
Bar Chart Has Very Faint Line Graphs Behind It

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#1135]
**Home Assistant release with the issue:**

0.68 and 0.68.1

**Last working Home Assistant release (if known):**

0.67

**Browser and Operating System:**

Windows 10 - Chrome 66
Android 8 - Chrome 66

**Description of problem:**

When I open up the more info panel on a light or a switch I see some odd graph lines behind it on mobile and desktop

![bar-line](https://user-images.githubusercontent.com/1634145/39459543-1deff510-4cb1-11e8-83ce-ae033ef641ea.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

Seeing this in multiple devices, no excel is not open :) have tried to clear cache, do force refreshes etc...  It seems to be part of the design/background?  Hard to unsee once I see it :)

**Comment by fanthos** [comment]
I didn't notice the line behind the bar before. The line was hidden because drawing code changed.

**Comment by fanthos** [comment]
Found that it only happens when there only 1 item, weird.
