### ISSUE TITLE
Migrate Map panel to use pure LeafletJS

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#114]
We are currently using LeafletJS web components for the map panel. However these seem to not work correctly when enabling native ShadowDOM instead of the ShadyDOM polyfill.

On top of that, the Leaflet web component development seems to have stagnated.

Since we do not use much functionality  anyway, we should upgrade to a pure JS implementation using LeafletJS 1.0 instead of the LeafletJS web components.

**Comment by justweb1** [comment]
Would it be better to update the web components module than build a JS only panel? I know there hasn't been any action on the repo for a year and a half but maybe we can just fork it and update it ourselves.

**Comment by balloob** [comment]
Done!
