### ISSUE TITLE
Uncaught js error after config flow voluptuous error

### ISSUE THREAD

**Issue by MartinHjelmare** [home-assistant/home-assistant-polymer#1140]
**Home Assistant release with the issue:**

0.68.0.dev0
home-assistant-frontend 20180426.0

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Chrome Version 66.0.3359.117
Ubuntu 14.04

**Description of problem:**

Submitting invalid input to config flow doesn't show any feedback in frontend to the user about the invalid input. JS console shows errors.

**Config**
```yaml
frontend:
  javascript_version: latest
```

**Steps to reproduce**
1. Start `hass`
2. Go to integrations under configuration in the frontend.
3. Click the configure button for the Zone integration.
4. Click the submit button without entering any info.
5. See errors in js console.

![config_flow_feedback](https://user-images.githubusercontent.com/3181692/39577075-9a201cec-4ee0-11e8-8d81-0405d67aeaff.png)

**Javascript errors shown in the web inspector (if applicable):**
```
frontend-f9c85492ac8ddd09005dd3c9153053a5.html:11 POST http://localhost:8123/api/config/config_entries/flow/0e6a49071be545bcad9ec45e52caf148 400 (Bad Request)
(anonymous) @ frontend-f9c85492ac8ddd09005dd3c9153053a5.html:11
window.hassCallApi @ frontend-f9c85492ac8ddd09005dd3c9153053a5.html:11
callApi @ frontend-f9c85492ac8ddd09005dd3c9153053a5.html:148
_submitStep @ ha-panel-config-ac9bba79fca21a4a43b79ea956af0fba.html:7
(anonymous) @ frontend-f9c85492ac8ddd09005dd3c9153053a5.html:1
integrations:1 Uncaught (in promise) {error: "Response error: 400", status_code: 400, body: {…}}body: {message: "User input malformed"}error: "Response error: 400"status_code: 400__proto__: Object
Promise.then (async)
_submitStep @ ha-panel-config-ac9bba79fca21a4a43b79ea956af0fba.html:7
(anonymous) @ frontend-f9c85492ac8ddd09005dd3c9153053a5.html:1
```

**Additional information:**
The relevant backend code is here:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/helpers/data_entry_flow.py#L88-L89

**Comment by mindigmarton** [comment]
Same thing happens for me. Also, it looks like optional / required field validation isn't happening, all fields are passed to the server as empty strings. Meaning that an optional int field becomes required and string fields are always optional.

Home Assistant release with the issue:

0.70.1
home-assistant-frontend 20180531

Last working Home Assistant release (if known):

Browser and Operating System:

Chrome Version 67.0.3396.62 
Firefox 60.0.1
Microsoft Edge 42.17134.1.0
Raspbian Stretch (running in python 3.6.5 venv)
