### ISSUE TITLE
Weather Card

### ISSUE THREAD

**Issue by dgomes** [home-assistant/home-assistant-polymer#1144]
**Home Assistant release with the issue:** 0.69b0

**Last working Home Assistant release (if known):** 0.68.1

**Browser and Operating System:** Chrome, Safara - OSX

**Description of problem:**

I understand that the new weather card might work with all the existing provided weather platforms, but there are tons of other regional weather providers (and personal weather stations) that exist in the wild as custom_components.

<img width="387" alt="screen shot 2018-05-05 at 22 54 18" src="https://user-images.githubusercontent.com/137684/39667882-961e2926-50b7-11e8-91ea-1c52f423f9eb.png">

<img width="363" alt="screen shot 2018-05-05 at 23 01 02" src="https://user-images.githubusercontent.com/137684/39667903-3c14d834-50b8-11e8-9a5d-a634aafa18c4.png">

I think the image speaks by itself, but here goes:
- Temperature doesn't fit
- My weather station has no wind speed (why does the card show wind speed ?)
- My weather station has atmospheric pressure (why doesn't it show?)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by c727** [comment]
air pressure was voted out

**Comment by dgomes** [comment]
Yet, Wind Speed is there and I don't have wind speed.... 

All personal weather stations come with atmospheric pressure, if you pay extra you get wind, and if you pay even extra you get rain-meters. 

(for rain prediction purposes atmospheric pressure it the most important variable)

**Comment by c727** [comment]
chill... we will remove wind speed for you <3

**Comment by dgomes** [comment]
I'm cool 😎

I'm just making the case for prioritising what gets displayed.

**Comment by c727** [comment]
some other issues:
- translation for cardinal direction does not work
- weather BR shows visibilty `42200` km (should be fixed in main repo)
- not all stations have visibility attribute
- hourly forecast gets squashed on small cards

not sure if I can do it tomorrow, else on tuesday

**Comment by c727** [comment]
btw I see in your more info air pressure 101018 hPa, this also makes no sense. https://github.com/home-assistant/architecture/issues/24

**Comment by dgomes** [comment]
why doesn't it make sense ? hPa is a standard unit to measure atmospheric pressure (as proposed in https://github.com/home-assistant/architecture/issues/24)

Only thing wrong is that the value should be divided by 100.

**Comment by fabaff** [comment]
> Only thing wrong is that the value should be divided by 100.

Things like that could be solved with https://github.com/home-assistant/architecture/issues/10
