### ISSUE TITLE
Dark Sky weather does not show wheather

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#1156]
**Home Assistant release with the issue:**
0.69.0

**Last working Home Assistant release (if known):**
0.68.1

**Browser and Operating System:**
Chrome desktop and mobile

**Description of problem:**
The card shows very limited forecast information like hours and corresponding temperature only. Now it is mostly useless in terms of forecast. This PR https://github.com/home-assistant/home-assistant-polymer/pull/1117 added little value to this component removing graphs. It would be good to remember for developers that users live in different climate zones, therefore, temperature only is not the most important indicator for some areas. 

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by c727** [comment]
this has to be fixed/changed in backend, more details here https://developers.home-assistant.io/docs/en/entity_weather.html#recommended-values-for-state-and-condition
