### ISSUE TITLE
Custom UI & Panels: Modules & dependencies

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#1157]
When we switch to Polymer 3, we're no longer using HTML imports or the global scope to make functions available to other parts of the code base. Instead, we're using JS modules and functions are imported directly by the code that uses it.

I want to propose that we deprecate HTML-based custom UI and replace it with JS module custom UI. This will be easier to bundle up for users, meaning they can include their own dependencies, including Polymer.

Following plan:

**When we release Polymer 3**
 - Announce deprecation
 - Add a support layer to keep custom UI working that depends on global objects (we need to expose `Polymer` on `window`). 

**Soon thereafter**
 - Add support for JS-based custom UI

**2 months later**
 - Remove support for HTML-based custom UI (no longer expose `window.Polymer`)

**Comment by andrey-git** [comment]
What is the upside of exposing window.Polymer? Authors need to update their code anyway.

**Comment by balloob** [comment]
We need to expose it to support HTML imports support. I am assuming, and correct me if I'm wrong, that custom UI doesn't bundle polymer and expects it on the window object. Polymer imported via es modules will not expose itself on the window object.

**Comment by andrey-git** [comment]
Depending on implementation it might need Polymer for v1-2 hybrid or PolymerElement for v2

**Comment by balloob** [comment]
We'll keep both around until we remove the HTML support

**Comment by balloob** [comment]
There was some confusion in the chat because we only expose Polymer on the window object. All other things (like utilities, mixins) are no longer available. This is on purpose.

We should limit the API that we expose to custom UI such that the frontend can evolve without breaking the expectations of custom UI. 

Our API to custom UI should be:

 - You give HASS a web component name and url for HASS to load it
 - Loading that url will define specified web component
 - HASS will instantiate your web component and set `hass` and `stateObj` as properties.

Custom UI can use any framework they want. They are not limited to Polymer. In fact, the Polymer team is actively suggesting to no longer use Polymer templates. Instead, they suggest you use their new Lit Element ([source](https://www.polymer-project.org/blog/2018-05-09-polymer-at-io-2018.html))

**Comment by andrey-git** [comment]
Disclosure: my code also gets ha polymer elements via customElements.get and tweaks their prototype to achieve advanced features, like user-supplied js templating.

I'm aware this is brittle, but this allows the advanced tweaking.

**Comment by balloob** [comment]
I am down to add hassUtils back in the legacy layer. Which methods are people using?

**Comment by balloob** [comment]
I've added `window.Polymer.html` back in #1202

**Comment by ptc** [comment]
I'm missing hassUtil.relativeTime

**Comment by fanaticDavid** [comment]
I agree with @ptc : it would be great to have `hassUtil.relativeTime` back through Custom UI.

**Comment by balloob** [comment]
We can do that, but it requires the input of the `localize` function too. Why not copy the 20 lines into your project?

**Comment by cgarwood** [comment]
Is there anything left to do with this issue?

**Comment by balloob** [comment]
Not removing `window.Polymer` until the last Polymer element is removed from the initial load.
