### ISSUE TITLE
Failed to fetch thumbnail

### ISSUE THREAD

**Issue by mike9011** [home-assistant/home-assistant-polymer#1169]
**Home Assistant release with the issue:**
0.69.0

**Last working Home Assistant release (if known):**
0.68.x

**Browser and Operating System:**

**WIN 10:**
- Chrome
- Firefox
- IE

**Description of problem:**
The image of the mediaplayer cannot be loaded from local storage (www dir); "Failed to fetch thumbnail" I can load the image with the url /local/**.jpg

![Thumbnail error](https://i.imgur.com/M6zZ16d.png)

**Javascript errors shown in the web inspector (if applicable):**
`Uncaught (in promise) {code: "thumbnail_fetch_failed", message: "Failed to fetch thumbnail"}`

**Additional information:**
-

**Comment by balloob** [comment]
All thumbnail images are fetched via the websocket connection at the backend. Not sure how this would happen. What media player?

**Comment by mike9011** [comment]
This is the PS4 "media player". But the strange thing is that is worked perfectly before the latest update. 

-----------
After the .69 updates I also see a lot of "caching errors" in the console and flashes of X's when loading the page on the place where a image should be. Don't know if this is related...

![imageissue](https://preview.ibb.co/fa6JLd/20180514_192120.jpg)

**Comment by cgarwood** [comment]
@mike9011 Does this still happen on newer HA releases?

**Comment by zsarnett** [comment]
Closing- No Reply
