### ISSUE TITLE
JS based custom panels

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#1188]
Custom panels based on HTML imports are deprecated (we're removing all HTML imports).

In it's place we want to add JS-based panels. However, this has 1 big downside compared to HTML imports: since it's 1 big script (instead of many small script tags), defining a web component that already exists will result in an exception and stop the importing of the panel.

This isn't the first time that we are fighting with duplicate web components. We've had, and solved, the same problem for Hass.io by running it in an iframe. Inside the iframe panels still have access to the `hass` object and can fire events to open/close the sidebar. It works by making the parent web component `setProperties` function available on the `window` object, which then is accessed by the Hass.io panel inside Home Assistant:

 - [`src/panels/hassio/ha-panel-hassio.js`](https://github.com/home-assistant/home-assistant-polymer/blob/master/src/panels/hassio/ha-panel-hassio.js) - renders iframe and passes info down
 - [`/hassio/src/hassio-app.js`](https://github.com/home-assistant/home-assistant-polymer/blob/master/hassio/src/hassio-app.js) - renders inside iframe, forwards info

So to add JS based custom panels, I want to suggest we generalize the Hass.io approach.

 - Create a new JS mini-app to be embedded in iframe that instantiates web component and connects to main HASS
 - Add `/static/custom_panel.html` that renders the mini-app
 - Add a new panel type "custom" that renders iframe with the HTML. Add `?es5` if it's an ES5 based custom panel
 - Make external panels that register with the frontend.py expose themselves as type: custom.
 - Pass data to the iframe via [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage):
   - panel url: string
   - web component name: string
   - config: object

**Comment by andrey-git** [comment]
This approach has a disadvantage of loading all of polymer again.

I think the hass.io case is more difficult as it need to be able to release separately from HA.

A panel can just load everything it needs *except* what HA loads. This means it might need to be re-released with HA update that adds/removes dependencies.

Since custom UI will need to do that anyway I don't think custom panels need a different treatment.

**Comment by balloob** [comment]
I don't want to put the burden on authors to maintain custom panels that will work for each version of Home Assistant. Another pain point is that if a custom panel defines a web component, and then a built-in panel is loaded after that and also defines that component, our panel breaks because `customElements.define()` will raise ([this proposal will solve that, but it's still in draft](https://gist.github.com/justinfagnani/d67d5a5175ec220e1f3768ec67a056bc)).

I think that not putting it in an iframe will:
 - make it complicated to do it right, or easy to do it wrong
 - puts the update burden on the users

The idea would be that custom panel authors would not have to know about that it runs in an iframe. It will just work.

**Comment by balloob** [comment]
After working more with the new frontend, putting it in an iframe is really the way to go. The big problem is overlapping custom elements.

If a custom element is already defined but it is included in another panel that is loaded on the fly (either being built-in or custom), it will raise when calling `customElements.define` and the JS script will stop executing. This was not a problem with the HTML import because it would contain many different JS imports, resulting in it just stopping to execute the one script tag and moving on. With JS imports, we now have a single script, stopping execution means the final panel (which is always the last JS to be executed), is not loaded.

**Comment by andrey-git** [comment]
Theoretically authors could catch wrap the define with a try-catch...

While iframe will work for custom panels, it won't work for custom UI, right?
Also custom panel authors can already make an iframe panel without core support (by using existing iframe panel)

**Comment by balloob** [comment]
Correct, it won't work for custom UI.

It could work with wrapping it in a try…catch, except that we don't control the components that usually conflicts (like `<paper-input>`). With ES modules, all import statements are processed before running any code and cannot be inside the code like `require(…)`. Exception is the `import(…)` "function", however, this would mean it's a code split point, resulting in many different files and undoing tte bundling.

**Comment by balloob** [comment]
Okay, after implementing the custom panel implementation using iframe, I have now reversed my decision. I am going to make it optional to run inside an iframe. The main reason is that running a panel in an iframe has the big downside of not being able to use modals and have the overlay gray out the whole page (only the iframe is grayed out).

**Comment by balloob** [comment]
Fixed in #1236
