### ISSUE TITLE
Split Sliders in 0.70.0.b0

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1190]
**Home Assistant release with the issue:**
0.70.0.b0

**Last working Home Assistant release (if known):**
Unsure, don't use this much and only just noticed it.

**Browser and Operating System:**
Chrome + iOS app (haven't tried others)

**Description of problem:**
The screenshot below shows the issue. It's probably worth mentioning I'm forcing use of es5 JS due to another issue (compatibility with a custom component I use) introduced in this release. So maybe using es5 in modern browsers is causing this, which is why it hasn't been raised/seen yet?
![image](https://user-images.githubusercontent.com/24840952/40267633-0ac00582-5b9f-11e8-883f-dc7b263f55e0.png)

**Javascript errors shown in the web inspector (if applicable):**
No errors showing.

**Additional information:**

**Comment by balloob** [comment]
CC @NovapaX

**Comment by balloob** [comment]
The problem is that with Polymer 3, templates are returned as tagged template literals and not as templates.
