### ISSUE TITLE
Custom UI Breaking Change (EventsMixin)

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1200]
**Home Assistant release with the issue:**
0.70.0.b0

**Last working Home Assistant release (if known):**
Unsure, I was running running dev builds, was working up until late in 0.69

**Browser and Operating System:**
Firefox, Chrome, iOS app.

**Description of problem:**

Saw the post on FB about maybe fixing this as legacy for now. No big deal if it can't be, as I'm sure c727 will get around to it eventually, and using es5 instead works okay. Or maybe it's an easy enough fix that I could make?

The latest frontend builds have broken the use of the [Custom UI Tiles](https://github.com/c727/home-assistant-tiles) component, which uses the EventsMixin command. There's more info about this in the issue I raised here:
https://github.com/c727/home-assistant-tiles/issues/48

**Javascript errors shown in the web inspector (if applicable):**
```
state-card-tiles.html:90
Uncaught TypeError: Cannot read property 'EventsMixin' of undefined at state-card-tiles.html:90
```

**Additional information:**

**Comment by balloob** [comment]
Answered in c727/home-assistant-tiles#48 but it looks like you're running an old version of the tile plugin.
