### ISSUE TITLE
P3 (Beta): some icons disappear on page reload

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1206]
**Home Assistant release with the issue:** 0.70.0b3

**Last working Home Assistant release (if known):** 0.69

**Browser and Operating System:** Win 7 Chrome 66

**Description of problem:**
After a page reload (F5) some icons disappear
![11](https://user-images.githubusercontent.com/11984118/40562123-fa80673c-605f-11e8-8eb4-a644cc8a9106.PNG)

**Additional information:**
No issues in Firefox

**Comment by balloob** [comment]
Hmm, weird. I have already included the fix by @andrey-git ([source](https://github.com/home-assistant/home-assistant-polymer/blob/4e9a7a4a237ce4c44565bacb127aa1037cbe2bba/src/components/ha-iconset-svg.js)).

**Comment by balloob** [comment]
I am btw unable to repro this on my Mac / Chrome 66 on both a local and a remote instance.

**Comment by c727** [comment]
hm I also have this in Android Chrome. Imo this should be fixed before the final release as it also effects the icons in the views/cards

**Comment by balloob** [comment]
Can you try this with Chrome on a different computer?

**Comment by fabaff** [comment]
I see the same behavior while running `dev` with Chromium (Version 65.0.3325.181 (Developer Build) Fedora Project (64-bit)) but not with Firefox (59.0.2 (64-bit)) and Midori (0.5.11).

**Comment by c727** [comment]
fixed in beta5

**Comment by balloob** [comment]
This is solved.
