### ISSUE TITLE
P3 (beta): Hassio webcomponents-lite not found

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1209]
**Home Assistant release with the issue:** 0.70.0b3

**Last working Home Assistant release (if known):** 0.69

**Browser and Operating System:**
Firefox

**Description of problem:**
browsers that need the polyfill show an empty page

**Javascript errors shown in the web inspector (if applicable):**
```
404: http://192.168.1.36:8123/static/webcomponents-lite.js
```

**Comment by hvbhome** [comment]
Had this exact error after updating to the last Custom-ui (though not necessarily related), on Hassio 69.1:

see: https://community.home-assistant.io/t/customui-discussion-thread/48694/143?u=mariusthvdb

**Comment by balloob** [comment]
Fixed in c6f2f43767ad9b133dc29476cf7f02f64c8b0779
