### ISSUE TITLE
Allow linebreaks in the template editor

### ISSUE THREAD

**Issue by kellerza** [home-assistant/home-assistant-polymer#122]
Linebreaks are not accepted in the HASS template editor for a while. This seems to be isolated to Firefox, tried it with Chrome and Safaric on iOS and it works fine.

The default template editor screen displays the following:

![20161009-000447-home assistant](https://cloud.githubusercontent.com/assets/6756881/19219841/4218cd20-8e1e-11e6-90bb-ee9375e9c7d3.png)

[Enter] is never accepted

**Comment by justweb1** [comment]
@kellerza are there any other text area boxes in other elements that this is occuring?

**Comment by kellerza** [comment]
As @justweb1 mentioned FF 49.0.1 most likely fixed this.

The "Service Data" text area is also fixed in the new Firefox.
