### ISSUE TITLE
History Panel: Datepicker overlays history graph

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1222]
**Home Assistant release with the issue:** 0.70.0

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Win 7 Chrome 66
**Description of problem:**
![history](https://user-images.githubusercontent.com/11984118/40663487-10d7207e-6359-11e8-8600-1cf3b057138e.png)

**Comment by balloob** [comment]
I think it's a feature of the new version of the vaadin date picker that we use.

**Comment by frenck** [comment]
Seems to be fixed 👍 

![image](https://user-images.githubusercontent.com/195327/72875151-fa2a0a00-3cf3-11ea-83ff-e25b9973d5ba.png)
