### ISSUE TITLE
Mailbox Panel: Email dialog behind backdrop

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1223]
not sure if anyone is using this panel, but it's included in `demo:`

**Home Assistant release with the issue:** 0.70.0
**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Win 7, Chrome 66
**Description of problem:**
![mailbox](https://user-images.githubusercontent.com/11984118/40663791-c70258dc-6359-11e8-99bb-3665d192d8fc.PNG)

**Comment by balloob** [comment]
I sometimes wonder if we should just remove the mailbox component and panel. There is only 1 platform and not even sure if anyone is using it.

**Comment by cgarwood** [comment]
Just tested with the demo platform and the UI is working fine.
