### ISSUE TITLE
Media Image doesn't display in Universal Media Player

### ISSUE THREAD

**Issue by willscottuk** [home-assistant/home-assistant-polymer#1224]
**Home Assistant release with the issue:** 0.70.0

**Last working Home Assistant release (if known):** Not Known

**Browser and Operating System:** Chrome (66.0.3359.181) / Safari (11.1) on MacOS

**Description of problem:** 

(Apologies if this is a backend rather than a frontend problem - happy to move it there if needed!) 

The Universal Media component is no longer displaying the media image from the currently active player. That image displays correctly in the card for the active media player.

<img width="926" alt="screenshot 2018-05-29 16 24 32" src="https://user-images.githubusercontent.com/28684940/40670273-d345f7d2-6360-11e8-9a08-b6e1d4e86941.png">

The state attributes for both the universal and regular media_players has the same url for entity_picture but the universal media_player causes the following error in the log.

~~Javascript errors shown in the web inspector (if applicable)~~ **From main Home Assistant log:**
```
2018-05-29 16:41:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 977, in send_image
    data, content_type = await player.async_get_media_image()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 511, in async_get_media_image
    return await _async_fetch_image(self.hass, url)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 909, in _async_fetch_image
    response = await websession.get(url)
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/client.py", line 313, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 210, in __init__
    self.update_host(url)
  File "/srv/homeassistant/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 253, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /api/media_player_proxy/media_player.livingroomtv?token=53ff6a0dd6c3fd4e3fa587aea18aacda024146fa914b80e27021bf7f4d15ec3b&cache=ebc1dbb0e7bc2af4
```

**Additional information:**

**Comment by balloob** [comment]
Ah, this is a backend issue but it is triggered by the frontend. I will put it on my list.

**Comment by azogue** [comment]
This is the same error I've found for Kodi, and it's [this backend issue #14782](
https://github.com/home-assistant/home-assistant/issues/14782)

The fix proposal is in [#15572](https://github.com/home-assistant/home-assistant/pull/15572)

**Comment by blackjid** [comment]
Hi, it looks that his problem is not really solved. I have a universal media player and the image is not showing in the media-control card with lovelace.

This is the websockets frame where the thumbnail is requested
![image](https://user-images.githubusercontent.com/228037/50369453-b30f9980-0574-11e9-9d44-ce9602dd2c18.png)

This is the frames with the response
![image](https://user-images.githubusercontent.com/228037/50369457-bacf3e00-0574-11e9-83a7-99ad106b90c4.png)

**Comment by iantrich** [comment]
Don't comment on closed issues, please. Open a new issue and reference this.
