### ISSUE TITLE
Allow basic formatting for templates of UI elements

### ISSUE THREAD

**Issue by kellerza** [home-assistant/home-assistant-polymer#123]
Basic formatting for UI elements like persistent_notifications and device attributes could improve the information significantly.

This could include: linebreaks as a minimum, links, and lastly bold or italics. 

Examples of current UI displays that could be improved:
- persistent_notifications for invalid config [see PR [HA #3738](https://github.com/home-assistant/home-assistant/pull/3738)] 
![20161009-000448-home assistant](https://cloud.githubusercontent.com/assets/6756881/19220135/548ab9e8-8e26-11e6-8401-4823a65c01ac.png)
 
- Device attributes could benefit from having links (e.g. pointing at source data / attribution)
![20161009-000449-home assistant](https://cloud.githubusercontent.com/assets/6756881/19220179/6d67331e-8e27-11e6-88f1-c05e1a140ceb.png)

**Comment by balloob** [comment]
The best way to do this would be to add Markdown support (same formatting as we use on GitHub). The smallest library that supports this comes in at 5kb: https://github.com/SimonWaldherr/micromarkdown.js

That's small but still quite big for a feature that might not be used by 95% of the users.

I would be open for including this if we can conditionally load this on demand.

**Comment by kellerza** [comment]
What if we support only our current use cases?

- honor linebreaks `\n` --> `<br>`, and
- support links `(url)[http://xyx]` --> `<a href='http://xyx'>url</a>` 

It will cover the startup messages and attribution cases, and will allow the following message:

---

## Invalid config
The following platforms contain invalid config: [sensor](http://home-assistant.io/components/sensor)

Please check your configuration files and see [logs](/dev-info) for more information. For fault finding tips see  [here](http://home-assistant.io/help_me_out)

---

**Comment by justweb1** [comment]
We could create an element for markdown. This way it will only load the js if the element is loaded.
`<ha-markdown>(url)[http://xyx]</ha-markdown>`

**Comment by balloob** [comment]
All elements for cards in the UI are included in the initial load so they would be included in the initial load.

**Comment by justweb1** [comment]
ah... that's right it will flatten it.

**Comment by justweb1** [comment]
I'm not seeing a good way to do this.

**Comment by balloob** [comment]
One way I can think of is having a web component that includes the markdown be included in the static folder. We'll load it on demand when the card with a notification is shown. ( Using `this.importHref` in a web component or `Polymer.Base.importHref` outside). HTML imports have the nice side effect that they will never be resolved twice.

**Comment by justweb1** [comment]
I like the idea of importing it directly in the Web components that will need it. it only loads if they use those components and like you said, once it is loaded it'll be there.

**Comment by justweb1** [comment]
@balloob we could just install it with node it that will work for you.

**Comment by justweb1** [comment]
@kellerza I have added markdown to persistent notifications for now. Should be merged soon. I don't know that we are adding it anywhere else at this point.

**Comment by kellerza** [comment]
Thanks, persistent notification will be a great improvement!

Not sure if there is an easy way to enable this for platform attributes? (like links)

**Comment by justweb1** [comment]
probably just a concatenated string.

**Comment by justweb1** [comment]
@kellerza Do we want to close this for now?

**Comment by kellerza** [comment]
Thanks @justweb1!
