### ISSUE TITLE
Can't set input_datetime value via the iOS application

### ISSUE THREAD

**Issue by maartenpaauw** [home-assistant/home-assistant-polymer#1232]
**Home Assistant release with the issue:**

0.70.0

**Last working Home Assistant release (if known):**
0.69.1

**Browser and Operating System:**

IOS mobile application

**Description of problem:**

I can't edit the input (date) time via the mobile iOS application.

**Additional information:**
![img_1029](https://user-images.githubusercontent.com/4550875/40723351-0c9dff66-641f-11e8-8035-4ee3dd4b0781.PNG)

**Comment by c727** [comment]
what about Mobile Safari?
Clear the app-cache maybe

**Comment by balloob** [comment]
I had to drop the `paper-input-datetime` component because it was not Polymer 3 ready. I replaced it with `input[type=time]`, but realize now that it's not Safari compatible https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by c727** [comment]
Fixed in 0 .70.1
