### ISSUE TITLE
History graph dialog: blank page if opened again

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1240]
**Home Assistant release with the issue:** 0.70.0

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Win 7, Chrome 66

**Description of problem:**

Open history graph dialog -> close -> open again -> blank page

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Can't reproduce. Anything in your logs? Custom UI?

**Comment by c727** [comment]
nothing in the logs, no custom UI.

I tested with `demo:` you can open the history dialog again after you opened another dialog

**Comment by balloob** [comment]
My bad, I was at the history panel. You're right, graph dialog not visible.

**Comment by balloob** [comment]
Ah yes, the beauty of race conditions. We keep the DOM around of a more info dialog when it's not rendered. So if you open the dialog again, the chart is already there and it is probably trying to render while it's still hidden -> sets height to 0px.

**Comment by zsarnett** [comment]
@cgarwood Was this fixed with the latest `.5` Patch?

**Comment by zsarnett** [comment]
Waiting on a reply here @cgarwood

**Comment by balloob** [comment]
Was fixed.
