### ISSUE TITLE
Increase size of line charts, maybe add some options

### ISSUE THREAD

**Issue by covrig** [home-assistant/home-assistant-polymer#125]
The line charts are too small considering that once you click on them you can't do anything else in the frontend. A lot of information is lost because of the tiny size. This feature is easy to fix.
It would be nice if some of the chart options could be editable (height, width, colors, data point labels etc.).
Thanks.

**Comment by justweb1** [comment]
Thanks for your interest. Issues should only be used for functionality issues and bug fixes. You could either make the changes yourself and submit a Pull Request or you can request this enhancement on the forums https://community.home-assistant.io/.
