### ISSUE TITLE
Javascript based caching make problems to iframe intergrated applications

### ISSUE THREAD

**Issue by terba** [home-assistant/home-assistant-polymer#1270]
**Home Assistant release with the issue:**

0.67.1

**Last working Home Assistant release (if known):** 

Don't know exactly but some releases before it was working well.

**Browser and Operating System:**

All, I think

**Description of problem:**

The server serving HASS also serves other applications. It is an Apache reverse proxy. The other applications are also proxyed on the same Apache virtual host, so these are also accessible on the same host as HASS. I have `panel_iframe`s configured for the other webapps, so these are all accessible in HASS as a single entry point.

But with a newer release of HASS some browser side (JS) caching was implemented or modified, and HASS frontend started to cache the resources of those external applications. And those started to misbehave.

Example configuraton:

```
panel_iframe:
  statistics:
    title: Statisztika
    icon: mdi:chart-areaspline
    url: /grafana/dashboard/db/ha?orgId=1
```

I could track down the problem to this:
The browser JS is caching in $$$toolbox-cache$$$ the resources of the other applications as they also reside on the same host as HASS. Maybe it does that with other host too.

So I modified `...python3.6/site-packages/hass_frontend/service_worker.js` (and the service_worker.js.gz) and added some more patterns to this row:

```
toolbox.router.get("/(home-assistant-polymer|api|cgi|cgi-bin|luci-static|munin|munin-cgi|grafana)/*", toolbox.networkOnly, {});
```

And all my apps work like before.

The problem should be the line with `toolbox.router.get("*", toolbox.fastest, {});` which adds everything else to the cache (as I understand).

I would really appreciate if a more generic solution could exist to achieve this. Thanks in advance!

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Hosting other apps on the same domain as Home Assistant is not supported. Just block the service worker file in your Apache config and you're fine.
