### ISSUE TITLE
Home assistant web interface constantly  connecting/disconnecting websocket

### ISSUE THREAD

**Issue by charbelsarkis** [home-assistant/home-assistant-polymer#1281]
Home Assistant release with the issue: 0.71.0
Home-assistant polymer with issue: tested on 20180613.0 and 20180608.0b0

Browser and Operating System:
Home Assistant running on ubuntu 18
Python version: 3.6.5
Using node v8.11.1 with npm v5.6.0

**Description of problem:**
Home assistant web interface constantly  connecting/disconnecting websocket
![capture1](https://user-images.githubusercontent.com/39876671/41342752-b07fbea8-6f05-11e8-928d-ab618006da88.PNG)
![capture](https://user-images.githubusercontent.com/39876671/41342753-b0a7158e-6f05-11e8-94cc-9ddb6b4d90cc.PNG)

. 
No error logs even at debug level 

recurring log:
persistent_notification.notification=notifying; title=Welcome Home!, message=Here are some resources to get started:
Jun 13 12:05:02 HASS hass[2254]:  - [Configuring Home Assistant](https://home-assistant.io/getting-started/configuration/)
Jun 13 12:05:02 HASS hass[2254]:  - [Available components](https://home-assistant.io/components/)
Jun 13 12:05:02 HASS hass[2254]:  - [Troubleshooting your configuration](https://home-assistant.io/docs/configuration/troubleshooting/)
Jun 13 12:05:02 HASS hass[2254]:  - [Getting help](https://home-assistant.io/help/)
Jun 13 12:05:02 HASS hass[2254]: To not see this card popup in the future, edit your config in
Jun 13 12:05:02 HASS hass[2254]: `configuration.yaml` and disable the `introduction` component. @ 2018-06-13T12:04:10.176304+03:00>, <state sun.sun=above_horizon; next_dawn=2018-06-14T01:38:05+00:00, next_dusk=2018-06-13T16:08:10+00:00, next_midnight=2018-06-13T20:53:24+00:00, next_noon=2018-06-14T08:53:18+00:00, next_rising=2018-06-14T02:03:45+00:00, next_setting=2018-06-13T15:42:32+00:00, elevation=87.07, azimuth=241.62, friendly_name=Sun @ 2018-06-13T12:04:10.421730+03:00>, <state sensor.yr_symbol=1; attribution=Weather forecast from met.no, delivered by the Norwegian Meteorological Institute., friendly_name=yr Symbol, entity_picture=https://api.met.no/weatherapi/weathericon/1.1/?symbol=1;content_type=image/png @ 2018-06-13T12:04:11.301726+03:00>, <state persistent_notification.config_entry_discovery=notifying; title=New devices discovered, message=We have discovered new devices on your network. [Check it out](/config/integrations) @ 2018-06-13T12:04:23.870788+03:00>, <state media_player.kd65x8500c=off; friendly_name=KD-65X8500C, supported_features=21437 @ 2018-06-13T12:04:23.985891+03:00>, <state media_player.mibox3=off; friendly_name=MIBOX3, supported_features=21437 @ 2018-06-13T12:04:24.401452+03:00>]}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378682880: Closed connection
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 INFO (MainThread) [homeassistant.components.http.view] Serving /api/websocket to 172.16.100.100 (auth: True)
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Connected
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'subscribe_events', 'event_type': 'state_changed', 'id': 2}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Sending {'id': 2, 'type': 'result', 'success': True, 'result': None}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'subscribe_events', 'event_type': 'component_loaded', 'id': 3}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'subscribe_events', 'event_type': 'service_registered', 'id': 4}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'subscribe_events', 'event_type': 'service_removed', 'id': 5}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'get_states', 'id': 6}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Received {'type': 'frontend/get_translations', 'language': 'en', 'id': 7}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Sending {'id': 3, 'type': 'result', 'success': True, 'result': None}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Sending {'id': 4, 'type': 'result', 'success': True, 'result': None}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Sending {'id': 5, 'type': 'result', 'success': True, 'result': None}
Jun 13 12:05:02 HASS hass[2254]: 2018-06-13 12:05:02 DEBUG (MainThread) [homeassistant.components.websocket_api] WS 140375378683216: Sending {'id': 6, 'type': 'result', 'success': True, 'result': [<state persistent_notification.notification=notifying; title=Welcome Home!, message=Here are some resources to get started:

Javascript error:
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection._handleClose @ haws.es.js:1
states:1 Uncaught (in promise) {type: "result", success: false, error: {…}}
Promise.then (async)
_loadPanels @ app.js:389
reconnected @ app.js:244
(anonymous) @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.fireEvent @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.setSocket @ haws.es.js:1
(anonymous) @ haws.es.js:1
Promise.then (async)
(anonymous) @ haws.es.js:1
setTimeout (async)
c @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection._handleClose @ haws.es.js:1
states:1 Uncaught (in promise) {type: "result", success: false, error: {…}}
Promise.then (async)
loadBackendTranslations @ app.js:131
reconnected @ app.js:243
(anonymous) @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.fireEvent @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.setSocket @ haws.es.js:1
(anonymous) @ haws.es.js:1
Promise.then (async)
(anonymous) @ haws.es.js:1
setTimeout (async)
c @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection._handleClose @ haws.es.js:1
states:1 Uncaught (in promise) {type: "result", success: false, error: {…}}
Promise.then (async)
_loadPanels @ app.js:389
reconnected @ app.js:244
(anonymous) @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.fireEvent @ haws.es.js:1
./node_modules/home-assistant-js-websocket/dist/haws.es.js.Connection.setSocket @ haws.es.js:1
(anonymous) @ haws.es.js:1
Promise.then (async)
(anonymous) @ haws.es.js:1
setTimeout (async)

**Comment by c727** [comment]
"Using node v8.11.1 with npm v5.6.0"
What are you trying to do here?

**Comment by charbelsarkis** [comment]
I am in a development environment.
Forgot to explicitly mention that....

**Comment by c727** [comment]
Have you followed these instructions?
https://developers.home-assistant.io/docs/en/frontend_development.html

**Comment by c727** [comment]
...You will also need dev branch of home-assistant main repo as there are changes related to web sockets

**Comment by charbelsarkis** [comment]
Yes of course.
-Bootstrap script completes successfully 
- develop script running with no errors

**Comment by charbelsarkis** [comment]
Aha, thanks for the hint. i'll try that

**Comment by balloob** [comment]
Make sure you run latest backend and frontend when in development.
