### ISSUE TITLE
Pages not loading except Overview

### ISSUE THREAD

**Issue by KapJI** [home-assistant/home-assistant-polymer#1287]
**Home Assistant release with the issue:**

0.71.0

**Last working Home Assistant release (if known):**
0.69.0

**Browser and Operating System:**

Latest Chrome, Safari, Firefox on macOS 10.13.4

**Description of problem:**

All pages except Overview (/states) are not loading. Downgrading to 0.69.0 fixes this. But starting from 0.70.0 it doesn't work.

Also, some menu icons are missing but this is probably a separate issue because it started from 0.71.0
![screen shot 2018-06-16 at 12 32 01 pm](https://user-images.githubusercontent.com/3767331/41498578-21bc0224-7169-11e8-9737-ff5e13bf4169.png)

**Javascript errors shown in the web inspector (if applicable):**
```
GET /undefined 404
```

**Additional information:**
It still doesn't work with the latest backend. It uses frontend version 20180615.0.

But if I serve frontend in developer mode with `script/develop` everything works both with current release 0.71.0 and dev versions of the backend.

hass is running inside virtualenv on Debian Sid but when I installed the same developer version of frontend with pip and ran `hass --skip-pip` it didn't work and seemed to be using the old version of frontend because some widgets looked differently from developer mode. (I'm sure I cleared cache and fully reloaded page).

**Comment by balloob** [comment]
When clearing the cache, did you also remove the service worker? (In chrome go to dev tools, application, to clear cache + service workers)

Also, try disabling all your browser extensions

**Comment by balloob** [comment]
When you run in development mode btw, make sure both frontend and backend are running latest commit.

**Comment by KapJI** [comment]
Or I figured out what was wrong.
Before I started using virtualenv, homeassistant put its deps to ~/.homeassistant/deps/
But when running from virtualenv it was still using those packages which become very old even while newer versions was available inside virtualenv. So that's the issue in hass, not it frontend.

**Comment by balloob** [comment]
hmm, yes, that is a good point. I think that we should remove the `<config>/deps` folder when running in a virtual env.

**Comment by balloob** [comment]
(closing it here as it's not a frontend issue)
