### ISSUE TITLE
Calendar panel issues in 0.72.0b2

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1289]
**Home Assistant release with the issue:** 0.72.0b2

**Last working Home Assistant release (if known):** -

**Browser and Operating System:**
Win 7, Chrome 67

**Description of problem:**

```yaml
demo:
```

- [ ] 1. events missing
- [ ] 2. vertical lines missing
- [ ] 3. localization does not work, it requires `import 'moment/locale/de';` etc

![cal](https://user-images.githubusercontent.com/11984118/41512037-ee12418e-7282-11e8-943c-04ff8208df6e.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
1 & 2 don't appear running frontend dev

**Comment by balloob** [comment]
The events seems to be provided correctly to the React component but are not getting rendered 🤔 

![image](https://user-images.githubusercontent.com/1444314/41514854-2d413212-7278-11e8-813b-cc5c6f760c63.png)

I sadly can't figure out what is going on. I hope it's not an issue with preact-compat as that would mean that a fix is a lot harder.

**Comment by balloob** [comment]
CC @titilambert

**Comment by balloob** [comment]
To debug this:

- add `import 'preact/debug'` to `ha-panel-calendar.js`
- open `node_modules/preact/debug.js` and change the `NODE_ENV` check to be always `true`
- Compile frontend in prod mode with `NODE_ENV=production webpack`

**Comment by titilambert** [comment]
Hello,
I don't understand why you have this issues. I just made a test with the last commit (backend 0.72b4 and frontend master)
And I have this:
![5867a567-78c2-4003-88f2-9a87bc03a1ca](https://user-images.githubusercontent.com/47721/41598604-a38a1142-739e-11e8-81ff-0d5d242da1a2.png)

This only issue is the localization.
So maybe I have some "cache" ?!

Now I will try the debug method from @balloob

**Comment by titilambert** [comment]
I can not reproduce it :(
When I run this:
`NODE_ENV=production node_modules/webpack/bin/webpack.js`
The terminal is stuck and nothing appends even with `--debug` and/or `--verbose`

**Comment by c727** [comment]
you have to do a build.
you can also test (without frontend dev ofc) in home-assistant dev branch or the current HA beta release `pip3 install --upgrade --pre homeassistant`

**Comment by titilambert** [comment]
I just reproduced the issue.
You can add an other issue: View change is not working

**Comment by balloob** [comment]
View change is not working because of string ref. I feel like it's either the minifier or preact compat aliasing that is breaking it in a prod build

**Comment by titilambert** [comment]
@balloob do you have an idea how to fix that ?

**Comment by titilambert** [comment]
@balloob I think you're right !
When I run the webpack commit I find this in the logs:
```
...
    chunk   {14} 76166c9db7232564086e.chunk.js, 76166c9db7232564086e.chunk.js.map (panel-calendar) 16 KiB <{46}> ={13}= ={3}= ={4}= [rendered]
        > ../panels/calendar/ha-panel-calendar.js [] 97:17-107
     [586] ./src/panels/calendar/ha-panel-calendar.js + 1 modules 16 KiB {14} [depth 3] [built]
           [no exports]
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/app-layout/app-header-layout/app-header-layout.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/app-layout/app-header/app-header.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/app-layout/app-toolbar/app-toolbar.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/paper-card/paper-card.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/paper-checkbox/paper-checkbox.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/paper-item/paper-item.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/paper-listbox/paper-listbox.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/polymer/lib/utils/html-tag.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/@polymer/polymer/polymer-element.js
           ModuleConcatenation bailout: Cannot concat with ./node_modules/moment/moment.js (<- Module is not an ECMAScript module)
           ModuleConcatenation bailout: Cannot concat with ./node_modules/preact-compat/dist/preact-compat.es.js (<- Module uses injected variables (process))
           ModuleConcatenation bailout: Cannot concat with ./node_modules/react-big-calendar/lib/index.js (<- Module is not an ECMAScript module)
           ModuleConcatenation bailout: Cannot concat with ./node_modules/react-big-calendar/lib/utils/dates.js (<- Module is not an ECMAScript module)
           ModuleConcatenation bailout: Cannot concat with ./src/components/ha-menu-button.js
           ModuleConcatenation bailout: Cannot concat with ./src/mixins/events-mixin.js
           ModuleConcatenation bailout: Cannot concat with ./src/mixins/localize-mixin.js
           ModuleConcatenation bailout: Cannot concat with ./src/resources/ha-style.js
           import() ../panels/calendar/ha-panel-calendar.js  ./src/layouts/partial-panel-resolver.js 97:17-107
           | ./src/panels/calendar/ha-panel-calendar.js 11.7 KiB [depth 3] [built]
           |     [no exports]
           |     ModuleConcatenation bailout: Module is referenced from these modules with unsupported syntax: ./src/layouts/partial-panel-resolver.js (referenced with import())
           |     import() ../panels/calendar/ha-panel-calendar.js  ./src/layouts/partial-panel-resolver.js 97:17-107
           | ./src/panels/calendar/ha-big-calendar.js 4.25 KiB [depth 4] [built]
           |     [no exports]
           |     [no exports used]
           |     harmony side effect evaluation ./ha-big-calendar.js  ./src/panels/calendar/ha-panel-calendar.js 30:0-30
...
```

**Comment by patchedsoul** [comment]
This is still broken after applying 0.72.1 (macOS HS, Safari, and Chrome)
[https://imgur.com/a/miztEEi](https://imgur.com/a/miztEEi)

**Comment by sdomotica** [comment]
Same issue for me 0.72.1
https://community.home-assistant.io/t/calendar-component/57916/11
Bye
Sandro

**Comment by balloob** [comment]
I should have disabled it. Will do so in a hot fix

**Comment by iantrich** [comment]
@balloob Do you think we'll continue to pursue this panel? Might be better suited for a simpler card within Lovelace

**Comment by iantrich** [comment]
Closing with no response
