### ISSUE TITLE
Fix weather card imperial units

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1313]
- visibility
- air pressure

**Comment by mtl010957** [comment]
Unfortunately, this fix didn't completely fix the issue. If using Dark Sky as the weather provider with "us" units, it returns the air pressure in millibars, not inches of mercury. The fix will be more complicated and probably needs to be handled architecturally per [#10](https://github.com/home-assistant/architecture/issues/10).
