### ISSUE TITLE
Support hebrew RTL in HA UI

### ISSUE THREAD

**Issue by dindan100** [home-assistant/home-assistant-polymer#1320]
Home Assistant release with the issue: 0.71.0
Last working Home Assistant release (if known): N/A
Browser and Operating System:
ALL

Description of problem:

HA is supporting hebrew translation under configurtion which seems to be working just fine however hebrew (and arabic) is written from right to left and not from left to right (e.g: english)
This means that the HA UI is basicaly not supporting hebrew and it looks funny.

some exmaples to make things clear (will try to check every aspect of the GUI if asked):

1. The all Home assitence frame should be alinged to the right and not to the left (i am not an expert so my suggestions is that this will done by checking the configurted language upon start and using the dir="rtl" to the html tag

2. All objects (including developer tool) under the  Home assitence frame should be alinged to the right and not to the left in such way the the relvent icon will apear to the right and the title of the object to the left  (probably and html tag).

3. Main page title should be alinged to the right and microphone symbol to the left (this can be checked agnist the current title value upon start, if it english leave as is and its hebrew align to the right.

4. Any object title in the main screen should be alinged to the right, in this exmaple the אוטומציה is the hebrew translation for automation and should be alined to the right, the current value buttons at the picture are set properly as they are in english but if there will be another one written in hebrew than it should be vice versa  

![image](https://user-images.githubusercontent.com/29107749/41774966-8b43aed4-762a-11e8-9c7f-c84d7398b7ba.png)

Thanks! and let know if there;s something else i can assit you with!

**Comment by c727** [comment]
Duplicate and discussed here https://github.com/home-assistant/architecture/issues/34
