### ISSUE TITLE
History card: long entity name are cut off

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1323]
![screen_shot_2018-06-22_at_14 08 00](https://user-images.githubusercontent.com/11984118/41780331-b674fb4e-7634-11e8-88f3-641cea1384fa.png)

**Comment by fanthos** [comment]
The cutoff is by design. It should make devices with small screen work better when the entity name is longer.

**Comment by iantrich** [comment]
This looks to be acceptable on newer builds

![image](https://user-images.githubusercontent.com/1287159/55116595-cf602c80-50b5-11e9-8cfb-e801130053d2.png)

Cutting off the end of the text instead of the beginning
