### ISSUE TITLE
Custom Panel race condition resulting in inaccessible UI/config/etc for existing HassIO deployments

### ISSUE THREAD

**Issue by patchedsoul** [home-assistant/home-assistant-polymer#1326]
**Home Assistant release with the issue:**
0.72

**Last working Home Assistant release (if known):**
n/a

**Browser and Operating System:**
MacOS High Sierra / Safari

**Description of problem:**
Custom Panel race condition resulting in inaccessible UI/config/etc for existing HassIO deployments - in an existing HassIO deployment upon upgrading seemingly an offending custom panel entry in configuration.yaml, creates an inaccessible/blocking UI condition, which prevents access to other HASSIO add-ons (like IDE, terminal, etc). This makes resolution of the offending yaml entry, far more difficult. 
[screenshot](https://imgur.com/SOE0p41)

**Javascript errors shown in the web inspector (if applicable):**
```
n/a
```

**Additional information:**
n/a

**Comment by DyArt** [comment]
I have the same problem. How can I see which panel causes this problem?

**Comment by balloob** [comment]
Can you repro this in a browser in incognito mode?

**Comment by frenck** [comment]
I can repro this constantly, MacOS Chrome (Including incognito mode).

2 files stay in pending state and eventually fail: 

- custom_panel.js
- entrypoint.js

![image](https://user-images.githubusercontent.com/195327/42123364-fedb7788-7c50-11e8-9520-0005c6050c7d.png)

![screen shot 2018-06-30 at 10 31 07](https://user-images.githubusercontent.com/195327/42123366-0dc53d38-7c51-11e8-89e2-8957365194ca.png)

So far I have concluded that this only happy to me if I enable SSL. I've ensure my reverse proxy was not a factor in this, by add-ing the SSL certs straight into HA (problem persists).

**Comment by frenck** [comment]
Removed my comments, since I've found the issue to be my own and not related.

**Comment by patchedsoul** [comment]
closing as this was a caching issue from previous config
