### ISSUE TITLE
Conditionally load promise polyfill 

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#134]
To support some older browsers, let's conditionally include a promise polyfill.

**Comment by balloob** [comment]
Can be added as a standalone script that gets included

**Comment by balloob** [comment]
Quote from another PR https://github.com/home-assistant/home-assistant-polymer/pull/145#issuecomment-256448567 :
> The promise polyfill should be added to the static folder in HA repo and should be loaded before core.js right here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/frontend/templates/index.html#L90

**Comment by NovapaX** [comment]
I'm going to close this.
I'm not under the impression we lack browser support.
If we do, we should make a new issue with more details, based on current situation.
