### ISSUE TITLE
Scrolling on hassio logs not working as expected

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-polymer#1350]
**Home Assistant release with the issue:**

0.72.1

**Browser and Operating System:**

Chrome

**Description of problem:**

Scrolling on the log card can overflow the page and is not scrolling correctly (especially on mobile devices)

**Comment by frenck** [comment]
Screenshot showing the issue:

![image](https://user-images.githubusercontent.com/195327/41996575-9ca4eff6-7a55-11e8-8d81-9a5dffae7785.png)

**Comment by timmo001** [comment]
Why is this issue closed? It is still an a problem: https://photos.app.goo.gl/sbQ2J946wmdstunE9
