### ISSUE TITLE
Hass.io add-on cards disappear underneath the top navbar

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#1351]
**Home Assistant release with the issue:**

Hass.io Generic Linux
0.72.1 (supervisor 109).

**Last working Home Assistant release (if known):**

Unsure, this thing is nagging me for a long time already

**Browser and Operating System:**

![image](https://user-images.githubusercontent.com/195327/41996956-c5501bdc-7a56-11e8-8180-16345dab4d4b.png)

**Description of problem:**

Sometimes, when I toggle/jump between the add-on store and the Hass.io dashboard,
it card disappear underneath the menu/header bar thingy.

**Javascript errors shown in the web inspector (if applicable):**

Nope. All clean.

**Additional information:**
![image](https://user-images.githubusercontent.com/195327/41997030-173321d8-7a57-11e8-92b0-2c4bbd28a7dd.png)

**Comment by timmo001** [comment]
This may be a global frontend issue. I have just had the same happen when backing out from the customisation section in settings:

![image](https://user-images.githubusercontent.com/28114703/42000316-332dcd56-7a58-11e8-93ba-8e426038ed2c.png)

**Comment by c727** [comment]
^Ok this didn't fix it
