### ISSUE TITLE
Hassio: Add upload option in snapshot UI for snapshots

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-polymer#1356]
**Home Assistant release with the issue:**

Hassio 109/ HA .72.1
**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

Any
**Description of problem:**

Add upload option for snapshots.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by c727** [comment]
It's about Pascal to add support for HTML form uploads
