### ISSUE TITLE
Climate more-info does not open anymore.

### ISSUE THREAD

**Issue by turbokongen** [home-assistant/home-assistant-polymer#136]
I cannot open climate more-info anymore due to some recent change in the frontend.
Running dev.
This is what the console tells me:

![image](https://cloud.githubusercontent.com/assets/16622752/19619473/c25a32b8-9868-11e6-883f-775f42596a2c.png)

**Comment by justweb1** [comment]
@turbokongen I have not changed anything on climate. Rebuild the frontend `script/build_frontend`

**Comment by turbokongen** [comment]
I am only running what is fetched from the repo.
Dev from the backend and production from frontend.

**Comment by justweb1** [comment]
Issue resolved in .31
