### ISSUE TITLE
Lovelace Weather Forecast: TypeError: this.lastChild.setProperties is not a function

### ISSUE THREAD

**Issue by quthla** [home-assistant/home-assistant-polymer#1376]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

```
    - type: weather-forecast
      entity: weather.weather
```

Weather entitiy is of platform yweather
**Javascript errors shown in the web inspector (if applicable):**
`TypeError: this.lastChild.setProperties is not a function`
 `hui-legacy-wrapper-card.js:30:6`

**Additional information:**

**Comment by c727** [comment]
incomplete issue template and false repo
