### ISSUE TITLE
Service Dev tools Empty field with linefeed not posting

### ISSUE THREAD

**Issue by kellerza** [home-assistant/home-assistant-polymer#140]
If the `Serive Data` field has a spare linefeed / `Enter` in it the data fails to post.

Expected behavior: Whitespace (and linefeeds) should be trimmed before validating the user input

**Comment by justweb1** [comment]
@kellerza is this just after the .31 update?

**Comment by balloob** [comment]
Fixed in 7a4b6f7db9b60f39bdfb0d860921b26ff9e8f6d5
