### ISSUE TITLE
Plant Card Isn't Displaying All Values

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#1409]
**Home Assistant release with the issue:**
0.73.0.dev0

**Last working Home Assistant release (if known):**
I'm running dev builds, was working okay on an early 0.73 one, but is broken on one built today. To confuse matters, I only added the entity_picture to it today, at the same time.

**Browser and Operating System:**
Tried on Windows 10 using Chrome (with cache cleared), Firefox, as well as via the iOS app. All display the same symptom.

**Description of problem:**
As per the below screenshot, humidity, temp and battery won't show values. Clicking on their placeholder brings up the more info with values and graphs as expected.
![image](https://user-images.githubusercontent.com/24840952/42306562-a0c31f8a-806e-11e8-8cd2-f9a12e683be0.png)

**Javascript errors shown in the web inspector (if applicable):**
Can't see any.

**Additional information:**
I'm also seeing this on my Lovelace plant card.

**Comment by c727** [comment]
Simulated plant needs some time to send the correct data after HA was started. That's an issue in the backend component
