### ISSUE TITLE
Can't disarm when alarm in 'arming' state

### ISSUE THREAD

**Issue by BioSehnsucht** [home-assistant/home-assistant-polymer#1415]
**Home Assistant release with the issue:**
0.68.1 (haven't yet tested on latest - but I'm guessing this has been the case always)

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Chrome / Windows

**Description of problem:**
This might be working as intended, and I should implement exit timer state differently. I'm working on Elk M1 alarm panel integration and while setting `pending` works fine for entry timer (and `triggered` when timer reaches zero and still armed & alarming), setting `arming` on exit timer means the HASS UI won't allow you to input code to disarm (and this cancel the exit timer). You have to wait until the system is in `armed` state before the UI lets you disarm. `pending` lets me disarm, though. If there's a "more correct" way to reflect exit timer in the state of the `alarm_control_panel` entity, please let me know. Otherwise I'd like to propose a change to allow disarming during `arming` state.

**Javascript errors shown in the web inspector (if applicable):**
(none)

**Additional information:**
(none)

**Comment by gwww** [comment]
I have this problem also.

It appears that https://github.com/home-assistant/home-assistant-polymer/blob/e048060c72a3e16e63e7f88ed5e40e9d96971686/src/dialogs/more-info/controls/more-info-alarm_control_panel.js#L137-L138 should also check for `"arming"` and `"disarming"`.

**Comment by cgarwood** [comment]
Closing as #1549 has been merged
