### ISSUE TITLE
Color selector window jumps around

### ISSUE THREAD

**Issue by Fusseldieb** [home-assistant/home-assistant-polymer#1430]
**Home Assistant release with the issue:**

0.73.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Hass.io running on a RPi 3 - Chrome on Windows 10 (67.0.3396.99 x64)

**Description of problem:**

In certain screen sizes the color selector jumps around. I attached a GIF to show what it looks and feels like. This happens mostly when I'm using my notebook (1366x768) and using Chrome (maximized). To show the issue in a not-too-large GIF, I was able to reproduce this issue by zooming out the page and windowing Chrome, as you can see below.
![polymerbug](https://user-images.githubusercontent.com/4715129/42439978-b587b0e2-833a-11e8-8231-251e9331e96a.gif)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
It seems that setting the element `ha-color-picker` to 305px height solves this issue, but that's only a tip.

**Comment by balloob** [comment]
Looks like the slider increases its height when being dragged, causing a scrollbar if not enough vertical space is available.

**Comment by iantrich** [comment]
I am unable to replicate this on 0.90. Is this still an issue for you? The light more-info was recently reworked a bit.

**Comment by iantrich** [comment]
Closing with no reply
