### ISSUE TITLE
feature request: UI upload option for hassio snapshots

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-polymer#1441]
**Home Assistant release with the issue:**

Any
**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

N/A
**Description of problem:**

There is an option in the UI to download snapshots but no upload option.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by cgarwood** [comment]
Closing in favor of #1710
