### ISSUE TITLE
Graph Y Size

### ISSUE THREAD

**Issue by Redferne** [home-assistant/home-assistant-polymer#1453]
Would it be possible to automatically resize graphs to the available browser window size? Please see the attached screenshot for a example. It is quite difficult to get a good overview of any sudden spikes in the graph.

![image](https://user-images.githubusercontent.com/2379821/42777818-7bdd4576-893b-11e8-81d5-5c8666a9788d.png)

**Comment by balloob** [comment]
Did you try double clicking on the name?

**Comment by Redferne** [comment]
Yes Sir I did ☺️ It gave me the size in the screenshot. The default graph when opening/clicking a entity is somewhat the size of a postage stamp. I was expecting clicking the title would give me almost all full-screen view.
