### ISSUE TITLE
Trying to dim group lights throws a TypeError

### ISSUE THREAD

**Issue by TheJulianJES** [home-assistant/home-assistant-polymer#1466]
**Home Assistant release with the issue:**
0.73.2 // 0.74

**Last working Home Assistant release (if known):**
Not sure (maybe(!) 0.72 // 0.71)

**Browser and Operating System:**
Windows 10 (1803) and Chrome 67.0.3396.99 (64-Bit)

**Description of problem:**
In previous versions of Home Assistant you could click on the header of a group only consisting of lights and then dim or change the color of all the lights in the group. This is no longer possible and throws an error. (The color wheel and brightness slider don't appear anymore.)
![image](https://user-images.githubusercontent.com/6409465/42890667-ae2bca20-8aad-11e8-8786-70e154b20647.png)

**Javascript errors shown in the web inspector (if applicable):**
```
http://zhass.io:8123/frontend_latest/b8e8990946547661bcfb.chunk.js:618:268 Uncaught TypeError: Cannot read property 'length' of undefined
```

**Additional information:**
Issue https://github.com/home-assistant/home-assistant/issues/15513 was created in the home assistant issue tracker.

**Comment by mealan** [comment]
The lights group top part would have to contain sub lights that had that feature, if there was one light that didn't it would not appear. 

It seems like it's no longer appearing for anything, even groups that only have the same capability. at least that's what I'm experiencing with my lifx and other dimmable groups. 

Thanks,
Alan

**Comment by smuggyuk** [comment]
I've noticed this too and was going to raise an issue, but found this one so will support / follow this one instead.

This is still an issue in 0.74, and is also present in the Lovelace version of the UI.

This is a really frustrating bug for those of use who have multiple bulbs in a room and need to be able to control the brightness/colour of them (but still need individual light control so can't use light group, and don't want to/can't specify rooms in Hue) so hopefully someone can figure out why this has broken.  (I've tried looking through the code to determine where the issue is myself but with no luck).

**Comment by gluap** [comment]
This issue also affects uniform groups of other types of devices. I'm observing this with ``cover`` type devices (formerly a combined slider was available to set cover position, now it does not appear any more for the same group. Was working on 0.70.0, broken on 0.74.0. The same TypeError mentioned above is raised:

    http://192.168.1.220:8123/frontend_latest/9c70f781d9a3bcaf521c.chunk.js:618:268 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by smuggyuk** [comment]
Hi @balloob , based on the comments above the issue may have been introduced with a change you migrated?  If you've not seen this issue already could you take a look at it, it affects LoveLace too, but I've not been able to unpick the code to understand where the issue originates.  Thanks in advance!

**Comment by mealan** [comment]
this might be related, says it will be corrected in the next beta however they mention languages, I'm using English with the same issue. will wait and see.

**Comment by awarecan** [comment]
I barely check the "legacy" UI since lovelace released, until last night I was testing 0.76.0b2 beta. I just hit the same issue with very a simple setup
```yaml
# groups.yaml
climate:
  name: Climate
  entities:
    - climate.living_room
```

Browser console log:
```
more-info-group.js:60 
Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLElement.computeStates (more-info-group.js:60)
    at D (property-effects.js:815)
    at Object.E [as fn] (property-effects.js:432)
    at x (property-effects.js:159)
    at w (property-effects.js:125)
    at property-effects.js:409
    at HTMLElement._propertiesChanged (property-effects.js:405)
    at HTMLElement._flushProperties (properties-changed.js:335)
    at HTMLElement._flushProperties (property-effects.js:1555)
    at HTMLElement.ready (property-effects.js:1660)
```

**Comment by TheJulianJES** [comment]
On Home Assistant 0.76.0:
```Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLElement.computeStates (more-info-group.js:60)
    at D (property-effects.js:815)
    at Object.E [as fn] (property-effects.js:432)
    at x (property-effects.js:159)
    at w (property-effects.js:125)
    at property-effects.js:409
    at HTMLElement._propertiesChanged (property-effects.js:405)
    at HTMLElement._flushProperties (properties-changed.js:335)
    at HTMLElement._flushProperties (property-effects.js:1555)
    at HTMLElement.ready (property-effects.js:1660)```
```http://hass.io:8128/frontend_latest/df03c3bc2add9d4f4eab.chunk.js:618:268 Uncaught TypeError: Cannot read property 'length' of undefined```

**Comment by mealan** [comment]
yes I am not sure why this was closed?

**Comment by awarecan** [comment]
I can confirmed my issue has been fixed. Can you make sure you are running on latest frontend? Try Ctrl+F5 force refresh.

**Comment by TheJulianJES** [comment]
It still doesn't work. Although it was mentioned that the issue has to do something with climate (groups)?
I actually don't have anything like that and I'm just opening the "more-info" dialog on a group full of lights (no lovelace).

**Comment by awarecan** [comment]
They are sharing the same more-info-group.js code base.

As you log showed, the exception was thrown at `frontend_latest/df03c3bc2add9d4f4eab.chunk.js`. However, I cannot find this js file in the 0.76 frontend
```shell
pi@hassbian:/srv/homeassistant/lib/python3.5/site-packages/hass_frontend $ ll d*.js
-rw-r--r-- 1 homeassistant homeassistant 17225 Aug 17 14:19 d49e145c6f4386e42e11.chunk.js
-rw-r--r-- 1 homeassistant homeassistant   230 Aug 17 14:19 d8010a429cf327564ff0.chunk.js
-rw-r--r-- 1 homeassistant homeassistant 14513 Aug 17 14:19 d92ef4603b52b7f51cde.chunk.js
```

**Comment by TheJulianJES** [comment]
Mhm, that's weird. Restarted Home Assistant and also did a "Force Refresh" like you asked for.
https://i.imgur.com/yL5T1W7.png
Same issue is also present in the latest version of Firefox (otherwise in Chrome) (for me atleast). (Never used Hass there before).

**Comment by mealan** [comment]
It's still not fixed for me either. groups of lights that use to be dimmable no longer have that option still. full ui refresh and browser cache cleared.

**Comment by awarecan** [comment]
@mealan you are not on 0.76. The file you should was created on Aug 6, and 0.76 just released yesterday.

**Comment by sgripsga** [comment]
Same problem, no dimmable options for group lights and I’m running 0.76

**Comment by mealan** [comment]
@awarecan ohhhh, i'm pretty sure i know what version i'm on  :)

Home Assistant
0.76.0

**Comment by mealan** [comment]
@awarecan how does this get reopened?

**Comment by awarecan** [comment]
@mealan I am sure your front end is not on 0.76, please check clean your config/deps folder and try again.

**Comment by eemmeeuuffcc** [comment]
Same issue here.  I'm on 0.76.1

**Comment by mealan** [comment]
Might be getting closer, however not there yet. 
removed /deps folder that had the hass_frontend subfolder
rebooted
loaded page a new version of the front end is available, clicked refresh

clicked light group (still no dimming or color options)
same error
frontend_latest/df03c3bc2add9d4f4eab.chunk.js:618:268 Uncaught TypeError: Cannot read property 'length' of undefined
however, now I can't find that file either after looking, so it was in the HASS_frontend folder under deps.
now I'm not sure what component would be looking for that exact version or file name. 

Thanks for your assistance.

**Comment by TheJulianJES** [comment]
@mealan I'm now facing the same issue. Maybe the fix was only kind of a "workaround", to not throw the error (as the color wheel still doesn't show)?

**Comment by awarecan** [comment]
Like @TheJulianJES said, the fix resolve one front end issue, but may not be able bring the change group color feature back, please open a new issue along with new screenshot and console log if you have.

**Comment by mealan** [comment]
issue #1589 was opened in polymer.
