### ISSUE TITLE
Cannot focus to password field in Add User dialog

### ISSUE THREAD

**Issue by awarecan** [home-assistant/home-assistant-polymer#1468]
**Home Assistant release with the issue:**

Frontend: 20180718.0
Backend: dev branch

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Ubuntu 18.04 LTS
Firefox 61.0.1

**Description of problem:**

Maybe Firefox only issue, I won't be able to reproduce it in Chromium or Chrome
In the Add User dialog, I cannot focus on password field, it always change the focus back to username field in less than 1 second

**Javascript errors shown in the web inspector (if applicable):**
```
None
```

**Additional information:**
Screen Cast attached.

[Screencast from 07-18-2018 02:33:01 PM.zip](https://github.com/home-assistant/home-assistant-polymer/files/2207478/Screencast.from.07-18-2018.02.33.01.PM.zip)

**Comment by balloob** [comment]
I was testing it with FF experimental custom elements and shadow DOM enabled and there it worked all fine.

**Comment by awarecan** [comment]
Yes, indeed I did not enabled custom elements and shadow DOM. However, after I enabled those options, I still have same error on latest master branch. I can input in Name and Username fields, but cant focus on Password field.

**Comment by balloob** [comment]
I'm testing with Firefox Developer Edition 62.0b6 (64-bit) with disabled and it works fine.

**Comment by partofthething** [comment]
62.0.3 on Ubuntu 18.04 also can't add users. Curious about details on the workaround as well.

**Comment by iantrich** [comment]
@balloob tagging correct user

**Comment by balloob** [comment]
Disabled web components. However, WC will be enabled by default in 63 (making the UI a lot faster too).

**Comment by iantrich** [comment]
I'm unable to replicate this. Is this still an issue?

**Comment by partofthething** [comment]
Yes very much so on 0.81.5. If I click and type really fast I can get one character in at a time but it's a bit ridiculous. Definitely still an issue.

**Comment by partofthething** [comment]
Aha! It's actually a problem in an Ubuntu package: https://github.com/ibus/ibus/issues/2002
I installed [Diep's ibus-gtk3_1.5.17-3ubuntu4_amd64.deb](https://bugzilla.mozilla.org/show_bug.cgi?id=1405634) package and restarted firefox and it worked great. So this is not an issue in Home Assistant.
