### ISSUE TITLE
Integrations - optional fields are not optional

### ISSUE THREAD

**Issue by mindigmarton** [home-assistant/home-assistant-polymer#1472]
**Home Assistant release with the issue:**
0.73.2
home-assistant-frontend 20180708

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Chrome Version 67.0.3396.62
Firefox 61.0.1
Microsoft Edge 42.17134.1.0

Fedora 28
Windows 10

**Description of problem:**
Integrations entry UI shows 'User input malformed' when all required fields are filled, but optional fields are not. Filling in the optional field fixes the error.
It looks like all fields are passed to the server as empty strings. Meaning that an optional int / float fields always fails to parse the empty string, thus throwing an error.

**Javascript errors shown in the web inspector (if applicable):**
No errors in the console.

**Additional information:**
Good example is the Zone component. Radius has to be specified but is an optional field.

**Comment by mindigmarton** [comment]
Can this be confirmed? (still happens with the latest HASS) I'd like to integrate emulated_roku to use config entries, but it has a couple of optional fields, which should never be specified. Currently, you can't leave those fields empty, because it won't accept that.

**Comment by balloob** [comment]
I can confirm, just haven't had time for a fix yet. Could it be done without optional fields ? For example an optional boolean can still be passed in as true/false.

**Comment by mindigmarton** [comment]
The boolean field is True by default and default values don't seem to work either.
My current workaround is using str for everything (host, port, bool field), then using the correct voluptuous schema server side after sanitizing the input.
