### ISSUE TITLE
Climate controls no longer show set temperature in Lovelace UI

### ISSUE THREAD

**Issue by plinss** [home-assistant/home-assistant-polymer#1488]
**Home Assistant release with the issue:**

0.74

**Last working Home Assistant release (if known):**

0.73.2

**Browser and Operating System:**

Firefox 60 macOS and Chrome 67 macOS

**Description of problem:**

Climate controls no longer indicate set temperature in Lovelace UI.

After upgrading to 0.74 my climate controls now indicate the operation state, and the temperature units, but not the set temperature, e.g.:

    Downstairs Cooling        cool °F

where it used to indicate the set temperature and the current temperature, e.g.:

    Downstairs Cooling        cool 75 °F
                         Currently 77 °F

Note that the old UI still shows the set temperature and current temperature.

FWIW, I'm actually glad the current temperature no longer shows, given multiple climate controls per thermostat (heating and cooling) having the current temperature is redundant. I use the temperature sensor to indicate the current temperature elsewhere. If that's a bug, then an option to suppress it would be welcome.

**Javascript errors shown in the web inspector (if applicable):**
```
n/a
```

**Additional information:**

**Comment by dshokouhi** [comment]
I just filed this issue in UI schema, with screenshots and such:

https://github.com/home-assistant/ui-schema/issues/116
