### ISSUE TITLE
History page Period behavior

### ISSUE THREAD

**Issue by LordBoos** [home-assistant/home-assistant-polymer#1516]
**Home Assistant release with the issue:**
0.73.0

**Last working Home Assistant release (if known):**
unknown

**Browser and Operating System:**
Chrome 69.0.3493.3

**Description of problem:**
History page Period is confusing and not intuitive.
When I select current day and period of 3 days I expect that 3 days to the past will be shown but in fact it's 3 days to the future. On current day Period has no effect at all and seems like it's not working at all.
Is this behavior intentional? It would be much more intuitive to show past (selected period) days than showing future (selected period) days.

**Javascript errors shown in the web inspector (if applicable):**
```
none
```

**Additional information:**
none

**Comment by iantrich** [comment]
I agree, this is counter-intuitive. Wondering if we should just have a date range instead of a period instead?

**Comment by Boosik** [comment]
Yea that would IMHO be improvement.
