### ISSUE TITLE
Format date/time and numbers with browser locale

### ISSUE THREAD

**Issue by micw** [home-assistant/home-assistant-polymer#154]
I'm using chromium with german locale. Date and time formating is mixed 12/24h german/english. 

Example "Sunrise" Info-Popup with timechart:
Caption: "3 hours ago" (english)
Chart X-Asis: 10:00, 18:00, ... (24h format as used in germany)
Text "Setting in 5 hours 16:25" ("hours" english, time in 24h Format)
Text "Elevation 19.59" (english number format)

Mouseover-Popup on Timeline:
Sun: 4:27 nachm. - 7:24 vorm. ("nachm." is german for PM, "vorm." is german for "AM", Time is in 12h Format which is alomst never used in germany. It should be "16:27 - 7:24")
Dauer: 14.95 hours ("Dauer" label is german but the number ist in english format)

**Comment by justweb1** [comment]
@micw This is a duplicate issue. See https://github.com/home-assistant/home-assistant/issues/184
