### ISSUE TITLE
Unable to access hass.io menu

### ISSUE THREAD

**Issue by dmpanch** [home-assistant/home-assistant-polymer#1542]
Home Assistant:
0.75.1, installed from official recommended img to RPi 3 B+ (hassos_rpi3-1.9).

Browser and Operating System:
Chrome Version 68.0.3440.84 (Official Build) (64-bit)
Safari Version 12.0 (14606.1.30)
Firefox 57.0b14 (64-бит)
macOS Mojave 10.14 Beta (18A347e)

Description of problem:
Unable to access Hass.io menu - same issue as #1239 and #1329.

Error: `http://hassio.local:8123/frontend_latest/custom-panel.js 404 (Not Found)`

<img width="1280" alt="screen shot 2018-08-04 at 23 54 11" src="https://user-images.githubusercontent.com/4539449/43680405-a03471cc-9842-11e8-83e3-ab18eafb2a5c.png">

**Comment by Reiserx** [comment]
I updated last night both Home Assistant and Configurator and now I can't access hass.io or configurator. I can't even get into my back end on hassio.local:3218

**Comment by awarecan** [comment]
Duplicate as home-assistant/home-assistant#15816

**Comment by balloob** [comment]
This has been fixed in 0.75.1. Please clear your cache or try incognito window.
