### ISSUE TITLE
Cover tilt controls only shown if the SUPPORT_SET_TILT_POSITION is used

### ISSUE THREAD

**Issue by gpulido** [home-assistant/home-assistant-polymer#1546]
**Home Assistant release with the issue:**

0.75.0
**Last working Home Assistant release (if known):**

**Browser and Operating System:**

It happens on chrome for android and macos

**Description of problem:**

The cover tilt controls only appears if the SUPPORT_SET_TILT_POSITION supported_feature is added.
If the cover device only supports open / close /stop tilt and set the supported_features with only any of those features, the buttons on the card only appers if the SUPPORT_SET_POSITION is also added, which also includes the slider to set the position, the problem is that if the device doesn't support the set position the slider is useles for the user. 

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
@gpulido have you checked if this is true on Lovelace yet?

**Comment by gpulido** [comment]
Hello @iantrich 
Sorry for the late replay, I didn't know about lovelace until you named it. Just made a quick configuration using the jinja template and unfortunatelly the issue is still there. To show the up and down tilt buttons you need also to set the SUPPORT_SET_TILT_POSITION flag.
If you need me to test something else, please let me know
Gabriel

**Comment by iantrich** [comment]
This sounds like a backend issue to me. If the feature is not supported we're not going to display controls for it

**Comment by gpulido** [comment]
Hello,
Maybe I'm wrong, but I don't think is a backend issue. The UP / DOWN position buttons are shown even if the SUPPORT_SET_POSITION flag is not present. Why the TILT buttons behave different? For example in my backend at the end I have added the SUPPORT_SET_TILT_POSITION only to show the cover tilt controls and my backend does nothing with the til_position, it just ignores the info, so it can work without having the tilt_position.
Again, from my POW it should work the same way than the "normal" position controls...
