### ISSUE TITLE
Wrong translated message in spanish

### ISSUE THREAD

**Issue by etatus** [home-assistant/home-assistant-polymer#1555]
Hi there, I recently installed Home Assistant 0.75.2 and I detected a wrong message when you configure a switch (mqtt in my case) and you turn it on/off. Despite it works, the message always says there is an error:

“Error al llamar al servicio switch/turn_on”
“Error al llamar al servicio switch/turn_off”

In English the message is correct (no errors) and logs don't show errors, so I guess it is a problem related to the translation that maybe affects to other modules.

If the problem is that this part is not translated yet, I think it's better to display the correct message in English rather than a confusing error in Spanish when everything works fine (it took me a while to figure out what was happening)

**Comment by balloob** [comment]
See the docs on how to join the translation team and be able to fix it: https://developers.home-assistant.io/docs/en/internationalization_translation.html
