### ISSUE TITLE
Developer Tools links > 404: Not Found when opening in new Tab or Window

### ISSUE THREAD

**Issue by GaryOkie** [home-assistant/home-assistant-polymer#1556]
**Home Assistant release with the issue:**

75.2
**Last working Home Assistant release (if known):**
unsure

**Browser and Operating System:**

Both Chrome 68 & FireFox  on Windows 10.   
**Description of problem:**

When right-clicking the Developer Tools icons (States, Events, Templates, Info) to open them in a new browser tab or window, a "404 - Not Found" error results.   Only the Services link works properly.

The apparent issue here is the trailing "/" in the URL is OK when opening in the same tab, but not OK when opening in a new tab/window.   The Services link does not have a trailing "/", but all the other links do.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
simply removing the trailing / in the URL and refreshing the page in a new tab/window is a workaround to the issue.

**Comment by balloob** [comment]
fixed in next beta 👍
