### ISSUE TITLE
alarm_control_panel custom STATE_ALARM_* states not supported in UI

### ISSUE THREAD

**Issue by gwww** [home-assistant/home-assistant-polymer#1561]
**Home Assistant release with the issue:** 0.74

**Last working Home Assistant release (if known):** Never

**Browser and Operating System:** Chrome 67, OSX 10.12

**Description of problem:**
When adding a custom arming mode for an alarm_control_panel the UI does not recognize the custom arming mode.

For example, the ElkM1 alarm panel supports arming in vacation (custom state STATE_ALARM_VACATION) mode. There is no method to access vacation mode in the UI arming dialog. See https://github.com/gwww/ha-elkm1/blob/d4b82b0fa81f92119b45f0e89b06042a6b3bd8eb/alarm_control_panel/elkm1.py#L24-L35 for code under development.

What is the method to be able to arm a custom arming mode?

**Javascript errors shown in the web inspector (if applicable):** None

**Additional information:**
See related architectural issue https://github.com/home-assistant/architecture/issues/54. While this is issue manifests in the UI there is an underlying architectural issue of how to handle custom states.

**Comment by iantrich** [comment]
Is this an issue with the alarm-control-panel card in LL as well?

**Comment by iantrich** [comment]
Closing due to no reply
