### ISSUE TITLE
Cover controls icons missing for es5 on HA 0.75.3

### ISSUE THREAD

**Issue by mduran80** [home-assistant/home-assistant-polymer#1573]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
Not sure... possibly 0.71 or 0.72

**Browser and Operating System:**

I am using an iPad 2 (and another iPad 3) with iOS 9.3.5 (Safari and Companion App). The cover controls are shown correctly when displayed on an iOS > 11.

**Description of problem:**

I have several z-wave covers and the cover control icons have stopped displaying. The frontend javascript version is correctly detected as es5. Although the icons don't appear, the html entities are rendered (as shown in the screenshot below). The same happens to the automation icons.

![img_0003](https://user-images.githubusercontent.com/22393167/44197550-37718c00-a13f-11e8-898a-1dd9ff08f620.jpg)

![screen shot 2018-08-16 at 10 12 47](https://user-images.githubusercontent.com/22393167/44196989-c41b4a80-a13d-11e8-8f2a-51b4d1427970.png)

**Javascript errors shown in the web inspector (if applicable):**

![screen shot 2018-08-16 at 10 09 50](https://user-images.githubusercontent.com/22393167/44196930-97673300-a13d-11e8-8fdf-85dd18b9982e.png)

![screen shot 2018-08-16 at 10 10 15](https://user-images.githubusercontent.com/22393167/44196961-acdc5d00-a13d-11e8-9468-b41f8e278084.png)

![screen shot 2018-08-16 at 10 10 43](https://user-images.githubusercontent.com/22393167/44196965-b2d23e00-a13d-11e8-90ae-309860de9b50.png)

**Additional information:**

The home-assistant demo available in the website (version 0.28) displays the controls correctly

**Comment by balloob** [comment]
The es5 elements adapter is as expected, the `hass-icons` one is not.

**Comment by mduran80** [comment]
I agree @balloob , that's what I understood from reading previous comments (about es6 and the need to have the adapter to fail for es5) but I included it anyway just to complete the **javascript errors** section info.

By the way, the rest of the error message in `hass-icons` is `unexpected keyword 'const'. const declarations are not supported in strict mode`. 

[According to other forums](https://github.com/webpack/webpack-dev-server/issues/1101#issuecomment-330565601), the issue may be solved if the file is transpiled.
