### ISSUE TITLE
Lovelace an input_number entity

### ISSUE THREAD

**Issue by clyra** [home-assistant/home-assistant-polymer#1579]
**Home Assistant release with the issue:**  
0.75.3

**Last working Home Assistant release (if known):**
don't know

**Browser and Operating System:**
Safari and OSX

**Description of problem:**
When I select a lovelace panel which has a input_number entity I see Service System_log/write being called and this message on the logs:

Aug 16 21:29:16 ha hass[12142]: #033[31m2018-08-16 21:29:16 ERROR (MainThread) [frontend.js.latest.201808040] http://192.168.0.50:8123/frontend_latest/eb618cf11a4eca6918ea.chunk.js:266:14994 TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector("paper-slider").offsetWidth')#033[0m

Removing the input_number reference entity makes the error disappear. Below is my panel config:

- title: Treino
    cards:
    - type: entities
       title: Zfan
       entities:
        - fan.zwift_fan
        - input_number.zfan_speed    <-- removing this makes the error disappear
     - type: entities
       title: Temperatura
       entities:
        - sensor.temperature_158d000201f4e5
        - sensor.humidity_158d000201f4e5

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by clyra** [comment]
Maybe related to https://github.com/home-assistant/home-assistant-polymer/issues/1578 ?

**Comment by VDRainer** [comment]
Should be fixed in the next release.
https://github.com/home-assistant/ui-schema/issues/118
