### ISSUE TITLE
Profile badge/page and user config disappear when http trusted_networks enabled

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1584]
**Home Assistant release with the issue:**
0.76.1

**Last working Home Assistant release (if known):**
Don't know, reverted back until 0.75.0b5, but no change.

**Browser and Operating System:**
Latest Firefox on Ubuntu 18.04

**Description of problem:**
After enabling trusted_networks in configuration.yaml the profile badge and the user settings disappear.
No chance to edit users or change theme / language.

**Comment by balloob** [comment]
Yeah, we were a bit too optimistic and now theme/language is only available for people using new auth.
