### ISSUE TITLE
Icon/image for logged user

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#1594]
**Home Assistant release with the issue:**

0.76.2
**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Chrom, IE, Firefox
**Description of problem:**

Hi
When we have implement multiuser good option will be add option to user can setup image for icon user to view which user is logged. I think icon on the left menu…icon_user

Please add this feature

![icon_user](https://user-images.githubusercontent.com/16692223/44568331-8ee2ae00-a776-11e8-9b11-5ab1f1b2815f.jpg)

**Comment by balloob** [comment]
Please no feature request in the issues

**Comment by pepeEL** [comment]
Ok sorry
