### ISSUE TITLE
Option DELETE automatization

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#1596]
**Home Assistant release with the issue:**

0.76.2
**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

Hi
In automatization is option to edit automatization but dev lost about option delete automatization. Please maybe add as show on screen... Add three point and after click on three point show option to delete...
![delete_auto](https://user-images.githubusercontent.com/16692223/44569604-3f52b100-a77b-11e8-92d7-db1f2e344f3a.jpg)

**Comment by balloob** [comment]
Issues are not for feature requests
