### ISSUE TITLE
New Notifications in 0.77.0b0

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1597]
**Home Assistant release with the issue:**
0.77.0b0

**Last working Home Assistant release (if known):**
New Feature

**Browser and Operating System:**
Latest FF on Ubuntu 18.04

**Description of problem:**
Not sure if this should be an issue or a FR.

The new notifications solution is GREAT, only two things:
- The indication is a little inconspicuous and should follow themes.
  
![auswahl_142](https://user-images.githubusercontent.com/26381449/44609677-f5a8ab80-a7f8-11e8-8af8-93d726efc317.png)
- The notifications are gone after HA restart.

**Comment by VDRainer** [comment]
Thx @jeradM for the fast explanation.
I think i leave this open for a while for other users.
Will be closed after 0.77 comes out.

**Comment by balloob** [comment]
I don't want to keep issues open that are solved.
