### ISSUE TITLE
Ignore map zones in "map fit"

### ISSUE THREAD

**Issue by tenfire** [home-assistant/home-assistant-polymer#1598]
I feel that it it is unnecessary to fit every zone as default when opening the map. You usually don't use the map to look up where the zones are, you use it to look up where people/things are. Would it not be better to ignore zones when calculating the default focus point/zoom when opening the map view?

**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
I agree

**Comment by iantrich** [comment]
Looking for something to try to Hacktoberfest and this caught my idea. Would the idea to then be able to define a  configured zoom level from the Home lat/lon?

**Comment by balloob** [comment]
I think that we should just skip the zones when we're fitting the map.

**Comment by iantrich** [comment]
@balloob long term do you think we'll keep the map panel or just LL map card that can be in a view of its own?

**Comment by balloob** [comment]
We will keep the map panel, as I can see that panel eventually grow out to offer more functionality, like showing a timeline on the map of an entity etc. (Just an idea, no one is working on this)

**Comment by klejejs** [comment]
Any progress on this?

**Comment by balloob** [comment]
pull request welcome 👍 

[`[fitMap()]` source](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/map/ha-panel-map.js#L70)
