### ISSUE TITLE
TAB key in login screen on Firefox not working

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1605]
**Home Assistant release with the issue:**
0.77.0b2

**Last working Home Assistant release (if known):**
Never worked since auth is implemented.

**Browser and Operating System:**
Latest FF on Ubuntu 18.04

**Description of problem:**
TAB key doesn't work in the Login screen.
After setting username, have to klick on the password field and the i have to klick on the NEXT Button.

As always, works in chrome! :cry:

**Comment by balloob** [comment]
Can reproduce on the element demo page https://www.webcomponents.org/element/polymerelements/paper-input

**Comment by quthla** [comment]
@balloob In FF 63 it tabs from user to password but then only to the eye icon and back to password and never to the "Next" button

**Comment by iantrich** [comment]
Original issue is resolved in newer version of FF
