### ISSUE TITLE
Lovelace: Heading of glance card has to much padding

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#1615]
**Home Assistant release with the issue:**
0.76.2

**Browser and Operating System:**
All browsers

**Description of problem:**
The heading of the glance card has to much padding compared to the other headers.

The padding of a normal `div.header` is `padding: 4px 0 12px;`, the padding of the glance card header is `padding: 24px 16px 16px;`. The padding of the `ha-card` is also different.

**Additional information:**
![image](https://user-images.githubusercontent.com/1193779/44872457-e06acb80-ac95-11e8-9d97-419b3d406038.png)

**Comment by balloob** [comment]
Accidentally pushed it to master, but fixed in da19a1a9c6e87abe4f7d63ccfa94dd229ae7fc99
