### ISSUE TITLE
Group-On-State not supported in state-badge and therefore not supported in state-icon element

### ISSUE THREAD

**Issue by TheEggi** [home-assistant/home-assistant-polymer#1623]
It seems as if the group state is properly supported in the picture-glance-card, but is not checked inside of the state-icon (state-badge.js).

Would it be possible to expand the state-badge from
```
/* Color the icon if light or sun is on */
    ha-icon[data-domain=light][data-state=on],
    ha-icon[data-domain=switch][data-state=on],
    ha-icon[data-domain=binary_sensor][data-state=on],
    ha-icon[data-domain=fan][data-state=on],
    ha-icon[data-domain=sun][data-state=above_horizon] {
      color: var(--paper-item-icon-active-color, #FDD835);
    }
```
To add another check for data-domain=group
```
    ha-icon[data-domain=group][data-state=on],
```

**Comment by iantrich** [comment]
Sounds like an easy PR to submit ;)

**Comment by iantrich** [comment]
Hmm, thinking of this a bit more, I'm not sure if I agree with this idea. As noted in the comment, the icon coloring is meant to represent light. A group doesn't fall into that notion. Perhaps a different "on"/"active" color would be suitable, but does not fall within these color at least.
