### ISSUE TITLE
Names and other fields are capitalised by css

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#163]
When running Home Assistant in different languages, the automatic capitalisation of every word of a entity name can be annoying since it's not commonly written like that. Home Assistant actually ignores the case you've defined in the `friendly_name` of an entity.

It does make sense to capitalize "playing" to "Playing", but not so much in capitalising "Living room lights" to "Living Room Lights".

What's the consensus regarding this? I think it makes sense to keep the text as it is configured in `friendly_name`, and drop all the `text-transform: capitalize` lines for entity names.

This has been reported and assumed fixed before in https://github.com/home-assistant/home-assistant/issues/2055

**Comment by balloob** [comment]
PR welcome 👍
