### ISSUE TITLE
Lovelace: space not rendered between cards in vertical-stack in Firefox/Edge

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-polymer#1635]
**Home Assistant release with the issue:** 0.77.3

**Last working Home Assistant release (if known):** none

**Browser and Operating System:** Chrome/Opera Windows/Ubuntu

**Description of problem:**
Chrome and Opera display cards in vertical-stack with an additional space between them, ie the cards are not connected.
![ha-vertical-stack-chrome](https://user-images.githubusercontent.com/478555/45078928-80d74a80-b0f1-11e8-9f64-a6587cf229d7.png)

Firefox and Edge correctly display the cards as actually connected.
![ha-vertical-stack-ff](https://user-images.githubusercontent.com/478555/45078945-8896ef00-b0f1-11e8-96c3-878b8ff9e461.png)

**Comment by bieniu** [comment]
I understand. Is there any way to force Chrome to also ignore this margin? For me, connected cards without margin look better.

**Comment by VDRainer** [comment]
You can use this custom-card.
https://github.com/custom-cards/vertical-stack-in-card

**Comment by iantrich** [comment]
@bieniu 
Are you still seeing this issue? I'm unable to replicate on Firefox on Edge when running 0.79.3

**Comment by bieniu** [comment]
@iantrich Indeed, the isuue no longer exists on 0.79.3.
