### ISSUE TITLE
Autofocus not working on login/onboarding form

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-polymer#1641]
**Home Assistant release with the issue:**

0.77.3

**Browser and Operating System:**

* Chrome, Ubuntu 18.04
* Chrome, Android 8.0

**Description of problem:**

The username and/or 2-factor auth inputs are not autofocusing on desktop or mobile when the page loads.

**Additional information:**

This is likely an issue with the onboarding screen being the same for login in and sign up, so the name field takes presidence, but is hidden when logging in.

https://github.com/home-assistant/home-assistant-polymer/blob/master/src/onboarding/ha-onboarding.js#L39-L48

https://github.com/home-assistant/home-assistant-polymer/blob/master/src/onboarding/ha-onboarding.js#L50-L57

**Comment by iantrich** [comment]
This should be resolved once the page is rewritten as a LitElement

**Comment by iantrich** [comment]
should be fixed now
