### ISSUE TITLE
Entity ID editing fails when changing the platform

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/home-assistant-polymer#1643]
**Home Assistant release with the issue:**
0.75 and later

**Last working Home Assistant release (if known):**
N/a

**Browser and Operating System:**
N/A

**Description of problem:**
For obvious reasons when trying to use the UI to turn `binary_sensor.fish_tank` into `left_tank_sensor` it fails, with an invalid entity_id warning. The UI shouldn't allow people to change the platform/domain part, just the part on the right.

This has tripped up quite a few folks, who've wasted lots of time on it.

**Comment by balloob** [comment]
Will add something like this:

![image](https://user-images.githubusercontent.com/1444314/45289028-6daaed00-b4ec-11e8-97e8-af4ff9f998dc.png)
