### ISSUE TITLE
Automation GUI fire event wrong data

### ISSUE THREAD

**Issue by Aidenir** [home-assistant/home-assistant-polymer#1654]
**Home Assistant release with the issue:**

0.76.2
**Last working Home Assistant release (if known):**
Don't know, just started using hass

**Browser and Operating System:**

Tried both chrome and FF
**Description of problem:**

In the automation gui creation page, if you choose fire event, then the service data field is sent in as data, while the event_data is empty, resulting in the error: 
"Message malformed: extra keys not allowed @ data['action'][1]['event']"

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
Seems to be fixed
