### ISSUE TITLE
script/build_frontend 

### ISSUE THREAD

**Issue by varunr047** [home-assistant/home-assistant-polymer#167]
After script/fingerprint_frontend.py the panels Disappears other than state panel

**Comment by michaelarnauts** [comment]
Have you tried clearing the cache? I recommend to run in "incognito mode" during development, since I've noticed myself that the browser keeps things in cache.

Also, I don't think you need to run 'script/fingerprint_frontend.py` if you have `development: 1` in your configuration.

**Comment by balloob** [comment]
Ran the script last night, it's all good. Must be something in your config.

Note that when running in development, run `yarn run js_dev` to ensure you have a development service worker, or else you have prod caching enabled.
