### ISSUE TITLE
input_boolean icon does not turn yellow when it is on

### ISSUE THREAD

**Issue by samrenfrew** [home-assistant/home-assistant-polymer#1673]
**Home Assistant release with the issue:**
0.78.0

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Chrome 70 (MacOS)
Chrome 68 (Android 8.0)

**Description of problem:**
input_boolean domain does not turn turn yellow when it has a data-state=on. This exists for other domains, as below:

```
ha-icon[data-domain=light][data-state=on], ha-icon[data-domain=switch][data-state=on], ha-icon[data-domain=binary_sensor][data-state=on], ha-icon[data-domain=fan][data-state=on], ha-icon[data-domain=sun][data-state=above_horizon] {
    color: var(--paper-item-icon-active-color, #FDD835);
}
```

This just needs adding into the polymer framework:
```
ha-icon[data-domain=input_boolean][data-state=on]
```

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
N/A

**Comment by balloob** [comment]
All the ones that are turning yellow now are actually either using electricity or are yellow (the sun). Input boolean is neither.

**Comment by samrenfrew** [comment]
> All the ones that are turning yellow now are actually either using electricity or are yellow (the sun). Input boolean is neither.

binary_sensor is included in this list, and that does not necessarily use electricity, and neither does switch. Having it turn yellow is a good indicator that the input is on, especially when used in the new lovelace glance card - if I set 'show_state' to false, there is currently no indication that the input_boolean is on as the icon colour does not change
