### ISSUE TITLE
Zwave pop up log does not work

### ISSUE THREAD

**Issue by jamesking420** [home-assistant/home-assistant-polymer#1681]
**Home Assistant release with the issue:**
0.78

**Last working Home Assistant release (if known):**
0.77.3

**Browser and Operating System:**
Progressive web app (using Chrome) on Android 8.1.

**Description of problem:**
Pop up window does not show log when "Load" or "Tail" are clicked.

See below videos:

Expected behaviour:
https://imgur.com/gallery/cz8xGwC

Behaviour in Progressive web app (pop up is blank):
https://imgur.com/gallery/DgXrfn6

**Comment by balloob** [comment]
CC @cgarwood @turbokongen

**Comment by balloob** [comment]
It has to do with window.open and writing to that. I think a normal dialog should be used.

**Comment by turbokongen** [comment]
![image](https://user-images.githubusercontent.com/16622752/45879046-5cdb6080-bda3-11e8-840c-33d1b6cd72cb.png)
Will check into it.

**Comment by turbokongen** [comment]
Wierd one... 
Running Progressive Web app on windows, all works ok.
Running Progressive Web app on my Huawei mate P10 pro(Android 8.0.0)  only "Tail" works, but "Load" gives the same result as OP.

**Comment by turbokongen** [comment]
I've been looking into the dialog bit. (paper-dialog)
Unless I totally misunderstand it, there is no point moving to that, because:
* It defeats the real use case to have the log open side by side with the panel for observation when applying operations.
* To be honest, no offense to anyone, why would anyone manage such complicated task as viewing the log of OZW and operating the panel from a mobile? 

I am still scratching my head to why Tail will work, but not Load, as we do the excact same operations.

**Comment by jamesking420** [comment]
Can you make it behave differently depending on whether it's Android progressive web app or not?

I was finding it perfectly fine to read the log on android, until it stopped working on 0.78.

**Comment by turbokongen** [comment]
I've been at this for the last eight days, but on android, there is not `display-mode: standalone` in PWA mode which it should be. On desktop PWA it is set correctly, and behaves accordingly.
I am trying to make it behave differently with PWA mode and web, but the result is the same as the OP's original problem. All ok in Web view, and desktop PWA. But android PWA is at fault.
On Android 5 it behaves like it should as well. (PWA vs Webview.)
I can't figure out what display-mode android 8 is using for PWA's.
This seems to be limited to android 8 PWA.  Anyone with some ideas or hints?
