### ISSUE TITLE
Lovelace: conditional cards leave empty column when hidden

### ISSUE THREAD

**Issue by corbinchild** [home-assistant/home-assistant-polymer#1686]
**Home Assistant release with the issue:**

0.78.0

**Last working Home Assistant release (if known):**

Unknown

**Browser and Operating System:**

Likely all.  Tested in Chrome and Edge on Windows 10.

**Description of problem:**

Conditional cards in the new Lovelace UI have the following html tags even when they are hidden:

```
<div class="column">
    <hui-conditional-card></hui-conditional-card>
    <hui-conditional-card></hui-conditional-card>
</div>
```

This causes an empty column to appear in the UI if the conditional cards are the only elements displayed in that particular column and they are hidden at the time.  See the following screenshot for an example.

![capture](https://user-images.githubusercontent.com/3412472/45787402-3e089b80-bcc9-11e8-9fe3-ed6c8c251aa3.PNG)

It seems the conditional card html should either be removed entirely when the card is hidden, or there should be a check to display: none the elements and the column they are in while hidden (if they are the only cards in that column).

**Javascript errors shown in the web inspector (if applicable):**

None

**Additional information:**

None

**Comment by jeradM** [comment]
This has been an issue for a while: https://github.com/home-assistant/ui-schema/issues/127. I'll try to sort this out later this afternoon

**Comment by iantrich** [comment]
@corbinchild is this still an issue for you?

**Comment by corbinchild** [comment]
@iantrich I recently updated to 0.81.2 and now I receive the following error message:

![capture](https://user-images.githubusercontent.com/3412472/47827946-8a291e80-dde5-11e8-8f89-62c42bdc1a98.PNG)

Is this related to the changes you have made?

Thanks for your help!

**Comment by iantrich** [comment]
@corbinchild I haven't made any changes to the conditional-card, but this issue is known and will be resolved with 0.81.3 https://github.com/home-assistant/home-assistant-polymer/pull/1927

**Comment by corbinchild** [comment]
@iantrich Thanks for the info.  The error is gone now that I have updated to 0.81.3.  However, the empty column as shown in my first image above is still present.

**Comment by iantrich** [comment]
@corbinchild still an issue?
https://github.com/home-assistant/home-assistant-polymer/pull/1999 should have resolved it, I believe

**Comment by corbinchild** [comment]
@iantrich yes, this is fixed.  Thank you!

**Comment by barrymossel** [comment]
Same goes for rows:
![image](https://user-images.githubusercontent.com/10389401/50518335-716f7900-0ab5-11e9-9c07-3a9040092a0b.png)
In the red square are several horizontal stacks with conditional cards that are not shown due to their conditions. But still they lease empty rows.

**Comment by nikrolls** [comment]
@iantrich : This appears to have regressed by 0.84.6:
![image](https://user-images.githubusercontent.com/2626677/50577135-dd6f2a00-0e85-11e9-80d0-860a78677e61.png)
Tested in Chrome and Edge on Windows 10. Not visible in single-column (mobile) mode.

**Comment by iantrich** [comment]
Open a new issue and reference this. Don't comment on closed issues. Thanks.
