### ISSUE TITLE
Chrome shows "This site can't be reached" when unable to connect to HA

### ISSUE THREAD

**Issue by reef-actor** [home-assistant/home-assistant-polymer#1701]
**Home Assistant release with the issue:** 0.78
**Last working Home Assistant release (if known):** N/A
**Browser and Operating System:** Chrome for Android and Windows

**Description of problem:**
When navigating to `<ha_server>:8123` when it is not possible to connect to the server for any reason, the "This site can't be reached" error page is displayed.

**Javascript errors shown in the web inspector (if applicable):**
Nada

**Additional information:**
I am using ui-lovelace, but I believe the same behavior is present in the legacy UI also

**Comment by mf-social** [comment]
What error message were you expecting your browser to display when your site can't be reached?

🤔

**Comment by reef-actor** [comment]
I would expect it to load the cached ui shell and some indication that interaction is not available.  The lack of offline caching (and associated slow startup of the ui) is possibly a reason there are a number of native apps appearing and fragmenting the efforts of contributors.

**Comment by mf-social** [comment]
I'll happily be the only person on the planet who prefers it this way, but what's the point of displaying a cached version you can't interact with? 

The only reason to bring up the interface is to see the current data for a sensor, or to turn something on/off.

Having cached sensor data is pointless, and being able to see a switch that I can't turn on is equally so.

**Comment by reef-actor** [comment]
I would say cached state data is not completely pointless, for example it can be useful to know if you remembered to switch off device x before you left the site.
An additional benefit would be uninterrupted use of external services in [iframe cards](https://www.home-assistant.io/lovelace/iframe/).

It wouldn't be game-changing, but I believe there would be benefits to real-world usage and ui startup times.

_NB I'm not familiar with polymer so it is possible a simple fetch handler isn't possible_

**Comment by balloob** [comment]
We already implement offline support using a service worker, it will show you an HA error that it cannot connect. Service workers are limited to hosts that are accesses over HTTPS. This is a browser limitation that we can't circumvent.

**Comment by mf-social** [comment]
**for example it can be useful to know if you remembered to switch off device x before you left the site.**

But it won't necessarily show you that, it will show you the last state that was cached which is not necessarily the state the device is in now. So say I open my interface and switch off the living room lights then leave the house. My daughter then decides to switch them on before she goes to school. 

I then open the interface from work to make sure that the lights are off, but homeassistant is down. I get a snapshot of the lights when I last had the interface open, which says they're off when they're not. The only thing I should actually care about at this point is why is homeassistant down, as the states of all my devices are irrelevant if I can't do anything about them. It's the Schrodinger's cat of home automation 😃

I can see the advantage for the iframe to be fair, but I personally would prefer the error message. As I say, I'm not saying you're wrong, just exploring your suggestion as devil's advocate 👍
