### ISSUE TITLE
Web Front UI on IOS 9.3.3 (iphone 6s) not loading for home-assistant-frontend > 20180917.0

### ISSUE THREAD

**Issue by qosmio** [home-assistant/home-assistant-polymer#1743]
This seems to be related to issue #1266 

**Home Assistant release with the issue:**
0.80.0.dev0 

**Last working Home Assistant release (if known):**
home-assistant-frontend==20180917.0

**Browser and Operating System:**
Both Safari and native iOS App (iOS 9.3.3)

**Description of problem:**
The web ui does not load in either Safari/Firefox/Chrome for iOS or in the native iOS Home Assistant app. This worked find until version **20180917.0** of **home-assistant-frontend**

**Javascript errors shown in the web inspector (if applicable):**

These are taken from ios debug proxy on Chrome. I'm not sure how helpful they are.

```
(anonymous) @ core-ab3493d5.js:2
(anonymous) @ core-ab3493d5.js:2
__webpack_require__ @ core-ab3493d5.js:2
(anonymous) @ core-ab3493d5.js:2
global code @ core-ab3493d5.js:2
VMundefined compatibility-45fc06b6.js:1183 
(anonymous) @ app-11667c1b.js:formatted:36203
(anonymous) @ app-11667c1b.js:formatted:36203
(anonymous) @ app-11667c1b.js:formatted:36203
__webpack_require__ @ app-11667c1b.js:formatted:321
(anonymous) @ app-11667c1b.js:formatted:36203
__webpack_require__ @ app-11667c1b.js:formatted:321
(anonymous) @ app-11667c1b.js:formatted:36203
__webpack_require__ @ app-11667c1b.js:formatted:321
(anonymous) @ app-11667c1b.js:formatted:439
global code @ app-11667c1b.js:formatted:440
```

**Additional information:**

I know that newer features require a newer Webkit which in turn requires a newer iOS version. But I would really like to at least know what causes this to happen every few newer frontend releases.
![capture](https://user-images.githubusercontent.com/8892380/46565366-34d81b00-c8d4-11e8-9429-66e8aa9aad2a.PNG)

**Comment by balloob** [comment]
Ugh that's quite the useless stack trace. It doesn't even print the reason of the error.

Our ES5 builds with compatibility layer aim to work fine on older devices. Although I'm glad you got a stack trace, it doesn't tell me much. The first error is in the compatibility file which actually aims to polyfill certain features.

**Comment by balloob** [comment]
Ah, found the issue. It looks like the unfetch polyfill is using `=>` under the hood and that is not getting transpiled. I will put out a fix to transpile node modules too.

**Comment by balloob** [comment]
ugh, we did transpile node modules but unfetch decided to ship with the `mjs` extension and we didn't look for that. Opening a PR, thanks for the great logs, that helped find the issue fast 👍
