### ISSUE TITLE
LoveLace: Sensor Card Type not Found - Beta2

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/home-assistant-polymer#1749]
**Home Assistant release with the issue:**
0.80.0b2

**Browser and Operating System:**
Chrome running HA-Hassio on a RP3B+
Windows 10

**Description of problem:**
New Card - Sensor is not being recognized as a card type.
![Error](https://i.gyazo.com/60d78498327d67a5dd18b7f483d9181a.png)

**Comment by balloob** [comment]
Show me a screenshot of your dev info page that shows the version of Home Assistant

**Comment by teodoc** [comment]
Maybe a caching issue. Try Ctrl - F5.

**Comment by zsarnett** [comment]
![pic1](https://i.gyazo.com/0597223704f8ad43d3fe9392f6eb3881.png)
![pic2](https://i.gyazo.com/fe6a5a7263b1ef5d0e7058689acf328c.png)
![pic3](https://i.gyazo.com/4f8af66b10f2c00f5de3a8ef8f72edbf.png)

@balloob

**Comment by zsarnett** [comment]
I reported the issue of the versions not showing consistently in the #beta channel of the discord.

**Comment by balloob** [comment]
looks like tagging of the version went wrong, as the last screenshot shows b1.

**Comment by zsarnett** [comment]
Tagging of the version as in I reported the Wrong version on the Issue? or something in the upgrade to 0b2. I downgraded and re-upgraded last night before reporting the issue. I just thought dev-info didn't get the change to the version

**Comment by balloob** [comment]
No no, dev info is the one that is most accurate. I mistagged the b2 release so Hass.io images got b1. Closing this issue and will release b3 that should fix it all.

**Comment by zsarnett** [comment]
Gotcha. Thank you!
