### ISSUE TITLE
Integrations->Devices card's don't stack right

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/home-assistant-polymer#1751]
**Home Assistant release with the issue:**
0.80 dev

**Last working Home Assistant release (if known):**
Unknown

**Browser and Operating System:**
Chrome on Windows 10

**Description of problem:**
The cards on the devices page don't stack correctly. If you get a long card, the rest of them are pushed down leaving a bunch of blank space instead of filling in the area like the regular /states view.

![image](https://user-images.githubusercontent.com/7545841/46689818-b67ac200-cbce-11e8-814b-748c0fbcd998.png)
![image](https://user-images.githubusercontent.com/7545841/46689896-ecb84180-cbce-11e8-8331-9e199fa8281f.png)

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**
None

**Comment by balloob** [comment]
https://material.io/design/components/cards.html#behavior

For scrolling, it's okay to scroll within a card (set a max height on entities) if we're in desktop mode. To do this, we should just track the `narrow` property and behave accordingly.

**Comment by balloob** [comment]
Go for it ! 👍
