### ISSUE TITLE
[Lovelace] Add ability to slide between tabs with finger/mouse

### ISSUE THREAD

**Issue by deviant-studio** [home-assistant/home-assistant-polymer#1759]
It would be useful on mobile devices working as home dashboard. 
Tapping small iconic tabs on tablets/phones is real pain.

**Comment by balloob** [comment]
No feature requests here. This is for issues.

**Comment by deviant-studio** [comment]
Sorry. Created request here:
https://community.home-assistant.io/t/frontend-support-swipes-between-tabs/73239
