### ISSUE TITLE
Blank page when creating or edit automations in Automation editor (HassIO, 0.80)

### ISSUE THREAD

**Issue by martininio** [home-assistant/home-assistant-polymer#1768]
Home Assistant release with the issue:
0.80 (HassIO)

Last working Home Assistant release (if known):
0.79.3

Browser and Operating System:
Google Chrome 69.0.3497.100, Windows 10

Description of problem:
In the automation editor, when clicking on the + sign for creating a new automation only a blank page shows up.  Some existing automations aren’t editable too, showing the same blank page.

It look likes the issue only occurs in Google Chrome, in Microsoft Edge it's working fine..

Javascript errors shown in the web inspector (if applicable):
Uncaught (in promise) TypeError: Cannot read property ‘hours’ of undefined
at state_StateTrigger.render (286a08fb18870c9c81b7.chunk.js:1)
at renderComponent (8752a4221f36038e73c0.chunk.js:1)
at setComponentProps (8752a4221f36038e73c0.chunk.js:1)
at buildComponentFromVNode (8752a4221f36038e73c0.chunk.js:1)
at idiff (8752a4221f36038e73c0.chunk.js:1)
at innerDiffNode (8752a4221f36038e73c0.chunk.js:1)
at idiff (8752a4221f36038e73c0.chunk.js:1)
at diff (8752a4221f36038e73c0.chunk.js:1)
at renderComponent (8752a4221f36038e73c0.chunk.js:1)
at setComponentProps (8752a4221f36038e73c0.chunk.js:1)

**Comment by leoplanet** [comment]
Having same issue. I reinstalled from start and still automations is a blank page.

**Comment by balloob** [comment]
CC @armills

**Comment by Lafunamor** [comment]
is there a way to patch this on a running 0.80. installation?

**Comment by marschallphilipp** [comment]
Same here...
All browsers don´t work.

**Comment by Lafunamor** [comment]
@

> Same here...
> All browsers don´t work.

Just update to version 0.80.1. That includes the fix for this bug.

**Comment by marschallphilipp** [comment]
@lafunamor

I updated to 0.80.2 but can only confirm a partially fix.
I'm able to edit existing automations but get a blank page for new one...

**Comment by cgarwood** [comment]
there was another automation editor fix in 0.80.3, if it still doesn't work, please submit a new issue 👍
