### ISSUE TITLE
Hassio: System tab cards are expanded to bottom of screen

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-polymer#1813]
**Home Assistant release with the issue:**

0.80.2

**Last working Home Assistant release (if known):**

Unknown

**Browser and Operating System:**

Android Oreo 8.0.0
Chrome

**Description of problem:**

Under the system tab, the panels seem to expand to the size of the device and leave a vast amount of empty space. (see screenshots)

Likely a CSS height issue

**Additional information:**

![screenshot_20181019-143447](https://user-images.githubusercontent.com/28114703/47223694-c904b080-d3b1-11e8-9933-a3211ad92c6c.jpg)

![screenshot_20181019-143454](https://user-images.githubusercontent.com/28114703/47223698-c99d4700-d3b1-11e8-8004-373a00632752.jpg)

**Comment by gabrielboliveira** [comment]
I can confirm this also happens on iOS, app and Safari. Tested on iPhone 7 Plus running iOS 12.0.1

<details>

  <summary>iOS app</summary>

  ![img_0392](https://user-images.githubusercontent.com/11093090/47570303-3cf00d00-d90c-11e8-9e11-1b1d22dcb2be.PNG)

</details>

<details>

  <summary>iOS Safari</summary>

![img_0393](https://user-images.githubusercontent.com/11093090/47570304-3cf00d00-d90c-11e8-9e0d-d9db55da1673.jpg)

</details>

**Comment by gabrielboliveira** [comment]
My PR #1862 should have fixed it, however I see no updates to hassio panel being deployed to home-assistant. Is the build properly running?

**Comment by timmo001** [comment]
Fixed on hass.io supervisor v140

![image](https://user-images.githubusercontent.com/28114703/48809598-1eb7da00-ed1d-11e8-9e48-bfc2bc6d8614.png)
