### ISSUE TITLE
Graphs aren't loading on second click to the History tab. 

### ISSUE THREAD

**Issue by kwende** [home-assistant/home-assistant-polymer#1815]
**Home Assistant release with the issue:**
0.80.2

**Last working Home Assistant release (if known):**
0.72.1

**Browser and Operating System:**
Windows 10. Chrome Version 69.0.3497.100 (Official Build) (64-bit. 

**Description of problem:**
See https://www.youtube.com/watch?v=PMp4YxI8pGQ&feature=youtu.be for visual. 

To reproduce. Click on the "Overview" tab. From here, refresh your browser. Then click on the "History" tab. Note how the graphs appear immediately. Click on "Overview" again. Then click on "History" again. Note how the graphs no longer appear, but instead, you see "Loading state history..." forever. 

**Javascript errors shown in the web inspector (if applicable):**
Nothing appears in the Chrome console but the warning "Could not find style data in module named vaadin-date-picker-overlay-default-theme". No network traffic is shown in the Chrome network analysis tools. 

**Additional information:**

Just upgraded tonight. I don't recall this happening with earlier builds.

**Comment by Fusseldieb** [comment]
Fixed in 0.80.3. Can be closed.

**Comment by hmmbob** [comment]
Widely discussed in this issue as well: https://github.com/home-assistant/home-assistant/issues/17591
