### ISSUE TITLE
ui::components::relative_time::future instead of ui::components::relative_time::past on mobile browser when last-changed = 0 seconds?

### ISSUE THREAD

**Issue by priiduonu** [home-assistant/home-assistant-polymer#1817]
**Home Assistant release with the issue:**
0.80.0

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Firefox 62.0.3 on Fedora 27 (ok)
Chrome 69.0.3497.100 on Android 9.0.0 (problematic)

**Description of problem:**
If I click a switch, then on desktop browser (Firefox) the `last-changed` reads (correctly) "0 seconds ago":

![valik_143](https://user-images.githubusercontent.com/5614724/47259095-c9827180-d4ad-11e8-9e6b-ae2ee9e02b2f.png)

But on mobile browser (Chrome) it reads "In 0 seconds":

![screenshot_20181020-211043](https://user-images.githubusercontent.com/5614724/47259103-f6cf1f80-d4ad-11e8-9707-627e5e67e59b.png)

When `last-changed` is > 0 seconds, both read correctly "n seconds ago".

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

**Comment by garyt72** [comment]
I'm currently seeing the same thing with Chrome 72.0.3626.119
