### ISSUE TITLE
History bar frequently extends beyond dialog

### ISSUE THREAD

**Issue by jbcodemonkey** [home-assistant/home-assistant-polymer#182]
This happens every third or fourth new object, does not repeat when reloading the same object.
![image](https://cloud.githubusercontent.com/assets/4581542/22309271/919b9298-e318-11e6-8b7a-317f5cbdb0be.png)

HA 0.36.1 back through 0.34.x.
Windows 10, Chrome and Edge.

**Comment by balloob** [comment]
Fixed in b9cf35cced75028034ec26fe7ba19675a2859eb0
