### ISSUE TITLE
Cards don't accept control:hidden in certain conditions

### ISSUE THREAD

**Issue by Fusseldieb** [home-assistant/home-assistant-polymer#1820]
In Home Assistant 0.80.3 using Lovelace some cards still show the switch that shuts off the whole card, even if I specify `control: hidden` in `lovelace-ui.yaml`.

In my observation the card only accepts `control: hidden` if there are only **group** domains. If there's any light in the same card, the card won't hide the switch anymore, even if it's specified to `control: hidden`. Even using _only_ **light** domains in a card will make the card show the top switch.

![image](https://user-images.githubusercontent.com/4715129/47261007-7bb13d80-d49c-11e8-81c8-022e44460c00.png)
![image](https://user-images.githubusercontent.com/4715129/47260978-e9a93500-d49b-11e8-84d3-84331087484b.png)
_In the pictures below, **all** cards have `control: hidden` specified, but only some accept it_

**Comment by thomasloven** [comment]
How about if you use the correct `show_header_toggle` instead?
https://www.home-assistant.io/lovelace/entities/#show_header_toggle
