### ISSUE TITLE
State History Not Loading In More Panel For Entities (still not working)

### ISSUE THREAD

**Issue by JPM-git** [home-assistant/home-assistant-polymer#1829]
Home Assistant release with the issue:

0.80.3
Last working Home Assistant release (if known):

0.79.3
Browser and Operating System:

Windows 10 firefox 62.0.3

Description of problem:
History graphs still don't show

2018-10-19 22:17:04 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.1829567216] Received {'type': 'config/entity_registry/get', 'entity_id': 'history_graph.edp_spendings', 'id': 19}
2018-10-19 22:17:04 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.1829567216] Sending {'id': 19, 'type': 'result', 'success': False, 'error': {'code': 3, 'message': 'Entity not found'}}

I can, sometimes, get some graphs to load after a restart of the HA, but none is updated or can show the "detailed" view that you get after click on it.

Also the graphs that are showed aren't always the same.

I have clear the cache and even try a new browser I install just to test (chrome) but no luck.

Lovelace UI has the same problem.

**Comment by borpin** [comment]
Me too #1799 refers as does 

* https://community.home-assistant.io/t/cannot-load-history-anywhere-in-ha-loading-state-history/73799
* https://community.home-assistant.io/t/history-tab-not-working-after-80-2-update/74081/12
* https://community.home-assistant.io/t/history-graph-component-takes-significant-time-to-display/74164/16

**Comment by zsarnett** [comment]
@JPM-git After you update to 0.81.5 Do you still have these issues?

**Comment by Human** [comment]
I can't speak for others, but this was fixed in 0.81.x for me.

**Comment by christopheBfr** [comment]
Solved also for me. Perfect
