### ISSUE TITLE
0.81.0b0 - Lovelace doesn't load

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1836]
**Home Assistant release with the issue:**
0.81.0b0

**Last working Home Assistant release (if known):**
0.80.3

**Browser and Operating System:**
FF 62.0.3, Ubuntu 18.04

**Description of problem:**
Lovelace doesn't load, old states ui works.
2018-10-22 21:26:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139996373263696] Unable to serialize to JSON: Object of type 'TaggedScalar' is not JSON serializable

and then a monster dictionary (here just the beginning)

{'id': 14, 'type': 'result', 'success': True, 'result': ordereddict([('resources', [ordereddict([('url', '/local/tracker-card.js?v=0.1.5'), ('type', 'js')]), ordereddict([('url', '/local/gauge-card.js?v=0.2.0'), ('type', 'js')]), ordereddict([('url', '/local/column-card.js?v=e7fb09'), ('type', 'js')]), ordereddict([('url', '/local/slider-entity-row.js?v=2d9e00'), ('type', 'js')]), ordereddict([('url', '/local/vertical-stack-in-card.js?v=0.0.8'), ('type', 'js')]), ordereddict([('url', '/local/ext-weblink.js?v=0.3.2'), ('type', 'js')]), ordereddict([('url', '/local/card-modder.js?v=1c480b'), ('type', 'js')]), ordereddict([('url', '/local/toggle-lock-entity-row.js?v=a57ac1'), ('type', 'js')]), ordereddict([('url', '/local/fold-entity-row.js?v=9fbaab'), ('type', 'js')]), ordereddict([('url', '/local/button-card.js?v=0.0.3'), ('type', 'module')]), ordereddict([('url', '/local/mini-media-player.js?v=0.8.7'), ('type', 'module')])]), ('name', 'Home'), ('views', [ordereddict([('title', 'Home'), ('id', 'home'), ('icon', 'mdi:home-assistant')...

**Comment by balloob** [comment]
That's part of a breaking change: we no longer support `!include` (as previously announced, now it's enforced).

We could work on improving our error message

**Comment by balloob** [comment]
CC @bramkragten

**Comment by bramkragten** [comment]
The message is improved in the pr that was merged today

**Comment by VDRainer** [comment]
I have no `!include` in my ui-lovelace.yaml

**Comment by bramkragten** [comment]
You have some `!constructor` probably, merge dirs, or anything

**Comment by VDRainer** [comment]
Yes
```
              - type: custom:ext-weblink
                name: RPi Cam Control
                icon: mdi:webcam
                url: !secret rpi_cam_control
```
and
```
          - type: divider
            style: !secret divider
```
This is no longer supported?

**Comment by bramkragten** [comment]
No, not in ui-lovelace.yaml

**Comment by VDRainer** [comment]
Hmm, so i have to write secrets into the ui-lovelace.yaml and have to add
```
style:
  height: 1px
  width: 80%
  margin-left: auto
  margin-right: auto
  background: "var(--sidebar-text_-_background)"
```
to every divider. :confused:

**Comment by bramkragten** [comment]
Yes, but in return, you will get the possibility of editing Lovelace from the UI soon.

**Comment by VDRainer** [comment]
But i like to edit my files in a terminal with nano! :grinning:
So what, keep on your great work!

**Comment by balloob** [comment]
for your custom divider, you might want to check out the new section without a label, pretty similar to what you have

**Comment by tadly** [comment]
Not sure where to read about this but is there an explanation for why this has been removed?
This makes housekeeping really difficult for obvious reasons.

I also just now realized that the `ui-lovelace.yaml` edited itself adding *Automatically created ids* which I'm not to fond of :/

**Comment by iantrich** [comment]
@tadly we're progressing towards the ability to edit the UI from the UI itself which means we need to be able to edit the config file and assign ids to elements within. The removal of !include falls within this reasoning as well.

**Comment by tadly** [comment]
Hm... Automations and scripts can also be edited from within the UI (if you use the `automations.yaml` and `scripts.yaml` in the configs root) while still allowing config-file warriors to separate their stuff (I'm one of those warriors and like to have everything nicely grouped).

Would it something similar be possible for the lovelace ui?

**Comment by bramkragten** [comment]
No, inside `automations.yaml` and `scripts.yaml` it will also just in-line all includes once you save anything through the UI.

We could get the includes, but we would not be able to save it the way you had it.

From the start of Lovelace it was told we don't support includes, now we have to enforce it.

**Comment by tadly** [comment]
@bramkragten yes, that's what I mean. If you use the `automations.yaml` and/or `scripts.yaml` than they are UI managed but if you include them manually you can manage it yourself
```yaml
# configuration.yaml
script: !include_dir_merge_named includes/scripts/
automation: !include_dir_merge_list includes/automations/
```

Would be nice if lovelace would support the same like:
```yaml
# configuration.yaml
lovelace:
  name: Home Assistant
  resources:
  views:
    - !include includes/views/10-livingroom.yaml
    - !include includes/views/20-kitchen.yaml
...
```

**Comment by bramkragten** [comment]
Then you would have to opt-out of the managing Lovelace from the UI. Not possible now but I will discuss it...

**Comment by tadly** [comment]
Yeah that'd be super fine with me :)
As I said before, I prefer managing files myself and I'm sure I can't be the only one.

Thanks for maybe reconsidering it!

**Comment by bramkragten** [comment]
If you can edit your YAML in the UI, for each card and each view, would there really be a need for include?

**Comment by bramkragten** [comment]
My point is, the frontend will do this for you in the future. You can rearrange, edit, delete, add views and cards in both YAML and a form.
It is not practical for us to have 2 different ways of loading the YAML... So includes will not come back.

**Comment by Rocka84** [comment]
> the frontend will do this for you in the future.
I understand that many people would prefer to be able to configure stuff in the frontend.  
But I don't understand why this via can't be optional, like it already is for automations and scripts.

**Comment by tadly** [comment]
I agree with @Rocka84 
I don't know the source (yet. might start digging) but I'd assume the `include` functionality is abstract and doesn't require much to add.

**Comment by junior013** [comment]
I can let `include` (in ui-lovelace.yaml) go, but not the `!secret` constructor! I think, you have to implement some separate variable store in the frontend editor too, which can keep secretly, not in the generated config yaml!

**Comment by bramkragten** [comment]
@Rocka84 because we use a different yaml loader for Lovelace, that does not support these functions. And adding them would be a lot of work.

It was announced from the start that Lovelace would not support them.

**Comment by Rocka84** [comment]
@bramkragten Sorry, I really don't mean to be rude but this just doesn't make sense to me. Intended or not, it **did** work until it was removed in the 0.81 release.

> It was announced from the start that Lovelace would not support them.

Can't find that in the [lovelace docs](https://www.home-assistant.io/lovelace/) or on the "[Splitting up the configuration](https://www.home-assistant.io/docs/configuration/splitting_configuration/)" page. Could you point me to that announcement?

**Comment by iantrich** [comment]
https://www.home-assistant.io/lovelace/tips/#lovelace-config-generator-jinja2-script

**Comment by niemyjski** [comment]
We really need secrets in the ui for things like device trackers, locations and the like. I like to share my configs on GitHub but this change a lone will make me remove them.

**Comment by iantrich** [comment]
You could share/backup the precompiled files before you run them through the jinja2 script

**Comment by ronytomen** [comment]
Two points I would like to make concerning this issue of removing `!include` support.

1. Until the UI supports editing the Lovelace UI, wouldn't it be advantageous to wait to disable `!include` at the point they cause a problem?  I suggest this without understanding the timeline or efforts behind moving the Lovelace configuration to the UI.
2. Documentation still references utilities that depend on `!include`.  Example: [Lovelace Config Generator](https://www.home-assistant.io/lovelace/tips/#lovelace-config-generator)

I don't understand the complications or merits of supporting or not supporting YAML includes in the Lovelace Configuration.  Despite it being documented, and  I didn't know it was and didn't find it when looking, that `!include` was not supported.  It would be nice to issue a warning that this unintended functionality will be removed, AKA a warning in the logs.  Supplying a conversion routine so things just continue to work would be wonderful!  Just process the include, add a comment that it has been automatically removed and write an updated `ui-lovelace.yaml`.

**Comment by bramkragten** [comment]
![image](https://user-images.githubusercontent.com/5662298/47607130-45d00400-da1c-11e8-95d7-80df443c020e.png)

**Comment by bramkragten** [comment]
For the people that want to split their config and don't want to use the edit functionality that will come to Lovelace, I suggest you use Lovelace Config Generator.

**Comment by bramkragten** [comment]
You are looking at the jinja2 script. The lovelace configurator states;

> The Lovelace Config Generator by @thomasloven provides you with the ability to split your Lovelace configuration into multiple files.

**Comment by Rocka84** [comment]
Sorry, I really misunderstood you there. Well then I added a pull request to support `!secret`s to the tool you recommended :wink:

**Comment by Bishma** [comment]
I'll add a vote for an ability to opt out of any control UI to get includes and/or stop automatic file edits. I understand it's not at all practical but also understand that there are a lot of use that use home assistant because we like having total control over our files. I don't want a home assistant I can't control completely from my IDE.

**Comment by iantrich** [comment]
Voices have been heard, guys :) Please give feedback to our current proposal here: https://github.com/home-assistant/home-assistant/pull/17890

**Comment by b1g1an** [comment]
Apologies if this post offends anyone but I'd be interested to know how many users actually use the UI editors as I haven't come across any. 

You'd think it would be something specifically aimed at new users but, taking automations as the obvious example, it's far easier for beginners to understand when it's all laid out in the yaml file and most learn using the copy/paste/adapt method so can't use the UI. I know of many potential users who've seen the UI thinking, naturally, that's the simple way to do it, been totally confused and gone elsewhere...logically how can doing it in the code be simpler to learn but it is.

For users with more experience and comfortable with yaml they may understand how to create in the UI but often need to go back to the yaml to fix the problems the UI introduces so just stick with yaml.

Adding UI setup is a essential to get HA into the mainstream, and all credit for trying to do that, but at the moment it just seems to add headaches for a lot of users when they have to make a load of changes to their perfectly working code when support for a UI they don't use is added.

**Comment by bramkragten** [comment]
I think Lovelace will be different in this, as it will allow you to edit the YAML in the UI.

**Comment by tadly** [comment]
@bramkragten Could you give a quick explanation on how this is going to look like?
Will this end up being just one huge yaml like `ui-lovelace.yaml` or is it going to be filtered per view etc.?

**Comment by bramkragten** [comment]
No filtered per card: https://www.figma.com/file/TuPIOg8NI8vsL28fMwiKF8/Lovelace-UI?node-id=16%3A2&redirected=1

**Comment by SteveEdson** [comment]
I can just about accept not being able to use !includes in the lovelace config, but removing `!secret`s will force me and others to stop keeping the config open source. I have lots of things like photos and floorplans used in the picture entity cards which I don't want being public.

Thanks

**Comment by Aephir** [comment]
> `!secret` will be coming back

Great news! Any idea when?

**Comment by NicoHood** [comment]
Hey I just stumbled across this issue and gave it a short read.

It seems the initial decision got reverted and !include will work again? As alreayd asked, when will that happen and is this a long term solution or are you still moving forward to the ui editing mode?

Is the UI editing mode ready yet? I dont want to argue if it is better or not, but if it is not yet available, why do you break tons of configs before releasing the UI? Hope to see a bugfix release for this as soon as possible.

**Comment by bramkragten** [comment]
Both the alpha version of the edit UI as support for `!secret` and `!include` where release today with 0.82

**Comment by bramkragten** [comment]
Correct, as stated, only `!include` and `!secret` are supported. So `!include_dir_list` is not.

**Comment by NicoHood** [comment]
Why not? Now I have to specify each file, instead of just including all and not worrying about those. Was this just forgotten or has a special reason?

**Comment by bramkragten** [comment]
We had to switch to a different yaml library to make the editing of the yaml possible. So the functions of the old library are not available.

**Comment by NicoHood** [comment]
Wouldt it make sense to use this new library for the whole config/project, but fix this missing include directory feature? I guess that is already in the pipeline?

**Comment by tadly** [comment]
Is `!include` here to stay or just a temporary measure until the whole ui edit stuff is finalized?

**Comment by bramkragten** [comment]
The intention is that it will stay.

**Comment by NicoHood** [comment]
I now get the error `Could not find ui-lovelace.yaml in your config dir.`, but it definitely exist, because when I try to use the previous include_dir_list it throws another error. What si wrong here?

```yaml
# Usse views from separate directory. Each file has its own view.
#views: !include_dir_list lovelace-views/
views:
    - !include lovelace-views/home.yaml
    - !include lovelace-views/light.yaml
    - !include lovelace-views/sound.yaml
    - !include lovelace-views/temperature.yaml
    - !include lovelace-views/computer.yaml
```

**Comment by bramkragten** [comment]
It’s a bug, made a pr to fix it...

**Comment by awgneo** [comment]
@bramkragten which PR is that? thanks :)

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant/pull/18378
