### ISSUE TITLE
IOS Status obscures ISY Light Brightness

### ISSUE THREAD

**Issue by jbcodemonkey** [home-assistant/home-assistant-polymer#185]
IOS 10.2
HA 0.36.2 back to 0.34.x (maybe earlier)
ISY Lights (maybe others...don't have any other types)

![image](https://cloud.githubusercontent.com/assets/4581542/22309609/f21bddca-e319-11e6-82ca-4d891960a512.png)

The Status only appears on the first Brightness change and none after, and in this case, the lights were already on.
Is the status even necessary? Not sure if this is a UI issue or not.

**Comment by balloob** [comment]
Whenever you change any attribute, we call a service to change that property. Setting the brightness is part of the turn_on service, so this is expected behavior.
