### ISSUE TITLE
Disabled automations getting enabled once saving any change on any automation using UI

### ISSUE THREAD

**Issue by quammy** [home-assistant/home-assistant-polymer#1854]
**Home Assistant release with the issue:**

0.80.3

**Last working Home Assistant release (if known):**
Not sure, I've seen this behavior since several versions ago

**Browser and Operating System:**

Chrome and Maxthon, Windows and Android

**Description of problem:**

I have few automations defined but disabled in the UI (Overview -> Automation card)
Whenever I edit any of the automations (no matter if was enabled or disabled beforehand), ALL automations become enabled and I need to go to the Overview -> Automation card to disable the ones I want to keep disabled.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by engrbm87** [comment]
This has been happening since the automation editor was introduced. until now it hasn't been fixed. Sorry that i am not able to assist on this as i am not an expert in the UI but i just wanted to highlight that this is an issue for me also.

**Comment by cgarwood** [comment]
Do the automations have an `initial_state` set? If you go to the dev-services page and fire the `automation.reload` service do they turn on as well?

**Comment by quammy** [comment]
not sure about `initial_state` set, but yes, `automation.reload` enables all disabled automations.

**Comment by cgarwood** [comment]
Sounds like a backend issue in that case.
