### ISSUE TITLE
kuuji version of lovelace button-card 

### ISSUE THREAD

**Issue by jaburges** [home-assistant/home-assistant-polymer#1870]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
0.81

**Browser and Operating System:**

**Description of problem:**

no issue - but https://github.com/kuuji/button-card is a button card developed by kuuji who has taken on many requests for customization. 
HA team have integrated alarm panel card, but created their own button-card. 
Any way raising in the hope it will save the HA devs some time by leveraging what is already out there

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by zsarnett** [comment]
Please don't just request the community version. Request a feature or set of features and please describe them and why you think they need added

**Comment by jaburges** [comment]
sure - here is an extensive list of features:
icon or button color customization
blank cards (especially useful when building 'remote' looking layouts)
color choices
what color when off (to separate from theme)
sizing 
show state
custom style/css
color based on state (not just on/off - like red for hot or blue for cold)

**Comment by jaburges** [comment]
some additional context is that this 'button' style was used broadly in the older legacy custom tiles within custom UI - and so folks are transitioning to lovelace with similar expectations

**Comment by balloob** [comment]
Will close this as it's not really an issue.
