### ISSUE TITLE
"Vertical Stack Card" does not work after updating to 0.81

### ISSUE THREAD

**Issue by eastonhe** [home-assistant/home-assistant-polymer#1875]
Home Assistant release with the issue:
0.81.0

Last working Home Assistant release:
0.80.3

Description of problem:
When i use the vertical-stack, it seems to be a problem
![default](https://user-images.githubusercontent.com/43304392/47602398-f9cb9200-da10-11e8-8aad-20e25f9e2a66.PNG)
and here is my config
![2](https://user-images.githubusercontent.com/43304392/47602402-051ebd80-da11-11e8-94ef-88e28946be4e.PNG)

when i remove vertical-stack, everything seems to be ok
![3](https://user-images.githubusercontent.com/43304392/47602434-7eb6ab80-da11-11e8-85f9-315180b83725.PNG)
![4](https://user-images.githubusercontent.com/43304392/47602435-7eb6ab80-da11-11e8-8b7b-9b80322a36b2.PNG)

**Comment by iantrich** [comment]
Hot fix is already in place and will be in 0.81.1
