### ISSUE TITLE
Limit Lovelace Gauge to maximum and minimum

### ISSUE THREAD

**Issue by maweki** [home-assistant/home-assistant-polymer#1876]
**Description of problem:**
I use the Gauge card to show the unix-load of my home automation server. I have a minimum of 0 and a maximum of 1. But actually, there is no maximum and the formula for the rotation makes the gauge off, while it should just be at the maximum.

![bildschirmfoto von 2018-10-27 11-50-11](https://user-images.githubusercontent.com/613272/47602392-97599e00-d9de-11e8-9937-fb3a52af9368.png)
![bildschirmfoto von 2018-10-27 11-49-31](https://user-images.githubusercontent.com/613272/47602393-97599e00-d9de-11e8-90b9-c1a4e7224a59.png)

I think the fix is very easy but I don't have a development environment set up where I can test this.
I think the change should be in https://github.com/home-assistant/home-assistant-polymer/blob/13c5724d7c7a9dc3aefbf5055e9ae447c4833368/src/panels/lovelace/cards/hui-gauge-card.js

where it originally is

```
  _translateTurn(value, config) {
    return (5 * (value - config.min)) / (config.max - config.min);
  }
```

it should be

```
  _translateTurn(value, config) {
    var turn_value = Math.min(Math.max(value, config.min), config.max); // clamp value
    return (5 * (turn_value - config.min)) / (config.max - config.min);
  }
```

The displayed value should obviously stay the same.

**Comment by zsarnett** [comment]
Thank you for the detailed solution. Looking into this

**Comment by zsarnett** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/1886
