### ISSUE TITLE
Lovelace thermostat card broken if operation_list absent

### ISSUE THREAD

**Issue by mvn23** [home-assistant/home-assistant-polymer#1881]
**Home Assistant release with the issue:**
0.81.0

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Firefox on linux

**Description of problem:**

Thermostat card does not show up in the UI if the underlying entity does not expose an operations_list.

**Javascript errors shown in the web inspector (if applicable):**
```
TypeError: stateObj.attributes.operation_list is undefined    [Learn More] d076e229b8879acac643.chunk.js:1701
```

**Additional information:**
@balloob suggested that operation_list should always be present on a climate entity, but that would make support for operation_modes mandatory for climate platforms, which will look weird in both classic UI and lovelace if only 1 operation mode is supported.
Either way, the thermostat card should deal with a situation where this list contains less than 2 items, for example by hiding the operation modes.

**Comment by zsarnett** [comment]
I believe that dealing with the situation of 0 operation modes is needed. But if the operation mode is on the accepted list of modes then the icon will show if not then no icon will show but the thermostat will still render.

**Comment by balloob** [comment]
@mvn23 had a good observation in Discord yesterday: if the climate component does not support operation modes, it will never add `operation_list`. So we need to handle this.

**Comment by mvn23** [comment]
@balloob do we still need to handle this in the backend as well? Or do we consider an entity without an operation_list a possibility by design?

**Comment by balloob** [comment]
It's possible by design, no need to update the backend. Opened a PR to fix in frontend 👍
