### ISSUE TITLE
0.81.0 - Header toggle in entities card

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1887]
**Home Assistant release with the issue:**
0.81.0
**Last working Home Assistant release (if known):**
0.81.0b2

**Browser and Operating System:**
FF and Chrome on Ubuntu

**Description of problem:**
Header toggle doesn't work as expected.
I can switch all switches on, but not off.
If i switch one entity on, the toggle stays off

**Comment by zsarnett** [comment]
I have replicated this issue. Looking to resolution

**Comment by VDRainer** [comment]
Just for Info, if i refresh the view between the switch operations, it works as it should.
All switches on with header toggle -> refresh -> all switches off with header toggle.
One switch on, header toggle stays off -> refresh -> header toggle turns on
...

**Comment by zsarnett** [comment]
@balloob Would you mind look at this? I have tried a few things and can't seem to find what going on

**Comment by VDRainer** [comment]
Should this be fixed in 0.81.2?
Seeing the same behavior after upgrade.

**Comment by balloob** [comment]
Not included in 81.2
