### ISSUE TITLE
object-assign missing

### ISSUE THREAD

**Issue by lindstromhenrik** [home-assistant/home-assistant-polymer#191]
The [Add demo data back](https://github.com/home-assistant/home-assistant-polymer/commit/e4b2ec1710da8d6e134f9846813833e6d7ce2929) commit makes run js_dev fail as demo_data\state_history_data.js references 
"object-assign" that was removed from the list of npm dependencies in the [Getting rid of HA-JS](https://github.com/home-assistant/home-assistant-polymer/pull/180) merge.

**Comment by balloob** [comment]
Fixed in f67e728d6d3eddaa2d317e2cc95f9db7c8ff2b5c
