### ISSUE TITLE
Lovelace Thermostat shows "upstairs" for all homematic thermostats, also manual mode not supported

### ISSUE THREAD

**Issue by daenny** [home-assistant/home-assistant-polymer#1916]
**Home Assistant release with the issue:**
0.81.1

**Last working Home Assistant release (if known):**
N/A as thermostat card was introduced in 0.81

**Browser and Operating System:**
Chrome on Mac OS

**Description of problem:**
All my homematic thermostats show-up as "upstairs" in the lovelace-ui. I would have expected that I can either set the name or the entity name is used.

There is also no button to enable 'manual' mode.  The 'manual' mode issue is maybe related to:
https://github.com/home-assistant/home-assistant/issues/17742

**Additional information:**

Thermostat cards show up like this:
<img width="382" alt="screen shot 2018-10-29 at 21 28 50" src="https://user-images.githubusercontent.com/3392004/47678306-bbc1a000-dbc1-11e8-8062-d49e065e12f5.png">

Using the "entity-card":
<img width="368" alt="screen shot 2018-10-29 at 21 28 59" src="https://user-images.githubusercontent.com/3392004/47678307-bbc1a000-dbc1-11e8-8faf-ab93ebaa7989.png">

Corresponding lovelace-ui.yaml part:
<img width="555" alt="screen shot 2018-10-29 at 21 29 16" src="https://user-images.githubusercontent.com/3392004/47678308-bc5a3680-dbc1-11e8-8013-bdf0e67e5229.png">

**Comment by balloob** [comment]
We tagged wrong version on Docker 🙄 0.81.2 will have it fixed
