### ISSUE TITLE
Showing detailed information in "Configured" section of Configuration/Integrations does not work when profile language set to Dutch

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/home-assistant-polymer#1917]
**Home Assistant release with the issue:**
0.81.1

**Last working Home Assistant release (if known):**
Don't know. First time I noticed the Configured section in Integrations that has the issue.

**Browser and Operating System:**
Chrome 69 on Windows
Home Assistant on Raspberry Pi 3

**Description of problem:**

Selecting items in the "Configured" section under "Configuration >> Integrations" does not work when the language in my profile is set to Dutch (Nederlands). The window remains empty, just a small popup with the text "system_log/write" appears for a short while in the bottom left corner.

It works fine when I have the language in my profile set to English.

I tried with all integrations I have and they all behave the same ( Philips Hue, Google Cast and Sonos)

**Javascript errors shown in the web inspector (if applicable):**
```
app-c039924c.js:2090 Uncaught Error: The intl string context variable 'fabrikant' was not provided to the string 'door {fabrikant}'
    at MessageFormat.format (app-c039924c.js:2090)
    at HTMLElement.args (app-c039924c.js:2090)
    at runMethodEffect (app-c039924c.js:1067)
    at Function._evaluateBinding (app-c039924c.js:1067)
    at Object.runBindingEffect [as fn] (app-c039924c.js:1067)
    at runEffectsForProperty (app-c039924c.js:1067)
    at runEffects (app-c039924c.js:1067)
    at HTMLElement._propagatePropertyChanges (app-c039924c.js:1067)
    at HTMLElement._propertiesChanged (app-c039924c.js:1067)
    at HTMLElement._flushProperties (app-c039924c.js:1438)
```

**Additional information:**
Same error as in the javascript console show in the Home Assistant log.

Note: the text "fabrikant" mentioned in the error is Dutch for "manufacturer"

**Comment by mvdwetering** [comment]
Hmm, I just realized I put this into the `home-assistant-polymer` repository. I was positive I was submitting it on the main Home Assistant repository.

However since an error does show up on the javascript console I guess it might be the correct repo after all.

Please let me know if this is the wrong repo after all and I will submit it on the other repo.

**Comment by balloob** [comment]
Looks like someone translated the placeholder keys 🙄 

You'll need to fix it in the translations: https://developers.home-assistant.io/docs/en/internationalization_translation.html
