### ISSUE TITLE
Some mdi icon is missing

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#1926]
**Home Assistant release with the issue:**

0.81

**Last working Home Assistant release (if known):**
unknown

**Browser and Operating System:**

Chrome (Android, Windows)

**Description of problem:**

Materialdesign icon `face-outline` is missing

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Fixed in #1922
