### ISSUE TITLE
Support for Chrome 'Progressive web app'

### ISSUE THREAD

**Issue by aequitas** [home-assistant/home-assistant-polymer#194]
Progressive web apps is what Google calls websites that could behave nearly like native apps on Android devices. Features include:
- Offline support (local caching, no reload after app switch)
- Push notifications (without additional apps)
- Home screen/App drawer application Icon (not to be confused with a normal bookmark)

https://developers.google.com/web/progressive-web-apps/

In order to support PWA a website needs to adhere to a few criteria: https://developers.google.com/web/progressive-web-apps/checklist

Most are already ticked of by HA, are mostly common sense and not Chrome specific (responsive, https, progressive enhancement, cross browser compatibility, etc).

Some need to be addressed: A service worker is required for push notifications and offline/caching support, some rendering issues.

Google offers the [lighthouse tool](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) for Chrome to verify the criteria and provide advice on how to solve issues.

Report snippet:
<img width="994" alt="screen shot 2017-02-04 at 10 47 53" src="https://cloud.githubusercontent.com/assets/365827/22617514/6d8174fc-eac7-11e6-99a9-c830731f3083.png">

I think it would be great if HA supported the PWA standard as it allows HA to provide a more native experience on Android devices without having to resort to building a native app.

When I find the time I will try to make some investment into this effort if people here think this is a the direction HA frontend can be taken to and kept at.

**Comment by demonspork** [comment]
I believe that Home-Assistant is already using a Service Worker, so I am not sure how you got that result. I am using the 0.38dev at the moment (a few days old, haven't pulled the very latest yet) and got this result: 

![image](https://cloud.githubusercontent.com/assets/432305/22624104/4bec6d22-eb37-11e6-933e-9e19783c94a2.png)

**Comment by balloob** [comment]
We are a progressive web app and we already support push notifications.

Service workers only are allowed to be active when you serve Home Assistant over either localhost, 127.0.0.1 or over SSL.

**Comment by aequitas** [comment]
Was missing the https, I should have known that was a requirement.
