### ISSUE TITLE
0.81.4 - Lovelace toggles (switch, light, input_boolean, ...) wrong state

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#1968]
**Home Assistant release with the issue:**
0.81.4

**Last working Home Assistant release (if known):**
0.81.2

**Browser and Operating System:**
FF, Chrome on ubuntu

**Description of problem:**
If i turn a switch on, the toggle turns off after a second. Device stays on.
After LL refresh, the toogle turns to on again and shows the right state.

Header toggle on -> all switches turn on, but toggles stay off -> refresh, all is shown correct.

Switch on -> Header toggle turns on -> Switch toggle turns off, Header toggle stays on.
Refresh -> All toggles show the correct state

Looks like the Header toggles are fixed https://github.com/home-assistant/home-assistant-polymer/issues/1887 but now the entity toggles show this behavior.

Switching an entity from HADashbord, no state update in LL, needs refresh too.

**Comment by balloob** [comment]
Missed 1 PR in the hotfix 👎
