### ISSUE TITLE
lovelace needs to refresh for mqtt switch, but old gui does not

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/home-assistant-polymer#2018]
**Home Assistant release with the issue:** 0.81.4 and 0.81.6

**Last working Home Assistant release (if known):**

**Browser and Operating System:**  Android Chrome

**Description of problem:** When I use a switch via mqtt using an esp32 and esphomeyaml, the state switches briefly to the new state then reverts.  It stays this way until the page is manually refreshed, when the true state is shown.  The old GUI does not have this problem.  On the face of it, this seems to be the same as #1971 and #1968, but my issue isn't fixed in 0.81.6. I had first raised this in home-assistant/home-assistant#18226, before I was aware that lovelave was a part of the polymer repository.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Make sure that after you updated to 0.81.6, you are not running the cached old version of the frontend. Also please try it with 82.

**Comment by MatthewFlamm** [comment]
Fixed by clearing cache and running on 0.81.6.  Thank you for being patient with such a silly oversight.
