### ISSUE TITLE
Minor code typo in input_slider

### ISSUE THREAD

**Issue by buergi** [home-assistant/home-assistant-polymer#203]
The following code in src/state-summary/state-card-input_slider.html doesn't make too much sense
```
    if (max <= this.min) {
      this.min = min;
      this.max = max;
    } else {
      this.max = max;
      this.min = min;
    }
```
I assume the rhs operands in the if part should be swapped.

**Comment by balloob** [comment]
What is the error that you see in your UI?

We had issues with the input slider breaking if we would set a max that is lower than min. So this check does exactly what is intended.

**Comment by buergi** [comment]
Hm, I don't see any error in the UI. I just read through the code and found these lines that seemed to be quite useless to me, as the action in both cases is identical, only the two lines are swapped. I guess it should be something like

```
    if (max <= this.min) {
      this.min = max;
      this.max = min;
    } else {
      this.min = min;
      this.max = max;
    }
```

**Comment by buergi** [comment]
@balloob if you are really sure the coded is really correct please remove the misleading if construct. Again: the body of the if and else case is identical in the current code.

**Comment by andrey-git** [comment]
@buergi 
In Polymer, binded property assignment is a function call with side effects. So the order of those assignment matters and
```
this.min = min;
this.max = max;
```
is not equivalent to
```
this.max = max;
this.min = min;
```

**Comment by buergi** [comment]
@andrey-git What? Thats pretty weird. But I guess I understand, OK then I take back everything I said.  Thanks for clarifying.
