### ISSUE TITLE
Cards Title not shown correctly in iOS

### ISSUE THREAD

**Issue by deluxestyle** [home-assistant/home-assistant-polymer#2031]
**Home Assistant release with the issue:**
0.81.6

**Last working Home Assistant release (if known):**
not known

**Browser and Operating System:**
iOS 12.1

**Description of problem:**
From time to time the header/title of cards are not shown correctly in iOS
![647d8e27b50d828f3ab2736dc49a3045606483b7](https://user-images.githubusercontent.com/662779/48248197-a5ec8000-e3f6-11e8-8a43-960916fbcada.jpeg)
![2df2010859ea5e719276b3e8f58e2f151a463c9f](https://user-images.githubusercontent.com/662779/48248200-aa189d80-e3f6-11e8-854a-3ae9647ffcc0.png)

a reload helps

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Try disabling all your custom cards and try again.

**Comment by deluxestyle** [comment]
I disabled all custom cards but it happened again

**Comment by deluxestyle** [comment]
> column-card and old layout-card versions cause this. Update the layout-card and clear the browser cache.
> Look here https://community.home-assistant.io/t/lovelace-column-card/62039/28

I only have "mini-media-player" as custom card. no other.

**Comment by bieniu** [comment]
Open HA page in the browser with incognito mode. If the title style is correct then the problem is the browser cache.

**Comment by deluxestyle** [comment]
> Open HA page in the browser with incognito mode. If the title style is correct then the problem is the browser cache.

I did it already a few times.
I forgot to mention that it seems to happen only in the iOS App. In Safari I don't see the problem.

I deleted the app already and installed it new. But no change

**Comment by iantrich** [comment]
@deluxestyle you must have https://github.com/thomasloven/lovelace-column-card if you're getting that error. Please share your configuration

**Comment by deluxestyle** [comment]
> @deluxestyle you must have https://github.com/thomasloven/lovelace-column-card if you're getting that error. Please share your configuration

I do not have lovelace-column-card
You can find my configuration on github
https://github.com/deluxestyle/Home-AssistantConfig

**Comment by fillwe** [comment]
Have the exact same issue, I don't have column card installed either

**Comment by VDRainer** [comment]
Looks like i'm responsible for the false [error message](https://community.home-assistant.io/t/cards-title-not-shown-correctly-in-ios/77103/3?u=vdrainer). Raised in the moment when refreshing the iOS app.
Sorry for the confusion. :grin:
I see the same issue.
Card Headers look normal, switching a view tabs and then the Headers are small.

**Comment by deluxestyle** [comment]
I just removed the „false error“. Sorry for the confusion

**Comment by fillwe** [comment]
I've started getting spammed with this in the logs, could it be the cause of the issue? https://fillwe.duckdns.org/frontend_latest/app-79696026.js:1211:25571 TypeError: this.detached is not a function. (In 'this.detached()', 'this.detached' is undefined)

**Comment by deluxestyle** [comment]
I don't have any error in my logs and it happens only on iOS.

**Comment by fillwe** [comment]
Yeah same here, have tried clearing cache and removing all lovelace code except a single standard entities card, still happens...

**Comment by deluxestyle** [comment]
Is there a way to help to solve this issue?
I'm using home assistant mainly on my iPhone and there it is a little bit annoying

**Comment by fillwe** [comment]
No change in 0.83.1. I'm going nuts trying to figure out the cause of this, have tried finding similarities with @deluxestyle setup but nothing that I can see their either. Anyone experiencing this in safari on desktop that could se if there is any errors in the web inspector?

**Comment by Ernst79** [comment]
I have the same issue with Chrome on the iPad. It suddenly happens and after a refresh it’s gone for a short while. But it keeps coming back. Clearing cache doesn’t help.

**Comment by fillwe** [comment]
Chrome on iPad is still using the Safari/webkit engine so that's not that strange. Just tried booting up my old Mac, got the same bug in safari there but no errors in the web inspector. This is only happening with entities cards for me though, same for you others?

**Comment by deluxestyle** [comment]
Yes. Happens only on entities cards

**Comment by Ernst79** [comment]
Yes, only for entities cards.

**Comment by Mariusthvdb** [comment]
> I've started getting spammed with this in the logs, could it be the cause of the issue? Can't really tell what it means, any help?
> 
> frontend_latest/app-79696026.js:1211:25571 TypeError: this.detached is not a function. (In 'this.detached()', 'this.detached' is undefined)

I have this exact error since using the animated custom-weather card for Lovelace:

log complaining about:

2018-12-05 14:26:50 ERROR (MainThread) [frontend.js.latest.201811033] https://domain_redacted/frontend_latest/app-79696026.js:1211:25571 TypeError: this.detached is not a function. (In 'this.detached()', 'this.detached' is undefined)

inspector posting to this line in .js file:

`    this.content.innerHTML = ``

**Comment by fillwe** [comment]
Problem still on 0.84.1, moved my lovelace to the storage option, adapted my cards for the ui editor, cleared cache but the same problem seems to persist

**Comment by Ernst79** [comment]
Issue is still there on 0.85.

**Comment by Ernst79** [comment]
I think this can be closed, no more issues since (I think) 0.87
