### ISSUE TITLE
Version missing in info page

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#205]
Since the update to 0.38.1, the version is missing from the info page. Path to config dir is also missing.

I guess this is since #180 due to a change on this line:
https://github.com/home-assistant/home-assistant-polymer/pull/180/files#diff-6c51c4757d1b505461f2babb6d5d88d3L74

**Comment by michaelarnauts** [comment]
![image](https://cloud.githubusercontent.com/assets/1193779/22860681/750c4cd0-f105-11e6-8b61-6ee2f386b4a4.png)

**Comment by balloob** [comment]
Nop, it's not. You're just still using the cached old version. 0.38.1 is based off Polymer 1.8. Close all your Home Assistant browser windows and you will be served the new version next time you come back.
