### ISSUE TITLE
Lovelace thermostat card does not fully work with Tado devices

### ISSUE THREAD

**Issue by cicero200272** [home-assistant/home-assistant-polymer#2058]
**Home Assistant release with the issue:**
0.82.1

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

**Description of problem:**
The thermostat card does not show any operation mode for Tado devices

![thermostat](https://user-images.githubusercontent.com/15817602/48604357-e3628780-e979-11e8-81f8-e1f18f225bc9.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Tado devices have different operation modes than "standard" climate devices:
* Off [capital "O"!]
* Tado mode
* Manual
* Smart schedule
* Timer

Would be nice if the lovelace thermostat card also supports these. One could re-use some of the icons for other modes as implemented with #2039:
* Off -> off
* Smart schedule -> auto

**Comment by zsarnett** [comment]
Agree. Only Official Modes will be supported. Off and Manual are the only 2 within those Modes. And support for those will be in the next beta/ full release

**Comment by agross** [comment]
> this should be moved to the backend

Where can I find it? I also use tado and since 0.86 forces the new UI on me the tado thermostats have become nearly useless to me.

<img width="333" alt="2019-01-25_01-39-22" src="https://user-images.githubusercontent.com/16245/51717674-12643c00-2042-11e9-86b9-e1e3db86afed.png">

**Comment by iantrich** [comment]
You can still use states. 

And in Lovelace, put this entity in an entities card to get the same thing as in states

**Comment by agross** [comment]
@iantrich Thank you! I was able to restore the old layout using the Entities card.

**Comment by gigios** [comment]
@iantrich , Is it possible to have an example?
Sorry but form me it's the first usage of Lovelace but I'm not able to manage correctly the Tado° thermostat.

**Comment by iantrich** [comment]
```yaml
type: entities
entities:
  - climate.mytadodevice
```

**Comment by gigios** [comment]
Ok, I probably misunderstood your previous answer.
I already have a panel with the Tado° entities, my question was related the possibility to add the toggle icons directly in this panel.

![immagine](https://user-images.githubusercontent.com/8749627/52414785-86442100-2ae5-11e9-9ff7-289c2cb14338.png)

Thanks for your answer

**Comment by iantrich** [comment]
@gigios that's related to the Tado component itself and would require a backend change to align the proper modes in that component
