### ISSUE TITLE
Problem with card title (header). macOS. Safari

### ISSUE THREAD

**Issue by hekm77** [home-assistant/home-assistant-polymer#2068]
**Home Assistant release with the issue:**
0.82.1

**Last working Home Assistant release (if known):**
< 0.80

**Browser and Operating System:**
macOS 10.14.1
Safari 12.0.1 

**Description of problem:**
Cards title look normal, they become small after switching the view tabs.
I don't use custom cards (removed from ui-lovelace)
I see the same issue on iOS https://github.com/home-assistant/home-assistant-polymer/issues/2031

**Comment by zsarnett** [comment]
Closing. Referencing #2031
