### ISSUE TITLE
Lovelace UI gauge card non-numeric sensor error

### ISSUE THREAD

**Issue by jeweet** [home-assistant/home-assistant-polymer#2074]
**Home Assistant release with the issue: 82.1**

**Last working Home Assistant release (if known): unknown**

**Browser and Operating System: Firefox on Linux - all browsers**

**Description of problem:**
I use the Lovelace UI Gauge card to show the SMA solar current power. This sensor has a state in watts, but when the SMA (at night) is in stand-by it returns unknown

Error in the UI is: Entity is non-numeric: sensor.current_power

It is however expected behavior for the sensor.

**Additional information:**

**Comment by adbaHA** [comment]
I have the same 'problem'. It's happening since an update from a few weeks ago. It would be great if the Gauge card would just be visible when this happens, but it just shows '0'.

**Comment by adbaHA** [comment]
I found a solution. Add the code below to confguration.yaml, under 'sensor:'. After restart, a new sensor will be created named 'current_power_incl_0', which can be placed in ui-lovelace.yaml. It will show the gauge card all the time.

`- platform: template`
`  sensors:`
`    current_power_incl_0:`
`      friendly_name: 'Huidige opbrengst'`
`      value_template: "{{ states.sensor.current_power.state | replace('unknown','0')  }}"`
