### ISSUE TITLE
Alarm Panel - Conform Button Size

### ISSUE THREAD

**Issue by kvvoff** [home-assistant/home-assistant-polymer#2075]
**Home Assistant release with the issue: 82.1**

**Last working Home Assistant release (if known): unknown**

Browser and Operating System: Chrome on Windows 10 - all browsers

**Description of problem:**

The alarm panel in English (lovelace ui) looks amazing! But I am Russian-speaking, and my Home Assistant works in Russian. And in Russian, the alarm panel in the Lovelase UI looks awful because of the translation of the “clear” button - all the letters in the right column are larger than others.
I even searched to install English for this lovelace card, but I didn’t find how

And the night mode button is not translated into Russian, but these are trifles

sorry for my English

![ha-alarm-wrong](https://user-images.githubusercontent.com/38342171/48826330-05457b00-ed7b-11e8-9cc3-b3f46ea705fb.png)

Additional information:

**Comment by hekm77** [comment]
You can use the full state name **"armed_night": "Охрана (ночь)"**
https://github.com/home-assistant/home-assistant-polymer/blob/dev/translations/ru.json#L26
```
- type: alarm-panel
  entity: alarm_control_panel.alarm
  states:
    - armed_home
    - armed_night
    - armed_away
```
<img width="502" alt="555" src="https://user-images.githubusercontent.com/22895433/48828300-b0e8ce00-ed6f-11e8-9f8f-24732efe5be1.png">
The same problem with the right column

**Comment by kvvoff** [comment]
> You can use the full state name **"armed_night": "Охрана (ночь)"**

Thanks! It remains only to solve the problem with the size of the buttons

**Comment by kvvoff** [comment]
@hekm77 
> states: - armed_home - armed_night - armed_away

When I changed the "states" to the ones you specified (armed), the security panel doesn’t turn on or turn off the security at all — nothing happens. If states "arm" - all warking Apparently this is another mistake.

**Comment by hekm77** [comment]
> > states: - armed_home - armed_night - armed_away
> 
> When I changed the "states" to the ones you specified (armed), the alarm panel doesn’t turn on or turn off the security at all — nothing happens. If states "arm" - all warking. Apparently this is another mistake.

Sorry, this is my mistake. Not checked. It only changes to the correct name in the alarm panel.

**Comment by zsarnett** [comment]
If the translations are wrong, you will need to update them in Lokalise. For the Arm_night that isnt translating, most likely means that there is no translation in Lokalise. The Translation code is there. Its just pulling from the current translations that it has. Fix them and it will pull correctly

**Comment by kvvoff** [comment]
But what about the wrong size of the buttons ???

**Comment by kvvoff** [comment]
> If the translations are wrong, you will need to update them in Lokalise. For the Arm_night that isnt translating, most likely means that there is no translation in Lokalise. The Translation code is there. Its just pulling from the current translations that it has. Fix them and it will pull correctly

But what about the wrong size of the buttons ???

**Comment by kvvoff** [comment]
@zsarnett 

But what about the wrong size of the buttons ???

**Comment by iantrich** [comment]
Is this still an issue? we have switched to mwc-button

**Comment by kvvoff** [comment]
![image](https://user-images.githubusercontent.com/38342171/54069275-aba08800-4267-11e9-96c1-e2e908ece42e.png)

Anyway, the button is wrong!

> Is this still an issue? we have switched to mwc-button

**Comment by kvvoff** [comment]
@iantrich Anyway, the button is wrong!

![image](https://user-images.githubusercontent.com/38342171/54069297-ea364280-4267-11e9-9c7b-7e6eafa13849.png)

**Comment by iantrich** [comment]
I dont see anything wrong?

**Comment by kvvoff** [comment]
@iantrich 
Seriously? Is the letter "o" written so ? The letter "o" is half hidden

**Comment by iantrich** [comment]
Seriously? You think I should know what that button should say in a language I don’t know? Please don’t come here and be rude/condescending

**Comment by kvvoff** [comment]
@iantrich
with all due respect, I see you too lazy to scroll up the page and see how this word was displayed earlier? This word "clear" in Russian. I have done more than one screenshot above, and with the latest updates, this button now covers the word. and yes, the letter "o" in English and Russian is still the letter "o". our letters are similar, it is not Hebrew. I ask you to be a little more attentive the next time before writing this to me.

**Comment by iantrich** [comment]
I’m not here to play “spot the difference”. I’m done here.

**Comment by kvvoff** [comment]
@iantrich
what is the difference? You wrote to me that you do not see any error in the display! You made a conclusion on the basis of something? or do you just write it for nothing to do? need to answer for their words. if you don’t see something or don’t understand, then you don’t need to write that all is well. I hope you will no longer write incompetent things here. thank. I discovered the problem so that it could be fixed, and not so that you just write all sorts of rubbish without even understanding what it is about

**Comment by balloob** [comment]
This tone is not acceptable. This is run by volunteers. We can't fix this and you got yourself temporarily banned. When the ban is over, your attitude should change if you want to participate in this community again.
