### ISSUE TITLE
Unnecessary padding under top menu

### ISSUE THREAD

**Issue by mrysz** [home-assistant/home-assistant-polymer#2084]
**Home Assistant release with the issue:** 0.81.0

**Browser and Operating System:** Safari, Chrome, Firefox - all on MacOS

**Description of problem:**

I see unnecessary padding right under top menu. 
Change was made in commit 685915e.

<img width="828" alt="screenshot 2018-11-22 at 12 54 43" src="https://user-images.githubusercontent.com/7117887/48901631-5e361180-ee56-11e8-9372-cc387a310993.png">

**Comment by balloob** [comment]
CC @zsarnett

**Comment by zsarnett** [comment]
Shouldnt be there if there aren't any badges... When you inspect the element do you seen the Badges div rendering there?

**Comment by mrysz** [comment]
Div is empty and is rendered

![screenshot 2018-11-27 at 19 54 11](https://user-images.githubusercontent.com/7117887/49104500-6ccd6000-f27e-11e8-83ef-3ea413b501b3.jpg)

**Comment by zsarnett** [comment]
Does your view have any badges?

**Comment by mrysz** [comment]
Yes, but just for test I remove everything leaving one camera sensor - padding is still there
![screenshot 2018-11-27 at 20 08 51](https://user-images.githubusercontent.com/7117887/49105290-7f489900-f280-11e8-9393-5df10153f5a5.jpg)

**Comment by zsarnett** [comment]
Can you post the yaml with that

**Comment by mrysz** [comment]
```
default_view:
  view: yes
  name: Start
  icon: mdi:home
  entities:
    - camera.driveway
```

**Comment by zsarnett** [comment]
ah this is regular ui not lovelace. Let me go to that..

**Comment by zsarnett** [comment]
Fixed it in the Referenced PR
