### ISSUE TITLE
Lovelace light card

### ISSUE THREAD

**Issue by mf-social** [home-assistant/home-assistant-polymer#2105]
**Home Assistant release with the issue:** 83.b0

**Last working Home Assistant release (if known):** Unknown - not used before

**Browser and Operating System:** Chrome // Windows

**Description of problem:**

Using the Light lovelace card - https://www.home-assistant.io/lovelace/light/

On my mobile (Chrome // Android) tapping on the card switches the light on/off and long-press opens the more info.  On my laptop neither the tap (mouse-click) or long-press (tried long hold on mouse, and right click, don't know what it's supposed to be!) work.  The swipey brightness works fine.

**Javascript errors shown in the web inspector (if applicable):**

None that I can find, but I'll be honest I don't really understand the inspector.  Certainly usually when something goes wrong I get a load of bold red text, but there's nothing appearing for this.

**Additional information:**

I'm a bit behind the times with locelace so I have no idea how long this has been a problem, but I couldn't find any other issues related to the light card.

**Comment by zsarnett** [comment]
Closing as this is related to #2085
