### ISSUE TITLE
Lovelace 0.83.1 Climate and Light Cards Break Quickly (iOS)

### ISSUE THREAD

**Issue by awgneo** [home-assistant/home-assistant-polymer#2153]
**Home Assistant release with the issue:**
0.83.1

**Last working Home Assistant release (if known):**
Never Worked

**Browser and Operating System:**
Safari iOS12 (iPad or iPhone), Safari Desktop (Mojave)

**Description of problem:**
Any card that has the circular slider eventually dies with minimal usage. The same thing occurs in 0.82.1 and up. You have to play with the sliders for a few times as everything works fine initially. It is random when it starts. The only way to recover is to refresh the page completely. Chrome on my Mac and on my Android device do not experience this issue at all.

**Javascript errors shown in the web inspector (if applicable):**
None in Safari desktop console

**Additional information:**
![screen shot 2018-11-29 at 8 17 02 pm](https://user-images.githubusercontent.com/3988798/49262313-e185d300-f413-11e8-926f-149838bc2680.png)

**Comment by iantrich** [comment]
Is anyone still having these issues? They should have been resolved

**Comment by Ernst79** [comment]
@iantrich Yes, it is resolved.
