### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#2171]
Feature Request
Good option will be add position to menu to logout. As i show on screen. It was more comfortable to user and fatster logout than click on name user and then logout.
![logout](https://user-images.githubusercontent.com/16692223/49375480-b1388000-f704-11e8-8855-ce2a84ab60ed.jpg)

**Comment by balloob** [comment]
We're not going to fix this. Log out is not a common scenario and so we follow a similar approach to native apps on phones.

**Comment by pepeEL** [comment]
But when we not logout he generate tokens which will be store in Home Assistant. But when we logout and then close web browser token is delete.

**Comment by balloob** [comment]
Correct, but most people store their login using the popup in bottom right after login.
