### ISSUE TITLE
Resizing removes some cards

### ISSUE THREAD

**Issue by Tommatheussen** [home-assistant/home-assistant-polymer#220]
I've noticed when I resize my browser (tested in Chrome Version 56.0.2924.87 (64-bit) only for now), some of my cards, in particular the Weather component cards, get removed.

It seems a bit hard to reproduce, since it doesn't happen in every kind of card re-arrangement, I've listed here when it does happen:

**Sidebar open**
- Sizing up from 2 to 3 columns
- Sizing down from 2 to 1 column

**Sidebar closed**
- Sizing up from 2 to 3 columns
- Sizing up from 3 to 4 columns
- Sizing down from 4 to 3 columns
- Sizing down from 2 to 1 column

I thought it was just on the main page, but I've put 1 Weather platform in it's own tab, and the whole tab is empty after the resizing.

This isn't an urgent bug I guess, since usually people have it open in the same size window all the time.

**Comment by Tommatheussen** [comment]
This might be partially related to #223, as there are some errors being thrown regarding Containers not being found, will verify with the PR

**Comment by Tommatheussen** [comment]
Fixed by #223 , was only happening when having Weather charts

**Comment by balloob** [comment]
For the next time, have a look at the browser console, would have pointed at the weather card right away
