### ISSUE TITLE
Column parametr not working in editor UI

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#2211]
Version 0.84.0b1

When add card with option column after come back to again edit i see this error.
![column_fail](https://user-images.githubusercontent.com/16692223/49641901-d9c8be80-fa11-11e8-86f9-367d4694d619.jpg)

**Comment by balloob** [comment]
You've set column to a string, it should be a number.

**Comment by pepeEL** [comment]
But i set as number by editor UI. Look
![column1](https://user-images.githubusercontent.com/16692223/49644080-b1dc5980-fa17-11e8-9536-7fcaa5a63603.jpg)


![column2](https://user-images.githubusercontent.com/16692223/49644082-b4d74a00-fa17-11e8-856a-74da115eecb6.jpg)

**Comment by balloob** [comment]
Ah, yeah that's a bug.

**Comment by pepeEL** [comment]
thanks
