### ISSUE TITLE
Add cards withou option setu ID

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#2215]
version 0.84.0b1

With new editor UI we can add new cards but without option to setup ID. We can switch to line editor but in GUI select we can not add ID.
When we add new card we have this without ID:
![add_card](https://user-images.githubusercontent.com/16692223/49651184-d0018400-fa2e-11e8-9257-7bec4e53450c.jpg)

But in new editor when we add VIEW we have option to set ID:
![add_view](https://user-images.githubusercontent.com/16692223/49651220-e0b1fa00-fa2e-11e8-9fc3-88c5d7f38735.jpg)

Good option will be also fix it to add in editor to add/edit card with option set ID.

**Comment by zsarnett** [comment]
New UI will show no ID to the user

**Comment by pepeEL** [comment]
No for user. For cards... But why show for VIEW ?

**Comment by zsarnett** [comment]
We wont show any ids for anything

**Comment by iantrich** [comment]
@pepeEL to clarify, the user won't need to worry about them from the UI. We plan to have an optional url_path that one can define for navigation purposes though. https://github.com/home-assistant/home-assistant-polymer/issues/2219
