### ISSUE TITLE
0.84.0b1 - LL TouchEvent is not defined

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#2218]
**Home Assistant release with the issue:**
0.84.0b1

**Last working Home Assistant release (if known):**
0.83.3

**Browser and Operating System:**
FF on Ubuntu 18.04, works in Chrome

**Description of problem:**
Clicking on a picture-entity in Chrome opens the more info (bigger picture).
In FF nothing happens and error in the log:
```
2018-12-07 16:23:03 ERROR (MainThread) [frontend.js.latest.201812070] http://192.168.178.67:8123/frontend_latest/9246e4c506c7b3370b91.chunk.js:3388:2072 ReferenceError: TouchEvent is not defined
```
ui_lovelace.yaml
```
          - type: picture-entity
            entity: camera.yr_vorhersage_48h
            show_name: false
            show_state: false
```

**Comment by iantrich** [comment]
Confirmed on Windows 10-Firefox using the long-press demo: https://5c082b5540e2a42226a03895--home-assistant-lovelace-gallery.netlify.com/#demo-util-long-press

**Comment by iantrich** [comment]
On my Windows 10 machine with touchscreen I have no errors, btw. Just my desktop machine that does not have a touchscreen.

**Comment by balloob** [comment]
Please try the long press demo in https://github.com/home-assistant/home-assistant-polymer/pull/2226

**Comment by VDRainer** [comment]
Just for clarification, also short click doesn't work and raises the error.

**Comment by steve28** [comment]
Another data point - same error in glance card with touch-event defined for an entity.  This is in 0.84.0b1:
```
2018-12-07 14:55:56 ERROR (MainThread) [frontend.js.latest.201812070] https://my.server.com/frontend_latest/9246e4c506c7b3370b91.chunk.js:3388:310347 ReferenceError: Can't find variable: TouchEvent
```
