### ISSUE TITLE
Dev panel says "errors" but they're not all errors

### ISSUE THREAD

**Issue by lindsaymarkward** [home-assistant/home-assistant-polymer#225]
Hi. I'm not sure if this should be an issue, or if there's a better way to raise this... issue.

In Developer Tools > Info, it says:
> The following errors have been logged this session

Then shows an excerpt from a log file with normal info messages like
```
17-03-01 21:53:55 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=homeassistant, service=turn_off>
17-03-01 21:53:55 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=homeassistant, service=turn_on>
```

I think using *errors* is misleading. The first time I saw it, I wondered why these were errors and what I had to do to solve them.
Can I suggest changing this to "events" or something more appropriate?
Thanks!

**Comment by andrey-git** [comment]
Maybe we should support level filtering: info/warning/error
The info stream is huge and hardly scrollable anyway.

**Comment by lindsaymarkward** [comment]
I was going to say that too, but thought I'd start small. Yes, I think that would make it super useful!

**Comment by andrey-git** [comment]
@lindsaymarkward You are probably using the `logger` component in your config.

By default info+ messages go to the console and warning messages  are saved into a file. This file is loaded into Developer Tools > Info.

However when `logger` is used its setting override both console & file, so now everything that goes to console according to `logger` also goes to the file.

HA should be fixed to write severals files per logging levels and the UI should support getting the correct file.

**Comment by andrey-git** [comment]
@balloob does this approach sounds good to you?

**Comment by balloob** [comment]
I agree that this is a Home Assistant problem and not a UI problem. `home-assistant.log` is by default only used for warnings and errors. If people log other things to it… well then the error log will show them.

(closing this as not a frontend issue)
