### ISSUE TITLE
Sorting entity on cards

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#2254]
New iterface editor UI is very good :) I like it
But good when will be add also new function to we can soft entity on edit card. Now we can not do it... Maybe good option will be add arrow as i show on screen.
![sort_encje](https://user-images.githubusercontent.com/16692223/49761040-3bb14e80-fcc6-11e8-936a-82b5507ef833.jpg)

**Comment by iantrich** [comment]
Yeah. Good idea.
