### ISSUE TITLE
[0.84.0b3] Lovelace Raw Editor Scroll Bar Position

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#2256]
**Home Assistant release with the issue:**
0.84.0b4

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Windows 10 - Opera 56

**Description of problem:**
As per the below screenshot, when using the new Lovelace Raw Editor, the vertical scroll bar for it hides under the page scroll bar. Meaning you need to scroll to the side a bit to see it. This doesn't feel/look intended. I don't think the horizontal scroll bar is required at all given the word wrapping.

![image](https://user-images.githubusercontent.com/24840952/49775340-c7b78a80-fd47-11e8-912f-65f50038c4ec.png)

**Comment by balloob** [comment]
Yeah the page shouldn't scroll just the text area. Already fixed in final
