### ISSUE TITLE
Add option config TITLE GENERAL

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#2273]
Hi
Good option will be also ad to ne UI Editor Lovelace option to user can configure GENERAL TITTLE for Home  Assistant. Now only can in RAW Editor.
![title](https://user-images.githubusercontent.com/16692223/49851622-f71ad580-fde1-11e8-8d7c-a00ef90d91a6.jpg)

**Comment by balloob** [comment]
This repo's issues are only for bugs, not feature requests.
