### ISSUE TITLE
Glance card editor not auto-filling entities

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/home-assistant-polymer#2281]
**Home Assistant release with the issue:**
0.84.1

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

**Description of problem:**

When using the new Lovelace editor, you can't add entities to a Glance card using the picker, nothing happens. Manually typing the entity works.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
@DubhAd please confirm that you're no longer having issues with this. I am unable to replicate

**Comment by iantrich** [comment]
Closing as no response
