### ISSUE TITLE
Glance and Entities card editor config error

### ISSUE THREAD

**Issue by bogdanalexe90** [home-assistant/home-assistant-polymer#2288]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
0.83

**Browser and Operating System:**
Chrome latest version

**Description of problem:**
Error in glance and entities card editor. See screnshots.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

[
<img width="651" alt="screenshot 2018-12-13 at 12 37 22" src="https://user-images.githubusercontent.com/8752468/49933338-08dca580-fed4-11e8-9bcc-9f58a7146f0c.png">
](url)
<img width="651" alt="screenshot 2018-12-13 at 12 34 52" src="https://user-images.githubusercontent.com/8752468/49933352-13973a80-fed4-11e8-8217-1c24596173d9.png">

**Comment by balloob** [comment]
This is correct. Our UI editor does not support all options yet and so in such cases it will bail out to the YAML editor. We should probably replace the error with a small info text: "UI Editor not supported (?)"

**Comment by bogdanalexe90** [comment]
Sure... but neither name or icon are supported and the editor still works. I was expecting same behaviour for tap and hold action
