### ISSUE TITLE
Split icons in two groups

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#229]
Our icon situation has gotten out of hand. We are depending on the community maintained material design icons and they keep growing. And each icon that is added, is another icon that we ship over, parse and keep in memory and might never use.

It is currently the biggest asset that we ship at 185kb minified. To make it worse, because the renderer `iron-icon` is unable to be notified to re-render, we are currently loading the icons before showing the UI.

I think that it's time to split icons into two files:

Create one file with 'internal' icons. Those are the ones that are used in the UI or by cards or domains. We will prefix that collection with `hass:`. These icons will be included with the main app bundle.

We will also create a new web component named `hass-icon`. If the given icon starts with `mdi:` it will make sure to load the icons from the server before rendering the `iron-icon`.

This should improve load performance a lot.

**Comment by justweb1** [comment]
The recommendation for this is to only use a custom specific file like hass-icons.html. In this project it could be broken out further to specific sensor types to ensure the entire file isn't loaded if it is not necessary. You can then select only to import the proper files based on the components needed and call the icons like hacore:person or haweather:thermometer

File Structure:
icons/
/hass-core-icons.html
/hass-light-icons.html
/hass-weather-icons.html
/hass-camera-icons.html
/hass-location-icons.html

etc... etc... etc...

**Comment by Molodax** [comment]
Meanwhile, would it be possible to update md icons?
There are new ones that are missing in 0.45.x and 0.46 versions.

**Comment by balloob** [comment]
Fixed in #1214
