### ISSUE TITLE
Add a delay before sending thermostat target temp updates

### ISSUE THREAD

**Issue by janLo** [home-assistant/home-assistant-polymer#230]
Since 0.39 the thermostat widget uses up/down buttons instead of a slider. If I try to set the temperature more than one step it sends a lot of service calls. So to change the temp from 17°C to 21°C I have to press the button eight times. The frontend will send eight service calls, triggers all assigned automations eight times and the number in the ui switches back and forth due to races between changes made by the button and streamed updates from the backend. This is also a problem because platforms like homematic are not able to send out such a lot of updates in a short timeframe due to radio limitations.

All this renders the temperature selection almost useless. I see the following options:
* delay and aggregate the servicecalls in the frontend (e.g. send a service call only if the walue was not changed for to seconds or similar)
* revert to the old slider
* provide a separate option to select a target temperature.

**Comment by andkit** [comment]
I'd like to second this wholeheartedly. The old slider could admittedly be a bit fiddly at times on mobile but I apparently had enough sensitivity in my fingers to not be annoyed by it ;)
Even without the race-issue I'd be annoyed by having to tap eight times and right now I have to tap-wait-tap-wait....

If it were up to me I'd replace the static text with the current value with an editable input and add the delay to the up/down arrows as @janLo suggested (it's a nice touch [pun intended] for small adjustments and I've heard some people don't like typing)

**Comment by balloob** [comment]
I don't like keyboards spawning up. I think a better approach would be that you can hold the up/down buttons to have it keep increasing/decreasing the temperature and only sending it at the end.

**Comment by JDiPierro** [comment]
How about a combination of the two?

![](https://cloud.githubusercontent.com/assets/867375/23562041/d14f3468-000e-11e7-8648-9f3ecdef37fa.png)

**Comment by sdague** [comment]
Also discussion in home-assistant main tracker - https://github.com/home-assistant/home-assistant/issues/6365

**Comment by sdague** [comment]
Playing around with paper-button demo on my phone, the capture of the pressed event seems promising. I'll see if I can find some examples of increasing at a rate while pressed is happening.

**Comment by sdague** [comment]
I think there is a pretty clear short term fix where instead of firing 'changed' on every change of value, we record the timestamp when the last value change happened, and only fire after there has been no change for some interval (maybe default 2 seconds). I could probably get that coded up for review over the next day or so.

**Comment by janLo** [comment]
It would be really great if this could be part of the next release. Otherwise I wold prefer to revert the change until we've a solution.

**Comment by janLo** [comment]
It seems to work in 0.40. Shall we close the issue or is there more to do?

**Comment by balloob** [comment]
Closing should do 👍
