### ISSUE TITLE
Add arrows to either side of the temp slider on more-info-climate

### ISSUE THREAD

**Issue by JDiPierro** [home-assistant/home-assistant-polymer#231]
Heya,

I use the "Target temperature" slider on the More Info Climate dialog as the primary way of setting my thermostat. It's pretty annoying to have to grab the slider and move it a short distance to go up half a degree though. I'd love to see arrows on either side of the slider I could click to go up in increments.

Thanks!

Current:
![image](https://cloud.githubusercontent.com/assets/867375/23561986/9f0a5c9e-000e-11e7-8e53-132c53bfbd69.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/867375/23562041/d14f3468-000e-11e7-8648-9f3ecdef37fa.png)

**Comment by balloob** [comment]
We already do this, you're using an old version.
