### ISSUE TITLE
"more-info" does not have a turn on/off option when using "glance".

### ISSUE THREAD

**Issue by chierichetto** [home-assistant/home-assistant-polymer#2323]
**Home Assistant release with the issue:**
0.84.2
**Last working Home Assistant release (if known):**
0.82

**Browser and Operating System:**
Hassio and Chrome

**Description of problem:**
"more-info" does not have a turn on/off option for switches when opening from a glance card. Works when using the lovelace card "entities".

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

**Comment by zsarnett** [comment]
Can you post a Gif or image of this issue?

**Comment by chierichetto** [comment]
Seems to work again. Switched back to glance from 'entities' now, and i've also updated to 0.84.3.
