### ISSUE TITLE
Edit UI - Can't edit object after ESC

### ISSUE THREAD

**Issue by xNuno** [home-assistant/home-assistant-polymer#2331]
**Home Assistant release with the issue:**

0.84.2

**Last working Home Assistant release (if known):**
None. This is new feature, edit object directly on browser.

**Browser and Operating System:**

Google Chrome - Windows 10 Latest

**Description of problem:**

When using the Edit UI, after click on edit object it opens but if you click ESC you can't edit it again until you refresh the browser contents. If you press edit after the ESC nothing happens.
If on other way the cancel it's clicked then everything works as expected and it's possible do edit object again. 
I guess ESC is exiting the edit mode globally and no only the object being edited.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![image](https://user-images.githubusercontent.com/8095169/50046679-2ad65380-009f-11e9-91b3-a7db2374b641.png)

**Comment by iantrich** [comment]
I can't replicate this on Windows 10 - Chrome

**Comment by xNuno** [comment]
> I can't replicate this on Windows 10 - Chrome

1 - Try to edit any object you have
2 - Press ESC key
3 - Try to edit it again... it will not open if you click edit

**Comment by xNuno** [comment]
![issue](https://user-images.githubusercontent.com/8095169/50054997-b653f100-0140-11e9-8279-fd0e1e2d80a1.gif)

**Comment by iantrich** [comment]
I did exactly that and it worked fine. ¯\_(ツ)_/¯

**Comment by balloob** [comment]
I fixed this in dev. #2290
