### ISSUE TITLE
Lovelace gauges don't show up in edit mode until a YAML change is made

### ISSUE THREAD

**Issue by mlevit** [home-assistant/home-assistant-polymer#2333]
**Home Assistant release with the issue:** 0.84.*

**Last working Home Assistant release (if known):** N/A

**Browser and Operating System:** Google Chrome Version 70.0.3538.110 / macOS 10.14.2

**Description of problem:** When entering "Configure UI" mode, gauges no longer appear. You must click the Edit button of the group they belong in, then make a change to the YAML which will force them to appear.

The last two groups in the below screenshot are gauges:
![image](https://user-images.githubusercontent.com/233717/50047567-e6cd6800-010b-11e9-9206-7df398324d07.png)

Even after clicking Edit they don't appear:
![image](https://user-images.githubusercontent.com/233717/50047573-06fd2700-010c-11e9-9a7d-c35e18662985.png)

Only after making a change to the YAML will they appear:
![image](https://user-images.githubusercontent.com/233717/50047578-13817f80-010c-11e9-8d59-b287fb802944.png)

**Javascript errors shown in the web inspector (if applicable):**
```
N/A
```

**Additional information:**

**Comment by iantrich** [comment]
This has been fixed in my testing. Please let me know if you're still seeing issues though.
