### ISSUE TITLE
Plant component not shown

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant-polymer#2341]
**Home Assistant release with the issue:**

0.84.x
**Last working Home Assistant release (if known):**
0.83

**Browser and Operating System:**

Chrome (Android, Windows)
**Description of problem:**

The plant component is not shown in UI after update to 0.84.2

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
Log Details (ERROR)
Mon Dec 17 2018 00:55:31 GMT+0100 (Central European Standard Time)

https://xxx.com/frontend_latest/bf7146608f595468a214.chunk.js:3157:1377 Uncaught TypeError: Cannot read property 'name' of undefined

See the same problem in the forum (latest posts): https://community.home-assistant.io/t/plant-component-not-shown/38828/6?u=molodax

**Comment by iantrich** [comment]
Fix already made. Will be in next beta
