### ISSUE TITLE
Problem with automations in 0.84.x

### ISSUE THREAD

**Issue by labachev** [home-assistant/home-assistant-polymer#2355]
**Home Assistant release with the issue:**
0.84.3

**Last working Home Assistant release (if known):**
0.83.x

**Browser and Operating System:**
Chrome
Windows 10

**Description of problem:**
Automation does not trigger.

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
If space and single quotes are added to automation alias it is working.
If space is added via Automation Editor UI it is working.
The automations can be triggered manually from the UI in dev-service

**Comment by fernmac2** [comment]
I have the same issue: Automations do not trigger when HA restarts although they work fine in UI
No space or quotes work for me

**Comment by labachev** [comment]
There is a change that requires to set an attribute to each and every automation: 
initial_state: 'on'

This solves the issue.
