### ISSUE TITLE
WebOSTV Card not showing in the overview page.

### ISSUE THREAD

**Issue by GoldilokZ** [home-assistant/home-assistant-polymer#2365]
Home Assistant release with the issue:
0.84.2, 0.84.3
Previous issue #2350 was closed as fixed in 0.84.3, but it isn't.

Last working Home Assistant release (if known):
0.84.1

Browser and Operating System:
Google Chrome 71.0.3578.98 / Win10 1803 (November update) and Server 2016 (December Update)
Works fine in Microsoft Edge v42.17134.1.0 / win10 1803 (november update)

Description of problem:
On the overview page in chrome, my LG WebOSTV only occasionally shows up as a card, but it's usually not. Sometimes refreshing the page brings it back, or going to another page in HASS, and back to the overview bring it back...sometimes not.

It is showing up as an entity, and the below is the config I'm using.
I've tried re-pairing the TV too, but does the same thing,.
  - platform: webostv
    host: 192.168.1.3
    name: LG 55UH652T

Javascript errors shown in the web inspector (if applicable):

No errors that I could see in the console.

Additional information:
What it looks like when the card isn't there...but it looks like the frontend is trying to render it due to the column being down slightly...if I remove the media player section completely the columns line up properly.
 
![image](https://user-images.githubusercontent.com/45279619/50179832-c5f75380-0353-11e9-8028-48e65f2fbb04.png)

and this is what it looks like when the card is there.
 
![image](https://user-images.githubusercontent.com/45279619/50179844-cd1e6180-0353-11e9-9fec-b2b3de2cecd4.png)

**Comment by balloob** [comment]
Errors in console? Is this lovelace?

**Comment by GoldilokZ** [comment]
Nah mate...no errors unfortunately.
Not lovelace either.

The entity is showing as media_player.lg_55uh652t, and I can control it fine via the devtools / services menu

**Comment by iantrich** [comment]
Would you mind trying Lovelace and seeing if it shows up in the auto generated dashboard?

**Comment by GoldilokZ** [comment]
Lovelace appears to work fine.

**Comment by balloob** [comment]
Can you try in a Chrome browser in incognito mode?

**Comment by GoldilokZ** [comment]
Incognito mode has the same problem.
I checked it on a couple of computers before lodging the report.  Edge is fine, chrome isn't

**Comment by iantrich** [comment]
as this is a states only bug, we won't be fixing it as we focus more energy on lovelace.
