### ISSUE TITLE
Lovelace picture-entity card stoped working with any ffmpeg based cameras after update

### ISSUE THREAD

**Issue by MaximumSU** [home-assistant/home-assistant-polymer#2368]
**Home Assistant release with the issue:**
0.84
**Last working Home Assistant release (if known):**
0.83
**Browser and Operating System:**
Windows 10, MacOS, Chrome, Firefox

**Description of problem:**
Lovelace picture-entity card stoped working with any ffmpeg based cameras after update. It simply not show anything in the place of card. It looks like i not have this card in config, but it is here. Before 0.84 it worked without problem.

**Javascript errors shown in the web inspector (if applicable):**
```
no errors
```

**Additional information:**

**Comment by iantrich** [comment]
is this true after the new `stream` option added in April?

**Comment by iantrich** [comment]
closing with no response
