### ISSUE TITLE
Moon sensor not picking up translations.

### ISSUE THREAD

**Issue by tomeeka** [home-assistant/home-assistant-polymer#2372]
**Home Assistant release with the issue:**
0.84.5

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
Firefox/Chrome Android/Windows

**Description of problem:**
Moon sensor not picking up translations.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![kep](https://user-images.githubusercontent.com/41842441/50288337-f29b9000-0465-11e9-8c3c-48335cf016b5.png)

**Comment by tomeeka** [comment]
Sometimes if the translation is there, after a browser refresh it is gone.

**Comment by iantrich** [comment]
I believe these caching issues were resolved awhile back. If not, I'll reopen

**Comment by tomeeka** [comment]
Still...
![kép](https://user-images.githubusercontent.com/41842441/66259701-7257d880-e7b4-11e9-9687-95b3ce777fbe.png)
Usually after I restart Home Assistant the translation is missing.
I have tried with different browsers on pc and android. If the translation is missing on one of them, the same happens on the others.
But only with the moon sensor for me.
