### ISSUE TITLE
Lovelace: Entity Button triggers ALL scripts

### ISSUE THREAD

**Issue by PDekker** [home-assistant/home-assistant-polymer#2374]
**Home Assistant release with the issue:**
0.84.5

**Last working Home Assistant release (if known):**
0.83

**Browser and Operating System:**
Safari / MACOS
IOS 

**Description of problem:**
When I push one of the entity button cards configured to trigger a script. ALL scripts (even on different views) are trigged

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

Config:

          - cards:
              - entity: script.alle_rolluiken_open
                icon: ' '
                name: Goedemorgen
                tap_action:
                  action: call-service
                  service: script.turn_on
                type: entity-button
              - entity: script.welterusten
                icon: ' '
                name: Welterusten
                tap_action:
                  action: call-service
                  service: script.turn_on
                type: entity-button
            type: horizontal-stack
          - cards:
              - entity: script.alle_rolluiken_open
                icon: ' '
                name: Rolluiken open
                tap_action:
                  action: call-service
                  service: script.turn_on
                type: entity-button
              - entity: script.alle_rolluiken_dicht
                icon: ' '
                name: Rolluiken dicht
                tap_action:
                  action: call-service
                  service: script.turn_on
                type: entity-button
            type: horizontal-stack

**Comment by iantrich** [comment]
You need to specify the entity_id in the service_data
