### ISSUE TITLE
Units of measurement capitalized in state badge labels

### ISSUE THREAD

**Issue by DavidMStraub** [home-assistant/home-assistant-polymer#238]
Since the state badge labels are transformed to uppercase by CSS, the units of numerical sensors are also transformed to uppercase. While there are many uppercase units like °C,  W, etc., where this is not a problem, as a physicist I find it annoying (and possibly ambiguous) for units like lm (Lumen), lx (Lux), in (inches), mm, etc. Now I have a magnetic field sensor measuring µT (microteslas) and it is transformed to MT (megateslas? ;)). Would it be possible to add another `<span>` for units of measurement and prevent them from being capitalized?

**Comment by andrey-git** [comment]
@balloob , this can be solved by extra customization :smiling_imp: 
An attribute like `capitalize: false` passed from `ha-state-label-badge` to `ha-label-badge`

**Comment by NovapaX** [comment]
Although an old issue, still valid.
I think we should not change case of unit_of_measurement at all.
We don't do that in the state-cards either. So unit of measurement should be defined with the correct case anyway.
