### ISSUE TITLE
States Page broken if “lovelace: mode: yaml” is set.

### ISSUE THREAD

**Issue by SiliconAvatar** [home-assistant/home-assistant-polymer#2382]
**Home Assistant release with the issue:**

0.84.6

**Last working Home Assistant release (if known):**

0.83.X

**Browser and Operating System:**

Hassio running on Ubuntu 18.04.1 LTS on an Intel NUC

**Description of problem:**

When using Home-Assistant with:
```
lovelace:
  mode: yaml
```

Set in Configuration.YAML the states page is broken. Opening the states page causes a second left-hand-side menu to appear with an empty main page. An example of this (from another user) can be found here: https://i.imgur.com/XOvYBtk.png

On my own setup, the default language is english, if that has any bearing on things.

This issue appears even when lovelace is *not* set as the default UI. In that case, the main GUI gives the same behaviour as shown in the photo. (For completeness, the issue likewise appears when lovelace *is* set as the default UI and you access the states page via the URL)

I'm not sure if this is related, but since upgrading to the new UI, I see this appear in the logs, which I do not recall seeing previously:

```
Overwriting component states
December 23, 2018, 11:34 PM components/frontend/__init__.py (WARNING)
```

This was also noted by another user in the forum:
https://community.home-assistant.io/t/states-page-dont-work-since-0-84-1/84600

**Comment by balloob** [comment]
That screenshot is not from our states panel, but a custom entry on the left sidebar, probably pointing at something custom configured

**Comment by SiliconAvatar** [comment]
Ok, If that's what you think then here's a screenshot of my own system.

https://i.imgur.com/vA65EnL.png

The "States" button is simply this:

```
  states:
    title: States
    icon: mdi:google-circles-extended
    url: https://[XXXXXXXXXX].duckdns.org:8123/states

```


If I access it from another computer, which does not have lovelace set as the default, this is what loads:

https://i.imgur.com/rMx5iey.png

**Comment by balloob** [comment]
That's not supported. That way you're loading the whole UI again, now to be shown on the right, so that will include a sidebar again too.

**Comment by SiliconAvatar** [comment]
I do not think you are understanding the issue here.

Let's entirely ignore loading the states page as an iFrame (which worked 100% fine on 0.83.X).

If I have lovelace mode set to YAML, and do NOT have lovelace set as the default UI, the normal GUI (states page) just does not load at all. 

If I go to a computer that does not have lovelace already set as the default UI, then Home-Assistant just does not work. It loads a blank page that says "States" at the top, and I have to set lovelace as the default on that browser before I can interact with anything.

Are you saying that if you choose to enable lovelace, that as of 0.84.X it's no longer possible to use the old GUI?

**Comment by iantrich** [comment]
The issue is how you are navigating to states page I believe.

**Comment by SiliconAvatar** [comment]
> The issue is how you are navigating to states page I believe.

Here's how I'm trying to navigate to the states page:

If I open a new browser, on a different computer, that has never used Home-Assistant before, log-in then the default page it lands you on should be the states page. That's it. And when I do that, I get [this](https://i.imgur.com/0FooyBZ.png). Are you suggesting that this is not the correct way to load the default GUI? If so, what is the correct way? (If I just navigate to "/states" in the address bar, my results are the same)

AFAIK, you have to enable lovelace as the default in the dev-info panel to make lovelace load as default. If you do not do that, it should load the states page by default, which seems to now be broken.

The only changes made to my system between it working fine and now are upgrading to 0.84 and setting lovelace: mode: yaml.

**Comment by bramkragten** [comment]
That something works doesn't mean it is supported... As in we probably didn't even realize it worked, so when changing something didn't realize something would be broken... What you did was basically a hack.

**Comment by artmg** [comment]
If you want to have a neat way to get from Lovelace into the legacy States Page, then you can use the technique mentioned in [this post](https://bonani.tech/lovelace-accessing-home-assistant-states-page-with-just-one-click/). It is simply a weblink out to the old url for the States Page. Although you no longer have the little View Tabs at the top like in Lovelace, you can easily 'go back' simply by clicking on Overview in the top left navigation
