### ISSUE TITLE
Deleting Lovelace cards/views on iOS fails

### ISSUE THREAD

**Issue by hagenuck1** [home-assistant/home-assistant-polymer#2386]
Hi, deleting Lovelace cards on iOS (Safari, Hass.io App, from iPad & iPhone) fails. The query if it really should be deleted isn’t shown. 

Using Hass.io 84.6.

**Comment by iantrich** [comment]
Is this still an issue for you? I can't replicate.

**Comment by hagenuck1** [comment]
Was fixed with 0.87, thanks.
