### ISSUE TITLE
Lovelace Ignoring Background Theme Colours

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#2387]
**Home Assistant release with the issue:**
0.84.6

**Last working Home Assistant release (if known):**
Unsure

**Browser and Operating System:**
Chrome, Safari, iOS

**Description of problem:**
When applying a theme to a Lovelace view, where that theme includes custom `primary-background-color`, and `secondary-background-color`, neither are applied. Using a custom `primary-color` seems to work on the per-view basis as part of the same theme (although should that variable also change the header bar? Because it doesn't). I'm just defining the theme as per the docs.

I've tried the usual browser cache clears, reboots, etc. My test theme is about as simple as it gets (have also tried hex codes):

I haven't gone digging to see what else is affected, as I mostly wanted to change the background colour to suit a tablet view I'm setting up.

themes.yaml:
```
tablet:
  primary-color: 'orange'
  primary-background-color: 'yellow'
  secondary-background-color: 'green'
```

**Javascript errors shown in the web inspector (if applicable):**
```
Nothing
```

**Additional information:**
I also don't seem to have the option to select a backend theme from the configuration page. Unsure if this is because I'm using Lovelace.

**Comment by hunter-hunter** [comment]
I'm having the same problem on 0.86.0. Have you been able to find a reason?

**Comment by setlursh** [comment]
I'm experiencing the same issue, though I am able to select themes from the user page. While background colour isn't respected when I set a theme on a per-view basis, it is respected when I set a theme on a per-user basis. My current workaround is to create a user for each device that needs a theme, as opposed to setting per-view themes.

**Comment by iantrich** [comment]
I believe this is fixed now
