### ISSUE TITLE
Lovelace: conditional cards leave empty column when hidden

### ISSUE THREAD

**Issue by nikrolls** [home-assistant/home-assistant-polymer#2395]
**Home Assistant release with the issue:**
0.84.6

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Chrome & Edge on Windows 10 1809

**Description of problem:**
When a conditional card is hidden, there is still an empty column reserved for it. This is not a duplicate of #1686; it's a new issue or a regression.

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
![image](https://user-images.githubusercontent.com/2626677/50577135-dd6f2a00-0e85-11e9-80d0-860a78677e61.png)

**Comment by tompaterson14** [comment]
Did you ever find a fix for this? Seems slightly different to #2167

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/home-assistant-polymer/issues/2167
