### ISSUE TITLE
Not showing play buttons or Samsung TV

### ISSUE THREAD

**Issue by SimplyGardner** [home-assistant/home-assistant-polymer#2410]
Moved as requested - [original issue](https://github.com/home-assistant/home-assistant/issues/6969)

I am able to control turn on / off, volume etc but when the TV is on - I am unable to see the Play button....

This also works in the services section:

```
**Service:** media_player.media_pause
**Entity:** media_player.bedroom_tv

**Service Data:**
{
  "entity_id": "media_player.bedroom_tv"
}
```

<img width="515" alt="screenshot 2019-01-04 at 11 21 16" src="https://user-images.githubusercontent.com/46373533/50685925-34563a00-1013-11e9-84e1-1ab0af2242ef.png">
<img width="517" alt="screenshot 2019-01-04 at 11 21 33" src="https://user-images.githubusercontent.com/46373533/50685927-35876700-1013-11e9-979d-f8bedb564dde.png">

**Comment by balloob** [comment]
Can you copy paste the state attributes from the state dev tool for this media player?

**Comment by SimplyGardner** [comment]
<img width="500" alt="screenshot 2019-01-13 at 16 11 50" src="https://user-images.githubusercontent.com/46373533/51087660-02994d80-174e-11e9-9b22-ec4b16fd57b8.png">

**Comment by iantrich** [comment]
@SimplyGardner is this working in Lovelace in an entities card?

**Comment by anapaulagomes** [comment]
It was fixed on my Samsung TV but it persists on my Chromecast:

<img width="410" alt="screen shot 2019-02-16 at 12 01 22" src="https://user-images.githubusercontent.com/1899950/52898811-ebcd9700-31e2-11e9-851b-ab692cc3ab38.png">

**Comment by iantrich** [comment]
@anapaulagomes when "Unavailable" that is intended. I would argue that we should hit forward/back buttons as well when Unavailable

**Comment by SimplyGardner** [comment]
Hi @iantrich - just testing this now and it is not working in Love Lace either. 
<img width="505" alt="screenshot 2019-02-18 at 10 49 12" src="https://user-images.githubusercontent.com/46373533/52946067-0599e600-336b-11e9-8c88-6de0c0e0d24d.png">

**Comment by SimplyGardner** [comment]
Wondering if i have to add some elements here to enable the play pause buttons etc?
<img width="986" alt="screenshot 2019-02-18 at 10 54 39" src="https://user-images.githubusercontent.com/46373533/52946308-a688a100-336b-11e9-99ab-c0d0223658f9.png">

**Comment by iantrich** [comment]
@SimplyGardner thought @anapaulagomes was OP without checking.

This is your starting point to debug if interested: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/cards/ha-media_player-card.js#L332
