### ISSUE TITLE
 Lovelace default themostat is unusable.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant-polymer#2412]
**Home Assistant release with the issue:**

0.84.6

**Last working Home Assistant release (if known):**

none

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io/Hass.OS

**Component/platform:**

generic thermostat

**Description of problem:**

As title.
I'm using celsius degrees and in celsius half degree is important.

The new lovelace UI does not let me choose 20.5 degree but only 20 or 21.

I cannot visually set the away mode.

New UI does not have an history of temp and furnance use like the old one.
https://postimg.cc/hhY45kBP

I think that this "component" in this state is a huge regression over the older one.
Please remove it until it is in a usable state.

**Traceback (if applicable):**
```
none found
```

**Additional information:**
none

**Comment by iantrich** [comment]
Older one?

**Comment by sblantipodi** [comment]
@iantrich the one used in the old UI not lovelace one. what you don't understood?

**Comment by iantrich** [comment]
meant to reference my PR https://github.com/home-assistant/home-assistant-polymer/pull/2369
it's already in the pipeline
also, not sure what removing it would gain us? don't use it if you find it unusable

**Comment by sblantipodi** [comment]
what about the history like this
https://postimg.cc/hhY45kBP

and the away mode that we have in the generic-thermostat on non lovelace Ui?

**Comment by iantrich** [comment]
Use the climate entity row to get the same look/actions as states or just continue to use states overall
The thermostat card will gain more-info displaying in a future update

**Comment by iantrich** [comment]
It looks like you have it.

```yaml
- type: entities
  entities:
    - climate.room_heat
```

Which you already have, will give you a climate entity row, which is essentially the same as what was on states. Clicking it brings up the same more-info dialog. So not sure what you think is missing? Can you perhaps show me side-by-side states vs lovelace?

**Comment by sblantipodi** [comment]
I solved by using the new storage mode for lovelace and showing the entity as a separate object. thanks
