### ISSUE TITLE
0.85.0b0 - Gauge card scaling broken

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#2418]
**Home Assistant release with the issue:**
0.85.0b0

**Last working Home Assistant release (if known):**
0.84.6

**Browser and Operating System:**
FF, Chrome, iOS

**Description of problem:**
Scaling gauges in a horizontal stack doesn't work.
![auswahl_163](https://user-images.githubusercontent.com/26381449/50741853-8958a280-1203-11e9-9bcd-fe6535cb22b7.png)

**Comment by VDRainer** [comment]
Fixed in 0.85.0

**Comment by VDRainer** [comment]
Reopening this because after a while when going back to a view it sometimes looks like this.
![auswahl_171](https://user-images.githubusercontent.com/26381449/51053096-ff308580-15d8-11e9-98f3-b79324bba572.png)
After refreshing the view all is goog again.

**Comment by Fusseldieb** [comment]
> Reopening this because after a while when going back to a view it sometimes looks like this.

Are those Lovelace gauges? Never seen those... If they are third-party, you might be in the wrong place to ask
