### ISSUE TITLE
Lovelace - Changes to group visibility require a page refresh to see

### ISSUE THREAD

**Issue by sqldiablo** [home-assistant/home-assistant-polymer#2419]
**Home Assistant release with the issue:**
0.85.0b0

**Last working Home Assistant release (if known):**
Unknown (I'm new to Lovelace)

**Browser and Operating System:**
Browser: Chrome 71.0.3578.98 on Windows 10
Home Assistant: HASS.io on a Raspberry Pi 3 B+ (32bit)

**Description of problem:**
I have an automation that sets certain groups visibility on or off based on certain conditions. In the old UI, these visibility changes are instantly reflected in the UI without needing to refresh the page. In Lovelace, I have to do a page refresh to see the change in group visibility.

**Comment by VDRainer** [comment]
I think the group visibility is not intended for lovelave.
You can do it for cards in LL with the [Conditional Card](https://www.home-assistant.io/lovelace/conditional/)
