### ISSUE TITLE
Frontend doesn't send websocket 'ping' request after 60 seconds

### ISSUE THREAD

**Issue by PaulAnnekov** [home-assistant/home-assistant-polymer#242]
I see home-assistant-js (https://github.com/home-assistant/home-assistant-js/blob/0203764d05dab62d896585e3a84936ba7dde614c/src/modules/stream/actions.js#L39) was doing this. As you get rid of it - `ping()` is not called anymore. 
So connection will be closed by e.g. nginx (by default after 60 sec) and re-created. Connection re-creation will trigger some parts of interface redraw, e.g. `panels`, including iframe panels. So each 60 secs if no events will be sent from server - chosen iframe panel will reload. It's annoying.

Please, return back `ping` frame.

**Comment by balloob** [comment]
Wrong repo - this should be implemented in [Home Assistant JS Websocket](https://github.com/home-assistant/home-assistant-js-websocket). PR welcome 👍
