### ISSUE TITLE
Friendly_name not shown in name input field from discovered switch

### ISSUE THREAD

**Issue by toSvenson** [home-assistant/home-assistant-polymer#2422]
**Home Assistant release with the issue: 
0.85.0b0

**Last working Home Assistant release (if known): 
Unknown

**Browser and Operating System: 
Chrome 71 / Windows 10

**Description of problem:
A newly discovered switch (in my case from Tuya) is correctly discovered and listed in the device state overview, including the correct friendly_name as retrieved from Tuya. When editing the switch, the "name" field is empty, although the title correctly displays the friendly name.

Entering a new friendly name is accepted is expected and overwrites correctly the original name.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
The name is empty because that field is to override the name provided by the integration, and there is currently no override. When you make it empty, it will start using the provided name again.
