### ISSUE TITLE
Climate temperature cannot be manually raised

### ISSUE THREAD

**Issue by mgies** [home-assistant/home-assistant-polymer#2427]
**Home Assistant release with the issue:**
Version 0.84.6

**Last working Home Assistant release (if known):**
unknown -> never experienced this working before...

**Browser and Operating System:**
Bug occurs on:
Laptop running kubuntu 18.04.1 with Chromium
Galaxy S5 running LineageOS 15 with Fennec-fdroid

**Description of problem:**
I control my heating through HA and KNX. Everything works fine, except manually turning up the tempereature in the webUI. Turning the temperature down works fine.
There are no errors in the log on the info page.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by mgies** [comment]
Sorry, the issue I was referring to concerns HA itself:
https://github.com/home-assistant/home-assistant/issues/14531

**Comment by bramkragten** [comment]
Is this a frontend problem? Does this work with a service call?

**Comment by mgies** [comment]
With a service call it works in the manner HA is currently handling it: climate.set_temperature

The thing is though: my knx heating controller does not accept this. HA thinks it has successfully changed the target temperature, but when i re-read it from the knx controller it returns the previous value.

My controller expects either a 1bit +/- value or a 2byte step value like +/-0,5K. The calculation of the new target temperature is done in my controller and then the target-temperature is sent to the target-temp KNX-group. So HA should only send a shift command and then wait for the response on target-temp KNX group to be sure the target temp has actually been changed.

But HA seems to be completely lacking a climate.shift_temperature service. It seems to me the     setpoint_shift_address: '1/0/10' config is completely useless like this.

So there seem to be two things going wrong:
1. When increasing the temp in the GUI, nothing happens. No packets on the KNX bus. Seems like a GUI probelm to me. Maybe the service is not called.
2. When decreasing the temp in the GUI, HA sends a new target temp, which is not acceptet by my controller. Seems like a HA problem: wrong behavior for KNX usage.

**Comment by bramkragten** [comment]
The frontend does the same for every climate platform, we will not make it different for KNX, this should be solved in the backend.

When you raise the temperature do you get a toast with: `Service climate/set_temperature called.` ?
