### ISSUE TITLE
0.85 - UI Constantly Refreshes while in edit mode

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/home-assistant-polymer#2441]
This has been happening the last few releases... When you are either in edit mode or raw edit mode the ui will refresh and completely remove any changes you had since you saved it. Your only option is to type quick and save often (every few seconds). This is really annoying.

**Comment by iantrich** [comment]
Need more details. What browser are you running, what version of HA are you currently running, etc?

**Comment by niemyjski** [comment]
I'm running 0.85 and I'm running the latest version of safari on Mac. It's been doing this since Lovelace came out.

**Comment by Mariusthvdb** [comment]
not sure what edit mode is, but I am using Lovelace in Yaml mode, and have noticed this also:
https://community.home-assistant.io/t/lovelace-refreshes-refocusses-page-frequently/87446

**Comment by Mariusthvdb** [comment]
Think I don't have that:

![schermafbeelding 2019-01-11 om 17 31 13](https://user-images.githubusercontent.com/33354141/51046579-ba035800-15c6-11e9-8364-d91628b6d701.jpg)

**Comment by iantrich** [comment]
![image](https://user-images.githubusercontent.com/1287159/51048968-1c8e3100-1592-11e9-9e5d-97f416c2a684.png)

It's now up in your menu bar (I'm guessing, I don't have a mac and am stealing this workaround from another ticket)

**Comment by balloob** [comment]
So this might happen whenever a state changes and thus the `hass` object. If that's the case, we can attempt a repro by opening 2 UIs and in one UI open the editor and make a change, in the other UI toggle a switch

**Comment by iMartien** [comment]
Have the same issue on Safari on MacOS Mojave, Chrome works fine.

Same problem exsist on iOS in safari and the HA iOS App.

**Comment by chrisgott** [comment]
right, happens on safari on a mac (Version 12.0.2 (12606.3.4.1.4)) and on all iOS safari on iphone7/6, ipad5 - even on a older ipad2.

**Comment by hako74** [comment]
The _ServiceWorkers_ option is also available on iOS , it should be here:
Settings --> Safari --> Advanced --> Experimental Features

**Comment by iantrich** [comment]
Are people still having issues after trying the service worker fix?

**Comment by rudders** [comment]
Seemed to be fixed in .87. 
Service worker fix did nothing for me.

**Comment by PrimozFrelih** [comment]
For me not fixed with any update. I have resintalled hassio, access with Win, Ubuntu, Chrome, Firefox. it always keeps reloading randomly. Maybe a little less on ubuntu + Firefox, but still.

**Comment by markdchurchill** [comment]
This happens for me too (0.96.0). It happens in Chrome with the service worker unloaded or not. Nothing specific comes down the websocket to trigger it. It's really frustrating because it basically makes all ingress apps and the developer tools completely useless - as you've got about 15 seconds before they get reset.

The workaround is to copy the ingress iframe uri out and hit that directly, it's the only way I can work with Cloud9 & NodeRed.

**Comment by jorioux** [comment]
I also have this issue on 0.103.5

When I'm configuring a new automation and filling the fields, a new websocket is opened after a few seconds of editing:

wss://<hass_url>/api/websocket

and all the fields resets!

**Comment by jorioux** [comment]
Never mind, I fixed it by adding "timeout tunnel 1h" in my HAPROXY backend section.

**Comment by iantrich** [comment]
Just an FYI; create new issue tickets rather than commenting on closed ones. You can always reference the closed one in the new
