### ISSUE TITLE
Lovelace flash on load (0.84 + 0.85)

### ISSUE THREAD

**Issue by yosilevy** [home-assistant/home-assistant-polymer#2443]
In 0.84 lovelace load would initially show the non lovelace UI and then redirect to lovelace.
In 0.85 this somehow changed (or maybe it didn't) but now it loads and immediately refreshes.
Note: happens in both RTL & LTR so language is irrelevant.

Video:
https://drive.google.com/file/d/1KnU2qygIyNRCThpcgJ1NgY0LP0Ui8oW_/view?usp=sharing

**Comment by bramkragten** [comment]
This is probably because the custom elements you use are not loaded in time, when they are loaded the view is reloaded.

**Comment by yosilevy** [comment]
Nope. Happens also with 0 custom controls. IMHO I also think that even If what you wrote would have been true it's something that should be solved. Flickering UIs are perceived as low quality.

**Comment by bramkragten** [comment]
So you removed all resources from your config?

**Comment by yosilevy** [comment]
You're right. The files themselves are the cause. But this was never the case before 0.84 and never so obvious as in 0.85. As I believe many users use these files I think this should be a priority to fix. Maybe create a dynamic webpack based on a folder?

**Comment by yosilevy** [comment]
Yes. I'll write to him on Discord. It is no good.

**Comment by yosilevy** [comment]
Seems like @thomasloven will be working on a fix to avoid calling rebuild so whoever has this problem should upgrade going forward.

**Comment by thomasloven** [comment]
Turns out this isn't exclusive to card-tools. The flashing will happen if *any* custom element is used.

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/common/create-card-element.ts#L107-L109
