### ISSUE TITLE
UPnP/IGD integration shows blank pop up/dialog with "submit"

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-polymer#2449]
**Home Assistant release with the issue:**

0.85.0
**Last working Home Assistant release (if known):**
n/a

**Browser and Operating System:**

Windows 10 Chrome/FF/Edge
**Description of problem:**

![upnp](https://user-images.githubusercontent.com/2456810/51047494-d632d500-1585-11e9-894e-31b4389744d2.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
That's a translation issue.

**Comment by balloob** [comment]
I'm unable to repro this on backend and frontend both on dev

![image](https://user-images.githubusercontent.com/1444314/51064363-20cb4600-15b4-11e9-969b-c6bc25c6ad24.png)

**Comment by DavidFW1960** [comment]
I get the same as @cogneato and I'm configured for English..
