### ISSUE TITLE
Use static get styles()

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2462]
With Lit Element 2.0.0-rc2, a new `static get styles()` was introduced. It will use performance optimizations for stylesheets when possible. This new method should return an array of CSS stylesheets that are rendered using the imported `css` tag from `lit-element`.

```ts
// Example
import haStyle from "./ha-style.ts";

class Bla extends LitElement {
      static get styles() {
        return [
          css`.header { color: green; }`,
          haStyle,
        ];
      }
}
```

We should migrate our elements to use this.

**Comment by iantrich** [comment]
Do you want to keep this open as a reminder for conversion?

**Comment by balloob** [comment]
Nah
