### ISSUE TITLE
Introduce decorators again

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2463]
With Lit Element 2.0.0-rc2, decorators are compatible with [babel 7](https://github.com/Polymer/lit-element/pull/422).

This means that we should start adding decorators again, as it makes for nicer looking code.

See above linked PR for the babel changes necessary.

Example how decorators will look from [Lit Element guide](https://lit-element.polymer-project.org/guide/properties#declare-properties-with-typescript-decorators):

```ts
import { LitElement, html, customElement, property } from 'lit-element';

@customElement('my-element')
export class MyElement extends LitElement {
  @property({type : String})  prop1 = 'Hello World';
  @property({type : Number})  prop2 = 5;
  @property({type : Boolean}) prop3 = true;
  @property({type : Array})   prop4 = [1,2,3];
  @property({type : Object})  prop5 = { subprop1: 'prop 5 subprop1 value' };

  render() {
    return html`
      <p>prop1: ${this.prop1}</p>
      <p>prop2: ${this.prop2}</p>
      <p>prop3: ${this.prop3}</p>
      <p>prop4[0]:</p>${this.prop4[0]}</p>
      <p>prop5.subprop1: ${this.prop5.subprop1}</p>
    `;
  }
}
customElements.define('my-element', MyElement);
```

**Comment by balloob** [comment]
I just gave this a shot, even just adding babel plugins

```
    ["@babel/plugin-proposal-decorators", {"decoratorsBeforeExport": true}],
    "@babel/plugin-proposal-class-properties",
```

broke Lovelace …

**Comment by iantrich** [comment]
fixed in https://github.com/home-assistant/home-assistant-polymer/pull/2711
