### ISSUE TITLE
Iframe cards in lovelace not stacking correctly

### ISSUE THREAD

**Issue by kloknibor** [home-assistant/home-assistant-polymer#2477]
**Home Assistant release with the issue:**

0.84.6
**Last working Home Assistant release (if known):**
-

**Browser and Operating System:**

Chrome, windows 7

**Description of problem:**

Iframe cards will keep vertically stacking even while the cards don't vertically fit in the screen anymore. When adding even more iframe cards the frontend will start using vertical stacks / columns. So I'm thinking the right height of the iframe card is not passed on to the alignment system. Could this be true? 

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
This is how it shows, the expected behavior on this wide screen would be to make 2 columns with 2 graphs each. Instead of 4 cards vertically positioned. Horizontal stack doesn't help since this will make the cards too small, trying to fit it in 1 column... 

![image](https://user-images.githubusercontent.com/10560390/51140796-c1856400-1847-11e9-8415-9a61d2a5e4f3.png)

**Comment by iantrich** [comment]
I've confirmed this issue. Not sure why yet, however

**Comment by bramkragten** [comment]
getCardSize is called before the card has a height...
