### ISSUE TITLE
Yeelight discovery doesn't appear in integrations

### ISSUE THREAD

**Issue by grea09** [home-assistant/home-assistant-polymer#2491]
**Home Assistant release with the issue:**
0.85.1

**Last working Home Assistant release (if known):**
None

**Browser and Operating System:**
Chromium/ Ubuntu

**Description of problem:**
Yeelight doesn't appear in the integration menu when discovered. It is therefore impossible to change its entity_id from anywhere since it doesn't appear in the configuration files. Would it be possible to add better yeelight integration so that it displays similarly to what have been done on ESPHome ?

**Comment by akinomeroglu** [comment]
@balloob could you kindly control that is this bug related this project or HA's itself?

**Comment by iantrich** [comment]
Are you able to edit it from the new Entity Registry editor introduced in 0.87?

**Comment by akinomeroglu** [comment]
Hello @iantrich,

I can't see led strip in entity registry editor. Using 0.88b0

**Comment by iantrich** [comment]
Still an issue? I would think this would be a backend issue, actually.

**Comment by akinomeroglu** [comment]
@iantrich sorry I missed your question. It is still an issue and device does not show up entity registry.

**Comment by iantrich** [comment]
@bramkragten do you agree that this would be backend? I don't think we differentiate at all, right?

**Comment by bramkragten** [comment]
This is not a bug and definitely not a frontend issue. Yeelight just doesn't have unique IDs and config flow support.
