### ISSUE TITLE
script/develop won't compile or run

### ISSUE THREAD

**Issue by Fusseldieb** [home-assistant/home-assistant-polymer#2494]
On the dev page https://developers.home-assistant.io/docs/en/frontend_development.html it teaches us how to set up a developer environment, but no matter how I try, it fails at the last part.

First thing is that it says to select [the "right" nvm version](https://developers.home-assistant.io/docs/en/frontend_development.html#installing-nodejs). Which one? I don't have a clue. I tried with 10.0.0 and 11.6.0 (latest at time of writing). After that I should run `script/bootstrap`.
Well, this does well and it installs a crapton of packages and stuff, half of them with unmeet-peer-dependencies, but anyways, it finishes without error.

After that it says to build the frontend with `script/develop`, but it's there that it gives a error called ```gulp[12228]: src\node_contextify.cc:631: Assertion `args[1]->IsString()' failed.``` and no matter how many times I try to clean install or change nvm versions, nothing solves it.

If there's any solution to this, I would be very glad. I was about to fix some issues on the HA Frontend, but I now can't, I suppose.

I'm using Windows 10 x64 and the Bash output is below:
```
Valentino@DESKTOP-CAABV6I MINGW64 ~/Desktop/home-assistant-polymer (dev)
$ nvm install 10
10.0.0
Downloading node.js version 10.0.0 (64-bit)...
Complete
Creating C:\Users\Valentino\AppData\Roaming\nvm\temp

Downloading npm version 5.6.0... Complete
Installing npm v5.6.0...

Installation complete. If you want to use this version, type

nvm use 10.0.0

Valentino@DESKTOP-CAABV6I MINGW64 ~/Desktop/home-assistant-polymer (dev)
$ nvm use 10
10.0.0
Now using node v10.0.0 (64-bit)

Valentino@DESKTOP-CAABV6I MINGW64 ~/Desktop/home-assistant-polymer (dev)
$ script/bootstrap
yarn install v1.13.0
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "fecha@^2.3.3". Ignoring it.
warning Resolution field "@webcomponents/webcomponentsjs@2.2.1" is incompatible with requested version "@webcomponent
s/webcomponentsjs@^1.0.7"
warning Resolution field "@webcomponents/webcomponentsjs@2.2.1" is incompatible with requested version "@webcomponent
s/webcomponentsjs@^1.0.7"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-big-calendar@0.19.2" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning " > react-big-calendar@0.19.2" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning "react-big-calendar > react-overlays@0.7.4" has unmet peer dependency "react@^0.14.9 || >=15.3.0".
warning "react-big-calendar > react-overlays@0.7.4" has unmet peer dependency "react-dom@^0.14.9 || >=15.3.0".
warning "react-big-calendar > react-prop-types@0.4.0" has unmet peer dependency "react@>=0.14.0".
warning "react-big-calendar > uncontrollable@4.1.0" has unmet peer dependency "react@>=0.11.0".
warning "react-big-calendar > react-overlays > prop-types-extra@1.1.0" has unmet peer dependency "react@>=0.14.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 112.87s.

Valentino@DESKTOP-CAABV6I MINGW64 ~/Desktop/home-assistant-polymer (dev)
$ script/develop
gulp[12228]: src\node_contextify.cc:631: Assertion `args[1]->IsString()' failed.
 1: node::DecodeWrite
 2: node::DecodeWrite
 3: uv_loop_fork
 4: v8::internal::interpreter::BytecodeDecoder::Decode
 5: v8::internal::RegExpImpl::Exec
 6: v8::internal::RegExpImpl::Exec
 7: v8::internal::RegExpImpl::Exec
 8: 000001E429F04281

Valentino@DESKTOP-CAABV6I MINGW64 ~/Desktop/home-assistant-polymer (dev)
```

**Comment by balloob** [comment]
Our nvmrc is pointing at Node 8.11.1, not 10.

**Comment by iantrich** [comment]
You should run a dev backend on the same machine and point it towards the frontend you are serving up. https://developers.home-assistant.io/docs/en/development_environment.html

**Comment by Fusseldieb** [comment]
> You should run a dev backend on the same machine and point it towards the frontend you are serving up. https://developers.home-assistant.io/docs/en/development_environment.html

Ooh okay, I'll try that tomorrow. 

Thanks to everyone for the useful help. I think I can close this issue now.
