### ISSUE TITLE
lovelace turns white and displays no tab content in safari

### ISSUE THREAD

**Issue by RezzZ** [home-assistant/home-assistant-polymer#2497]
**Home Assistant release with the issue:**
0.85+

**Last working Home Assistant release (if known):**
0.84.6

**Browser and Operating System:**
Safari Version 12.0 (14606.1.36.1.9)
MacOS Mojave

**Description of problem:**
Lovelace stops working when it is open for a x nr of minutes. First the tabs stop showing content and later the blue theme turned to white.
A refresh of the page or switching from dev-tools back to overview solves the problem as well.

![lovelace white bug](https://cdn.pbrd.co/images/HWQU09C.png)

At first it thought it was an issue with custom-ui but even with custom-ui disabled this behaviour still happens.

Chrome seems unaffected.

**Javascript errors shown in the web inspector (if applicable):**
none

**Additional information:**

**Comment by fillwe** [comment]
Been getting this as well

**Comment by RezzZ** [comment]
perhaps it was a caching issue because I haven't seen these white screens for a while now. What about you @fillwe?

**Comment by RezzZ** [comment]
has this been fixed in 0.86.1? @balloob

**Comment by balloob** [comment]
oops, didn't see your last sense. Thought you couldn't repro

**Comment by balloob** [comment]
@thomasloven found an issue with hui-generic-row and I just opened PR #2636 to attempt to fix it.

**Comment by balloob** [comment]
Also, hi @NovapaX 👋 , long time no see !

**Comment by iantrich** [comment]
Did 0.87 memory leak fixes resolve this for people?

**Comment by fillwe** [comment]
Yeah I haven't had this issue since 0.87

**Comment by RezzZ** [comment]
i'll start testing as well

**Comment by RezzZ** [comment]
no issues on my side. Hurray!
