### ISSUE TITLE
Lovelace Entity Button card - entity_picture (customize) not displayed

### ISSUE THREAD

**Issue by raffertyp1** [home-assistant/home-assistant-polymer#2500]
**Home Assistant release with the issue:**
0.85.1

**Last working Home Assistant release (if known):**
Unknown

**Browser and Operating System:**
OSX - Chrome & Firefox; iOS - Safari

**Description of problem:**
The Entity Button card does not display the 'entity_picture' defined in customizations. The default icon is displayed, even if no icon is defined in ui-lovelace.yaml while an entity_picture is defined. 

The Entity Button documentation seems to indicate that defining an icon in lovelace would overwrite the entity_picture (and therefore not defining an icon would allow the entity_picture to be displayed):

> Icon - (string)(Optional)Overwrites icon or entity picture.

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
N/A

**Comment by iantrich** [comment]
entity-button does not support entity_picture. You can override the icon in your lovelace configuration.
