### ISSUE TITLE
Lovelace: show_header_toggle doesn't apply for binary sensors

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-polymer#2507]
**Home Assistant release with the issue:** 0.85.1
**Last working Home Assistant release (if known):** didn't notice

**Browser and Operating System:** latest Chrome / Windows 10

**Description of problem:** 
Lovelace shows Header toggles even when the group only has non toggleables - like binary_sensors

**Javascript errors shown in the web inspector (if applicable):** no JS error
**Additional information:**
Thread on forums: [here](https://community.home-assistant.io/t/lovelace-shows-header-toggle-with-non-toggleable-entities/)

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/6/1/612055438c2cdbc5b35d0972b2d0621b37d45974.jpeg)

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/8/a/8a37b954c8f66d5b816141860e2870e4764bfcc7.jpeg)

**Comment by iantrich** [comment]
The default is true, [regardless of types](https://www.home-assistant.io/lovelace/entities/#show_header_toggle)

Set it to false to hide it

**Comment by andriej** [comment]
I've checked that in docs and of course it's set!
```yaml      - id: 1ac51e99e0a14c8bab71bfe07f718d02  # Automatically created id
        type: entity-filter
        show_empty: false
        **show_header_toggle: false**
        entities:
          - binary_sensor.door_window_sensor_158d0001exxxxx
          - binary_sensor.door_window_sensor_158d0001dxxxxx
          - binary_sensor.door_window_sensor_158d0001bxxxxx
          - binary_sensor.door_window_sensor_158d0001exxxxx
          - binary_sensor.door_window_sensor_158d0001exxxxx
          - binary_sensor.door_window_sensor_158d0001exxxxx
          - binary_sensor.door_window_sensor_158d0001dxxxxx
          - sensor.template_taras_stan
        state_filter:
          - "on"
          - "otwarte"
          - "uchylone"
        card:
          title: Otwarte okna`

**Comment by andriej** [comment]
@iantrich can you please reopen?

**Comment by iantrich** [comment]
@andriej are you saying you havr it set to false and it still shows?

**Comment by andriej** [comment]
Yes. I've pasted code above (without "-id: <auto generated number>" which is missing).

**Comment by iantrich** [comment]
HA version?

**Comment by andriej** [comment]
Latest.
![image](https://user-images.githubusercontent.com/6303489/52914109-a386a580-32c4-11e9-9275-9ac3ee42c340.png)

**Comment by andriej** [comment]
Ok, the 'show_header_toggle' should be under 'card' not where I have it in code.
