### ISSUE TITLE
Zigbee Management Panel Missing Help Text For Reconfigure Node

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#2565]
**Home Assistant release with the issue:**

0.86.2
**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

Win 10 Chrome and Android Chrome
**Description of problem:**

1. Login to HA
2. Configuration -> ZHA
3. Select any node
4. Select help icon under second section

When I navigate to the ZHA Zigbee Management Panel and click on the help text icon I do not see any help text for Reconfigure Node.  I only see help text for Remove Node.  I am not sure what Reconfigure Node does and don't see anything in the docs.  When compared to the Z-wave panel all buttons have a proper description so I feel this is missing.

![image](https://user-images.githubusercontent.com/1634145/51774795-66097080-20a8-11e9-92a1-c57fb213ae45.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by dmulcahey** [comment]
I'll try to get a PR up for this tomorrow. It is similar to heal node in zwave. It will rebind clusters and set reporting up again
