### ISSUE TITLE
Microsoft Edge not working with Lovelace UI

### ISSUE THREAD

**Issue by Cloudenius** [home-assistant/home-assistant-polymer#2566]
**Home Assistant release with the issue:**

0.86.2 & 0.86.1

**Last working Home Assistant release (if known):**

Not sure as I was using States UI before.

**Browser and Operating System:**

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows 10 1809 (OS Build 17763.253

**Description of problem:**

The Lovelace UI doesn't seem to work in Microsoft Edge. The screen is just stuck at the moving donut. See the following screenshot (resized the window to keep the screenshot small):

![image](https://user-images.githubusercontent.com/14926452/51786104-0e2e4080-2160-11e9-8af0-e388243b2e32.png)

And a screenshot of the UI in https://demo.home-assistant.io/

![image](https://user-images.githubusercontent.com/14926452/51786109-2605c480-2160-11e9-8879-c655091966b2.png)

**Javascript errors shown in the web inspector (if applicable):**

Error Message in Console - let me know if I can get other logs:
```
CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization
```

**Additional information:**

I'm using the States UI for now but would love to migrate to Lovelace. If this is something related to the EdgeHTML engine, Microsoft will soon replace it for the Chromium engine: https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/

**Comment by iantrich** [comment]
closing as edge has been replaced
