### ISSUE TITLE
UI Frontend did not convert Upgrading to 0.86.2

### ISSUE THREAD

**Issue by blacksheepone** [home-assistant/home-assistant-polymer#2567]
**Home Assistant release with the issue:**
Home Assistant 0.86.2

**Last working Home Assistant release (if known):**
Home Assistant 0.85.1

**Browser and Operating System:**

**Description of problem:**
Had everything laid out in precious version and had no errors.
I even created a ui-lovelace.yaml file when using the lovelace UI was an option from the Home Assistant Info screen and adjusted it to where it displayed properly without an issue.

Last  night I backed performed a full backup (snapshot) then performed the updated to 0.86.2.

I cleared cache on browser and  all of my sensors and readings are being diaplayed on the home page, instead of split up into tabs like I had it.  Also the sensors and readings are all being displayed with the default icons, see screen print.  Also, there is a lot of sensors and readings that are missing completely.

What are the steps to resolve this and can I go back to the previous version?  As I put a lot of work into the initial design and don't wish to spend additional time to re-do it again.

Thank You.

P.S.  Checkered portion of screen is where the video camera snapshot appeared that I removed.

![image](https://user-images.githubusercontent.com/47060833/51789783-a9241c00-215a-11e9-8314-1ccc6715a30b.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by blacksheepone** [comment]
Also seeing this notification message:
![image](https://user-images.githubusercontent.com/47060833/51789850-6151c480-215b-11e9-947b-591ad81e0d43.png)

**Comment by blacksheepone** [comment]
Closed by mistake.

**Comment by balloob** [comment]
If you're using ui-lovelace.yaml, you need to put Lovelace in YAML mode as per the docs: https://www.home-assistant.io/lovelace/yaml-mode/

Have a look at the breaking changes for the things that could not get set up: https://www.home-assistant.io/blog/2019/01/23/release-86/#noteworthy-breaking-changes
