### ISSUE TITLE
Lovelace Not Loading Conditional Custom Cards

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#2571]
**Home Assistant release with the issue:**
0.86.2

**Last working Home Assistant release (if known):**
0.85.x (I 'think')

**Browser and Operating System:**
All (Windows/Mac, Chrome/Opera)

**Description of problem:**
A bit of a strange behaviour, but I can definitely reproduce it now. I also found another mention of the same thing on the forum, so figured I'd raise it here.

I have a Lovelace view set up such that it has a bit of a menu system. Effectively two vertical stacks. The left stack is a bit of a menu system, the right stack is a collection of conditional cards which display (or not) based on what is selected on the left.

This has been working well, but recently I've found that for custom cards (tiles and a few animated weather ones), are not being loaded with the page. What happens is whatever conditional card is showing when the page is first loaded (with a cleared cache), displays just fine. But if I change something with my menu system and display a different card, the custom elements for that card don't display (NOTE: the non-custom elements, i.e. entities, display fine). Once I give the page a normal refresh (not clearing the cache), it loads everything, and I can happily switch to any conditional card and it'll be loaded.

**Javascript errors shown in the web inspector (if applicable):**
```
None
```

**Additional information:**
While I can reload the page, it's annoying for a tablet I use this on.

**Comment by balloob** [comment]
what framework does the custom cards use?

**Comment by mynameisdaniel32** [comment]
Unsure what you mean by framework sorry, two of the cards where this occurs are:
https://github.com/rodrigofragadf/lovelace-cards/tree/master/tiles-card
https://github.com/iammexx/home-assistant-config/tree/master/ui/darksky

**Comment by mvereecken** [comment]
I experience the same behaviour. I try to use it with the current version 0.88.2, I don't know if it ever worked before.
I have a vertical stack of 3 cards. Every card is shown in a certain condition. When the state changes on a card, another card should be shown, depending on the condition. The current card disappears, while the other card (that meets the condition) is not shown instead. There's a custom card ('custom:card-modder') inside every conditional card.
If I refresh the screen, the right card is displayed.

**Comment by PiotrMachowski** [comment]
Issue still exists in 0.92.0. Card is not visible in UI, additionally in HTML there is an error reported:
```
<hui-conditional-card style="">
  <hui-error-card style="display: none;">
  (...)
    "Custom element doesn't exist: weather-card."
  (...)
  </hui-error-card>
</hui-conditional-card>
```

**Comment by mynameisdaniel32** [comment]
Still an issue in 0.93.0b2, although seems to be most prevalent on some Android devices running Fully Kiosk Browser (slower reloading than my desktop browsers) where it happens 9/10 reloads.

Playing around with this a bit further, it looks like this is an issue in how the webpage is rendered after a refresh. I moved away from the standard conditional cards to instead use @thomasloven's [state-switch](https://github.com/thomasloven/lovelace-state-switch) and the same behaviour with intermittent loading of other custom components is present. If I do a page resize (or rotate device to portrait and back) then everything displays perfectly. I'm using a few different components, beyond those mentioned earlier and it appears to affect all of them.

I'm also seeing similar behaviour after a refresh using the custom card [vertical-stack-in-card](https://github.com/custom-cards/vertical-stack-in-card) with custom components within it. Again, a resize fixes it. Perhaps an issue with custom cards being used beyond a certain 'level'?

**Comment by balloob** [comment]
This is most likely due to a race condition in your custom cards and errors are probably logged in the browser console.

**Comment by mynameisdaniel32** [comment]
Looks like this has already been identified and tackled by another custom component so I'm closing this one off. While I don't like the idea of using a custom component to fix this, it works as advertised.

https://github.com/thomasloven/lovelace-card-loader

**Comment by balloob** [comment]
As per the documentation of that custom card, it works around code in custom cards that's not implemented correctly. I don't like the idea either but it is also not our code that is at fault.
