### ISSUE TITLE
Allow opening more info in Thermostat card

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2581]
Add a triple dot button in top right of the card that opens the more info dialog for the thermostat.

**Comment by iantrich** [comment]
![6d3a5cf3-8909-416a-9a49-2428d57ad9cc](https://user-images.githubusercontent.com/1287159/51804661-8e6ca880-2229-11e9-83be-371dcab685a5.jpeg)

Are we going for this design?

**Comment by balloob** [comment]
not really, I expect the dots to be vertical, like we have on the media player card

**Comment by iantrich** [comment]
I think we should do the same for the light card, the long press for more-info is easily missed

**Comment by iantrich** [comment]
@bramkragten I like the dots more as then lights card could be the same and others as we build them out; cover, switch, etc.

**Comment by balloob** [comment]
We should prioritize consistence across cards above what works best for a single card.
