### ISSUE TITLE
add a 'resources' editor

### ISSUE THREAD

**Issue by iantrich** [home-assistant/home-assistant-polymer#2592]
this can of course be done in the raw editor, but I think having a dedicated editor will avoid some confusion people are having with custom card usage in storage mode

**Comment by bramkragten** [comment]
I believe @balloob wanted this to remain a 'pro' function and not have a UI for it...

**Comment by iantrich** [comment]
Then I'm going to have explain this to people over and over again. Having it costs us nothing

**Comment by bramkragten** [comment]
I think we could have a UI for it, with a big warning message that you should not just add anything because it can harm your system...
