### ISSUE TITLE
Automation UI no save button when using LTR e.g. hebrew

### ISSUE THREAD

**Issue by rafiw** [home-assistant/home-assistant-polymer#2596]
**Home Assistant release with the issue:**
- Frontend -> Developer tools -> Info
0.86.2

**Last working Home Assistant release (if known):**
0.85

**Browser and Operating System:**
using windows 10
chrome 71 doesn't work (worked in 0.85)
works in firefox but it loads the LTR website so i guess that why it works

**Description of problem:**
No save button when editing\adding automation using the UI

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
when changing the bottom px from 16 to 96 i saw the save button
![image](https://user-images.githubusercontent.com/3034707/51807597-6dd83900-2291-11e9-96f6-8c21aaf68d94.png)

**Comment by iantrich** [comment]
I believe this now works
