### ISSUE TITLE
0.86.3 - Lovelace main tab not updating states

### ISSUE THREAD

**Issue by jjgadget** [home-assistant/home-assistant-polymer#2604]
**Home Assistant release with the issue:**
Started with 0.86.0 and still present on 0.86.3

**Last working Home Assistant release (if known):**
0.85.0

**Browser and Operating System:**
OSX - Safari and Chrome browsers for web interface
Docker install for HA

**Description of problem:**
Main Lovelace tab does not update states while other tabs do. Clicking on entity on main tab to view more info will display true info/state. See battery status below for example.

Main Lovelace tab:
![capture1-1](https://user-images.githubusercontent.com/27093132/51810346-1b305a00-225c-11e9-91ac-edb53276214f.png)
![capture1-2](https://user-images.githubusercontent.com/27093132/51810352-271c1c00-225c-11e9-97d7-dcdefdf8360c.png)

Second Lovelace tab:
![capture2](https://user-images.githubusercontent.com/27093132/51810355-2c796680-225c-11e9-8e39-89dc49843a35.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
New log from fresh reboot:

2019-01-27 17:33:44 WARNING (MainThread) [homeassistant.loader] You are using a custom component for switch.hadockermon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-01-27 17:33:52 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for camera.camera_backyard (<class 'homeassistant.components.camera.arlo.ArloCam'>) took 3.701 seconds. Please report platform to the developers at https://goo.gl/Nvioub

**Comment by quammy** [comment]
I have the same issue, only that my log has no errors.
Here is a forum post reporting the same issue with more examples: [https://community.home-assistant.io/t/lovelace-doesnt-always-reflect-correctly-states/97197/14](url)

**Comment by jjgadget** [comment]
> I have the same issue, only that my log has no errors.
> Here is a forum post reporting the same issue with more examples: [https://community.home-assistant.io/t/lovelace-doesnt-always-reflect-correctly-states/97197/14](url)

Do you use a map card? I removed it then the all the info on the tab started to work again.

**Comment by HudsonMC16** [comment]
I have this same issue. I'm getting errors in the javascript console, but they're all related to the embded windy.com iframe. issue still persists after removing this card. 

To reproduce the issue, you may select a different tab from the "three line" menu (logbook, configuration, etc.) and then select overview again. Things stop updating at that point.

**Comment by iantrich** [comment]
still an issue?

**Comment by jjgadget** [comment]
No longer an issue for me.
