### ISSUE TITLE
History datetime labels are too long

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-polymer#261]
This was a recent change it seems. Previously I believe it only showed `03:00 PM`. Now it shows `Sat, Apr 15, 2017 03:00`. When I hover over the labels it shows a tooltip with the full text.

@balloob suggested we haven't made any recent changes, Google must have.

<img width="353" alt="screen shot 2017-04-16 at 3 20 56 pm" src="https://cloud.githubusercontent.com/assets/18516/25074782/0fed3716-22b9-11e7-9219-7ed454964b19.png">

**Comment by andrey-git** [comment]
Some time ago when I added support for 3 & 7 days graphs in history panel, I changed the format for *multiday* graphs. I'll check why it started to apply to single-day
