### ISSUE TITLE
Lovelace interface gets stuck after several minutes in Fully Kiosk Browser

### ISSUE THREAD

**Issue by hanzoh** [home-assistant/home-assistant-polymer#2619]
**Home Assistant release with the issue:**

0.86.3
**Last working Home Assistant release (if known):**
0.85.4

**Browser and Operating System:**

Fully Kiosk Browser, WebView 71.0, Android 9.0
**Description of problem:**

The lovelace interface renders fine and is responsive after initial load. But after some minutes, the interface is stuck (entities do not update, view cannot be scrolled anymore). Swiping from left to right to get to Fully's menu is also very slow and can take some seconds to appear. Reloading the home page via Fully's menu fixes the problem then until it reappears.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
No custom components, just stock lovelace cards.

**Comment by balloob** [comment]
Will you be able to share your config? Any cameras, iframes? 

Does it fail on Chrome too?

**Comment by hanzoh** [comment]
I downgraded to Android 8.1 (and updated Chrome / WebView to 72) and that solved it.
So I assume that was a Fully problem with Android Pie.
