### ISSUE TITLE
Add native language alignment

### ISSUE THREAD

**Issue by sonic4002** [home-assistant/home-assistant-polymer#262]
Hi, 
my native home language is not english
therefor i would like to align the entire system to the right

is it possible to do it?
if yes, how?
if not, can you add this option?

**Comment by justweb1** [comment]
This is possible. You can look into implementing it and contributing back to the project. This is where I would start. https://www.polymer-project.org/1.0/toolbox/localize

**Comment by justweb1** [comment]
It also looks like this has been started. Take a look at https://github.com/home-assistant/home-assistant-polymer/pull/227

**Comment by zsarnett** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/1966

There was an attempt for this here. There is still progress being made to fix the issue that broke then it will be merged again

**Comment by zsarnett** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/2014

This can now be done. A PR for the language that would need Right Aligned is needed thought
