### ISSUE TITLE
Feature Request: Sub navigations for Lovelace

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [home-assistant/home-assistant-polymer#2632]
**Home Assistant release with the issue:**

All releases

**Description of problem:**

It would be great if you could add a subnavigation menu to lovelace, so it's much easier to seperate the views. 

Do you think this is possible?

**Comment by iantrich** [comment]
Can you elaborate on this?

**Comment by lichtamberg** [comment]
I mean a subnavigation for the views, which mans that there is not only one visible navigation (if subnavigation is defined), but 2 - one for the main navigation points and one subnavigation, which has the corresponding navigation points for the clicked main navigation point.

See this mockup:

![bildschirmfoto 2019-01-30 um 14 22 24](https://user-images.githubusercontent.com/10075/51984793-794b8000-249c-11e9-951b-38dd936a216c.png)
