### ISSUE TITLE
Nest Thermostat Eco mode shows 'null' in Lovelace Temperature Card

### ISSUE THREAD

**Issue by Curtisjk** [home-assistant/home-assistant-polymer#2647]
**Home Assistant release with the issue:**
0.86.4

**Last working Home Assistant release (if known):**
Unknown - 0.86 is when I started to use Lovelace 

**Browser and Operating System:**

macOS 10.14.3, Safari 12.0.3

**Description of problem:**
When the Nest Thermostat is in the Away/Eco mode the Lovelace temperature card shows the temperature as null. It seems like this is being taken from the entity's `temperature` attribute which is set to null - perhaps a null check should be added and the value is not displayed in this scenario?

![Imgur](https://imgur.com/PeJ0i7S.png)
![Imgur](https://i.imgur.com/bB0vDGi.png)

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
N/A

**Comment by technofreak74** [comment]
I'm developing a new climate component and I am also seeing this issue. It functions as expected in the states UI, I think because it explicitly checks to see if it is undefined before using it (as you suggest).

My hardware doesn't have a concept of a target temperature when it is off so I report null for that value. I'm not sure if this is a problem with lovelace or the backend components behaving in a way they shouldn't but it looks like a regression to me..

**Comment by iantrich** [comment]
I think this line [283](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-thermostat-card.ts#L283) needs to be changed to fallback to current_temperature if temperature does not exist
OR
line [290](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-thermostat-card.ts#L290) should give an empty string if a null value.

What do you think is preferable?

**Comment by technofreak74** [comment]
Just having an empty string would work for me. The current temperature is already displayed prominently so I'm not sure it makes sense to display it twice? I don't know what the lovelace policy is though..

**Comment by Curtisjk** [comment]
I agree. The main temperature value already defaults to the current temperature so there would be no need to display it again.

**Comment by balloob** [comment]
Why would ecobee have `null` as temperature? Does it eco/away mode not have a target temperature?

**Comment by MartinHjelmare** [comment]
Some operation modes don't have a target temperature so reports `None` for those cases. It could be due to using high and low target temperatures, it could be due to device being off, etc.
