### ISSUE TITLE
RTL issues in demo

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2651]
Created an issue to act as catch all for RTL issues. Found most of them by going to the demo and setting language to hebrew (it's the right aligned one in the language dropdown under profile)

- [ ] Lovelace thermostat card
![image](https://user-images.githubusercontent.com/1444314/52159152-249f3500-2655-11e9-91f8-5e74a97f89ff.png)

- [ ] state card input select & state card input number have a padding-left instead of padding right
![image](https://user-images.githubusercontent.com/1444314/52159170-4e585c00-2655-11e9-8e62-a2d48072ebc7.png)

- [ ] Lovelace alarm panel card
![image](https://user-images.githubusercontent.com/1444314/52159181-662fe000-2655-11e9-8684-5946e8d2851a.png)

- [ ] Media player card, icons point wrong direction
![image](https://user-images.githubusercontent.com/1444314/52159187-721ba200-2655-11e9-8f1e-1a23785ce529.png)

- [ ] ha demo card, icons point wrong direction, text should be translated.
![image](https://user-images.githubusercontent.com/1444314/52159190-7ba50a00-2655-11e9-8abb-c62e10b8eb92.png)

- [ ] gauge card
![image](https://user-images.githubusercontent.com/1444314/52159208-b313b680-2655-11e9-87eb-e414454a84f7.png)

**Comment by planecore** [comment]
There are still issues in layout:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/12946462/63773920-d6010300-c8e4-11e9-8072-5ad0a01d2271.png">
