### ISSUE TITLE
Alarm Panel width impacts column count

### ISSUE THREAD

**Issue by raccettura** [home-assistant/home-assistant-polymer#2679]
**Home Assistant release with the issue:**

0.86
**Last working Home Assistant release (if known):**
0.85

**Browser and Operating System:**

Chrome

**Description of problem:**

Alarm panel seems to result in a change in column behavior.  Prior this UI would result in 3 columns, now it results in two columns.  All other combinations of panels I can find seem to have 3 columns.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
![screen shot 2019-02-04 at 10 02 25 pm](https://user-images.githubusercontent.com/126830/52251063-f3c73600-28c8-11e9-9abd-9a04ccb023c0.png)

**Comment by raccettura** [comment]
01/10/2019
--

**Comment by balloob** [comment]
Alarm card has a size of 4 and Home Assistant will fill up a column until it has at least 5. Judging from your screenshot, I would say that we should change it to 3 or 8, depending on if the keypad is shown.

**Comment by raccettura** [comment]
That would make sense.  My primary use case is a tablet... so this is needless scrolling (and terrible screen usage) in this situation.  With 3 columns this becomes very usable.

**Comment by raccettura** [comment]
Digging a little deeper found a maybe related issue... at one point I used this custom implementation of the alarm card and noticed it was doing the same thing:
https://github.com/ciotlosm/custom-lovelace/tree/master/alarm_control_panel-card

Throwing some debug in, I found it wasn't even calling `getCardSize` resulting in similar behavior here and in another custom card which I never noticed.
