### ISSUE TITLE
Cannot use certain MDI icons as view icons

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#2684]
**Home Assistant release with the issue:**
0.86.1

**Last working Home Assistant release (if known):**
n/a

**Browser and Operating System:**
Google Chrome 65.0.3325.162 / OS X 10.11.6
Google Chrome 72.0.3626.76/Android 7.0

**Description of problem:**
When I define a group with view: true and icon: mdi:shield-home (or mdi:shield-home-outline,  mdi:shield-lock), it doesn't show any icon.
Can see no error messages in the log.
Another icons (i.e mdi:shield-key, mdi:shield ) show up as expected.
It might have something to do with a [custom alarm](https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386) I have installed in my HA as it uses a similar icon, but I can see no reason why I cannot use it on a separate page.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
We are currently using [mdi 3.0.39](https://cdn.materialdesignicons.com/3.0.39/) which does no include sheild-home. Looks like shield-home was introduced in [mdi 3.2.89](https://cdn.materialdesignicons.com/3.2.89/)

https://github.com/home-assistant/home-assistant-polymer/blob/dev/package.json#L20

**Comment by akasma74** [comment]
Well, there is no mention of the current MDI version in [the documentation](https://www.home-assistant.io/docs/configuration/customizing-devices/) - should it be amended then?

**Comment by iantrich** [comment]
Yeah. That cheatsheet link should probably be updated

**Comment by akasma74** [comment]
Please do that as it would have saved me an hour :\

**Comment by iantrich** [comment]
We’re a community, anyone can submit a PR to change it ;)

**Comment by akasma74** [comment]
believe it or not, I haven't submitted any yet - how can I do that? ;)

**Comment by iantrich** [comment]
![image](https://user-images.githubusercontent.com/1287159/52294178-32e39e80-293e-11e9-9bfa-9932cf1415bf.png)
