### ISSUE TITLE
Alarm Panel - Arm Custom Bypass button shows blank

### ISSUE THREAD

**Issue by woothok** [home-assistant/home-assistant-polymer#2702]
![ffd01822-1efd-4a61-9190-b5edcba2f7b8](https://user-images.githubusercontent.com/39659400/52460242-39c90780-2b1e-11e9-9ec8-d894f9bdfd21.png)

**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
There's a typo in the editor. Toggle the yaml editor and change `arm_custom_bypass` to `armed_custom_bypass`. Will submit a PR to resolve

**Comment by woothok** [comment]
Thanks.   FWIW, the workaround is not functional for me, although it does add text to the button.   However, it tires to call service "armed_custom_bypass" rather than arm...

**Comment by woothok** [comment]
So I don’t think the issue is with the editor per se.    happy to help test fixes....

**Comment by iantrich** [comment]
@woothok I'll check it out

**Comment by iantrich** [comment]
@woothok I went the wrong way with my fix. The problem was the translation, actually. Thanks for catching that.

**Comment by woothok** [comment]
Ah - makes sense!    The good news is that the re-fix should the the correct one.   Thank you!
