### ISSUE TITLE
Lovelace overview displays states

### ISSUE THREAD

**Issue by bmf7777** [home-assistant/home-assistant-polymer#2707]
**Home Assistant release with the issue:**

0.87.0
**Last working Home Assistant release (if known):**
0.86.4 venv on intel skull canyon nuc running ubuntu 18.04

**Browser and Operating System:**

Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOS 10.14.2

**Description of problem:**

prior to 0.86.4 pressing the overview button would display http://192.168.1.xxx:8123/lovelace/home after upgrading to 0.87.0 pressing overview displays http://192.168.1.xxx:8123/states showing a huge list of all entities rather than my lovelace web page

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Clear your browser cache

**Comment by iantrich** [comment]
Closing as no response
