### ISSUE TITLE
Focus not being set to editor

### ISSUE THREAD

**Issue by yosilevy** [home-assistant/home-assistant-polymer#2710]
**Home Assistant release with the issue:**
0.87.0

**Last working Home Assistant release (if known):**
0.86 (not sure)

**Browser and Operating System:**

Chrome on Windows

**Description of problem:**

Opening lovelace editor, focus is not set to the editor and using the arrows scrolls the background document and you can't edit the code until you click the code box.

**Comment by balloob** [comment]
You want to fix it? 👍  Just implement `firstUpdated()`

**Comment by yosilevy** [comment]
firstUpdated is fired even before the yamlEditor has been created so that's too early

**Comment by yosilevy** [comment]
Need @bramkragten to take a look. The only way I found is to add another line to focus after timeout in hui-edit-card.ts -> `_loadedDialog`

Since you were forced to add the code refresh I guess it has similar root cause:

`      setTimeout(() => {  
        this.yamlEditor.codemirror.focus();  
      }, 500);  
    }  
  }`

**Comment by yosilevy** [comment]
@bramkragten any idea? Should I add the focus after timeout?

**Comment by bramkragten** [comment]
Is this still happening in the beta? Not seeing it here...

**Comment by yosilevy** [comment]
Where are you looking. Try a lovelace editor that defaults to code view.

**Comment by bramkragten** [comment]
Yeah I am... https://demo.home-assistant.io I edit the floorplan and get a focused editor:
![image](https://user-images.githubusercontent.com/5662298/53012671-f044ba80-3443-11e9-8ba3-b6da45985325.png)

**Comment by yosilevy** [comment]
Don't see the caret in your screenshot... :-)

I did same and I see the problem. I'm on latest chrome:
Version 72.0.3626.109 (Official Build) (64-bit)

Sending you a video on Discord.

**Comment by bramkragten** [comment]
You can see the right side is blue, meaning it is has focus :-)

**Comment by yosilevy** [comment]
Fixed in dev. Will be in the next release probably. This can be closed.
