### ISSUE TITLE
mdi:motion-sensor missing

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2719]
**Home Assistant release with the issue:**

0.87.1

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**

Chrome 72.0.3626.96 on macOS 10.13.6 (17G4015)

**Description of problem:**

The icon for ```mdi:motion-sensor``` is missing in Home Assistant and does not display. 

I first noticed this a few weeks ago but assumed it would be added next time icon pack was updated in HA, which happened in 0.87, but this one is still missing.

**Comment by iantrich** [comment]
This is not a bug. See MDI list: https://cdn.materialdesignicons.com/3.0.39/
