### ISSUE TITLE
CodeMirror Height does not scale to card height

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-polymer#2723]
**Home Assistant release with the issue:**
0.87.1

**Browser and Operating System:**
Chrome
Ubuntu 18.10 Linux

**Description of problem:**

The `.CodeMirror` class seems to always be 300px even though it should be set to `100%` 

**Additional information:**

![image](https://user-images.githubusercontent.com/28114703/52586825-65a30080-2e30-11e9-8589-807ee4160c18.png)

![image](https://user-images.githubusercontent.com/28114703/52586976-c6323d80-2e30-11e9-82b4-87a24de4172b.png)

**Comment by iantrich** [comment]
I agree
