### ISSUE TITLE
Thermostat: Card not applying themes

### ISSUE THREAD

**Issue by LukasQ** [home-assistant/home-assistant-polymer#2756]
Hi there

My Setup includes a Generic Thermostat, build around MQTT and some fronend themes.
Unfortunately the style of the Thermostat Card in Lovelace is not applied.

If I add the "theme:" property, nothing changes.
ha: latest
Platform: Ubuntu 18.04 native in VM

See:
![image](https://user-images.githubusercontent.com/5947912/52843783-5ad3be80-3103-11e9-9d3a-7efd9fc7a74f.png)
"Accent Color" (orange) is applied, but configured as red. If I switch to "default", the default theme works (blue)
Chrome: latest

Could it be that we mix up different properties per card?

Cheers, Lukas

**Comment by LukasQ** [comment]
Okay, next issue: one draws a circle instead of a line. Issues with transparent cards.
![image](https://user-images.githubusercontent.com/5947912/52947021-d8066a00-3375-11e9-968e-f2583ca9d18b.png)

**Comment by mkono87** [comment]
The pie chart is what I get with a custom theme. Will this ever be resolved?

**Comment by iantrich** [comment]
This should be resolved once we remove the jQuery

cc: @thomasloven

**Comment by thomasloven** [comment]
I thought I all but told you to do it?
But yes, the new round-slider will fix this.

**Comment by iantrich** [comment]
Was looking for confirmation

**Comment by mkono87** [comment]
This should be ready for next release?

**Comment by iantrich** [comment]
Not 0.100

**Comment by mkono87** [comment]
okay thanks
