### ISSUE TITLE
0.88.0b1 - picture-entity with entitiy camera

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#2760]
**Last working Home Assistant release (if known):**
0.87.1

**Browser and Operating System:**
FF and Chrome und ubuntu

**Description of problem:**
picture-entity with entitiy camera (generic, still_image_url) refreshes every few seconds and shows the 'picture not found' background.

https://streamable.com/jt7hv

**Comment by arsaboo** [comment]
Yeh can confirm...seeing the same.
