### ISSUE TITLE
Custom-element-es5-adapter.js - Const declaration is not supported

### ISSUE THREAD

**Issue by MatteGary** [home-assistant/home-assistant-polymer#2765]
**Home Assistant release with the issue:** 0.87.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:** Safari on iOs 9.3.5

**Description of problem:**

When running Lovelace on iPad Mini 1st Gen with iOs 9.3.5 on Safari, Custom component aren't shown and errors are logged. Looks like the transpile funtionality is not working properly, since on iOs 9.3.5 Safari use a browser with es5 functionality.
Among other errors logged, one is referred to a core file (not a custom one)

**Javascript errors shown in the web inspector (if applicable):**
```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
(anonymous function) — custom-elements-es5-adapter.js:13 
```

I don't know how the transpile engine should work in HA, but it looks like one of the es5 compatible file (it uses 'strict' at the beginning of the file) have an incompatible feature (const).

**Comment by balloob** [comment]
This is on purpose . The custom elements es5 adapter is only for newer browsers that do support custom elements but are served the old frontend. On older browsers it just fails and that's fine.

**Comment by MatteGary** [comment]
I don't get the point in doing that.

Why someone would use es5 compatibility mode in an es6 capable browser?

Basically you are providing es6 custom element to a browser that asks for es5 mode, but not providing custom element to an es5 browser.

I think it would be a good improvement to let custom element work in es5 mode: of course you cannot do that for all the custom element around, but at least let it be possible. Then custom element's developer will decide whether develop their custom element with es5 functionality, or release 2 versions (es6 and es5).
