### ISSUE TITLE
Username says 'user' instead of name

### ISSUE THREAD

**Issue by GrandadEvans** [home-assistant/home-assistant-polymer#2783]
**Home Assistant release with the issue:**

v0.88.0b2

**Last working Home Assistant release (if known):**
v0.87.x

**Browser and Operating System:**

Arch Linux -> Google Chrome -> Version 71.0.3578.80 (Official Build) (64-bit)
Arch Linux -> Firefox Quantum -> v65.0
Android 7.1.1 -> Firefox -> 65.0.1

**Description of problem:**

In the Home assistant sidebar, which holds all the links such as map; history etc. The username in the circle simply 'user' and not my name.
For myself, the name area normally says 'John'.
My name is displayed correctly in the user area page (reached by clicking on the 'user' circle.
![image](https://user-images.githubusercontent.com/896346/52942865-c74cf880-3363-11e9-8635-a54d6eadedff.png)

**Javascript errors shown in the web inspector (if applicable):**
```
I cannot see any errors in the console, that refer to this. I have errors saying that the system cannot find the custom-compact-header.js file, but I was having these in the last version as well (where the name displayed properly)
```

**Additional information:**

**Comment by VDRainer** [comment]
Already fixed https://github.com/home-assistant/home-assistant-polymer/pull/2777
