### ISSUE TITLE
Change user language selection won't auto change Lovelace UI resource

### ISSUE THREAD

**Issue by awarecan** [home-assistant/home-assistant-polymer#2795]
**Home Assistant release with the issue:**

Current dev (0.88 beta)
**Last working Home Assistant release (if known):**
Unknown

**Browser and Operating System:**

**Description of problem:**

Steps
1. Login -> Profile
2. Change the language, notice that profile page resource changed to selected language
3. Navigate to Config page, the "classic" panel immediately changed to selected language
4. Navigate to Overview (Lovelace UI), notice that only the resource localized in backend got changed, all frontend resource string kept in previous language
5. F5 refresh browser page, notice that whole UI changed to selected language

As an user, I expected Lovelace UI has the same capability as the classic UI that can change to selected language without refresh page   

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Which parts of Lovelace are impacted? I bet it's some `shouldUpdate` method causing troubles.

**Comment by awarecan** [comment]
Spend some time on this. The problem is we localized string such as title of hui-entities-card in the `generateViewConfig`, e.g. the lovelace config already localized before `render()`

I am going to change it back to each card's `render()` method
