### ISSUE TITLE
"Person" pop-up doesn't scale user id

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-polymer#2811]
**Home Assistant release with the issue:** 0.88.0
**Last working Home Assistant release (if known):** n/a
**Browser and Operating System:** Chrome / Windows

**Description of problem:**
user_id (long field with id) doesn't scale in popup causing scroll to show up

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Additional information:**
![image](https://user-images.githubusercontent.com/6303489/53125069-4eb18c00-355d-11e9-8508-306e504b8ec4.png)

**Comment by iantrich** [comment]
I'm thinking just breaking the word will be the only good looking solution
