### ISSUE TITLE
Unused Entities Page is Blank

### ISSUE THREAD

**Issue by cjsteward** [home-assistant/home-assistant-polymer#2817]
**Home Assistant release with the issue:**
87-88

**Last working Home Assistant release (if known):**

**Browser and Operating System:**
All, mobile and desktop

**Description of problem:**
The "unused entities" button in the top right displays a blank screen. Clearing cache doesn't fix issue.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by raman325** [comment]
I am seeing the same problem. I tried inspecting the page and this is all HA is returning for the space that used to have entities listed: `<div id="view" class="tabs-hidden"></div>`

**Comment by BlodKolle** [comment]
I've tried different browsers on different platforms and have the same problem.

**Comment by BlodKolle** [comment]
I removed some lovelace cards that I don't use anymore and the Unused Entities returned.
These are the ones I removed: monster-card, gauge-card, button-entity-row, bignumber-card and swipe-card

**Comment by MikelRbrts** [comment]
In my case I had a blank tab. Removing that tab allowed the unused entities to populate.

**Comment by iantrich** [comment]
This should be fixed after conversion to new interface
