### ISSUE TITLE
Improving the Update Available screen (mockup)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2819]
**Home Assistant release with the issue:**
0.87.1

**Description of problem:**
I've made a mockup which I believe improves upon the current update available page and makes it more user friendly. First, here's an image comparison of the current one (left) and my mockup (right). In hindsight I probably should've switched back to the default theme before doing all this, but hopefully this still gets the ideas across. Click for bigger version.

![Home Assistant Update Mockup](https://i.imgur.com/FzWNQrK.png)

Here is what I changed and the thought process behind it:

- Made the heading bigger (simply applied h2 tag), which makes it easier to see at a glance.
- Increased the size of the Home Assistant icon. It fills up the empty space on the right and increases brand awareness as well. 😃Made it a similar size as the [iOS update screen](https://www.iphonetricks.org/wp-content/uploads/2017/12/ios-11.2.1-software-update-screen.jpg) icon. 
- Removed the duplicate release notes link. There is not much point in having two release note links directly next to each other like that.
- Introduced a brief mini update summary. This makes it far more professional looking imo. And there's barely any extra work involved because this mini-summary is already written for the tweet announcements and such, so that could be re-used in this area. For super minor updates could always just use a generic "Bug fixes and performance enhancements" type message there too.
- Note how after moving the icon over to the right, all the text lines up neatly on the left side.
- Swapped the order of buttons, so Release Notes comes first and then Update. This subtly encourages users to check the release notes first without blindly updating and hosing their system. 
- Lastly I right aligned the buttons so it looks cleaner and so that people are more likely to read the text. This also seems to be how most operating systems and update screens seem to do it as far as I know: Windows ([pic](https://www.kraftkennedy.com/wp-content/uploads/2018/03/w10-bug.jpg)), Ubuntu ([pic](https://lcom.static.linuxfound.org/images/stories/ubuntu_update_manager.png)), Mac ([pic](https://media.idownloadblog.com/wp-content/uploads/2019/02/macOS-Mojave-10.14.3-Supplemental-Update-prompt.png)), Chrome ([pic](https://i.imgur.com/hlyEMrO.png)) etc for some examples.

I think that overall it looks a lot cleaner and more professional, is more functional and user friendly, and encourages safer practices of reading the notes before upgrading.

**Comment by iantrich** [comment]
looks really nice

**Comment by cogneato** [comment]
It's the little things...
These are simple thought out changes which make a great difference.

**Comment by pepeEL** [comment]
Very very goood.... But it is only for Hass.io ? Should be also available to Hassbian and other.... replace with badge icon.

**Comment by balloob** [comment]
Looks great!

@pepeEL this is the Hass.io update card inside the Hass.io panel, so yeah, Hass.io only.

**Comment by iantrich** [comment]
Looks like I need to get hassio dev env setup this weekend 😄
