### ISSUE TITLE
Person home not_home not translated

### ISSUE THREAD

**Issue by boced66** [home-assistant/home-assistant-polymer#2821]
**Home Assistant release with the issue:**
0.88.0 

**Last working Home Assistant release (if known):**
New Feature

**Browser and Operating System:**
All

**Description of problem:**
For the new component "Person", the translations are not present, (at least in French)
In French, it indicates "home" instead of "Présent" and "not_home" instead of "Absent"

**Comment by boced66** [comment]
Same in 0.88.1

**Comment by pimoon** [comment]
+1 👍 
A translation will be appreciated!

**Comment by boced66** [comment]
Seem ok in 0.89.0
commit : 8f4d24b6daba83732219f4dc259b3aef7b15805d
