### ISSUE TITLE
Climate temperature slider ignores max_temp / min_temp

### ISSUE THREAD

**Issue by Julius2342** [home-assistant/home-assistant-polymer#2827]
**Home Assistant release with the issue:**

current `dev` on home assistant, commit: `921efbdfef1e6d419b654a28f4219084c1bc5847`

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

Lovelace UI tempeature slide ignores `max_temp` and `min_temp`. 

The KNX component throws an error if a target temperature `>max_temp`<min_temp` is set. Both limits vary dependent on the current mode. (e.g. when being in away mode, 17<=target_temp<=20, when being in comfort mode 20<=target_temp<=23, the values are dependent on various internal KNX settings).

In the old states ui, the dropdown only showed values within the allowed range. It also works within the additional menu (when you click the paper-icon-button, the one with the vertical dots).

**Additional information**

After switching to the old states-ui, going to a climate device, changing the mode, the max/min temperature are used for rendering the slider for this specific device. All other climate devices still use 0 to 100 as allowed range.

After a restart, all devices fall back to the old uninitialized state.

**Comment by iantrich** [comment]
I can't replicate this in the thermostat-card
![image](https://user-images.githubusercontent.com/1287159/54077612-72284680-4280-11e9-97b9-b4000f046e2d.png)

![image](https://user-images.githubusercontent.com/1287159/54077616-7d7b7200-4280-11e9-917b-c8c6f64a07c0.png)

**Comment by Julius2342** [comment]
I updated to current dev, and now it seems to be fixed. Thank you for investigating.
