### ISSUE TITLE
Can't log in to HA using Firefox ESR

### ISSUE THREAD

**Issue by tjorim** [home-assistant/home-assistant-polymer#2828]
**Home Assistant release with the issue:**

0.88.x

**Last working Home Assistant release (if known):**
0.87.x

**Browser and Operating System:**

Tor Browser (based on Firefox ESR) and Firefox ESR (60.5.x).

**Description of problem:**

Trying to log into HA, I get the following error.
```
Logging in with Home Assistant Local.
Error: Message format incorrect: required key not provided @ data['client_id']
```
First noticed this when trying to access my HA over Tor.
On a new HA install I tried accessing it locally with Firefox with the same result.
Was working fine before the 0.88 series (issue was present in beta).

**Javascript errors shown in the web inspector (if applicable):**
```
Error submitting step 
TypeError
​
columnNumber: 0
​
fileName: ""
​
lineNumber: 0
​
message: "NetworkError when attempting to fetch resource."
​
stack: ""
​
__proto__: Object { stack: "", … }
authorize-6d9831df.js:4078:2880
```

**Comment by fernandex00** [comment]
Same issue here

**Comment by fernandex00** [comment]
Any news of this?

**Comment by awarecan** [comment]
custom elements and shadow DOM on Firefox ESR 60 is not enabled by default

[custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements)
> From version 59 until version 65 (exclusive): this feature is behind the dom.webcomponents.customelements.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.
> Until version 59 (exclusive): this feature is behind the dom.webcomponents.enabled preference (needs to be set to true) and the dom.webcomponents.customelements.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.

[shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow)
> From version 59 until version 65 (exclusive): this feature is behind the dom.webcomponents.shadowdom.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.

**Comment by awarecan** [comment]
Add some additional information, even after change both options, FireFox ESR 60 is still not useable due the misalign of icons

![image](https://user-images.githubusercontent.com/7366491/53466768-2962c900-3a08-11e9-8c03-1db4f8367782.png)

**Comment by awarecan** [comment]
So, the `iron-icon` and lots of other polymer component are using [`:host()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host()) that only be supported after FireFox 61 (with turn on the shadow component support).

**Comment by awarecan** [comment]
After apply #2860, I can login with FireFox ESR 60 with default settings.
