### ISSUE TITLE
Script Editor not creating friendly entity id

### ISSUE THREAD

**Issue by DoctorIOT** [home-assistant/home-assistant-polymer#2829]
When creating a script using the Script Editor the script is saved with an alias as entered in the name field along with a numeric entity id. This entity id is not displayed or editable from the script editor. The result is that the script is hard to choose from elsewhere unless to know the random numeric id.

Fix it so that the entity id is a sanitized name based on the alias.

and/or

Modify the script editor to allow editing of the entity id and default it to a sanitized name.

**Comment by jjMustang** [comment]
I am experiencing the same issue. Screenshot attached.
![scripteditor](https://user-images.githubusercontent.com/35104990/62536487-1c9a9a80-b81c-11e9-9a62-fa9ea8e9181c.png)
