### ISSUE TITLE
Add tooltips on hover in Lovelace unused entities screen

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2832]
**Home Assistant release with the issue:**
0.88.1

**Browser and Operating System:**
macOS High Sierra 10.13.6 (17G5019), Chrome version 72.0.3626.119 (Official Build) (64-bit)

**Description of problem:**
As you can see in this example, it's impossible to read entity id's in some cases. It is especially true for the Input number section where you can't even see a single character of the entity id. And unlike some of the other sections, clicking on a input number does not display more info window.

Increasing the width of browser window does not help, because each of these cards is a fixed width.

I think adding a tooltip on hover that displays the entity ID would be a quick and simple fix.

![Unused Entities](https://i.imgur.com/WvevQgF.png)

**Comment by iantrich** [comment]
there shouldn't be anything stopping them from showing more-info, I believe, so perhaps a bug?

**Comment by SeanPM5** [comment]
It might be, cause every other card in the unused entities screen seems to support more-info except for this particular one. 

This one is kind of a unique case among the other cards on unused entities page, because the slider and number on the right is taking up more than half the input number card leaving just a few characters left over. If I didn't have friendly names or icons set up for these, it'd be even less usable.

Another possible solution besides a tooltip or more-info fix would be to just remove the slider completely on this page only. But I understand this is more of an infrequently used maintenance helper screen so I suggested what I thought might be the easiest fix.

**Comment by iantrich** [comment]
I think this will work itself out once #2786 is merged

**Comment by iantrich** [comment]
"input_number",
  "input_select",
  "input_text",
  "scene",
  "weblink",

All are hard coded to not show more-info. I'm not sure what the history behind that is. @balloob do you happen to know?

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/const.ts#L55

**Comment by balloob** [comment]
More info is not really needed, their controls is all in the row. 

I think that the rework that Bram is doing in #1959 will fix the need for a tooltip.

**Comment by iantrich** [comment]
@balloob I think you're right. Will close this.
