### ISSUE TITLE
Lovelace: Light card shows dimming slider on non-dimming lights.

### ISSUE THREAD

**Issue by rradillen** [home-assistant/home-assistant-polymer#2838]
**Home Assistant release with the issue:**
0.86.4

**Browser and Operating System:**
Firefox 65.0.1/Chrome 72.0.3626.119 

**Description of problem:**
In the lovelace ui a 'light' card configured with a light entity that is not dimmable still has the dimming slider. I'd expect the dimming slider not to be shown. The entity button is not a valid alternative as it cannot be used in a horizontal stack in conjunction with dimmable lights as the UI elements are not the same height.

**Comment by iantrich** [comment]
Entity button is the solution. You can use card-modder if you want to specify card height

**Comment by rradillen** [comment]
I can see it as a temporary workaround not a solution.

**Comment by iantrich** [comment]
If we we remove the slider from the light card it is an entity button...

**Comment by xichen-li** [comment]
I can see it as a temporary workaround not a solution. i argee more
