### ISSUE TITLE
mwc-button not respecting styles

### ISSUE THREAD

**Issue by finity69x2** [home-assistant/home-assistant-polymer#2840]
**Home Assistant release with the issue:**

88.1

**Last working Home Assistant release (if known):**

87.1 with paper-button
**Browser and Operating System:**

chrome on windows

**Description of problem:**

trying to apply styles to the new mwc-button and they aren't being allowed to take effect.

inspecting in the browser dev-console it looks like a shadowDOM is preventing the style from working

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

I'm using a custom entity row that has buttons included and the switch to mwc-button breaks the style of the button.

here is the code of the style I'm trying to achieve:

```
            <style>
                :host {
                    line-height: 1.5;
                }
                .speed {
                    min-width: 30px;
                    max-width: 30px;
		    margin-left: 2px;
                    margin-right: 2px;
    	            background-color:#759aaa;
	            border: 1px solid lightgrey; 
	            font-size: 10px !important;
	            float: right !important;   
                }
            </style>
            <hui-generic-entity-row hass="[[hass]]" config="[[_config]]">
                <div class='horizontal justified layout' on-click="stopPropagation">
                    <mwc-button
                        class='speed'
			style='[[_lowOnColor]]'
                        toggles name="low"
                        on-click='setSpeed'
                        disabled='[[_isOnLow]]'>LOW</mwc-button>
```

This is what it used to look like with paper-button:

![ex](https://user-images.githubusercontent.com/32221243/53328774-b26aea80-38b8-11e9-85d9-ca58e0fbc075.gif)

this is what it looks like now with mwc-button with the same style:

![ex3](https://user-images.githubusercontent.com/32221243/53328828-d29aa980-38b8-11e9-9c29-f5c7056122ba.gif)

the bottom row in the above picture is still using paper-button.

For some reason the mwc-button isn't respecting the style.

**Comment by balloob** [comment]
We don't make mwc-button, it's maintained by a third party.

I think the best solution here is to not use mwc-button but just style a <button>

**Comment by finity69x2** [comment]
i'm sorry to comment here again but the end of your post got cut off.

"but just style a..."?

**Comment by balloob** [comment]
My bad, I forgot the backticks and GitHub thought it was HTML.
