### ISSUE TITLE
Frontend looses connection after time

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#285]
The frontend looses it connection sometimes, it doesn't say "reconnecting at the bottom" but it looks as if all is ok. Since most is loaded in the browser, you can still click around and think its working but its just old data.

An example, load up the hass page. Close down the lid on the mac and come back the next day, then i usually have these kind of issues.

Don't know if something like this is implemented, but with some frontend apps, if you loose focus of the browser tab, it will stop polling and updating information. If you come back it will start again (it is also good for less strain on the system if multiple people have browsers still open) have seen this for example on Jira.

**Comment by balloob** [comment]
What browser / OS ?

**Comment by riemers** [comment]
Chrome / MacOS

**Comment by riemers** [comment]
Another example, i came to work. Hass page was still open, it didn't update, checked the logs and it was giving 401's which i can imagine. Then after some time it started to work again. Don't know if this is of any use:

![image](https://cloud.githubusercontent.com/assets/682041/26191643/fb436bdc-3bae-11e7-95f9-4558168af367.png)

You can see it started to work again, i didn't re-login only had the page open. 401's should either return to the login screen or report back on the screen something no?

**Comment by andrey-git** [comment]
The calls started to succeed when the token changed.

**Comment by balloob** [comment]
Camera tokens expire so you'll need the latest token to receive the images, which you'll get as part of the websocket connecting.

30 seconds is not too bad ;-)

**Comment by riemers** [comment]
If you compare it to the ios app, you see at the bottom the "lost connection, reconnecting" thingy, and it instantly starts refreshing everything. I would expect the same for the chrome browser, i don't mind waiting 30 seconds.. it is just that i don't know for 30 seconds that i am clicking around in old data. But would fall under the 'nice to have/beautify' code day.

**Comment by riemers** [comment]
I timed it this time, it took more then 5 minutes before it retried the websocket. I don't know all ins & outs of websockets, but perhaps the timeout should be lower? You could always check the response code of the camera's (if not 200, reaquire socket) but that only works if you have cameras.

**Comment by riemers** [comment]
I'll close this since a fix is at hand (refresh if takes too long after wakeup)
