### ISSUE TITLE
Sonos player component flickers

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#286]
I am uncertain if this belongs in here or the main home assistant, but a movie tells more then words.

https://www.youtube.com/watch?v=LUkKGq-dook

The sonos component in the gui "flickers" and i tried discovery, also setting the ip's too it but result is the same.

p.s. just found out that if there is a picture for the stream (playing or not) it will stop flickering..

**Comment by balloob** [comment]
Yeah that's not good.

**Comment by addelovein** [comment]
I have the same, however if I remove Z-Wave (which is throwing HA lots of events) It stops flickering. So my gut feeling is that Sonos is handling events that it really should ignore.

**Comment by d1vanloon** [comment]
I don't have Z-Wave configured on my HA system, but I see this "flickering" of the Sonos component GUI.

**Comment by riemers** [comment]
Just to update (before the bot comes in) i still see this.

**Comment by NovapaX** [comment]
Is this still an issue?

**Comment by riemers** [comment]
I don't have any channels without a picture anymore, so i can't check it anymore. Can someone check?

**Comment by NovapaX** [comment]
As there's been a ton of work on the sonos component lately I'm going to close this issue.
Please file a new (and up to date) issue if this is still a problem.

**Comment by riemers** [comment]
That is a good call, if i see it i'll do a proper checkup again. So far so good, thanks.
