### ISSUE TITLE
Geo-Location map not displaying events

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-polymer#2871]
**Home Assistant release with the issue:**

0.89.0b0

**Last working Home Assistant release (if known):**

0.88.2
**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio, generic Linux on debian
**Component/platform:**

**Description of problem:**

Does not display locations on map on iOS. Either in the app or chrome. Works on PC.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
![img_0066](https://user-images.githubusercontent.com/36390762/53608654-bdef4600-3c17-11e9-97b4-f04090cf05b4.jpg)

**Comment by iantrich** [comment]
Is this different than your #2430 issue?

**Comment by DavidFW1960** [comment]
It was resolved previously but is back again now with 0.89.0bx
I didn't realise the other one was still open.

**Comment by DavidFW1960** [comment]
It's doing it on my Win10 PC in chrome now as well. No events on the map at all.

**Comment by iantrich** [comment]
Closing in favor of #2430
