### ISSUE TITLE
Chrome crashes a couple of seconds after Home Assistant loads

### ISSUE THREAD

**Issue by layanto** [home-assistant/home-assistant-polymer#2876]
**Home Assistant release with the issue:**
0.88.1

**Last working Home Assistant release (if known):**
Not sure

**Browser and Operating System:**

Chrome on Windows 10 1809

**Description of problem:**

Chrome crashes a couple of seconds after Home Assistant loads - see below.
![hassio](https://user-images.githubusercontent.com/245078/53680191-131c7c00-3d2c-11e9-9974-f4dc09739aa2.gif)

**Javascript errors shown in the web inspector (if applicable):**
Chrome crashes so unable to bring up web inspector

**Additional information:**
Used to work but I mainly use Home Assistant on my Android phone (via PWA saved on Home screen - which continues to work well. Attempting to use desktop Chrome today to modify my Lovelace UI.

**Comment by layanto** [comment]
Not sure what happened before but issue seems to have gone away - Chrome doesn't crash anymore.

**Comment by balloob** [comment]
What Chrome version? And if you have any custom cards, please disable them all.
