### ISSUE TITLE
Dev-tools/states/entity

### ISSUE THREAD

**Issue by towerhand** [home-assistant/home-assistant-polymer#2877]
**Home Assistant release with the issue:**

0.89.0b1
**Last working Home Assistant release (if known):**
0.88

**Browser and Operating System:**

Hass.io
Safari, chrome, iOS app.
**Description of problem:**

The x in the dev-tools/states/entity doesn’t clear the selection when clicked/tapped.

Was discussed in the discord #beta channel and a few people confirmed the behavior.
**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by ludeeus** [comment]
![fixed](https://user-images.githubusercontent.com/15093472/68543952-1fc69900-03be-11ea-973d-0f74c2071575.gif)
Looks like the issue has been fixed by someone/something 👍

**Comment by towerhand** [comment]
On dev? Still happens on 0.101.3.

**Comment by ludeeus** [comment]
Initially tested on dev, but retested on 0.101.3 now, and it works for me there.
Do you get any messages in your browser console?

**Comment by bramkragten** [comment]
I think this might be about the entity picker? Because that doesn't work...

**Comment by ludeeus** [comment]
Ahhh, yeah that one looks broken.

**Comment by towerhand** [comment]
Thanks for the fix.
