### ISSUE TITLE
Climate icon does not change to yellow . Lovelace ui

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/home-assistant-polymer#2878]
**Home Assistant release with the issue:**

0.88.1
**Last working Home Assistant release (if known):**
0.84.1

**Browser and Operating System:**

Firefox / Chrome 
**Description of problem:**

When climate change to cool, the icon does not change to yellow. 

**Javascript errors shown in the web inspector (if applicable):**
```
none
```

**Additional information:**

**Comment by iantrich** [comment]
provide screenshots and configurations

**Comment by iantrich** [comment]
closing due to no reply
