### ISSUE TITLE
Entity in unused entities if used only in picture-elements card

### ISSUE THREAD

**Issue by treehoof** [home-assistant/home-assistant-polymer#2889]
**Home Assistant release with the issue:**
0.88.2

**Last working Home Assistant release (if known):**
-

**Browser and Operating System:**
- All testes on Mac: Safari, Chrome
- iOS in App

**Description of problem:**
If I use an entity only in a picture-elements card it is shown in unused entities page.
I thought unused entities is based on all used entities in all Lovelace cards.

**Javascript errors shown in the web inspector (if applicable):**
None found.

**Additional information:**
I'm using yaml mode.

**Comment by iantrich** [comment]
We need to make the computation of "unused" more robust

**Comment by iantrich** [comment]
Can't replicate this
