### ISSUE TITLE
External connection to googleapis.com

### ISSUE THREAD

**Issue by flo-wer** [home-assistant/home-assistant-polymer#2907]
**Home Assistant release with the issue:**
0.89.1

**Last working Home Assistant release (if known):**
N/A

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
all

**Description of problem:**
The new Lovelace UI makes external requests to https://fonts.googleapis.com/icon?family=Material+Icons .
As external requests can be considered a privacy issue, especially because by default the Referrer transmits the full URL to Google, this request should be served from a local copy.
I tracked this down to the usage of "@material/mwc-button", which in turn depends on "@material/mwc-icon" that includes https://github.com/material-components/material-components-web-components/blob/master/packages/icon/src/mwc-icon-font.ts

**Comment by awarecan** [comment]
Known open issue: https://github.com/material-components/material-components-web-components/issues/90

**Comment by awarecan** [comment]
Fixed via #2975
