### ISSUE TITLE
Change Password gives "Unknown command." error

### ISSUE THREAD

**Issue by ericlathrop** [home-assistant/home-assistant-polymer#2912]
**Home Assistant release with the issue:**

0.89.1

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

**Browser and Operating System:**

Firefox 65.0.1 / Ubuntu

**Description of problem:**

When trying to update my password on `/profile`, I get a red error of `Unknown command.`

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
unable to replicate
