### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isOff' of undefined

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-polymer#2915]
![image](https://user-images.githubusercontent.com/18516/54177197-a2bddb00-444e-11e9-83b9-e85d43f8304d.png)

https://github.com/home-assistant/home-assistant-polymer/blob/a2816800e8a607091d2c1b8ca19e778dc45a8f10/src/cards/ha-media_player-card.js#L295

**Comment by ericmiller777** [comment]
http://10.0.0.245:8123/frontend_latest/chunk.8abe6b9573af3d1ad82d.js:2875:1345 Uncaught TypeError: Cannot read property 'isOff' of undefined

Same issue? Does anyone know what this is?

**Comment by nkaminski** [comment]
@ericmiller777 what are the preconditions needed to trigger/reproduce this issue?

**Comment by gfetters** [comment]
getting this too
