### ISSUE TITLE
Cloud Remote login page sometimes fails to initiate

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2931]
**Home Assistant release with the issue:**
0.90.0b0

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Version 73.0.3683.75 (Official Build) (64-bit)
macOS High Sierra 10.13.6 (17G5019)

**Description of problem:**
In 0.90b the login page for HA Cloud remote (at <url>.ui.nabu.casa) sometimes shows this error:

```[[localize('ui.panel.page-authorize.initializing')]]```

Here is a screenshot:
![image](https://i.imgur.com/FfdAGMZ.png)

If you refresh the page you might be able to reproduce it.

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/7d92eede1f48e7e71363ecef2a082aeda694b032/src/auth/ha-authorize.ts#L56

This should be `${this.localize('ui.panel.page-authorize.initializing')}` instead.
