### ISSUE TITLE
Panel breadcrumb breakage

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-polymer#2933]
**Home Assistant release with the issue:**  0.89.0.dev0

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** Config

**Browser and Operating System:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

**Description of problem:**
Configuration -> Area Editor -> Integrations link -> Any Integration -> Back button -> No UI update -> Back button again -> Area Registry

UI should update to take me back to Integrations view when hitting back.

**Javascript errors shown in the web inspector (if applicable):** None

**Additional information:** None

**Comment by JensVanhooydonck** [comment]
Can't reproduce Bug in 0.99.3
