### ISSUE TITLE
/states crashing mobile Safari

### ISSUE THREAD

**Issue by adrianmihalko** [home-assistant/home-assistant-polymer#2939]
**Home Assistant release with the issue:**

Home Assistant 0.89.1

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io / Ubuntu

**Component/platform:**

**Description of problem:**

Mobile Safari constantly crashing if I try to open /states. In Chrome it is working correctly.

Video about the problem:

https://youtu.be/5Hp7RTLoh2A

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by robbiet480** [comment]
You mean it works fine in Chrome for iOS or Chrome for desktop?

**Comment by balloob** [comment]
What version of Safari? And what about Lovelace?

**Comment by balloob** [comment]
Video shows Chrome for iOS. Isn't that the same renderer? 😕

**Comment by robbiet480** [comment]
That is Safari in the video. They share the same HTML renderer but afaik Safari has the added bonus of the Nitro engine for much faster JS processing.

**Comment by adrianmihalko** [comment]
"You mean it works fine in Chrome for iOS or Chrome for desktop?"

It only crashes in mobile Safari (constantly). Chrome for iOs or on desktop everything is working fine.

Lovelace works nicely, but my Lovelace interface contains only a few items.

**Comment by balloob** [comment]
For now, remove your lovelace config and it will generate something that resembles 90% of your states page. If you use managed mode, remove `<config>/.storage/lovelace` and restart 👍

**Comment by iantrich** [comment]
We're not actively patching the old States UI
