### ISSUE TITLE
Z-wave config panel doesn't fit properly in screen

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#294]
The node config options can sometimes be a big list, but you now have to scroll down inside the little screen. Only displays 5 options now for me, is there otherwise a reason for only showing 5? prefer to just see them all and just scroll down the complete page instead. (after all, if all is working you should no longer need to be there anyways)

![image](https://cloud.githubusercontent.com/assets/682041/26488272/1836b578-4203-11e7-8d04-ba981bc565fe.png)

**Comment by cgarwood** [comment]
It 's not set to a fixed number, but depends on the amount of space above or below the dropdown. Some nodes have a *lot* of config options, so I'm not sure displaying them all in a list would be the best direction to go.
