### ISSUE TITLE
New Stream Player Not Loading On Android Phone

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#2948]
**Home Assistant release with the issue:**

0.91.0.dev0 with latest frontend installed: 20190315.1

**Last working Home Assistant release (if known):**

N/A new video player

**UI (States or Lovelace UI?):**

Lovelace
**Browser and Operating System:**

Pixel 3 XL Android 9 March security update.  Google Chrome 72.0.3626

**Description of problem:**

When I attempt to view (more info panel) an `amcrest` or `generic` camera with a valid RTSP stream the new video player never loads on my pixel (even in desktop mode).  When I am on Windows 10 Chrome 72.0.3626 the player loads fine, even in responsive mode.  When I go to do remote debugging in chrome I noticed that on mobile the entire `video` element is missing where in desktop it is not missing, see image links below.  There is no console log here and the network calls are successful.  You can even see the stream being processed while the panel is opened so it seems to just not load. 

mobile: https://imgur.com/a/wb9EL0I
desktop: https://imgur.com/a/X876rE9

**Javascript errors shown in the web inspector (if applicable):**
```
n/a
```

**Additional information:**

This issue does not occur in the old player, I am still able to load it successful on mobile.  I have also attempted to view: https://video-dev.github.io/hls.js/demo/ on my phone the player loads successfully and as I understand it this is the player we are using.

**Comment by hunterjm** [comment]
I've been able to replicate using [Android Studio](https://developer.android.com/studio/) to emulate a Pixel 2 on Android 9.0.  I can look into this a little bit deeper.
