### ISSUE TITLE
0.90b - Notifications cut off in iOS app

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2960]
**Home Assistant release with the issue:**
0.90b3

**Last working Home Assistant release (if known):**
0.89.x

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
iOS App (2.0 beta & 1.5.1 stable)

**Description of problem:**
It seems the width of the notification center panel was increased, and now they're kinda unreadable in the official iOS app. Half of the notification appears off-screen as you can see in the screenshot below. I have confirmed this behavior in both the upcoming 2.0 app and stable 1.5.1 app.

![image](https://i.imgur.com/axOdQYG.png)

In this screenshot with no notifications you can't even read the "Notifications" heading (just half of the final "s" character). 

![image](https://i.imgur.com/oEVw1lL.png)

**Comment by iantrich** [comment]
Hmm, likely a victim in my styles cleanup like markdowns. I’ll take a look.

**Comment by iantrich** [comment]
Nevermind, I didn't touch the notifications as they are not converted yet...

**Comment by SeanPM5** [comment]
I am pretty sure this bug was introduced in either **b2 or b3**. I didn't notice it in the initial beta and I then went from b1 to b3 which I'm still on now. (b4 still doesn't appear for me in Hassio panel).

Hopefully that narrows it down a little bit.

**Comment by dshokouhi** [comment]
same issue on android too: https://imgur.com/a/DbPnAOD

**Comment by SeanPM5** [comment]
This was fixed in official stable build, closing issue.
