### ISSUE TITLE
0.90b - cloud.remote_connect and disconnect service calls don't update toggle state

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2961]
**Home Assistant release with the issue:**
0.90b3

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Description of problem:**
When you call the service `cloud.remote_connect` or `cloud.remote_disconnect` it does not update the "Remote Control" toggle on the HA Cloud page, so it shows the wrong state. Only refreshing the browser shows proper state.

In example below, I turned on remote cloud service (connect) yet the toggle still shows it as disconnected.

![image](https://i.imgur.com/M4SepcF.png)

**Comment by iantrich** [comment]
still issue? don't instance up right now to check

**Comment by SeanPM5** [comment]
Just tested and it's still an issue in 0.100

The service calls work fine but the toggle doesn't update until a page refresh. So user could potentially see a wrong state.
