### ISSUE TITLE
HA browser tab crashes since 0.90 beta

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/home-assistant-polymer#2963]
Since version 0.90.0b4 (can't tell if it was also in the earlies betas, but certainly not in 0.89) HA sometimes crashes and uses 99% of my chrome CPU:
![Screenshot_2019 03 18_14h21m30s_001_](https://user-images.githubusercontent.com/1368405/54532948-5f50f880-4989-11e9-82e1-f5685534a9a3.png)

And chrome asks me to force close the tab:
![Screenshot_2019 03 18_14h21m47s_002_](https://user-images.githubusercontent.com/1368405/54532950-5fe98f00-4989-11e9-8316-9a928f53a451.png)

This sometimes happen on the `/config` url, sometimes on the `/dev-state` url and sometimes on the `/dev-info` url. I can't see a pattern there. (most of the time they all work as expected)

Also I have this issue on two completely independent HA instances in two different networks (one work, one home).

If you need more information or can tell me how I can debug this, please let me know.

Browsers are chrome desktop, chrome mobile and electron (through [Nativefier](https://github.com/jiahaog/nativefier))

**Comment by balloob** [comment]
Do you use hass.io ?

**Comment by TheZoker** [comment]
Yes I use Hassio. Is it fixed in b5?
