### ISSUE TITLE
Add error for Cloud Remote on Home Assistant Cloud page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2966]
**Home Assistant release with the issue:**
0.90b3

**Description of problem:**
Remote Cloud service aims to be very user friendly, and it's a massive success at that. The only issue is that when something goes wrong, there's not really user-friendly troubleshooting steps.

The main one is **Trusted Networks / 127.0.0.1 doesn't let you enable cloud.** This is probably going to be a common scenario, since I think that is or was a default part of configuration.yaml? 

When that line is in config it doesn't let you toggle on the cloud remote switch at all, and doesn't seem to display any message either on the current page or in the logs. I ran into this myself and the only reason I had any idea how to fix it or what the problem was is because I hang out in Discord.

Here is a quick mockup of a conditional error message being presented right in the same card as the toggle. The text could be improved but this is the idea. User is told exactly what the issue is and how to fix it.

![image](https://i.imgur.com/5fqZzmC.png)

**Comment by pvizeli** [comment]
> The main one is Trusted Networks / 127.0.0.1 doesn't let you enable cloud. This is probably going to be a common scenario, since I think that is or was a default part of configuration.yaml?

No, they were never a default setting. Since you can store the security token it's also a not good idea for your security to use `Trusted Networks` in anyway.

**Comment by SeanPM5** [comment]
Well it might not have been a default setting then, but it was and still is on [http docs](https://www.home-assistant.io/components/http/) and [authentication providers docs](https://www.home-assistant.io/docs/authentication/providers/#trusted-networks). As someone without much networking knowledge i just copied the code block from the http docs long ago without realizing the implications. 🤷‍♂️I doubt I am the only one.

This cloud remote feature is aimed at users like me who had difficulty figuring it out before, so I suspect `Trusted Networks` config might be a common scenario.

**Comment by balloob** [comment]
I have a PR open that will be in the final 0.90 that will show the error. I will also update the examples on the pages you linked. Trusted networks is for logging in, not for API access, so localhost does not make much sense.
