### ISSUE TITLE
Insteon with wrong password breaks the Front End.

### ISSUE THREAD

**Issue by alfonsolsl** [home-assistant/home-assistant-polymer#2972]
HA Release: 0.89.2

platform: Insteon

FrontEnd: lovelace, (first issued with States)

Issue: INTEON hub2 with wrong password setup at configuration.yaml the **frontend Crash permantently.** 

The issue has been there severals versions before.

**Comment by cgarwood** [comment]
This sounds like more of a backend issue. I would guess the insteon component is hanging startup if the password is wrong, so the frontend never has a chance to initialize. Are any state changes logged in the database or in the home assistant log, or do automations still run when HA is in this state?

**Comment by alfonsolsl** [comment]
Hello! That's correct. HA appears to load completely wo showing the frontend, the logs shows severals insteonplm logging attempts in 20s, 60s, 120s and so on...

In addition and most sensitive, if you Insteon Hub get disconnected and HA can't reach it so the same happens with the front end.
