### ISSUE TITLE
Minor typo in HA Cloud intro notification

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#2983]
**Home Assistant release with the issue:**
0.90

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**

Spotted a very minor typo when upgrading my friends system just now. This is the card that appears in notification center directly after updating if you're a Nabu Casa subscriber.

![image](https://i.imgur.com/MlsqyJQ.png)

**Comment by iantrich** [comment]
I can't find any reference of where this is coming from in the frontend or backend. @balloob is this notification coming from the cloud service itself?

**Comment by balloob** [comment]
https://github.com/NabuCasa/hass-nabucasa/blob/dev/hass_nabucasa/const.py#L48
