### ISSUE TITLE
After clicking on any link in Configuration screen it extend itself, but not displaying new page

### ISSUE THREAD

**Issue by vlad36N** [home-assistant/home-assistant-polymer#2992]
**Home Assistant release with the issue:**

0.90

**Last working Home Assistant release (if known):**
0.89

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io

**Description of problem:**
After cliking on any link in Configuration screen it extend itself, but not displaying new page

**Additional information:**
[You can see animated .gif file posted on forum](https://community.home-assistant.io/t/0-90-remote-ui-streams-user-groups/106670/128)

**Comment by rccoleman** [comment]
This appears to be related to custom_ui, and commenting that out makes the problem go away for me.  Someone else already filed an issue against custom_ui earlier today: https://github.com/andrey-git/home-assistant-custom-ui/issues/170

**Comment by tdejneka** [comment]
I have it commented out because it stopped working in 0.89. I still have the problem described above.
```yaml
# customizer:
#   custom_ui: local
```

**Comment by balloob** [comment]
This seems related to custom_ui. Cannot be reproduced.

**Comment by tdejneka** [comment]
Wish I could not reproduce it on my system! :)

`custom_ui` is commented out yet the `Configuration` page continues to produce the undesirable behavior described above.

**Comment by iantrich** [comment]
@tdejneka did you clear your cache?

**Comment by rccoleman** [comment]
These are the lines that need to be commented out:

```
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
```

It's the Javascript in there that's causing the problem.

**Comment by tdejneka** [comment]
@iantrich 

Doh! Always overlooking the little things! Thanks for reminding me! Just cleared it and now the `Configurations` page works correctly.  Good!

**Comment by rccoleman** [comment]
I forked the origin repo and commented out the code that adds the new entry in the config panel.  Colors are working in Lovelace and config navigation is also working for me.  Here's the repo, and you should just need the *.html files.  Use at your own risk, of course.

https://github.com/rccoleman/home-assistant-custom-ui
