### ISSUE TITLE
History and Logbook Components does not work in fronend when I set my language to Turkish

### ISSUE THREAD

**Issue by akinomeroglu** [home-assistant/home-assistant-polymer#3013]
**Home Assistant release with the issue:**

0.90.1

**Last working Home Assistant release (if known):**
Don't remember

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Safari 12.0.2 / Mac osx 10.14.2

**Description of problem:**

I am using my HA frontend in Turkish. When I try to open logbook and history component page stays blank and nothing happens. I can see this components pages without an error when I set the language to English.

I checked logs and saw that there is a error log like 

```
2019-03-24 23:36:57 ERROR (MainThread) [frontend.js.latest.201903210] http://my-ha-ip/frontend_latest/app-0a9a98f1.js:723:261107 SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "\xE7" found. 
```

\xE7 translate to ç character which we use in Turkish while we write açık (means open). So this could be the root cause of the problem.

**Comment by awarecan** [comment]
Thanks for reporting this. One translation in Turkish is wrongly changed since last October.

I have fixed it, and the fix will come in the next frontend release, usually the next beta release.

**Comment by akinomeroglu** [comment]
@awarecan thanks for your interest and support. I will check this in next beta and then close the issue.

**Comment by awarecan** [comment]
If you have interest, welcome to join our translation task force. We have just 50% Turkish translation in frontend project and only 1% has done in back end project.

https://developers.home-assistant.io/docs/en/internationalization_translation.html

**Comment by akinomeroglu** [comment]
@awarecan I am sorry for my late answer. I will be happy to help improve translations for my language. Thanks for information. Beta release resolved this issue.
