### ISSUE TITLE
Drawer menu missing after page reload

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/home-assistant-polymer#3016]
**Home Assistant release with the issue:**
0.90.1

**Last working Home Assistant release (if known):**
0.89

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome on Windows 10 and Android

**Description of problem:**
Drawer menu only shows on first page load. After reloading (and having password saved), the menu is completely gone.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught (in promise) TypeError: Cannot read property 'is_admin' of null
    at e82d02eae7c564ba3679.chunk.js:97
    at HTMLElement.value (e82d02eae7c564ba3679.chunk.js:97)
    at HTMLElement.update (app-0a9a98f1.js:2)
    at HTMLElement.performUpdate (app-0a9a98f1.js:2)
    at HTMLElement._enqueueUpdate (app-0a9a98f1.js:2)
```

**Additional information:**

**Comment by tboyce021** [comment]
It seems a shift+F5 will get it back, but then doing another F5 will get the same error again.

**Comment by tboyce021** [comment]
It seems to be fairly random. I can get it to happen on a new instance by repeatedly refreshing the page, although it seems to be less frequent than on the other instance.

**Comment by tboyce021** [comment]
Hmm.. looks like this might have actually been fixed with #2993. I will test again with the next release with that patch and close this issue if that fixes it.

**Comment by iantrich** [comment]
@tboyce021 fixed?

**Comment by tboyce021** [comment]
I actually don't have a setup to test with anymore (been packed away in preparation for moving). I'll likely get it set up again at some point but probably not for at least a month or two. I can reopen or create a new issue if I run into it then if you want to close this.

**Comment by iantrich** [comment]
Cool. Thanks!
