### ISSUE TITLE
dev-info page loads error_log without any restrictions

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#303]
I have my log file generating more information then normal, i normally tail this file from the prompt. But if you go to the dev info page it will load the error_log (which is just the home assistant log no?) without restrictions.

![image](https://user-images.githubusercontent.com/682041/27101079-9fbcce84-5080-11e7-9b14-d0c88e4329f6.png)

Hence it was too big, and chrome window hangs/crashes. Showing only latest xx lines/pagination would address this issue.

**Comment by balloob** [comment]
The Home Assistant log only contains errors and warnings. Having 139MB of warnings is … not normal.

**Comment by riemers** [comment]
I have it set to 'INFO' which just logs more information since i am still actively making changes. Those are not errors, but it does increase the size. Since all my z-wave communications also show in the INFO. That makes it big in a short time (since i have about 20+ zwave nodes)

**Comment by riemers** [comment]
Further debugging, one of the nodes was in "Probe" state (z-wave) which made it trigger something on z-wave level. This went into a loop constantly which was filling the logs at a increasing rate. If the log file of home assistant is normally acceptable you can close the ticket, although the initial 'bug' still exists.
