### ISSUE TITLE
Can access web resources without being logged in

### ISSUE THREAD

**Issue by pkozul** [home-assistant/home-assistant-polymer#304]
Even after logging out of the Home Assistant front end, it is still possible to access web resources.

Using a web browser (or `wget` via the command line), I was able to load a web page without being logged in to Home Assistant. The URL below is what I used as an example, and was able to successfully view/download the web page.

```
https://<home_assistant_host>8123/local/custom_ui/floorplan/ha-floorplan.html
```

I believe that all web resources should be protected within Home Assistant and should only be accessible when logged in.

**Comment by balloob** [comment]
It's impossible as the web is not setup for that. You can't specify auth when you add an image tag or HTML import to the page.

Custom UI should not contain any sensitive information. If you want password protection, create a component that registers a view (auth enabled by default). A custom_ui could then load the sensitive things from the component view using the auth that is available to it.
