### ISSUE TITLE
Card configuration: wrong behaviour on entities' removal

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#3045]
**Home Assistant release with the issue:**
0.91.0b2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Google Chrome 73.0.3683.86 64-bit, OS X 10.11.6

**Description of problem:**
When removing entities via Card Configuration, in some particular scenarios it behaves wrongly:
For example, there is a card with 4 entities (I just used the same entity 4 times).
Open it for editing:
![Screen Shot 2019-04-01 at 08 26 17 (2)](https://user-images.githubusercontent.com/13675855/55310902-89aab780-5459-11e9-89a6-470b0a3e033a.png)

and click on a cross (remove) next to the top entity:
![Screen Shot 2019-04-01 at 08 26 22 (2)](https://user-images.githubusercontent.com/13675855/55310911-90392f00-5459-11e9-81b4-31f3512f064e.png)

Repeat for the second from top and you'll see ALL entities' input fields empty , but they are still displayed in the right side of the configurator window
![Screen Shot 2019-04-01 at 08 26 29 (2)](https://user-images.githubusercontent.com/13675855/55310927-9cbd8780-5459-11e9-91d0-73dfb004f29d.png)

and if you click Save, next time there will be 2 entities.

Another example.
Create a card with 4 DIFFERENT entities and open it for editing:
![Screen Shot 2019-04-01 at 08 48 56 (2)](https://user-images.githubusercontent.com/13675855/55311654-6bde5200-545b-11e9-8011-db4e4da89f0f.png)

Click on a cross (remove) next to to the second from top entity (or the top one):
![Screen Shot 2019-04-01 at 08 49 04 (2)](https://user-images.githubusercontent.com/13675855/55311752-a647ef00-545b-11e9-90a2-92cce280bc0e.png)

Do it again, and instead of removing the entity it will open you a list of entities.
![Screen Shot 2019-04-01 at 08 49 10 (2)](https://user-images.githubusercontent.com/13675855/55311758-aa740c80-545b-11e9-9a4c-35877dc905d7.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
should be fixed now
