### ISSUE TITLE
Lovelace code editor on mobile is a pain

### ISSUE THREAD

**Issue by mu3** [home-assistant/home-assistant-polymer#3061]
**Description of problem:**
Lovelace code editor (card and raw config) doesn't work well on a mobile:
* Context menu is not showing up on tap, only on hold.
* «Select All» does nothing.
* Copied text includes line numbers
* ~~Multi-line copy stores only the first line~~ (can't reproduce, fixed?)

I can be wrong but I think it used to work better a few versions ago.

**Expected behavior:**
Native <textarea> (with a basic indent support).
Ideally, [Ace](https://github.com/ajaxorg/ace) may be a great solution. Node-RED happily uses it for the code editor inside UI.

**Home Assistant release with the issue:** 0.91
**UI (States or Lovelace UI?):** Lovelace UI
**Browser and Operating System:** Safari on iOS 12.2

**Comment by neffs** [comment]
Can someone please have a look at this?

Additionally to the issues reported by @mu3 the cursor positioning is broken. In most cases can’t add text to the front of a line. While the cursor is set to the front of a line, characters are always appended to the end of the line.

I tried the codemirror demos on their website and it works fine there.

**Comment by aptonline** [comment]
Yep same here, unable to copy, select all or generally reliables edit raw config in the editor.

Running iOS on 12.3.1 and the same within HA app and Safari.

**Comment by gohassgo** [comment]
>> Multi-line copy stores only the first line (can't reproduce, fixed?)

This is a problem for me on a Pixel 2 when using the Lovelace card editor. I'm up to 0.94.4.

It only copies one of the lines. It's also weird when just trying to place the cursor, add text, or even just save changes. There are a number of oddities here that I think are all related to the constant refreshing to preview the card.

**Comment by hagenuck1** [comment]
Im with you, editing the raw commands or the code editor is nearly impossible.

Selecting text by using force touch or coping/ replacing the selected text isn’t working and only replaces the first selected text. 
Shift isn't working, as it acts like CAPS Lock.  
It’s very 

Would be awesome if somebody could fix that :)

**Comment by aptonline** [comment]
I forgot I commented on this issue and raised another (sorry) but my new post gives us some more details on the problem: https://github.com/home-assistant/home-assistant-polymer/issues/4482

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/home-assistant-polymer/issues/4482
