### ISSUE TITLE
EDGE browser SCRIPT5007: Unable to get property 'attributes' 

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/home-assistant-polymer#307]
MS Edge browser

Navigating to ' Configuration' Page in the home menu, results in broken visuals.
Functionality still works.

Error in MS Edge Console:

> SCRIPT5007: Unable to get property 'attributes' of undefined or null reference
> javascript;charset=utf-8,Polymer({is:&quot;ha-form-group&quot;,properties:{hass:{type:Object},entity:{type:Object},entityName:{type:String,value:&quot;&quot;},entityType:{type:String},entityChildren:{type:Object}},handleRowChosen:function(t){t.detail&amp;&amp;window.navigator.vibrate&amp;&amp;window.navigator.vibrate(50)},loadEntity:function(t){var i=this.hass.states;return this.entity=t,this.entityName=t.attributes.friendly_name||&quot;&quot;,this.entityType=t.attributes.view?&quot;view&quot;:&quot;group&quot;,this.entityChildren=t.attributes.entity_id.map(function(t){return i[t]||{state:!1,entity_id:t,attributes:{}}}),Promise.resolve()},saveEntity:function(){var t={name:this.entityName,view:&quot;view&quot;===this.entityType,entities:this.entityChildren.map(function(t){return t.entity_id})},i=this.entity.entity_id.split(&quot;.&quot;)[1];return this.hass.callApi(&quot;POST&quot;,&quot;config/group/config/&quot;+i,t)}})
> //# sourceURL=http://192.168.1.150:8123/frontend/panels/config-59d9eb28758b497a4d9b2428f978b9b1.html-17.js
>  (1,310)

**Comment by balloob** [comment]
This is most likely broken in the next release.

**Comment by balloob** [comment]
Closing this as we changed the framework around and this report is no longer relevant.
