### ISSUE TITLE
Provide access loop on iPad2 using es5 

### ISSUE THREAD

**Issue by sagilo** [home-assistant/home-assistant-polymer#3070]
I'm using HA 0.90.2 (tested on 0.91.3 too)
Working normally on MacBook, cell phone and some Fire HD tablet

I've set up Home Panel and it asks to login to HA in order to give it access to its API.
In all the devices I've mentioned it works flawlessly, however, on my iPad 2, when I type in the credentials the hit the login button, the page reloads and returns to the same login page.

I've noticed it uses es5 when trying to login, I've tried to set javascript_version to latest but then it just says 'initializing' and doesn't show anything else.

Also tried to provide access by using HA internal IP address and whitelisting it using auth_provider, on the access screen it recognizes it as a trusted computer, asks me to select a user and as I select and log in, it returns to the same screen.

I've noticed the logs say it's 'invalid authentication' but I've been using trusted ip so I didn't even have to type anything, when I wasn't using trusted network, i typed the user and password and it worked when accessing HA directly but not when trying to provide access to external app.
[ha_login_logs.txt](https://github.com/home-assistant/home-assistant-polymer/files/3084987/ha_login_logs.txt)

**Comment by sagilo** [comment]
Still not working after upgrading to HomeAssistant 0.91.3

**Comment by iantrich** [comment]
Home Panel issues can be reported here https://github.com/timmo001/home-panel/issues

**Comment by sagilo** [comment]
@iantrich @timmo001 just closed the [issue](https://github.com/timmo001/home-panel/issues/272) on Home Panel project claiming this is HA issue

**Comment by iantrich** [comment]
https://github.com/home-assistant/home-assistant-polymer/issues/3092

**Comment by sagilo** [comment]
@iantrich as you can see this is not the same as #3092 , can you please reopen?

**Comment by DeviousPenguin** [comment]
I'm experiencing something similar using the Tileboard UI on an iPad 2 and an iPad 3 however I'm able to login and use Tileboard. 

Even though it logs in, I still get 'invalid authentication' errors in my HA log, so I think the issue is with the Auth component of HA.

I've managed to work around the issue by using a LLAT and a different Auth system, no ideal but it works.

**Comment by sagilo** [comment]
After some investigation, it looks like HomePanel (@timmo001) doesn't support ES5.
