### ISSUE TITLE
Camera images refresh issue

### ISSUE THREAD

**Issue by misakm** [home-assistant/home-assistant-polymer#3073]
**Home Assistant release with the issue:**
0.91.1

**Last working Home Assistant release (if known):**
0.87.1

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Fullykiosk, Chrome, Android 7.1.1

**Description of problem:**
When Android tablet temporally disconnect from network and connect again then my cameras stops refreshing images. This is valid for Generic camera, Foscam camera, Synology camera. I am using lovelace picture-entity.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by misakm** [comment]
Please check this https://community.home-assistant.io/t/0-91-more-streaming-better-zigbee-cameras-with-esphome/109274/108?u=misak000m

**Comment by bieniu** [comment]
I have the same issue on mu Android phone. I use PWA app (Chrome) to HA. Very often I have to reload page because picture-entity card shows old image from my ffmpeg camera.

**Comment by misakm** [comment]
I have upgraded to the the lastest 0.91.3 still the same issue

**Comment by tunip** [comment]
Same here with mjpeg and generic cameras on HA 0.91.4

**Comment by hawkeye217** [comment]
Same here on iOS 12 with the HA iOS app version 1.5.1.  Still on HA 0.93.2, but I'm guessing this hasn't been addressed in the latest HA yet...

Camera images initially are fine and refresh correctly but then after switching to another app/putting the phone to sleep and then reopening the HA app a short time later, all camera images show up as gray boxes.  I have to quit the app (swipe up) and reopen it to see the camera images again.
