### ISSUE TITLE
Entity Editor: Cannot delete more than one device

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3077]
**Home Assistant release with the issue:**
0.91.2

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Description of problem:**
In Person editor, you can remove one device but after that it's impossible to remove any more. 

Clicking the "X" button on a second device will incorrectly show the device select dropdown menu rather than removing the second device.

Please see this quick screen recording for demonstration: https://gfycat.com/BonyGreenCero

**Comment by iantrich** [comment]
Closing in favor of more complete issue: https://github.com/home-assistant/home-assistant-polymer/issues/3045
