### ISSUE TITLE
Road to Polymer 2.0

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#308]
I have been trying to get a list together of steps to take to get to Polymer 2.0. The initial goal is going to be to run Polymer 2.0 in legacy mode. That should already allow us to leverage v1 web components which run native on iOS.

Because of the hybrid approach that Polymer 2 offers, we should be able to update all components on Polymer 1 first and when that's done, switch the Polymer dependency from 1 to 2.

- [x] Replace dependency on meta-packages "iron-elements" and "paper-elements" with the actual dependencies. From a quick grep `paper-card paper-item paper-icon-button paper-input paper-dropdown-menu paper-listbox paper-menu-button paper-fab iron-autogrow-textarea iron-media-query paper-button paper-checkbox paper-spinner iron-icon paper-radio-group paper-radio-button paper-menu iron-flex-layout iron-image paper-material paper-progress paper-toggle-button paper-slider paper-dialog paper-dialog-scrollable neon-animation paper-styles paper-drawer-panel iron-pages iron-input paper-tabs paper-toast paper-range-slider`
- [x] Use only hybrid versions of dependencies (this will get tons of subtasks)
  - [x] All the above
  - [x] Switch from attr to slots
  - [x] GoogleWebComponents/google-apis#~1.1.6
  - [ ] polymer-sortablejs
  - [x] paper-menu

## Bugs noticed when switching to Polymer 2.0
- [x] states broken
- [x] maps CSS borked
- [x] sidebar menu items don't show
- [x] Edit automation renders X times
- [ ] Config - groups: Reorder entities is broken (polymer-sortablejs needs upgrade)

# Update - August 2

Final blocker is polymer-sortablejs. We're going to remove the code the functionality that depends on SortableJS. Minor impact feature that we remove, will unblock Polymer 2 for now. We can add it back later.

We have migrated to polymer-build. You can test running under Polymer 2 locally:

- Check out `polymer-2` branch for `home-assistant-polymer` repo. Run `bower install`
- Check out `polymer-2` branch for `home-assistant` repo

Currently all works in Chrome in dev mode. When we create a bundle, it breaks 😢

**Comment by balloob** [comment]
So it looks like the new Polymer uses ES2015 classes. This means that the last step for us to upgrade to Polymer 2 is to upgrade our build system to support transpilation.

Build system upgrades

 - Copy `webcomponentsjs/webcomponents-lite.js` instead of `webcomponentsjs/webcomponents-lite.min.js`
 - Transpile ES2015 code to ES5
 - Add [`custom-elements-es5-adapter.js`](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs)

We should probably move to either using the Polymer CLI or gulp, as that's the preferred approach. @armills, you did some work on a build pipeline using Gulp in #227. Would you be down to help with the conversion?

**Comment by balloob** [comment]
Unable to find a fix for sortable-js. Since it's only used for re-ordering group entities right now, I'm fine with removing that functionality to unblock the upgrade.

**Comment by armills** [comment]
Yeah, I can try to pick some of that up. I have been starting to dust off #227, so the gulp conversion is probably a good first step.

**Comment by balloob** [comment]
@armills @andrey-git could use some help with understanding why Polymer 2 is not running in bundled mode
