### ISSUE TITLE
Notification orange circle doesn't scale for value

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-polymer#3082]
**Home Assistant release with the issue:** 0.90

**Last working Home Assistant release (if known):** n/a

**UI (States or Lovelace UI?):** lovelace

**Browser and Operating System:** Chrome latest mobile and desktop

**Description of problem:** Number of notifications doesn't extend circle if value contains 3 digits

**Javascript errors shown in the web inspector (if applicable):** n/a

**Additional information:**
Screenshot of problem
![image](https://user-images.githubusercontent.com/6303489/55943242-81ffc580-5c46-11e9-9ecf-02ddeebc0a3f.png)

It was fault of sensor reporting 0/1 status, but showed problem too. ;-)

**Comment by JensVanhooydonck** [comment]
This can be closed i guess. Notifications are moved to the sidebar + scales now.
