### ISSUE TITLE
Lovelace "Configure UI" menu option enabled for non-admin users

### ISSUE THREAD

**Issue by bwolther** [home-assistant/home-assistant-polymer#3084]
**Home Assistant release with the issue:**
0.91.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome, Firefox, Edge (Windows)

**Description of problem:**
I logged into frontend using a username that I created in the "Users" group (not the "Administrators" group). I believe such a non-admin user should be unable to configure the Lovelace UI. However, when I navigate to the "Overview" tab, the 3-dot menu shows options for "Configure UI", "Unused entities" and "Help". All those options (excepting perhaps "Help") should only be available for admin users.

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Additional information:**

**Comment by iantrich** [comment]
@balloob I think we should block this for non admins for now and if we decide to split out configurations per user in the future we can revisit. Sound good?
