### ISSUE TITLE
Can't login to hassio with iPad on 0.91.3

### ISSUE THREAD

**Issue by ZhuDaHai** [home-assistant/home-assistant-polymer#3092]
Current: Home Assistant 0.91.3
Last Know working version: 0.91.2

Lovelace: 
Mode: yaml
resources: 0
views: 3

IPad iOS : 10.3.3 (latest version for this IPad - no newer versions available)
Safari Browser: Same as iOS version
Edge Browser: 44.1.7

Try to access Hassio either with DNS name or IP address and all that is show is:
"Home Assistant" (with Icon)
"Initializing"

No login screen for Username and Password.

Tried Private Browsing mode as well. Still no joy.
cleared cache, enabled pop-ups, etc: still no joy

Works via IPhone on iOS 12.x w/Safari, and Windows 10 with Chrome and Edge.

Used to work on Hassio 0.91.2 and provide screen for Username and Password on this old IPad. Now it does not.

Trying to re-purpose this IPad into a dedicated stand-alone display for Home Assistant. Would really like it if it worked again.

Thanks.

**Comment by sagilo** [comment]
Can you please try accessing it via ES5 frontend explicitly:
https://<ha address>:8123/states?es5

Also, please make sure you don't set the '[frontend](https://www.home-assistant.io/components/frontend/)' version to _latest_

**Comment by ZhuDaHai** [comment]
frontend was set to 'javascript_version: latest'
disabled that and everything works now!!
It was hiding in a frontend.yaml file of themes I found through one of the YouTube videos. 
Silly me for trusting it.
Thanks!!!!!!!!!!
