### ISSUE TITLE
0.91.3 Streaming fails with variable not defined.

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/home-assistant-polymer#3095]
I'm running Hassio on RP3B+, this issue is repeatable on chrome and safari (osx). My Amcrest camera (defined using Amcrest component) does not work and does not error. However, my three unifi RSTP streams fail with this error.

![image](https://user-images.githubusercontent.com/1020579/56218621-ea75ea80-602a-11e9-98bd-9d0daa2ca5c6.png)
^^ Safari

```
9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1 Uncaught ReferenceError: s is not defined
    at a (9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1)
    at r.addListener (9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1)
    at new t.default (9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1)
    at 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
a @ 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
r.addListener @ 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
t.default @ 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
(anonymous) @ 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
09:30:17.682 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1 Uncaught ReferenceError: s is not defined
    at Object.t.enableLogs (9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1)
    at 9752f203-f8bc-41a9-8dc8-bd73cc3af56f:1
```

My apologies for the crappy stack trace, it's all chrome would give me even when I tried to pretty the stack trace.. Would be nice if you shipped with source maps.

## AmCrest
Errors with `GET http://hassio.local:8123/api/hls/XXXXXXXXXXXXXXXXX/playlist.m3u8 net::ERR_NAME_NOT_RESOLVED`

![image](https://user-images.githubusercontent.com/1020579/56218483-b1d61100-602a-11e9-9da1-6926418e3b43.png)

^^ chrome

**Comment by iantrich** [comment]
still issue?

**Comment by iantrich** [comment]
closing with no response
