### ISSUE TITLE
Add link to HassOS releases

### ISSUE THREAD

**Issue by scop** [home-assistant/home-assistant-polymer#3097]
Would be nice to have a link to https://github.com/home-assistant/hassos/releases in the Hass.io Host system section when an update is available (in addition to the update button). I would add it myself but I'm unsure how this stuff is developed -- surely I'm not supposed to modify these files directly, but a source somewhere else?
```
hassio/api/panel/chunk.a6e3bc73416702354e6d.js
hassio/api/panel/hassio-app.html
```

**Comment by ludeeus** [comment]
Not sure if this is in the current supervisor, but it is in master on the dashboard tab.
![image](https://user-images.githubusercontent.com/15093472/73606055-54558580-45a6-11ea-925d-9aae841a3ccf.png)

This is the same place as the link for HA and the Supervisor are, so I think that is enough.
