### ISSUE TITLE
Reload Lovelace button doesn't work

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3107]
**Home Assistant release with the issue:**
0.91.3

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Description of problem:**
If you mess up and get the parser error message, underneath the error message is a "Reload Lovelace" button which doesn't actually do anything, and seemingly hasn't for a few versions now (I suspect when the 0.88 button switchover occurred). Another user on Discord said he had the same issue.

![image](https://i.imgur.com/kZd8HBP.png)

I had Chrome Inspector open and nothing seemed to be reported there when I clicked the "Reload Lovelace" button. No errors, nothing.

While I'm reporting this, also thought that maybe the button should be changed from `mwc-button` to `mwc-button raised` so that it looks more prominent with a colored background and everything:

![image](https://i.imgur.com/1wBGzRA.png)

**Additional information:**

To reproduce this error just break your config by adding an out of place character like the \ in this example:

```
        \- type: entities
          entities:
            - sun.sun
```

**Comment by davidjb** [comment]
Seeing the same issue with 0.91.4.  Clicking the 'Reload Lovelace' button doesn't issue a network request at all.  A workaround is to just reload the whole browser tab.

**Comment by davidjb** [comment]
Still an issue in 0.104.2.

**Comment by Mariusthvdb** [comment]
just to add this was also reported on the community: https://community.home-assistant.io/t/reload-lovelace-button-does-nothing/148304
