### ISSUE TITLE
No input box when using configurator

### ISSUE THREAD

**Issue by postlund** [home-assistant/home-assistant-polymer#312]
I'm trying to use the configurator to ask for a PIN code, but there is not input box (and the "description" is not shown) so it's not possible to enter anything. Should be possible to reproduce with any component/platform that require user input, e.g. tradfri. I have locally modified the tradfri component to always show the input dialog (since I don't own a gateway) and I ses the same behaviour there as in my code.

This is on dev. Rolling back to 0.47 and doing the same thing works as expected. @armills suggested that it might be related to the polymer 2.0 update.

**Comment by balloob** [comment]
Will push a new frontend build to dev later tonight.

ps which browser did you use?

**Comment by postlund** [comment]
Great, thanks! I tried with the following browsers (all on macOS):
* Chrome 58.0.3029.110
* Firefox 53.0.3
* Safari 10.1

**Comment by balloob** [comment]
The fix is in dev, does it work now ?

**Comment by postlund** [comment]
It seems to work! 👍
