### ISSUE TITLE
Hassio Addon Sidebar Icon remains after toggling off the switch

### ISSUE THREAD

**Issue by lettore** [home-assistant/home-assistant-polymer#3126]
**Home Assistant release with the issue:**

0.92
**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace
**Browser and Operating System:**

Chrome 73 Windows 10
**Description of problem:**

Hassio Addon Sidebar Icon, shortcut for the Ingress page, remains after toggling off the switch in the Hassio addon, I don't see a way to manually remove it.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
You have to restart

**Comment by lettore** [comment]
I have done it many times, from another browser it's correct, so I suppose
is cached in the browser.

Il Ven 26 Apr 2019, 17:53 Ian Richardson <notifications@github.com> ha
scritto:

**Comment by ludeeus** [comment]
Not sure when/where this was fixed, but it works now.
![fixedside](https://user-images.githubusercontent.com/15093472/68544042-286b9f00-03bf-11ea-850b-551dfb8167fa.gif)
