### ISSUE TITLE
Edit Gear/Cog Missing

### ISSUE THREAD

**Issue by tomhoover** [home-assistant/home-assistant-polymer#3142]
**Home Assistant release with the issue:**

0.92.1

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Chrome (MacOS)

**Description of problem:**

Edit gear/cog in upper right hand corner of "more info" panels is not there.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

This appears to be the same as #3051; however, the issue still exists in 0.92.1

**Comment by tomhoover** [comment]
More info: the cog appears on some sensors, but not others.

<img width="368" alt="Screen Shot 2019-05-03 at 6 53 17 PM" src="https://user-images.githubusercontent.com/159040/57170783-e55bbe00-6dd4-11e9-8443-bc562f784047.png">

<img width="368" alt="Screen Shot 2019-05-03 at 6 53 56 PM" src="https://user-images.githubusercontent.com/159040/57170789-ec82cc00-6dd4-11e9-873e-0f6df51b843a.png">

**Comment by iantrich** [comment]
Only if in the entity registry can things be edited from the UI
