### ISSUE TITLE
Some links throughout HA missing target _blank

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3153]
**Home Assistant release with the issue:**
0.92.2

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
There are a handful of links within Home Assistant that are missing `target="_blank"` meaning they take over the users current browser window when clicked on rather than opening in a new window/tab. 

This is inconsistent and unexpected behavior and can cause the user to lose work as I explain below. 

1. First is on the About / dev-info page when you click the large Home Assistant icon in the middle of the screen. All of the other links on the page open in new windows except for this one.
2. Second is the "Learn more about automations" link on the Automations Editor page (`/config/automation`). The following 3 will be when you're editing an automation:
3. "Learn more about triggers" link when editing an automation in the Automation Editor
4. "Learn more about conditions" link when editing an automation in the Automation Editor
5. "Learn more about actions" link when editing an automation in the Automation Editor

Number 3, 4, and 5 are especially bad because if you're in the middle of putting together an automation and then you need help and click those links, it navigates away from your current page and you lose all your progress.

**Comment by robbiet480** [comment]
Fixed via #3154
