### ISSUE TITLE
Custom element cannot displays on Android WebView across different devices

### ISSUE THREAD

**Issue by jerrychong25** [home-assistant/home-assistant-polymer#3186]
Hi all,

I have implemented some custom card in my HA Lovelace, as per following:
```
resources:
  - type: module
    url: /local/compact-custom-header.js?v=1.0.0

```

However, it is not display consistently on Android WebView (Same webview code) across different devices. It could show on  **Nexus 5X (Android 8.1)**, but not on **Redmi 3S Prime (Android 6.0)**, as per screenshot below:
![WhatsApp Image 2019-05-06 at 17 09 12](https://user-images.githubusercontent.com/15714095/57501434-09118d80-731a-11e9-9e55-25041d47a69a.jpeg)

Could advise on how to fix this issue?

Thanks.

**Comment by balloob** [comment]
This will be fixed in 0.93, as we will now feature detect instead of match browser user agent strings to determine which version of JS to ship.

**Comment by jerrychong25** [comment]
> This will be fixed in 0.93, as we will now feature detect instead of match browser user agent strings to determine which version of JS to ship.

Thanks for the updates.

Kindly tag me if this is fixed.

**Comment by jerrychong25** [comment]
@balloob, just to confirm, is this issue already fix?

Thanks.

**Comment by balloob** [comment]
We did ship new feature detection, so try it again?

**Comment by jerrychong25** [comment]
> We did ship new feature detection, so try it again?

@balloob,

Noted on your side have fixed new features.

I have tried again, but it still not working on my Redmi 3S Prime (Android 6.0 Marshmallow), as per screenshot below:
![device-2019-07-08-095828](https://user-images.githubusercontent.com/15714095/60777957-7fd6d580-a167-11e9-958d-cbdb113b2edd.png)

**Comment by balloob** [comment]
If your phone has an old browser version, you will also need a custom header version that supports old browsers. Most custom components don't ship that.

**Comment by jerrychong25** [comment]
> If your phone has an old browser version, you will also need a custom header version that supports old browsers. Most custom components don't ship that.

Noted. 

Any reference links to refer on how to add this custom header version?

Thanks.

**Comment by jerrychong25** [comment]
After upgraded **Android System Webview** to latest version via Google Play Store, it fixes this error.

So this issue can be closed.
