### ISSUE TITLE
Notification on HassOS updates?

### ISSUE THREAD

**Issue by rpitera** [home-assistant/home-assistant-polymer#3189]
Would be great if the hass.io dashboard would notify you of updates like it does with HA and AddOns.  Or is there anyway to create a sensor to show the latest version so an automation could be set up to notify you?  I often find out when there is an update a long time after it is released as I don't always check the system section of the hass.io panel.

**Comment by iantrich** [comment]
You could do it like this:
https://github.com/frenck/home-assistant-config/blob/master/config/automations/system/upgrade_alert.yaml

**Comment by DeviousPenguin** [comment]
> Thanks for a great alternative!

No problem, I guess you could also add the repos for any custom components you are using also.

**Comment by rpitera** [comment]
@iantrich That would work for Hass.IO but I already have that covered.  I'm looking for updates to HassOS itself.  But thanks!

**Comment by iantrich** [comment]
Ah. I totally didn't read properly 😜

**Comment by bramkragten** [comment]
This is done, needs an update of the Hass.io supervisor

**Comment by f00dagi** [comment]
Is there a way to read the current installed version of HassOS?

**Comment by rpitera** [comment]
I do it this way with a command line sensor:

```
- platform: command_line
  command: "cat /config/.HA_VERSION"
  name: Installed Version
```

**Comment by f00dagi** [comment]
But that is HA not HassOS?

**Comment by frenck** [comment]
@f00dagi There is not at this point in time, features for that are planned, but not available yet.
