### ISSUE TITLE
Thermostat component switches to idle on second click on active mode.

### ISSUE THREAD

**Issue by pszafer** [home-assistant/home-assistant-polymer#3195]
**Home Assistant release with the issue:** 0.94.0.dev0

**Last working Home Assistant release (if known):** don't know if it was like this sooner.

**Description of problem:**
I'm developing Bosch thermostat integration.
Climate device support only 2 operation mode: auto, manual.

When clicking on active mode, it is switching to idle. I think it shouldn't do anything if operation is not supported. Demo is not working that way.
![Peek 2019-05-13 18-12](https://user-images.githubusercontent.com/690510/57637042-b7cbfd00-75aa-11e9-9982-af93ddfb7ebd.gif)

**Comment by iantrich** [comment]
This does not appear to be an issues anymore. Let me know if I'm wrong.
