### ISSUE TITLE
Script editor box doesn't scale

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-polymer#3198]
**Home Assistant release with the issue:** 0.93.0
**Last working Home Assistant release (if known):** n/a
**UI (States or Lovelace UI?):** lovelace

**Browser and Operating System:** latest Chrome on WIndows 10

**Description of problem:** box with service details to be sent doesn't scale in UI so long content makes UI scrollable (screenshot):
![image](https://user-images.githubusercontent.com/6303489/57838892-dd811e00-77c5-11e9-88c6-6a62e8d1ed21.png)

**Javascript errors shown in the web inspector (if applicable):** n/a
**Additional information:** n/a

**Comment by iantrich** [comment]
that is intended
