### ISSUE TITLE
How to disale tracker notifications

### ISSUE THREAD

**Issue by iz3man** [home-assistant/home-assistant-polymer#3201]
I want notifications on my iOS enabled, but i don't like to see the non relevant tracker information, that gives me a note everytime someone comes home or leaves.
But i have no idea to disable this.

I'll give a screenshot of what i DON'T want to see anymore. Any help?

![IMG_1345](https://user-images.githubusercontent.com/11553674/57917987-2dc7b100-7896-11e9-8a73-0baba0f49ba5.PNG)

**Comment by iz3man** [comment]
Noone? Or is this the wrong sub forum?

**Comment by iantrich** [comment]
A few things:
1. The issue trackers are not meant to be used for support questions. The Discord forum is a better place for that.
2. Issues are not immediately addressed. We're a group of volunteers who do this in our free time.
3. This is related to the iOS application, not the Home Assistant UI

I suggest you try the [iOS Discord channel](https://discord.gg/Jye3bRG)
