### ISSUE TITLE
Tapping menu items does nothing

### ISSUE THREAD

**Issue by WofWca** [home-assistant/home-assistant-polymer#3202]
**Home Assistant release with the issue:** At least 0.93.1, 0.95.4

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Android, Firefox 66.0.5; Windows 10 Chrome Dev tools

**Description of problem:** Tapping menu items here

![image](https://user-images.githubusercontent.com/39462442/57933457-f38afd80-78ef-11e9-98b3-16de63a753e8.png)

does nothing 9/10 times.

**Javascript errors shown in the web inspector (if applicable):** None
```

```

**Additional information:**
[My HA config](https://github.com/WofWca/my-dacha-server/tree/dev/home/homeassistant/.homeassistant)

**Comment by iantrich** [comment]
Do you happen to have `!include` inside other `!include` files?

**Comment by WofWca** [comment]
Nope.
I've updated the issue description with my config.

**Comment by balloob** [comment]
Please try again with 98, we added a fix for it.

**Comment by WofWca** [comment]
Yep, it's gone.
