### ISSUE TITLE
Script editor not set up with translations

### ISSUE THREAD

**Issue by ottersen** [home-assistant/home-assistant-polymer#3203]
**Home Assistant release with the issue: ** 0.93.1

**Last working Home Assistant release (if known):** N/A

**UI (States or Lovelace UI?):** 
Frontend -> Configuration --> Script editor

**Browser and Operating System:**
hassio on ubuntu

**Description of problem:**
Script editor page is not set up with translations. All other pages under configuration are set up properly (automations/ares/entities/etc).

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
Script editor text is not included in translation file (src/translations/en.json) and text is not on localize.

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/home-assistant-polymer/issues/3429
