### ISSUE TITLE
Potential data loss when editing Lovelace UI in multiple browsers (storage mode)

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant-polymer#3212]
**Home Assistant release with the issue:**
0.93.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome/Chromium on macOS and Linux

**Description of problem:**

When the Lovelace UI is edited in one browser/tab, this isn't updated in any other browsers or tabs until the UI is refreshed. With YAML mode this was possible using the Refresh option in the top right menu. This option is removed when using storage mode, as it will apparently automatically refresh when the UI is edited. However, this only happens for the browser in which it was edited. This can potentially result in data loss, which can be replicated by doing this:

- Open Lovelace UI in two different browsers or in two browser tabs
- Edit UI in the first browser/tab and save changes
- Switch to the second browser/tab and don't refresh the page
- Edit UI and save changes

Since the second browser/tab had not refreshed with the latest Lovelace config, the changes made in the first browser/tab will be lost.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
This is fixed in 0.94
