### ISSUE TITLE
Secondary two-column views are always single column unless active while loading

### ISSUE THREAD

**Issue by TheLastProject** [home-assistant/home-assistant-polymer#3221]
**Home Assistant release with the issue:**

0.93.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Firefox on Fedora Linux & Firefox on macOS Mojave

**Description of problem:**

1. Open Lovelace with multiple views
![Screenshot_2019-05-27 Home Assistant](https://user-images.githubusercontent.com/1885159/58433860-45364380-80b9-11e9-9bcd-b8a2a833daac.png)
2. Switch to a second view and notice how only 1 column is shown
![Screenshot_2019-05-27 Home Assistant(1)](https://user-images.githubusercontent.com/1885159/58433923-7b73c300-80b9-11e9-8f75-0a89c360b160.png)
3. Refresh the page and notice how this second view has 2 columns now
![Screenshot_2019-05-27 Home Assistant(2)](https://user-images.githubusercontent.com/1885159/58433979-baa21400-80b9-11e9-98c5-2219de7a0de5.png)

**Additional information:**
In my tests, the first view was always rendered correctly in 2 columns, even when switching to it, but all other views were rendered in one column unless specifically being the active view while refreshing the browser. It seems like the column count in invisible views get calculated incorrectly. The column count also doesn't change when the view size changes. Although I don't know Polymer, a recalculate/redraw when switching view or when the view size changes should fix this issue in my idea.

**Comment by TheLastProject** [comment]
Hmm, this actually only seems to happen with 2-column views, 3-column views render correctly for me always. I've updated the title.

**Comment by iantrich** [comment]
These views should be rebuilt now when you switch. Is this still an issue?

**Comment by TheLastProject** [comment]
Just tested on Home Assistant 0.99.1 and it indeed seems to behave properly now. Thanks!
