### ISSUE TITLE
Overflow issue causes scrollbars when columns expand in height.

### ISSUE THREAD

**Issue by erikjoens** [home-assistant/home-assistant-polymer#3253]
**Home Assistant release with the issue:** 0.94.0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):** Lovelace UI

**Browser and Operating System:** Chrome 74, Win 10

**Description of problem:**

Scrollbars appear in columns due to `overflow-x: hidden;` on the `.column` class. See screenshot below. Eg. when hovering the history graph and the tooltip appears (since it flows outside the column a scrollbar appears). Removing overflow-x: hidden; on the .column class seems to fix the issue. 

![overflow-issue](https://user-images.githubusercontent.com/4865918/59050399-83d2b780-888a-11e9-925d-c32cef244464.png)

**Javascript errors shown in the web inspector (if applicable):** N/A

**Additional information:**

**Comment by VDRainer** [comment]
Can confirm, FF 67.0.1 on Ubuntu

**Comment by tomraithel** [comment]
I can tackle that one
