### ISSUE TITLE
0.94 config map starts in grey area

### ISSUE THREAD

**Issue by namadori** [home-assistant/home-assistant-polymer#3255]
**Home Assistant release with the issue:** 0.94

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Any

**Description of problem:**

Not a bug, but an usability issue that can be mistaken for a bug.

In the new General configuration interface the map starts middle ocean, the map appears all grey. To understand that it is the actual map and not a visualization error the user needs to zoom out 11 times.

The starting point for the map, if location is not set, should be on an area with some feature to avoid showing an all-gray tile.

**Comment by namadori** [comment]
I think something must be changed in the fitMap method if this.location is not set or is zero, but my knowledge stops here

[https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/map/ha-location-editor.ts#L30](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/map/ha-location-editor.ts#L30)

```javascript
  public fitMap(): void {
    if (!this._leafletMap || !this.location) {
      return;
    }
    this._leafletMap.setView(this.location, this.fitZoom);
}
```

**Comment by AndyRPH** [comment]
It would be nice if it defaulted to center on the city that matches the time zone chosen.
