### ISSUE TITLE
Can't delete more than one entity above the last entity, only opens drop-down menu

### ISSUE THREAD

**Issue by gohassgo** [home-assistant/home-assistant-polymer#3256]
**Home Assistant release with the issue:**
Currently running 0.94.0, but this has been happening for a while.

**Last working Home Assistant release (if known):**
I am not sure that this ever worked.

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Desktop and mobile Chrome
Chrome Version 74.0.3729.169 (Official Build) (64-bit),Windows 10
Chrome Version 74.0.3729.157 on Android Pi, Pixel 2

**Description of problem:**
- When editing a lovelace card via GUI and there are multiple entities, you can delete the last entity by clicking the X on the drop-down menu and then repeat successfully.
- If you delete an entity that is NOT the last entity, trying to delete the next one only opens the dropdown menu and doesn't delete the item.

**Javascript errors shown in the web inspector (if applicable):**
None

I think this happens in every card type that has multiple drop-down menus for entities.

Same issue as reported here for the person editor, which shows a video of problem.
https://github.com/home-assistant/home-assistant-polymer/issues/3077

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/home-assistant-polymer/issues/3077 and updated to indicate for all multiple dropdowns
