### ISSUE TITLE
Brave browser tab crashing when changing light color in circular color picker

### ISSUE THREAD

**Issue by SpiegelenbergT** [home-assistant/home-assistant-polymer#3264]
**Home Assistant release with the issue:**
0.93.1

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Brave (Version 0.65.118 Chromium: 75.0.3770.80 (Official Build) (64-bit)) @ Windows 10 & Brave (Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)) Mac OS 10.14.4

**Description of problem:**

The browser tab crashes when trying to change the color of my LED strips (WS2812B). When selecting a color in the circular color picker (which works in Chrome), the tab hangs and crashes.
![image](https://user-images.githubusercontent.com/4959767/59372100-1077ec80-8d47-11e9-895b-432099cc6910.png)

**Javascript errors shown in the web inspector (if applicable):**
none in console

**Additional information:**
EDIT: at closer inspection, all the modals caused tab crashing, but reaching the homeassistant via host-name instead of via IP fixes the crashes.

**Comment by rando-calrissian** [comment]
Can confirm - also happens in older states UI with Brave on history panels that have the bar state (instead of a graph).  Only happens if addressed via the IP.

**Comment by v3rm0n** [comment]
Same here, thanks for the tip though. I added the IP to the hosts file with a custom name and it works 👍

**Comment by iantrich** [comment]
this sounds like an upstream issue to me
