### ISSUE TITLE
entity-button can't control media_player volume individually

### ISSUE THREAD

**Issue by alexanderpett** [home-assistant/home-assistant-polymer#3270]
**Home Assistant release with the issue:**

0.94.1
**Last working Home Assistant release (if known):**
unknown
**UI (States or Lovelace UI?):**

lovelace
**Browser and Operating System:**

Google chrome and Microsoft edge, 
**Description of problem:**

Create an entity-button, to call media_player.volume_down, up, mute.
Edit: any media control using entity-button is haunted by this bug. 
Button is set to an entity, a LG tv (or any other media_player, with the same result).
Button now controls all media_player entities in home assistant.

If I use dev tool 'call service' from the UI, then media players are controlled individually (as they should)

Therefore I conclude the bug is in lovelace.
![1](https://user-images.githubusercontent.com/44246286/59514341-f233fd00-8ebc-11e9-9fa3-63aee47762dd.PNG)
![2](https://user-images.githubusercontent.com/44246286/59514346-f52eed80-8ebc-11e9-8619-d724c434cfcd.PNG)
![3](https://user-images.githubusercontent.com/44246286/59514358-f6601a80-8ebc-11e9-8eb8-5aa7c2e39227.PNG)

**Javascript errors shown in the web inspector (if applicable):**
```
Don't know how to find this, but there is an error popping up in the UI.
See attatched image above.


```

**Additional information:**
none

**Comment by iantrich** [comment]
You need to specify the `entity_id` in the `service_data`
