### ISSUE TITLE
The icon 'mdi:printer-3d-nozzle' doesn't work in lovelace

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/home-assistant-polymer#3283]
**Home Assistant release with the issue:**

Home Assistant 0.94.3

**Last working Home Assistant release (if known):**
None

**Operating environment (Hass.io/Docker/Windows/etc.):**

Raspbian Stretch

**Component/platform:**

Lovelace

**Description of problem:**
The icon 'mdi:printer-3d-nozzle' doesn't work in lovelace. This icon was added to MDI font a long time ago but still doesn't appear in HA. Please, add the support of actual icon set.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
icon: mdi:printer-3d-nozzle
```

**Traceback (if applicable):**
```
```

**Additional information:**

**Comment by Spirituss** [comment]
Thanks! But how can I update the HA Polymer?

**Comment by SeanPM5** [comment]
> Thanks! But how can I update the HA Polymer?

It'll be in Home Assistant 0.95 which releases in a couple of days (Wed June 26th - you can see the release calendar in the [middle of this page](https://developers.home-assistant.io/)).
