### ISSUE TITLE
Feature Request: picture-entity allow disabling state_filter

### ISSUE THREAD

**Issue by jantman** [home-assistant/home-assistant-polymer#3290]
**Home Assistant release with the issue:** 0.94.4

**Last working Home Assistant release (if known):** Unknown - upgraded from 0.74.2

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Not relevant, but Chrome 74.0 on Arch Linux

**Description of problem:**

I just upgraded HASS and AppDaemon across _many_ versions. After getting the system settled, I was shocked to see a subset of my ZoneMinder security cameras - represented with ``picture-entity`` cards - seemingly switched to night vision mode, because they were appearing in black & white (grayscale). After about fifteen minutes of very confused troubleshooting, I realized that those cameras were all disabled in ZoneMinder, hence had switches in the "off" position... and that, sure enough, there was a CSS style applied to set ``grayscale(100%)`` over the images.

This might be intuitive for folks who are using actual static pictures, but for anyone using ``camera_image`` that's coming from a night-vision-capable camera, the grayscale image feels _very_ unintuitive - and frankly caused me to panic a bit trying to figure out why my cameras had suddenly gone into IR mode in the middle of the day.

Providing some way to disable this for ``picture-entity``, I assume via a ``state_filter`` option, would be greatly appreciated.

**Comment by iantrich** [comment]
I'm adding the `state_filter` configuration to all entity-based picture cards so that you can override the default off state filter.
