### ISSUE TITLE
Upgrade sensor card to latest visuals from mini-graph-card

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#3316]
**Home Assistant release with the issue:**
0.94
**UI (States or Lovelace UI?):**
Lovelace
**Description of problem:**
The sensor card is based on the excellent [mini-graph-card](https://github.com/kalkih/mini-graph-card) by @kalkih. That card has gotten some very sweet visual upgrades that we should adopt in the core.

**Comment by iantrich** [comment]
OR we work on allowing custom cards into our UI editor; making them closer to first-class citizens?

**Comment by bramkragten** [comment]
I think that should be an AND. It would be easy to allow custom cards in the editor, balloob didn't want it yet because it would limit us in changing things later. I guess we could do it now...?

**Comment by balloob** [comment]
Not sure if I understand, can't custom cards already define a method to provide a UI editor ? I also don't think that those two things are related.

**Comment by bramkragten** [comment]
What Ian means is allow it as an option in the pick new card dialog.

**Comment by balloob** [comment]
Ooooh. Yes, we could add tabs to that dialog if custom cards are available to pick .

**Comment by zsarnett** [comment]
#4745 - Adds the fill feature
#4887
#4888 
@balloob are there more features you would like to adopt? I like the column chart type as multiple entities per sensor

**Comment by balloob** [comment]
I think this can be closed as this was about visuals. 

I like both column chart and multiple entities too!
