### ISSUE TITLE
Onboarding.html preloading of JS files not working

### ISSUE THREAD

**Issue by bwmcin** [home-assistant/home-assistant-polymer#3336]
**Home Assistant release with the issue:**

0.95.4, frontend 20190626.0
**Last working Home Assistant release (if known):**
N/A
**UI (States or Lovelace UI?):**

N/A
**Browser and Operating System:**

Windows 10 Pro, Chrome and Firefox;  running in virtual environment, python 3.7.3, using IntelliJ.
**Description of problem:**

onboarding.html is attempting to preload two javascript files (onboarding.fc2086c1.js and hass-icons.12323c6b).  Error is generated by browser stating 'failed to load module script' (see error message below).   It appears the content-type is being set incorrectly somewhere (I poked around but could not trace where this is happening).

 When I modify the html to load the file via a <script> tag, the files load.  I have also been "playing around" with HA 0.91.4 and this problem doesn't exist (the javascript is not being preloaded in this version).

**Javascript errors shown in the web inspector (if applicable):**
```
From console:

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.  onboarding.fc2086c1.js:1 


Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
hass-icons.12324c6b.js:1

from the network tab on chrome developer window:

Response header (for the Request URL: http://localhost:8123/frontend_latest/onboarding.fc2086c1.js) :
Accept-Ranges: bytes
Cache-Control: public, max-age=2678400
Content-Encoding: gzip
Content-Length: 88602
Content-Type: text/plain
Date: Sat, 06 Jul 2019 22:34:54 GMT
Last-Modified: Sat, 06 Jul 2019 21:55:45 GMT
Server: Python/3.7 aiohttp/3.5.4
Vary: Accept-Encoding

```

**Additional information:**

**Comment by balloob** [comment]
Possible that you did onboarding so often that you end up hitting a cached version? Open the Chrome dev tools, disable caching as [per the docs](https://developers.home-assistant.io/docs/en/frontend_development.html#development) and refresh the page. Is it still broken?

**Comment by bwmcin** [comment]
Yes, it is still broken.  Thank you for the reference to the Chrome dev tools to disable caching, as I was having to manually clear the browsing data before each attempt.

**Comment by balloob** [comment]
I am unable to reproduce this.

**Comment by bwmcin** [comment]
for the response for the onboarding.fc2086c1.js, is the response mime type application/javascript?  Right now I'm poking in mimetypes.py to see why it's returning text/plain.

**Comment by bwmcin** [comment]
It appears the content type is unknown for the preload case.  The processing calls the python library mimetypes to "guess" the mimetype.  Upon further investigation into mimetypes.py, the library accesses the windows registry to ascertain the content type.  In my machine, Computer\HKEY_CLASSES_ROOT\.js has content type of text/plain.  I changed it to application/javascript (hopefully didn't break anything in windows, but will see) and things work fine.

**Comment by balloob** [comment]
I think that I have heard about this issue once before. Did some Googling and found this flaks issue (also in Python): https://github.com/pallets/flask/issues/1045#issuecomment-42202749

So it looks like some editors will mess up the Windows registry 😱

**Comment by balloob** [comment]
Opened a PR to fix it on Windows, to help other Windows users with bad mimetype registries.

**Comment by bwmcin** [comment]
Thank you!
