### ISSUE TITLE
Can't scroll in Notifications panel in 0.96b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3366]
**Home Assistant release with the issue:**
0.96.0b1

**Last working Home Assistant release (if known):**
0.95.4

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 75.0.3770.100 (latest stable)

**Description of problem:**
I reported this in Discord a few hours after the first beta was released, stated it was an issue on iOS at the time. I've since encountered the same behavior on the latest Chrome desktop build as well though, so it seems to be a problem in general and not platform-specific.

To reproduce:
1. Visit Services page 
2. Select `persistent_notification.create`
3. Paste this into Service Data field `{"message" : "test notification to check scroll"}`
4. Press "Call Service" button like 7x so there's enough messages to cause a scroll
5. Attempt to read last notification and realize you can't scroll

No scrollbar appears, even though notifications are off-screen and require scrolling in order to view. Mouse scrollwheel (desktop) and swipe gestures (mobile) don't work either. 

Another perhaps easier way to reproduce, if you have the iOS 2.0 beta app, is to just open the Notifications panel and try pull-to-refresh. It won't work.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/3370/commits/09a19d2e7f0812f4c51691adb0c32df2019d91a6
