### ISSUE TITLE
New sidebar in 0.96 does not work well on tablets with no mouse

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/home-assistant-polymer#3381]
**Home Assistant release with the issue:**

0.96

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Problem is in new feature in 0.96

**Browser and Operating System:**

Safari browser on IOS12 on iPad Pro

**Description of problem:**

The new sidebar feature is cool as such but the feature is implemented so it only works well if you use a computer with a mouse that can hover over something.
The feature lacks an alternative for tablets where you use touch. You cannot hover with touch. You can only click.

When you minimize the left bar it stays wide on an iPad. But the main window grows to the left and hides behind the left bar and it is not obvious how the user can get it to shrink. The trick is that the user has to click somewhere on the main windows where there is no UI. 

And in the configurator add-on it is actually difficult to find a place to click on the main window where you can get the bar to shrink because the touch also has another function related to the left bar in the configurator.

When you want to change window by clicking on the left bar the bar grows again and stays wide and then you have to click again in the main window to make it shrink. 
On a PC with a mouse you just move the mouse away. You cannot do that in tablet touch mode 

Overall - on an iPad the hover over feature for the left bar is rather annoying and it would be better if it was not there It would be perfectly fine to simple shrink and grow it by clicking on the hamburger menu at the top of the left bar. 

The actual feature of being able to shrink the left bar is a great enhancement to the iPad experience - especially in functions where the old hamburger menu for closing the left bar was not available. So overall a great thanks for the narrow menu feature. It is just the hover over that is annoying.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
I added a feature to disable the expansion on hover when you click one of the icons directly. But I guess that is not the case if you click next to it . Hmm..

**Comment by balloob** [comment]
Actually, the code should be set up to ignore ANY hover events that come in the same time as a click event.

https://github.com/home-assistant/home-assistant-polymer/blob/4f2b82d7875223cd010b0880b268654451208302/src/components/ha-sidebar.ts#L278-L280

**Comment by KennethLavrsen** [comment]
I have been clicking on my iPad all over the place, on icons, on header, between. No matter where I click the left menu it stays. The only way to cancel the expansion is to click somewhere on the main window. 

This is standard iPad on IOS12. No beta or anything.
