### ISSUE TITLE
HA 0.96 shows blank screen with blue bar in Firefox ESR and Microsoft Edge

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/home-assistant-polymer#3383]
**Home Assistant release with the issue:**

0.96

**Last working Home Assistant release (if known):**

0.95.early   not sure if it workedin .3 or .4. Last time I looked was some weeks ago when I investigated the 12/24 hour problem

**UI (States or Lovelace UI?):**

0.96

**Browser and Operating System:**

Microsoft Edge in Windows 10 updated today on 18 July 2019

**Description of problem:**

When you try to look at HA 0.96 in Microsoft Edge in Windows 10 you get a white screen with a blue bar. No login. No text. No nothing. Totally broken. I asked on the forum and others see the same.

**Javascript errors shown in the web inspector (if applicable):**

I have no drivers license to Edge and debug tools but opening the tool I see no errors or warnings.

```

```

**Additional information:**

There has been some earlier reports of similar where it was just the Lovelace window showing white and blue bar. Now it is the entire thing that is invisible. The earlier bug was marked as an upstream bug. If upstream means Microsoft then it means that it will never get fixed. It is most likely some incompatible feature that you just have to make conditional when using Edge. One thing is to have some artefacts or features that do not work well. But this bug means that you cannot use HA at all in Edge and there will be many users that install hass.io on a Raspberry Pi and try to login on their Windows machine with the default browser and assume that it is HA that does not work at all, so I think it is pretty bad. You will loose many new users that just give up and do not know that it would have worked if they installed Google Chrome and tried looking at their Raspberry Pi IP address again.
And it cannot be that dramatic as it did work in 0.94 earlier versions

**Comment by frenck** [comment]
Just ran a test, Windows 10, Edge 18:

![image](https://user-images.githubusercontent.com/195327/61463217-3f9c0200-a974-11e9-9c44-86c336421102.png)

**Comment by balloob** [comment]
Edge is going to switch to the Chrome rendering engine, already available in edge canary builds. I'm no longer putting any effort in supporting their existing engine.

**Comment by beavis69** [comment]
Hello,
 i got same issue with Firefox-ESR 60.8.0esr (64-bit) on Gnu/Linux Debian 10 amd64  

After update from home-assistant 0.95.4 to 0.96.2 (docker version), web interface shows a blank screen with blue bar at top.

0.95.4 was ok.

0.96.2 works in chromium but not in firefox-esr

Firefox console shows the following warning : 
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing

**Comment by beavis69** [comment]
See attached firefox-esr screenshot
![Screenshot from 2019-07-21 15-40-43](https://user-images.githubusercontent.com/42270266/61592054-33ab7c80-abce-11e9-9af4-77011eee4aa9.png)

**Comment by KennethLavrsen** [comment]
I edited the title to also include Firefox

There must be a basic Javascript bug and not something unique to one browser. I also see many artefacts in Safari where I have to refresh the page to get it to display correctly. There is something rotten and it is not in the state of Denmark

**Comment by balloob** [comment]
We changed the way we do the web components polyfill to avoid a race condition. I guess that went wrong. The issue is here: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/html/_js_base.html.template#L20

**Comment by balloob** [comment]
Firefox ESR 68 was released on July 9, I would suggest you upgrade and have no problems :)

**Comment by beavis69** [comment]
For now 0.60.8 is current version for Debian 10,  https://packages.debian.org/buster/firefox-esr

Are you not supposed to close the script tag  ?
Either with a /> or </script> ?

**Comment by balloob** [comment]
We are. That is a good catch. Let me give it a shot.

**Comment by beavis69** [comment]
Tested 0.96.3 (docker rc) with frontend 20190721.1

I can confirm, it works for me with firefox-esr

Thank you for your support !

**Comment by claudegel** [comment]
I have the same problem with firefox on centos 7  when loading HA from hassbian pi. I've noticed the following error on page loading:
Fail to load element <script> from « blob:http://192.168.2.161:8123/1c1e0681-8d68-440b-8593-a632d390a992 ».
Fail to load element <script> from « http://192.168.2.161:8123/static/polyfills/webcomponents-bundle.js ».
Don't know which html page try to load those script but it look like there is a missing </script> that prevent those two script to load.

I also have that error message:
An unbalanced tree was written using "document.write ()" causing a new analysis of data from the network.
I think the first two have something to do with the blank screen. Not sure for the last one. Messages are translated from french. I hope it is clear enough.

**Comment by beavis69** [comment]
@claudegel, just wait for next release with frontend 20190721.1
this version fixes the unclosed script tag

**Comment by claudegel** [comment]
I hope it will be soon as I can't access my HA and I need to finish the update of my custom component to the new climate component structure. I've only access via my cellphone which is not very efficient to debug changes in custom component.
Thank you for the update

**Comment by balloob** [comment]
couple of hours !

**Comment by claudegel** [comment]
Le Tue, 23 Jul 2019 17:24:33 -0700
Paulus Schoutsen <notifications@github.com> a écrit:

> couple of hours ! 
> 
Home Assistant web site show new update 0.96.4 but
I can't get the 0.96.4 update.

the command: sudo hassbian-config upgrade homeassistant
 return

Collecting homeassistant==0.96.4
  Could not find a version that satisfies the requirement
  homeassistant==0.96.4 

maybe it is too soon ?

Thanks,

-- 
Claude Gélinas

**Comment by claudegel** [comment]
Can't upgrade to 0.96.4 I get the following message:
Collecting homeassistant==0.96.4
  Could not find a version that satisfies the requirement homeassistant==0.96.4
0.96.4 is published on the HA website

**Comment by iantrich** [comment]
Builds take time. Patience ;)

**Comment by claudegel** [comment]
Sorry,
When there is a new HA released, I'm like a children. :))

Claude

**Comment by claudegel** [comment]
Ok done the upgrade to 0.96.4 but still the same. blank screen with blue top line. But it is worst as the page keep reloading. I've catched those error message from firefox debug:
Fail to load http://192.168.2.161:8123/static/polyfills/webcomponents-bundle.js 
Fail to load « blob:http://192.168.2.161:8123/7eb4bff2-79b7-42ce-9f07-d04d2ca8c649 ».
I'm on firefox 60.7.2esr, centos7
