### ISSUE TITLE
Create long lived token creation option missing from profile page

### ISSUE THREAD

**Issue by cornim** [home-assistant/home-assistant-polymer#3396]
**Home Assistant release with the issue:**
0.96.0b1

**Last working Home Assistant release (if known):**
unknown

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Client: firefox on Ubuntu 18.04
Server: Home-Assistant docker image on Rasbian stretch 9.9

**Description of problem:**
The documentation [here](https://developers.home-assistant.io/docs/en/auth_api.html) states that
> Additionally, a long-lived access token can be created using the UI tool located at the bottom of the user's Home Assistant profile page.

But in fact there is no such option at the bottom of the page.

**Comment by SeanPM5** [comment]
Thanks for reporting. This was an issue with the beta, but it's been fixed in the stable release of 0.96 which is out now.

**Comment by cornim** [comment]
Thx for the info. You are correct.
Therefore I'm closing this ticket.
