### ISSUE TITLE
Background color issue on Notifications panel with non-default themes

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3397]
**Home Assistant release with the issue:**
0.96.2

**Last working Home Assistant release (if known):**
0.95.4

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
macOS 10.13.6 / Chrome 75.0.3770.142

**Description of problem:**
0.96 has tweaked the design and moved the notifications to sidebar, and since then it's had a white background. This occurs across all browsers and can be reproduced on 3 of the 4 themes at HA demo website: https://demo.home-assistant.io 

I believe it's the same thing as https://github.com/home-assistant/home-assistant-polymer/pull/3241 from a few weeks ago, where most existing themes have not been updated to the proper variables, so I assume the same fix would probably apply here.

Screenshot of how it looks on iOS app - the cards and everything else are the correct color etc, just not the background:
![bg](https://i.imgur.com/Y45qPcS.jpg)

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/dialogs/notifications/notification-drawer.js

Looks like there is no styling at all applied to it.
