### ISSUE TITLE
Z-Wave panel is not themed correctly when it is the first page loaded by the browser

### ISSUE THREAD

**Issue by joshmcrty** [home-assistant/home-assistant-polymer#340]
I'm running Home Assistant v 0.48.1 via Hassbian v1.23 on a Raspberry Pi 3.

I noticed that the Z-Wave panel is not themed correctly in terms of colors if that is the first page that is loaded by the browser (i.e. if you refresh the browser when on the Z-Wave panel). This carries over if you then navigate to the States panel, the Map panel, or Developer Tools' About, Events, and States panels. If you navigate to any other panel the theme changes to the usual colors.

I also noticed that on the States panel the sensor badges at the top of the screen are not displayed if the Z-Wave panel is the first one loaded.

Here is a GIF of the issue in Chrome 59 (I also experience it in the latest Firefox):

![hass-z-wave-theme-issue](https://user-images.githubusercontent.com/1522068/28240007-c4827a1e-692d-11e7-8366-9e5492faa0d0.gif)

**Comment by andrey-git** [comment]
Sorry for an unrelated question, but how do you make gufs like that?

**Comment by joshmcrty** [comment]
@andrey-git I used [LICEcap](https://www.cockos.com/licecap/) for Windows
