### ISSUE TITLE
No shading under climate graphs

### ISSUE THREAD

**Issue by definitio** [home-assistant/home-assistant-polymer#3423]
**Home Assistant release with the issue:**

0.97.0.dev0

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Chromium 75.0.3770.100 - Manjaro.

**Description of problem:**

The MQTT HVAC hasn't shade under graph. It's not related to `action_topic`, the issue persists when topic isn't set.
![Screenshot_20190725_104312](https://user-images.githubusercontent.com/37266727/61865559-79c15280-aee4-11e9-946f-4f6108ea1fa2.png)
![Screenshot_20190725_104534](https://user-images.githubusercontent.com/37266727/61865561-7a59e900-aee4-11e9-8bdd-af592afe93b0.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/3570
