### ISSUE TITLE
Long press not working on safari 

### ISSUE THREAD

**Issue by mf-social** [home-assistant/home-assistant-polymer#3425]
**Home Assistant release with the issue:** 96.4

**Last working Home Assistant release (if known):** No idea

**UI (States or Lovelace UI?):** lovelace 

**Browser and Operating System:** safari on iPhone 

**Description of problem:**
On my android phone (chrome) when I tap on a light (or anything really) on the lovelace interface it toggles that device, and a long press opens the device page. I've just discovered that the long press doesn't work on my other half's iPhone (she tells me that it never has!). I discovered this because my son just got an iPhone and couldn't get the long press to work. 

Kinda surprised this hasn't already been reported, but couldn't see an open issue. 

**Javascript errors shown in the web inspector (if applicable):**

I don't know ios, nothing is where you expect it to be, so someone will have to tell me how to get this if you need it.

**Comment by iantrich** [comment]
were you on ios 13 beta by chance? This should be resolved now.

**Comment by mf-social** [comment]
@iantrich - Ios 12.4.1 - not working still on both iPhone handsets in this house. 😥

**Comment by iantrich** [comment]
Can you give a specific example of a card where this is failing? Also, have you updated to the latest release yet?

**Comment by mf-social** [comment]
Hi, yeah, this is certainly on a picture elements card, not sure about anything else but can test pretty much anything you like (I just don't know where to look).

I'm on frontend version 20190919.1, homeassistant version 99.3 - both showing as latest.

**Comment by SeanPM5** [comment]
I think the issue might be with iOS behavior - iOS interprets a long press on a picture as the user wanting to save it to their photos app/camera roll, or drag it, or copy it. Which is normally the case, except not here obviously.

You could test this theory by adding a `hold_action` to any other (non-picture) cards like entity button. If long press works on those cards, it's likely a problem with iOS behavior on picture-elements.

**Comment by mf-social** [comment]
I don't have any 'hold_action' in my configuration at all, just tap_action/action: toggle.

Seems the default 'hold_action' should be to open the device page, but this does not work in safari.

Your telling me that in safari a long press on a picture would indicate saving it, surely if that was the case it would be progressing to the next step (save to... Etc), rather in this case it is just not doing anything at all.

**Comment by iantrich** [comment]
should be fixed in 0.105: https://github.com/home-assistant/home-assistant-polymer/pull/4639
