### ISSUE TITLE
hass.io icon hasn't moved down

### ISSUE THREAD

**Issue by rexyiy** [home-assistant/home-assistant-polymer#3426]
**Home Assistant release with the issue:**
0.96.4

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 75.0.3770.142 / Windows 10 May

**Description of problem:**
Thank you for integrating my suggestion #3406! As far as I see this should be integrated in HA version 0.96.4 with frontend version 20190721.1, but no change ...
I deleted all caches, tried incognito and another browser (Edge instead of Chrome - both up2date). The other changes of the new frontend version are visible!

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by bonanitech** [comment]
I noticed the same in Home Assistant 0.97.0 and using Chrome 76.0.3809.100 / macOS 10.14.6
