### ISSUE TITLE
Translate all the strings

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#3429]
All strings that are visible in the UI should be translatable.

Todo:
- [x] Cloud config panel
- [x] User config panel
- [x] Persons config panel
- [x] Script editor
- [x] Advanced mode toggle
- [x] ZHA config panel
- [ ] Days of the week
- [ ] A lot more, in dev we have the language Test that makes it easy to spot untranslated strings

**Comment by iantrich** [comment]
https://github.com/home-assistant/ui-schema/issues/255

**Comment by springstan** [comment]
Would love to help, but I am not sure how the translation workflow works. 
Furthermore, the [developer documentation](https://developers.home-assistant.io/docs/en/internationalization_translation.html) mentions a translation workflow, though the [link ](https://docs.lokalise.co/category/iOzEuQPS53-for-team-leads-and-translators)to that document seems to be broken. Has it been moved to a new location?

**Comment by iantrich** [comment]
That's in reference to doing the actual translation to another language. In terms of development we just need to use `hass.localize(myStringToTranslate);` instead of hard coding strings

**Comment by springstan** [comment]
That is very good to know, thanks @iantrich!

**Comment by springstan** [comment]
Cloud config panel has already been translated #3875

**Comment by springstan** [comment]
@bramkragten what exactly needs to be translated for Days of the Week and where can I find the mentioned language test?

**Comment by bramkragten** [comment]
@springstan the Test language can be found if you run the frontend in dev mode on the profile page at the bottom of the language picker.
![image](https://user-images.githubusercontent.com/5662298/66774216-5f828980-eec1-11e9-99b9-7bca2a50df0f.png)
![image](https://user-images.githubusercontent.com/5662298/66774272-8345cf80-eec1-11e9-8067-07d4639cfd18.png)

**Comment by bramkragten** [comment]
Not sure about the days of the week, there was an issue for it... https://github.com/home-assistant/ui-schema/issues/255

**Comment by springstan** [comment]
@bramkragten thank you very much! Yeah I saw that and could not figure it out either...
@ljmerza do you remember what #2657 was about?

**Comment by ljmerza** [comment]
> @ljmerza do you remember what #2657 was about?

It was for the calendar at the time. Not needed at the moment, but would be a nice to have

**Comment by springstan** [comment]
@ljmerza thanks for the quick answer, it really helps understanding the issue. 
And yeah I agree that would be a nice feature to have.

**Comment by iantrich** [comment]
on that note, @ljmerza, when are you brining calendar card to core 😜

**Comment by ljmerza** [comment]
> on that note, @ljmerza, when are you brining calendar card to core 😜

I wish but it's grown into a monster and a nasty hack just to get momentjs locale working for everyone. Would take a ton of work to get to HA core standards. 

Really, I need days of the week in HA so I don't have to import them in the card anymore ;-)

**Comment by iantrich** [comment]
I have no qualms with us adding days of the week to our translations even if we're not using them currently.

**Comment by springstan** [comment]
@ljmerza are there any specifc files where the days of the week need to be translated? :) I would like to translate them but I am not exactly certain which files I would have to modify.

**Comment by ljmerza** [comment]
@springstan no not currently, they woud be needed if calendar card was added to core.

**Comment by springstan** [comment]
@ljmerza okay, good to know. So Days of the week should probably be removed from this issue.

**Comment by RenzoBeux** [comment]
Hi, could this be translated, or edited with lovelace yaml?
![image](https://user-images.githubusercontent.com/47984043/81221369-1e66d980-8fb9-11ea-92df-942edf2a6ff7.png)
![image](https://user-images.githubusercontent.com/47984043/81221401-29ba0500-8fb9-11ea-9d4f-050d9de46f36.png)

**Comment by bramkragten** [comment]
Don't respond on old closed issues. And yes you can translate that on Lokalise, it is the state of the alarm panel.
