### ISSUE TITLE
Map issues in Safari & HA-App

### ISSUE THREAD

**Issue by nessor** [home-assistant/home-assistant-polymer#345]
I've running a fresh install of HA 0.49.0, installed with the all in one installer. Unfortunately in Safari as well as the HA-iOS App (think they just implemented the safari browser here) the Map looks like a swiss cheese:

![bildschirmfoto 2017-07-17 um 09 59 27](https://user-images.githubusercontent.com/3463261/28259464-ac0873a8-6ad6-11e7-8a8b-c243e46aa547.png)

In Chrome the Maps looks as desired.

**Comment by kirichkov** [comment]
In iOS Safari and Mac Firefox this issue is also present. Map looks properly on 0.48
