### ISSUE TITLE
Lovelace map card dark mode - white flash on load / recenter

### ISSUE THREAD

**Issue by noxhirsch** [home-assistant/home-assistant-polymer#3456]
**Home Assistant release with the issue:**
Current beta

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Up2date Win 10 & Chrome / Android 9 & Chrome

**Description of problem:**
I use the map card in dark mode. Everytime I open the tab/view with the map card or recenter it, the card flashes white. This is especially annonying in a dark environment.
I think that no flash is needed to hide any jumps of the card. If there's no way around the flashing, I think black would be better.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by broyuken** [comment]
Is there a way to control dark mode with an automation? I have a dark theme at night, and light during the day but the map looks bad if it's dark when I have a light theme, or light when I have a dark theme. I would love to switch it with my automation but I can't figure out how to do that.

**Comment by bramkragten** [comment]
@noxhirsch that is probably just the loading of the tiles, you don't see a white map first right, but a grey background?

**Comment by bramkragten** [comment]
@broyuken no, that is not possible yet

**Comment by noxhirsch** [comment]
@broyuken You could make two conditional cards - one with a light map and one with a dark map. Then you can switch an input_boolean to switch the cards

**Comment by noxhirsch** [comment]
@bramkragen: This might be background of the loading cards - it's just one color - not the white map.  Maybe the background behind the cards should be black so that it's dark before loading.

**Comment by broyuken** [comment]
@noxhirsch that’s essentially what I ended up doing, just used the sun.sun as a condition instead. Thanks
