### ISSUE TITLE
History front end broken

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/home-assistant-polymer#347]
Hi,

Ever since .49, it seems like the history on the front end never actually updates to show different states. I originally opened an issue in home assistant (#8550) but maybe it makes more sense here.

**Comment by balloob** [comment]
I don't understand the issue.

When I go to the history panel it all seems to work fine?

**Comment by cmsimike** [comment]
As long as it works for you, then I will close this. Seems like my hass instance is not loading any history at all on startup, not just the front end.

I'll continue debugging in the home-assistant repo.
