### ISSUE TITLE
Cover icon does not respect device_class property

### ISSUE THREAD

**Issue by sebr** [home-assistant/home-assistant-polymer#3473]
**Home Assistant release with the issue:** 0.96.3

**UI (States or Lovelace UI?):** Lovelace UI

**Description of problem:** `Cover` entity icon only respects the `device_class` property if set to `garage`, and otherwise always returns `window`.

**Expected functionality:** Lovelace should return an appropriate icon for other `device_class` values, as defined in the [cover documentation](https://www.home-assistant.io/components/cover)

**Comment by sebr** [comment]
See [`cover_icon.ts`](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/entity/cover_icon.ts):

```ts
  switch (state.attributes.device_class) {
    case "garage":
      return open ? "hass:garage-open" : "hass:garage";
    default:
      return domainIcon("cover", state.state);
  }
```

and [`domain_icon.ts`](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/entity/domain_icon.ts):

```ts
    case "cover":
      return state === "closed" ? "hass:window-closed" : "hass:window-open";
```

I'd be happy to contribute a PR - is following the model in `cover_icon.ts` the appropriate way?

**Comment by balloob** [comment]
Yeah, add it to `cover_icon.ts`.
