### ISSUE TITLE
Cover should not render unsupported feature with visibility:invisible

### ISSUE THREAD

**Issue by sebr** [home-assistant/home-assistant-polymer#3474]
**Home Assistant release with the issue:** 0.96.3
**UI (States or Lovelace UI?):** Lovelace UI
**Description of problem:** Cover ui renders controls for unsupported features with `visibility: hidden` and the UI element still takes up space on the page. To reproduce, create a `Cover` and set the `supported_features` attribute to `3` (which enables up/down but not stop).

<img width="446" alt="Screen Shot 2019-08-10 at 3 50 32 pm" src="https://user-images.githubusercontent.com/81972/62818172-f57afa80-bb86-11e9-82ff-cf67c6d3867c.png">

 Suggested fix is to change the css of [`ha-cover-controls.js`](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/ha-cover-controls.js#L14) to use `display: none`:

```diff
         [invisible] {
-          visibility: hidden !important;
+          display: none;
         }
```
<img width="444" alt="Screen Shot 2019-08-10 at 3 55 27 pm" src="https://user-images.githubusercontent.com/81972/62818188-4db1fc80-bb87-11e9-9369-761991e05c08.png">

**Comment by iantrich** [comment]
@sebr that is intended so that if you have multiple covers of different supported features, their controls still align.

**Comment by Tofandel** [comment]
Quick question, how do you set the supported_features in a cover.mqtt?

I tried in cover.yaml
```
- platform: mqtt
  name: "Garage"
  supported_features: 3
...
```

But it doesn't seem to be a valid option

**Comment by sebr** [comment]
@Tofandel you can set this value by customizing the entity attributes either in the States UI or via the config:

```
homeassistant:
  customize:
    cover.garage_door:
      supported_features: 3
```

![Screen Shot 2019-10-23 at 9 58 34 am](https://user-images.githubusercontent.com/81972/67341559-b3edcf00-f57b-11e9-9b35-15f86b5df706.png)
