### ISSUE TITLE
hassio.local:8123 login user+pass not save-able in Firefox

### ISSUE THREAD

**Issue by YRRK** [home-assistant/home-assistant-polymer#3478]
Dear developers,

On the standard login page http://hassio.local:8123/  the password and username are not save-able in Firefox. A while later after logging in you get a dialogue in the right corner who asks if you want to save it. You can click yes. But Firefox doesn't display the save username and password dialogue afterwards.

Reading the template, I consider this a bug. Since the frontend suggest with the dialogue the username and password should be save-able. Normally Firefox offers to save usernames and password. Wich makes loggin in on a dailybase a lot user friendly...

Latest: Home Assistant 0.97.1
Frontend version: 20190805.0 - latest

Latest: Firefox for Mac 68.0.1 (64-bits) DUTCH
Mac OSX Mojave 10.14.6 (18G87) DUTCH

Thanks if this can be fixed!

**Comment by YRRK** [comment]
Seems my post doesn't go anyware. Will close this in a few day to keep it clean.

**Comment by iantrich** [comment]
There are very few devs with limited time. Doesn't mean issues should be closed.

**Comment by balloob** [comment]
Our dialog to save authentication has nothing to do with saving username/password. It has to do with that you don't have to login again. We are unable to trigger Firefox save login dialog.

**Comment by YRRK** [comment]
Hmm that's a pity, and good to know. Well, I hope someone can put this 'detail' one the 2do list :-)

**Comment by masterwendu** [comment]
Hey I think it's related with this issue: https://github.com/home-assistant/home-assistant-polymer/issues/3133

**Comment by redbar0n** [comment]
> Hey I think it's related with this issue: #3133

No, it's not. That issue is related to filling details into the login form before you log in. Whilst this issue is related to the popup after login, just like this one: https://github.com/home-assistant/frontend/issues/5053
