### ISSUE TITLE
Allow browser to automatically size integrations card

### ISSUE THREAD

**Issue by poldim** [home-assistant/home-assistant-polymer#3479]
@balloob 

Can we change the fixed height integrations page to a dynamic "auto" setting?  This will allow you to see all of the entities for a given device rather than a bunch of short windows where the entities are clipped and require scrolling.
Any downsides to this other than potentially a large card to scroll down on mobile?

https://github.com/home-assistant/home-assistant-polymer/blob/8b93af1b561a5be6f357e956e2e4ea015f5dc160/src/panels/config/integrations/ha-device-card.js#L42

<img width="2116" alt="Home Assistant 2019-08-11 11-26-28" src="https://user-images.githubusercontent.com/16869713/62838019-6673ee00-bc2b-11e9-8c82-f3b3ae7ff2d9.png">

**Comment by iantrich** [comment]
I'm not in favor of this proposal. Perhaps a better indication that there are more entities below.

**Comment by balloob** [comment]
I want to ditch the whole cards layout here. Instead I want a table with all the devices. Clicking on a device will open a new sidebar that has different tabs: 
 - Info
 - Change name / location
 - See related entities
