### ISSUE TITLE
Firefox 60.8.0esr (64-bit) desktop showing mobile version 0.97.2

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/home-assistant-polymer#3483]
**Home Assistant release with the issue:**

0.97.2
**Last working Home Assistant release (if known):**
0.95.4
**UI (States or Lovelace UI?):**

Lovelace
**Browser and Operating System:**

Firefox 60.8.0esr (64-bit) Windows 10
**Description of problem:**

Firefox Desktop is showing mobile page home assistant instead of full screen version

**Javascript errors shown in the web inspector (if applicable):**
```
TypeError: this.toggleAttribute is not a function[Learn More]
```

**Additional information:**

**Comment by balloob** [comment]
![image](https://user-images.githubusercontent.com/1444314/62879941-122b4580-bce1-11e9-8f78-8df4fee9a172.png)

https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute#Browser_compatibility

Okay that is indeed to new of an API. We should stop using it.

**Comment by tyjtyj** [comment]
I think it is more that just toggle issue. it is showing mobile version instead of desktop. Photo below shows both screen on same browser 

![image](https://user-images.githubusercontent.com/5368474/62880617-61fd2180-bd60-11e9-8f19-68618a28f904.png)

**Comment by balloob** [comment]
Nah, that's maintained via CSS which the toggleAttribute controls :)

**Comment by balloob** [comment]
I'm actually a bit surprised that ESR 60.8 is not working. 60.8 should be based on FF 68, and it was introduced in FF 63.

![image](https://user-images.githubusercontent.com/1444314/62893871-5da11c00-bd00-11e9-9c85-c995b3199123.png)

Anyway, we won't use it starting the next release. You can verify that it's fixed in https://dev--home-assistant-demo.netlify.com/

**Comment by tyjtyj** [comment]
it is still there . toggle error does not really matter. More concern about overlapping side panel below
```
TypeError: this.toggleAttribute is not a function[Learn More]
home-assistant-main.ts:117:4
TypeError: this.toggleAttribute is not a function[Learn More]
hui-generic-entity-row.ts:83:6
Error: No Cast API available
cast_manager.ts:163:14


```

Also on chrome 
![image](https://user-images.githubusercontent.com/5368474/62894407-3a698180-bd7f-11e9-9448-8d223770407d.png)

on firefox notice the side panel overlap the right area
![image](https://user-images.githubusercontent.com/5368474/62894492-58cf7d00-bd7f-11e9-9d6d-ee5c69063bb9.png)

**Comment by tyjtyj** [comment]
Both issue gone.....4 minute after i posted. 

Thanks !!!! you guys are great !!!

**Comment by mnoorenberghe** [comment]
> I'm actually a bit surprised that ESR 60.8 is not working. 60.8 should be based on FF 68, and it was introduced in FF 63 ([source](https://www.mozilla.org/en-US/firefox/organizations/)).

I think you're confusing 60.8 with 68.0 the former is based on 60 whereas the latter is based on 68.

**Comment by balloob** [comment]
ah looks like it's the arrow in the docs that is confusing me. You're right. Can't wait for 68 esr :)
