### ISSUE TITLE
Add the full set of MDI icons v.4.0.96

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/home-assistant-polymer#3489]
**Home Assistant release with the issue:**

HASS.io 0.97.2

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Raspbian Buster

**Description of problem:**

Please, add support of the full set of MDi icons v.4.0.96 to Home Assistant. Particularly, the following icons don't work now:

- mdi:hand-heart

- mdi:lungs

- All new weather icons (mdi:moon-first-quarter, mdi:moon-full, mdi:moon-waning-crescent, etc., full list - see mdi tag "weather").

**Javascript errors shown in the web inspector (if applicable):**
```
None
```

**Additional information:**

**Comment by balloob** [comment]
#3490
