### ISSUE TITLE
Replace Google Chart to other chart library to support offline use.

### ISSUE THREAD

**Issue by fanthos** [home-assistant/home-assistant-polymer#349]
Google Chart used by this project will load script from google.com with no offline support. TOS from Google also does not allow offline usage of Chart.
There are some chart library that support offline usage, so I think it should be a good idea to replace the online version with one that supports offline use.

**Comment by balloob** [comment]
I agree.

**Comment by fanthos** [comment]
After some research, I found there are some good charting library.

[Plotly.js](https://plot.ly/javascript/) Powerful charting library based on d3.js.
[Chart.js](http://www.chartjs.org/) Simple library that supports sereval common used types.
[EChart](https://ecomfe.github.io/echarts-doc/public/en/index.html) Another powerful chart.
[c3.js](https://github.com/c3js/c3) Another library based on d3.js.

**Comment by balloob** [comment]
Here are some requirements for a charting library:

 - We should be able to load it async, only load it from the server when we need it
 - It should not be too big/CPU intensive. A lot of people use this on their mobile phones
 - Should support Gantt charts for the timeline and line charts for sensors.

**Comment by fanthos** [comment]
I found that d3.js with 3rd party extension can support Gantt charts. I think combine use Plotly.js(or c3.js) and another smaller library for gantt is an option.

**Comment by bagobones** [comment]
If gathering repquirments is open for comment I personally would like to see less randomness in the on / off binary sensor colour coding.

Currently if you open one sensors timeline red could be on and blue could be off, open another and it is the opposite.

**Comment by fanaticDavid** [comment]
Agreed! And on that same note I would love it if the new chart could respect the `device_class` of binary sensors so they'd show open/closed, detected/clear, moving/stopped, etc...instead of just on/off.

**Comment by bagobones** [comment]
Having more flexible filters on the history page would also be appreciated such as:

- arbitrary start date/time and end date time vs the current fixed days
- filter by name / wild card
- filter by type/class ( quickly see the matching graphs for all motion or temperature sensors for example)
- filter by measurement. (for example view all temperature sensors reporting in a unit or power consumption)

The current history page is very frustrating to use.

**Comment by fanthos** [comment]
I am trying to replace Google Charts with d3.js.
Trying to use hue color encoding for numerical sensor data, but the history data does not have sensor type information.
I think sensor data types should include `binary`, `numeric`, `string`.

**Comment by fanthos** [comment]
Current progress:
![default](https://user-images.githubusercontent.com/1490719/30160572-95d91bc6-93ff-11e7-928e-4ef6a1171a0c.png)
The upper chart is timeline by d3, the other one is Google Charts.
Some features are working in progress.

**Comment by balloob** [comment]
That's awesome @fanthos !

**Comment by fanthos** [comment]
Almost done.
I tried to build this on my device, the chart library increased frontend,html about 450kb, and 120kb gzipped.

**Comment by andrey-git** [comment]
It could be loaded on demand

**Comment by fanthos** [comment]
Thanks, adding the file to `polymer.json` works.
Where should I put the chart HTML file?

**Comment by balloob** [comment]
450 kB 😨 

Is there a way we can cherry-pick the parts of D3 that we need

**Comment by fanthos** [comment]
Tried to use dimple to replace billboard.js, and it cost 200kb with D3.js. I found that dimple is unacceptable slow when loading the chart if the dataset is not small, and has lots of bugs.
D3.js and billboard.js bundled costs 380kb minified, but it performs much better than dimple.

Google Charts using by this project is about 300kb gzipped.

**Comment by fanthos** [comment]
I Opened a PR with current working code
#429

**Comment by balloob** [comment]
I can help with making the chart code be loaded on demand, just like the Google Chart code. We wouldn't want this to have to be loaded before the initial screen can get shown, that makes our app slow.
