### ISSUE TITLE
Lovelace cards not correctly displayed (flexbox issue) with 0.97.2 and Edge

### ISSUE THREAD

**Issue by FDumarey** [home-assistant/home-assistant-polymer#3497]
**Home Assistant release with the issue: 0.97.2**

**Last working Home Assistant release (if known): 0.92**

**UI (States or Lovelace UI?): Lovelace UI**

**Browser and Operating System: Win10 + Edge + IE11**

**Description of problem: since update to 0.97.2 div#view style .hui-root#view includes display: flex. Makes the flexbox too small and parts invisible. I solved this issue by removing the display:flex line in de style sheet**

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information: **

**Comment by balloob** [comment]
We're no longer supporting Edge until Edge based on Chromium has been released. You can try the new edge at https://www.microsoftedgeinsider.com/en-us/
