### ISSUE TITLE
Toggle & labels squashed together in integration options

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#3509]
**Home Assistant release with the issue:**

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/Amsterdam
version | 0.98.0b0
virtualenv | false

**Last working Home Assistant release (if known):** New feature.

**UI (States or Lovelace UI?):**

mode | yaml
-- | --
resources | 10
views | 7

**Browser and Operating System:**

Vivaldi | 2.6.1566.49 (Stable channel) (64-bit)
-- | --
Revision | d126d99a97ff62b9503aa8f44003e70741c4d90f
OS | Mac OS X 10.14.5
JavaScript | V8 7.5.288.30
Flash | 32.0.0.223 /Users/frenck/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.223/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.145 Safari/537.36 Vivaldi/2.6.1566.49

**Description of problem:**

The toggle and labels are a bit smashed together.

![image](https://user-images.githubusercontent.com/195327/63502427-d6a52e00-c4cd-11e9-8d9a-ab2d5bc59267.png)

This screenshot is from configuring the UniFi integration

**Javascript errors shown in the web inspector (if applicable):** n/a

**Additional information:** n/a

**Comment by jcullen86** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/3501

**Comment by balloob** [comment]
I saw it but was not in a position to figure out how to fix it when making the UI :( It has to do with the text taking up more space, squashing the toggle. Will look into it.

**Comment by frenck** [comment]
It is just a minor thing I've noticed, it works flawlessly, which is the important part. :+1:

**Comment by iantrich** [comment]
fixed
![image](https://user-images.githubusercontent.com/1287159/67028375-caee7600-f0d0-11e9-9bbb-513de4a2f89a.png)
being lazy and don't want to track down the PR :stuck_out_tongue_winking_eye:
