### ISSUE TITLE
iOS 13 compatibility - Entity buttons and configure UI not working on iOS 13b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3510]
**Home Assistant release with the issue:** All
**UI (States or Lovelace UI?):** Lovelace
**Browser and Operating System:** Mobile Safari and thus every browser on iOS 13

**Description of problem:**
Before I begin, I am 99% sure these issues are on Apple's side of things, and I'm also fully aware that iOS 13 is currently still in the public beta stage. I have been instructing people to report these issues to Apple using Feedback Assistant for the last several weeks. 

But it seems clear at this point that it's not going to be fixed before the official iOS 13 release in mid-September which is just three weeks away. Majority of iOS users update very quickly and are probably going to blame Home Assistant for not working properly and potentially leave negative reviews for the official iOS app which would be a shame.

There are two main issues:

1) The "3 Dots" menu with Refresh, Unused entities, Configure UI, and Help does not work at all. You can see the menu options but tapping on them does nothing except dismiss the menu. https://github.com/home-assistant/home-assistant-iOS/issues/408

2) Arguably the bigger issue is with entity-buttons registering multiple presses. I can tell you from personal experience this was incredibly frustrating in my Lovelace setup. https://github.com/home-assistant/home-assistant-iOS/issues/431

For number 2 at least, RomRider explained the issue [in the community forum here](https://community.home-assistant.io/t/lovelace-button-card/65981/1933?u=seanm) and shared the workaround he used to fix it in custom button card. (The issue he described might also be the cause of number 1 but I don't know.)

Ideally some kind of (temporary?) workaround like the above could be squeezed into the 0.98 release so that this never becomes an issue for most people (iOS 13 will likely be released before 0.99).

**Comment by balloob** [comment]
Context menu bug also impacts mobile Firefox and has been reported as #3453

The 2nd issue is related to double press, and so I suggest we ask @RomRider to open a PR with his fix.

**Comment by RomRider** [comment]
I can probably PR something in the [long-press-directive.ts](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/common/directives/long-press-directive.ts) file, however the workaround is super ugly and requires a new library ([Bowser](https://github.com/lancedikson/bowser))

This is the code that fixes the issue on button-card: https://github.com/custom-cards/button-card/blob/master/src/long-press.ts#L187-L196

What do you think about this workaround @balloob?

**Comment by balloob** [comment]
We should be able to extract the mobile Safari detection from Bowser without pulling in the whole package. Looks like you can just search user agent for ipod/iphone/ipad https://github.com/lancedikson/bowser/blob/642fd6164f7cbef1198de4029d0e5bf396aae034/src/parser-platforms.js#L101-L106

**Comment by balloob** [comment]
Do we know why the workaround works like it does, and if this workaround could be applied for older browsers and they would continue to work too ?

**Comment by RomRider** [comment]
I can't answer to that, but that's what I saw while I was debugging this issue:
IOS 13 safari sends 4 javascript events when you tap a button:
* touchstart
* touchend
delay like 100 or 200ms (WTF?)
* mousedown (NEW, this creates a second click… that’s why it’s disabled again directly!)
* click

While IOS 12 only sends 3 events when you tap a button:
* touchstart
* touchend
* click

**Comment by balloob** [comment]
Is there any reason why we would even care about touchend/mousedown ? 

CC @thomasloven

**Comment by iantrich** [comment]
I'd be curious to see what happens with a mouse in the new iOS which I assume this was added to support.

**Comment by SeanPM5** [comment]
Tried the demo site on my iOS 13b iPad with a bluetooth mouse, and it exhibits the same behavior with the context menu at least. Can open the menu but can't click any menu items. Screen recording: https://gfycat.com/earnesttiredburro

There are _a lot_ of (I think) new touch-related accessibility settings in iOS 13 though which I suspect might be the reason for those additional javascript events/delays. https://i.imgur.com/4aNRKCw.jpg In that case it's probably not a bug and more of an intentional change.

**Comment by RomRider** [comment]
The tap assistance thingy seems to map with the behavior I've seen.

**Comment by thomasloven** [comment]
If I recall correctly, `touchend` is needed for long-press, because click is only sent on short clicks.
Same for `mousedown`, to know when the press is started.

**Comment by thomasloven** [comment]
Mostly. It varies between computers, iPhones, android devices and windows 10 computers with and without touchscreen.

**Comment by thomasloven** [comment]
I made this to study the behaviors back then.
https://codepen.io/thomasloven/full/xQVwZV
If you click or press and hold it will show you what events are sent.
The right one is tweaked to handle androids contextmenu-behavior.

**Comment by thomasloven** [comment]
Slowly catching up with the discussion here, sorry about the spamming.

From my attempts, you can probably check for "iPhone OS 13_" in the userAgent string, but I'm not sure if that works on ipad, or if the problem even exists on ipad. From what I've read, safari on ipad in ios 13 reports more like safari on macos?

**Comment by SeanPM5** [comment]
The problem does exist on the iPad, and you appear to be right that it does identify as a desktop browser now. Here's what I see from checking user agent online:

iPhone reports as the following:
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1 `

iPad reports as the following:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1`

Both are on iOS 13 beta 8. Not sure whether the official Home Assistant iOS app reports a different user agent or not, wouldn't know how to check that one.

**Comment by nenadmilano** [comment]
Problem with the double tap is still present for me on two iPad Air 2 with iPad OS 13.2.3 and Home Assistant App 2.0 (2019.1). Interesting thing is that i created a Safari PWA out of Home Assistant and there it does not show this behaviour. Home Assistant is 0.102.2 - my iPhone 8 and iPad mini 4 does work properly, just the two ipad airs show this behaviour.

**Comment by thomasloven** [comment]
Please do not comment on closed issues.
Open a new one and include `#3510` somewher in the text if you think it's related.
