### ISSUE TITLE
Config entry dialog submit button disabled on open

### ISSUE THREAD

**Issue by jjlawren** [home-assistant/home-assistant-polymer#3511]
**Home Assistant release with the issue:**

0.98.0.dev0

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

macOS Safari 12.1.2 and Chrome 76.0.3809.100

**Description of problem:**

When opening a config entry dialog with defaults provided, the 'Submit' button is disabled until any parameter is modified. Seen in both standard config flows and config flow options.
![image](https://user-images.githubusercontent.com/1203111/63532544-85e30480-c4d0-11e9-8a2d-471b4ff6540a.png)

**Javascript errors shown in the web inspector (if applicable):**
None observed.

**Additional information:**

Example schema returned which reproduces this behavior:
```
        return self.async_show_form(
            step_id="user",
            data_schema=vol.Schema(
                {
                    vol.Required(
                        CONF_ENABLE_MEDIA_PLAYER,
                        default=self.config_entry.options.get(
                            CONF_ENABLE_MEDIA_PLAYER, True
                        ),
                    ): bool,
                    vol.Required(
                        CONF_ENABLE_SENSOR,
                        default=self.config_entry.options.get(CONF_ENABLE_SENSOR, True),
                    ): bool,
                }
            ),
        )
```

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/ecfbfbf56bf341f5188c561a074bc10d214afa22/src/dialogs/config-flow/step-flow-form.ts#L47-L57

**Comment by balloob** [comment]
I think that the check where we load all defaults is not working correctly: https://github.com/home-assistant/home-assistant-polymer/blob/ecfbfbf56bf341f5188c561a074bc10d214afa22/src/dialogs/config-flow/step-flow-form.ts#L117-L130

This should have picked up all default values, making the required fields work.
