### ISSUE TITLE
Bug - Firefox Unable to Access HASSIO addons iframes

### ISSUE THREAD

**Issue by boojew** [home-assistant/home-assistant-polymer#3531]
Using hass.io (atleast supervisor 180 / hass 0.97.2) anytime trying to access to access an addon, I get "401: Unauthorized". Cache has been cleared and problem also persists in-private browsing. Chrome, edge, etc. dont have the issue. Firefox version 68.0.2. Using "standard" privacy.

Items added using an iframe in configuration.yaml do not have this issue.

**Comment by iantrich** [comment]
still an issue?

**Comment by ludeeus** [comment]
Looks lit it has been solved.
![image](https://user-images.githubusercontent.com/15093472/72662769-71f1ef00-39eb-11ea-98da-45686dc4df7a.png)
