### ISSUE TITLE
Add support for maskable icons 

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#3545]
Home Assistant 0.98

Add support for maskable icons to our `manifest.json`

https://twitter.com/Not_Woods/status/1167081719125684224?s=09

**Comment by iantrich** [comment]
just reading up on these. they sound very cool!

**Comment by balloob** [comment]
Requirements: https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/#article-header-id-1

Tested our favicon-apple-180x180.png from this repo, and it looks like we need some more spacing.

![image](https://user-images.githubusercontent.com/1444314/66602689-80647b00-eb5f-11e9-9b49-30cb889f1004.png)

We should be able to use https://github.com/home-assistant/home-assistant-assets/blob/master/logo.svg with some more blue around it. 

@SeanPM5 since you do mockups sometime, would you be able to help us out with a logo matching maskable icons spec ?

**Comment by SeanPM5** [comment]
Despite doing mockups I'm terrible with graphics stuff, but asked a friend to help. Not sure this is 100% perfect but looks better, and should hopefully meet the requirements?

![maskable](https://i.imgur.com/odoHerm.png)

Here is the revised svg file: http://www.mediafire.com/file/sqfdrx78ye11r5f/logo2.svg/file

**Comment by balloob** [comment]
Perfect 👍 Thanks !

**Comment by bramkragten** [comment]
Actually we don't use `favicon-apple-180x180.png` in our manifest but use `favicon-{size}.png` those seem to do fine masked. Unless we want to drop the drop shadow I think we should just keep using those?

![image](https://user-images.githubusercontent.com/5662298/68575351-2875a880-046c-11ea-8fae-4356228380fb.png)

**Comment by balloob** [comment]
Oh! 

yeah whatever works :)
