### ISSUE TITLE
Add view icons to Move card window (configure UI mode)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3548]
On the left is the "Move card" window in Lovelace configure UI mode. It doesn't have icons for the views. And on the right is the recently released Home Assistant Cast displaying a very similar type of UI but _with_ icons.

![Icons](https://user-images.githubusercontent.com/9065557/64041440-747fa500-cb2d-11e9-8a6a-733900db5d76.jpg)

The icons give it a nicer look, and are more user friendly because you can quickly scan the page without having to read text.

**Comment by balloob** [comment]
👍 

One note: Home Assistant Cast hides the icons if no views have icons.
