### ISSUE TITLE
External authentication is not working

### ISSUE THREAD

**Issue by estevez-dev** [home-assistant/home-assistant-polymer#3575]
**Home Assistant release with the issue:** 0.98.1

**Last working Home Assistant release (if known):** unknown

**UI (States or Lovelace UI?):** both

**Browser and Operating System:** Chrome OS, Chrome 76

**Description of problem:** External authentication is not working. I'm opening web UI with `?external_auth=1` injecting JS in the `head` section of the page. Here is JS code:
```javascript
console.log('Start');
window.externalApp = {};
window.externalApp.getExternalAuth = function(options) {
  var options = JSON.parse(options);
  console.log("external auth callback: "+options.callback);
  if (options && options.callback) {
    console.log("Calling callback: "+options.callback);
    window[options.callback](true, {access_token: "%my_access_token%",expires_in: 1800});
  }
};
``` 
`getExternalAuth` method is called. I'm getting the first and the second output in console, but the I'm getting an error.
I tried to call a callback in different ways:
```javascript
window[options.callback]({access_token: "%my_access_token%",expires_in: 1800});
```
and
```javascript
window[options.callback](true, JSON.stringify({access_token: "%my_access_token%",expires_in: 1800}));
```
No luck.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught (in promise) 1
```

**Additional information:**
So as a workaround I can call a callback with some delay after `getExternalAuth` was called.  This is because getExternalAuth called before Promise object created.

**Comment by balloob** [comment]
That error is the cannot connect error https://github.com/home-assistant/home-assistant-js-websocket/blob/6be6bdb3c31d8757b5e8b2e4614489eab6f97d04/lib/errors.ts#L1

**Comment by estevez-dev** [comment]
Yes, that's what it shows for a user. But all works fine if I'm waiting a bit before resolving the promise. Here is working JS I'm injecting in webview: https://github.com/estevez-dev/ha_client/blob/master/assets/js/externalAuth.js

**Comment by balloob** [comment]
Ah, so you're saying that our callback is not set up in time for when you call it? Or that if you call it too soon, you hit some race condition inside our code ?

**Comment by balloob** [comment]
oh I see the problem, we do indeed not set up the callback in time.

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/external_app/external_auth.ts#L66-L79

We should set the function on `window` first before calling your code.
