### ISSUE TITLE
Checkmark in Services tab dropdown overlaps service text

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3581]
**Home Assistant release with the issue:**
0.98.2

**Description of problem:**
The Services tab in Developer Tools displays a checkmark next to the actively selected Service. It's lacking spacing though and overlaps the text a bit as you can see in this screenshot. 

![checkmark](https://i.imgur.com/WEJUsS7.png)

Note: the "States" tab also displays the same checkmark and doesn't have this problem.

**Comment by balloob** [comment]
Might be fixed by #3571

**Comment by bramkragten** [comment]
#3571 seems to fix that:

![Schermafbeelding 2019-09-03 om 21 39 53](https://user-images.githubusercontent.com/5662298/64203307-6adea000-ce93-11e9-88ae-42d997f6ab2f.png)
