### ISSUE TITLE
Add timer controls to more-info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3594]
**Description of problem:**

There are four Timer services (`timer.cancel`, `timer.finish`, `timer.pause`, `timer.start`) but these are only accessible from Developer Tools -> Services tab currently. 

Not only does it feel a little bit silly having to go to "Developer Tools" to simply cancel a timer, but more importantly the permissions system blocks off that area to regular user accounts. So a non-admin account would have no way of stopping a nap timer if they woke up early for example.

It would be a lot more user friendly if these controls were displayed on the more-info dialog for timers. Here is a mockup:

![timer-moreinfo](https://i.imgur.com/V4ZDF2p.jpg)

**Comment by iantrich** [comment]
They are accessible via the entity row, FYI. 

That being said, having all available at once doesn't make sense. The current state should dictate what is an available option.

**Comment by balloob** [comment]
Correct. Only show what's needed. Wonder if we should have the more info dialog start using entity rows ?? They now use `state-info` but they are no longer really maintained.

**Comment by balloob** [comment]
Heck we might even more that state info into the header and make sure all controls below contain the right ones.
