### ISSUE TITLE
Inconsistent behavior on States page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3602]
**Description of problem:**
On Developer Tools > States, if you click on the hyperlink for an entity ID, it will pre-fill all of the fields with the state and state attributes JSON. A handy feature.

However, if you were to instead select an entity from the "Entity" dropdown it does **not** behave the same way like you would expect. The "State" and "State attribute" fields do not get filled in.

![statespage](https://i.imgur.com/zU830Sr.png)

Because of this, you could select an entity using one method  (by clicking the hyperlink) and then if you want to select a different entity using the dropdown list instead this time, it would still have the old/wrong service attribute JSON data in the textarea.

**Comment by iantrich** [comment]
...stop finding things... :rofl:
