### ISSUE TITLE
Change heading when renaming HA from Lovelace Configure UI mode

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3610]
**Description of problem:**
When you enter Configure UI mode and click the pencil icon to edit the name of your HA installation, the heading simply says "Edit Lovelace" which isn't great and can be confusing to new users.

![name](https://i.imgur.com/T0hN8n3.png)

It should say "Name of your Home Assistant installation" which eliminates any confusion and is also consistent with how it's worded in Configuration > General panel. Mockup:

![image](https://i.imgur.com/ldn07xc.png)

**Comment by balloob** [comment]
It's not actually the name of your Home Assistant installation (that is stored in the core config). This is just the title that is shown at the top of your Lovelace UI. 

I agree a better title is needed.
