### ISSUE TITLE
Change placeholder text of GA secure devices textfield

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3611]
**Description of problem:**
I think that the current UI for the Google Assistant secure devices PIN is not quite as clear as it could be:

![image](https://i.imgur.com/fR3wVxI.png)

It is asking the user to set a pin, but the placeholder text kind of makes it seem like that textfield is disabled at first glance. I think the "Secure devices disabled" placeholder text should be changed to something less confusing that cannot be misinterpreted. 

"Enter a PIN to use secure devices" perhaps?

Also, when you enter the pin, there is no indication that anything happened. You don't really know if your PIN was saved or not because there's no feedback. This seems like a good candidate for #3562

**Comment by SeanPM5** [comment]
Another potential idea would be to show just a toggle by default like:

[ toggle ] **Enable Secure Devices (Doors, Locks, Garage Doors)**

Then when the user toggles that on, underneath the toggle it would show the explanation paragraph and PIN field like it does today. This would keep the card more clean initially as not everyone owns (or wants to use) these devices.

![ga](https://i.imgur.com/asLjfvD.jpg)

**Comment by balloob** [comment]
Secure devices are always on as per Google rules. By not setting a pin, you are not able to control these devices and are redirected to the app to set a pin. You can disable pin control from individual entities, but there is no global toggle.
