### ISSUE TITLE
Toggle Editor is now named {} in UI.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant-polymer#3617]
**Home Assistant release with the issue:** 0.98.x

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** All

**Description of problem:** Toggle Editor button now has shows {} instead of the words 'Toggle Editor'.  Bunch of people on the forums are confused.  I agree with them, it's confusing.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Yeah, we're not saving any real estate really with that change. I think we can be even more explicit:
Show YAML Editor/Show UI Editor

**Comment by SeanPM5** [comment]
I agree with both of you guys, but think it could be further simplified by referring to it as "Visual Editor" and "Code Editor"

I think that is more clear, especially for beginners who might not know the terms "YAML" or "UI" etc.

**Comment by shmooey** [comment]
Hi, I've created a PR #3968 to change the Toggle Editor buton from {} to "Show Code Editor / Show Visual Editor".
Let me know how it is!

**Comment by ctrl50** [comment]
This was a 1 step forward 2 back situation imo. The update that "broke" the
button also messed up the editor. The preview on the editor is broken 50%
of the time now too.. used to work no matter what if the coding was right..
now ill go to edit working code and the preview dissapears.. but its
random. Sometimes it works...

**Comment by iantrich** [comment]
@ctrl50 this is unrelated to button text

**Comment by ctrl50** [comment]
Its related in the fact that the same update caused both issues on the same view. But other than that i know its not the same thing. Lol

**Comment by bramkragten** [comment]
@ctrl50 please create a new issue for that, so we can keep track of them.
