### ISSUE TITLE
Weather card has illegible error text when unavailable

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3620]
**Home Assistant release with the issue:**
0.98.3

**Description of problem:**
This is the same issue as  #2762 from February which @iantrich fixed in most cards. Noticed just now it occurs in Weather card too. So probably the same fix can be applied here.

Default theme looks fine:
![default](https://i.imgur.com/ZitefBz.png)

Same error message is unreadable on dark themes because it uses primary-text-color which is always white on dark themes:
![dark](https://i.imgur.com/0KDfh2w.png)

**Comment by iantrich** [comment]
@SeanPM5 I'm unable to replicate this using the core weather card. An error card is show if the entity is not available for me.

![image](https://user-images.githubusercontent.com/1287159/64308551-46e89080-cf5f-11e9-8901-9f87562fdbea.png)

**Comment by SeanPM5** [comment]
Oh gosh, this is super embarrassing. I use the [animated weather card](https://github.com/bramkragten/weather-card) by @bramkragten and got it mixed up with the core card. Apparently I can't read, sorry for the false alarm. 🤦‍♂ 

```
- type: custom:weather-card
  entity: weather.dark_sky
```

At least I can just copy and paste this issue to his repo now though 😅
