### ISSUE TITLE
Hide header for authenticated webview

### ISSUE THREAD

**Issue by estevez-dev** [home-assistant/home-assistant-polymer#3627]
**Home Assistant release with the issue:** any

**Last working Home Assistant release (if known):** none

**UI (States or Lovelace UI?):** both

**Browser and Operating System:** Android webview

**Description of problem:** When I'm using authenticated webview in my app, I'm providing back navigation and page title with native UI for better user experience and seamless transitions between webview and app. That is why I need an option to hide page header from HA web UI. See screenshots:
![awv01](https://user-images.githubusercontent.com/1819786/64337616-6972bc00-cfe8-11e9-9f11-e1d56dfcec57.png)
![awv02](https://user-images.githubusercontent.com/1819786/64337618-6b3c7f80-cfe8-11e9-828d-210110ba7929.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
I don't want to add that.
