### ISSUE TITLE
Binary sensor show value issue

### ISSUE THREAD

**Issue by KristijanL** [home-assistant/home-assistant-polymer#3648]
**Home Assistant release with the issue:**
 0.99.0.dev20190908 

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox v69.0, Chrome v75.0.3770.142, macOS Mojave
iOS application

**Description of problem:**
binary sensors from ZHA or z-wave have "[%key:state::cover::STATUS%]" instead of just STATUS.

<img width="494" alt="Screenshot 2019-09-08 at 19 19 31" src="https://user-images.githubusercontent.com/977481/64491887-a3a0bf80-d26d-11e9-9aea-5e2e3d507acb.png">

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by balloob** [comment]
Has been fixed
