### ISSUE TITLE
Add card name to Lovelace "Card Configuration" headings

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3658]
**Home Assistant release with the issue:**
0.98.4

**Description of problem:**
The GUI editor for each and every Lovelace card currently has the same exact title/heading of "Card Configuration."  

This can make it easy for users to lose their place, and forget which card they are on. Especially for newer users or demo users who are browsing through all 24 cards in quick succession. These headings should display the name of the card: "Markdown Card Configuration" , "Sensor Card Configuration" and so forth, so that there is never any confusion.

Before and after:

![image](https://i.imgur.com/wNhSvDW.png)
![image](https://i.imgur.com/wMOyVYh.png)

**Comment by balloob** [comment]
And those names should be localized
