### ISSUE TITLE
Lovelace UI no longer displays width correctly on Firefox after 0.98.4 upgrade

### ISSUE THREAD

**Issue by scstraus** [home-assistant/home-assistant-polymer#3660]
**Home Assistant release with the issue:**
0.98.4
**Last working Home Assistant release (if known):**
0.96.3
**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox 69.0 64-bit MacOS
**Description of problem:**
Lovelace now displays many of my tabs as wider than the browser window, with part hanging off the side of the window.. See below:

This is what it displays within the window:
![image](https://user-images.githubusercontent.com/7644023/64495215-5b969280-d297-11e9-97aa-407b34c06a9d.png)
But there's a bunch of cards hanging off the side with a different colored background:
![image](https://user-images.githubusercontent.com/7644023/64495236-97c9f300-d297-11e9-944e-62a73924d621.png)

config is here:

https://github.com/scstraus/home-assistant-config

The tab shown in the screenshot is this one:

https://github.com/scstraus/home-assistant-config/blob/master/lovelace/Tab1_Home.yaml

**Javascript errors shown in the web inspector (if applicable):**

Maybe this?
```
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
```

**Additional information:**
This doesn't occur on Chrome.

**Comment by iantrich** [comment]
Are you using any custom cards for layout? Sharing your config would be useful via hastebin or something

**Comment by scstraus** [comment]
Yes, but I tried disabling all of them on this tab and it didn't help..

Sorry, should have given you my config from the start, it's here:

https://github.com/scstraus/home-assistant-config

The tab shown in the screenshot is this one:

https://github.com/scstraus/home-assistant-config/blob/master/lovelace/Tab1_Home.yaml

**Comment by iantrich** [comment]
Is it just Firefox?

**Comment by scstraus** [comment]
Yep just Firefox. But same issue on 2 different macs so I can reproduce it.

**Comment by hawkeye217** [comment]
Same issue here. Just switched to Firefox from Safari (since Apple killed the amazing uBlock Origin tracking plugin with their latest update) and this was the first thing I noticed when bringing up my HA dashboard.

**Comment by bramkragten** [comment]
Related https://github.com/home-assistant/home-assistant-polymer/issues/3725?

**Comment by scstraus** [comment]
> Related #3725?

I have reverted back to 0.96.3 which still works fine for me, but will be happy to upgrade again to test a fix when it goes GA.

**Comment by bramkragten** [comment]
It will be in the next release 0.100, let me know if it is fixed!

**Comment by scstraus** [comment]
Ok will give it a go. Thanks. Wow 0.100, does that mean we have to get to .999 before version 1.0? ;-)

**Comment by scstraus** [comment]
Traveling this week. Will try to get to it next week.

**Comment by scstraus** [comment]
Hey, so I upgraded to .100.2 and it looks like everything is back to normal. Thanks!!
