### ISSUE TITLE
Alarm Panel card preview in UI Editor doesn't update

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3662]
**Home Assistant release with the issue:**
0.98.4

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
The preview for the "Alarm Panel" card does not update when changing the "Available States". It only updates when changing Entity or changing Name.

On the [demo](https://demo.home-assistant.io/), add the Alarm Panel card, select the Entity, and then add more states (`arm_night` & `arm_custom_bypass`) via the "Available States" dropdown. These are supposed to update the card preview with those buttons, yet nothing happens. If you click the YAML/Code toggle you can see it's not added there either.

Behavior I've noticed:
* If you toggle to YAML / code editor mode, and then delete or add the states that way, it will live update as expected. **So the problem is adding or removing available states in the GUI editor.**
* You can always make it refresh/update by changing the "Name" text field after making a change.
* If you add the extra "Available States" _before_ selecting the entity, it will show those buttons when it generates the initial preview.

**Comment by iantrich** [comment]
Not being near my dev instance at the moment; I assume that on save the changes that were not reflected are not saved as well?

**Comment by SeanPM5** [comment]
It seems to save under one very specific scenarios, but not most of the time. Seems pretty wonky.

If you add the `arm_night`and `arm_custom_bypass` states to a **brand new** alarm panel card, they will not be reflected in the preview nor the code editor (see image below), but they do get saved after you press the Save button and your additions will be visible on the newly created card.

![bug](https://i.imgur.com/hhhCMy1.png)

However if you were then to edit that newly created card, and _remove_ the `arm_night`and `arm_custom_bypass` states using the GUI editor, those changes **do not** get saved. If you remove `arm_night`and `arm_custom_bypass` using the YAML editor instead, those changes do get saved.

Can also test on the [demo](https://demo.home-assistant.io), edit the "Security" card in the top right corner and try to add the two extra available states. They do not show up in the preview nor do they get saved.

**Comment by iantrich** [comment]
derp, should have thought of using the demo site :)

**Comment by SeanPM5** [comment]
Still an issue in 0.104.3
