### ISSUE TITLE
Translation of air_quality is missing in unused devices overview

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-polymer#3667]
**Home Assistant release with the issue:**
0.98.4

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Android Firefox, Linux Firefox

**Description of problem:**

The translation of air_quality domain is missing. This can be seen in the unused devices overview.

I'm not sure if this belongs here. If not, please close the issue. I'll post it somewhere else then.

![Screenshot_20190909-164234~2](https://user-images.githubusercontent.com/15657682/64541129-a957dd00-d321-11e9-988c-c8488a353e2e.png)

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**
None

**Comment by iantrich** [comment]
closing in favor of generic https://github.com/home-assistant/home-assistant-polymer/issues/3429
