### ISSUE TITLE
Config Person view is not translated

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-polymer#3670]
**Home Assistant release with the issue:**
0.98.5

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
All

**Description of problem:**

The text in the config person view is not translated.
![grafik](https://user-images.githubusercontent.com/15657682/64590320-98ea4580-d3a7-11e9-8e21-bf7cca50c8cb.png)

**Javascript errors shown in the web inspector (if applicable):**
None

**Additional information:**

**Comment by Santobert** [comment]
Home Assistant Cloud login page is also not translated:
![grafik](https://user-images.githubusercontent.com/15657682/65241404-baec7200-dae3-11e9-89d2-13c0431eee30.png)

**Comment by iantrich** [comment]
Closing in favor of general https://github.com/home-assistant/home-assistant-polymer/issues/3429
