### ISSUE TITLE
Add controls to Counter more-info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3671]
**Home Assistant release with the issue:**
0.98.5

**Description of problem:**
Right now the more-info dialog for counters is view only. If you want to interact, you have to head to Developer Tools > Services tab (which is inaccessible to regular user accounts).

There are three services that would be very useful to have on more-info dialogs for counters, especially when you are crafting and testing automations. These would be displayed as 3 buttons at the bottom - Increment, Decrement, Reset. These would call the following services for that entity:

`counter.increment`
`counter.decrement`
`counter.reset`

There shouldn't need to be any logic involved, all three buttons would always show.

**Comment by iantrich** [comment]
No reason to reset something already at default, I guess.
