### ISSUE TITLE
Bayesian binary sensor details - strange details view.

### ISSUE THREAD

**Issue by MarekLe** [home-assistant/home-assistant-polymer#3689]
**Home Assistant release with the issue:**
0.98.5

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome v76 Windows 10

**Description of problem:**
Strange details about observations in Bayesian binary sensor. Maybe it is possible to display some info about currently active observations (probability?)?
Look how this looks now:
![image](https://user-images.githubusercontent.com/30925920/64699711-a84fb880-d4a5-11e9-9926-b09138cee92e.png)

**Comment by iantrich** [comment]
I've noticed more and more sensors using this approach of arrays of objects. I'm guilty of it myself in some of my custom components. We should be able to print the objects in a readable format 👍
