### ISSUE TITLE
Paper-dropdown near the bottom of the page leaves a tiny selection area

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#372]
I think the dropdown popout should move up somehow when opened near the bottom. This occurs in every more-info dialog that has a dropdown at the bottom. (fan, climate, media-player, ...)

![image](https://user-images.githubusercontent.com/1193779/28964660-f5826a26-790d-11e7-9610-ea17ac3bf104.png)

**Comment by andrewdolphin** [comment]
This seems to have got worse. I'm now unable to scroll the dropdown box on the climate tab.

**Comment by andrewdolphin** [comment]
![79107729-8ec9-4934-86d5-ebd28287da74](https://user-images.githubusercontent.com/31809425/33347371-8fc132b6-d48a-11e7-8540-eb9c518dd1ac.png)

**Comment by ciotlosm** [comment]
Could this be related to https://github.com/home-assistant/home-assistant-polymer/issues/775 ?

**Comment by NovapaX** [comment]
This should be fixed by now.
If not, please file another issue.
