### ISSUE TITLE
Lovelace frontend not loading on Safari iOS 9.3.5

### ISSUE THREAD

**Issue by esbenr** [home-assistant/home-assistant-polymer#3722]
**Home Assistant release with the issue:**
Home Assistant 0.95.4.

**Last working Home Assistant release (if known):**
Never - not even Home Assistant 0.98.5.

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
safari on iPad iOS 9.3.5.

**Description of problem:**
The lovelace UI doesent load on iOS 9.x. It works fine on devices with iOS 10.x and later.

**Steps to reproduce:**
1) Open your lovelace dashboard on an iPad with iOS 9.3.5.
2) Authentication works and redirects to the correct view.
3) Here the header loads succesfully, but not the views/cards.

[Screenshot here](https://drive.google.com/file/d/1kFGfjWQ5dMtQ4DYh-CTEqGGS7uHFEh5c/view?usp=sharing)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
I have written about this in multiple Facebook groups and other users seem to experience this too.

**Comment by SeanPM5** [comment]
The library that Home Assistant uses no longer supports iOS 9. From the [Polymer browser support overview](https://polymer-library.polymer-project.org/3.0/docs/browsers):

>Polymer 3.x works in the latest two versions of all major browsers: Safari 10+, IE 11+, and the evergreen Chrome, Firefox, and Edge.

I think your only option would be to use a very old version of Home Assistant on your iPad with iOS 9, but then of course you will be missing out on a lot of features, some necessary bug fixes for certain integrations to work, you wouldn't have Lovelace or custom cards, etc.

**Comment by esbenr** [comment]
Thanks, this explains why I can't make it work.
A related question: Do you know if Hassio has a open api to control and read entities? Then I could build my own frontend.

**Comment by iantrich** [comment]
Yes it does and you may want to try Home Panel and/or hadashboard

**Comment by balloob** [comment]
Here is a 50 line example of how to build a UI with streaming data that should work on older browsers https://hass-auth-demo.glitch.me/

**Comment by DeviousPenguin** [comment]
Hi I'm trying the example at https://hass-auth-demo.glitch.me/ on an iOs 9 device, and it gets stuck when you load the page, it shows the HA logo then 'Initializing' text below.

These are the errors in the console:

![Screenshot 2019-09-20 at 01 00 36](https://user-images.githubusercontent.com/11376139/65289369-38df6600-db42-11e9-9e41-1b63ee109201.png)

Is there any way I can just Login using iOs 9? I'm using Tileboard is works with ES5.

**Comment by balloob** [comment]
@DeviousPenguin can you please tell me which paths the files compatibility, hass-icons and authorize are loaded from, `frontend_es5` or `frontend_latest` ? And which version of HA are you on ?

**Comment by DeviousPenguin** [comment]
Hello, sorry for not replying sooner, looking at the 'Network' it looks like the files are being loaded from the `frontend_es5` folder.

- `frontend_es5/compatibility.775e2536.js`
- `frontend_es5/hass-icons.893bbe35.js`
- `frontend_es5/authorize.b0af507b.js`

I'm running the latest HA, v0.99.2, in a VENV on Python 3.7.3. I should mention that I have been able to load and authenticate using this iOs 9 device in past, but it was a while ago, around v0.95.x I think but I don't know the exact version.

**Comment by bramkragten** [comment]
Should be fixed with 0.99.3
