### ISSUE TITLE
Firefox mobile has horizontal scrolling and incorrect menu bar location

### ISSUE THREAD

**Issue by partofthething** [home-assistant/home-assistant-polymer#3725]
**Home Assistant release with the issue:**

0.98.5

**Last working Home Assistant release (if known):**
(not known)
**UI (States or Lovelace UI?):**

Lovelace: Frontend version: 20190828.1 - latest

**Browser and Operating System:**

Firefox mobile 68.1.1 on Android is bad. But in Chromium mobile on the same phone, it works as expected.

**Description of problem:**

In Firefox mobile, the UI is too wide, meaning I have to scroll horizontally to see the actual switches. Notably this tab has somewhat long items in an `input_select`, which may or may not be related. 

![Screenshot_20190915-100315_Firefox](https://user-images.githubusercontent.com/5360219/64925418-22818500-d7a5-11e9-8ee5-530e4945555f.png)

Then, when I do scroll down, the blue menu bar gets offset incorrectly, both vertically and horizontally:
![Screenshot_20190915-100339_Firefox](https://user-images.githubusercontent.com/5360219/64925420-29a89300-d7a5-11e9-8995-fff654abe1b8.png)

On Chromium, it works as expected:

![Screenshot_20190915-102133_Chromium](https://user-images.githubusercontent.com/5360219/64925428-31683780-d7a5-11e9-915a-546726fa1273.png)

**Javascript errors shown in the web inspector (if applicable):**
None found. I tried hooking up USB remote debugging and everything and didn't see any console errors, (though this was the first time I tried doing such remote debugging)

**Additional information:**

**Comment by bramkragten** [comment]
I was unable to replicate this, you mentioned long `input_select` items would you mind sending a screenshot and config of that?

**Comment by balloob** [comment]
I've seen this too in Firefox Preview on Android while at CEDIA. Unable to reproduce it now so not sure where I saw it. Maybe it was our demo set up.

@partofthething please send a screenshot of the full page on desktop so we can see what cards are there . Are you able to replicate it with Firefox on desktop if you go in menu to Tools -> Web Developer -> Response Design Mode?

**Comment by partofthething** [comment]
1. Yes I can replicate the exact issue on desktop using Responsive Design Mode. Sometimes I have to scroll up and down a bit to get it to "go wide".

![Screenshot from 2019-09-18 18-42-18](https://user-images.githubusercontent.com/5360219/65206689-2252e500-da44-11e9-81c4-a29d740e720c.png)

2. Here are all my cards on the front page: 

![Screenshot from 2019-09-18 18-43-53](https://user-images.githubusercontent.com/5360219/65206787-870e3f80-da44-11e9-91a9-d399c6adca2c.png)

I tried deleting that large input select from the lovelace but the issue persisted so I think that's a red herring. 

It also happens on my Automations tab, which has these cards:

![Screenshot from 2019-09-18 18-46-54](https://user-images.githubusercontent.com/5360219/65206874-d2c0e900-da44-11e9-9d02-fea7fee219cd.png)

Once it "goes wonky", most but not all tabs are wonky. Notably my security tab and weather tab are never wonky. They are unique only in that they have no "badges" up on the top. The Automations tab also has no badges, but it gets messed up. Perplexing.

**Comment by partofthething** [comment]
I think I found a pretty consistent way to replicate the messed up title bar in the Firefox Desktop Responsive Design view, given a too-wide view to start with (e.g. with horizontal scrolling, which I always have): You just adjust scroll a little to the right (so you can see the toggle switches) and then adjust the font size to be a little larger (Ctrl+Scroll up on mouse wheel).

I still am not sure what's causing the horizontal scrolling in the first place.

**Comment by bramkragten** [comment]
It will be in the next release 0.100, let me know if it is fixed!

(or could you also replicate it on the demo?)

**Comment by balloob** [comment]
note, the demo has not been fixed yet. So this would be the right moment to try replicating it

**Comment by partofthething** [comment]
Just upgraded. It's all good now. Thanks!
