### ISSUE TITLE
Weather panel not working for OpenWeatherMap since 0.50

### ISSUE THREAD

**Issue by abmantis** [home-assistant/home-assistant-polymer#373]
Previously, for the OpenWeatherMap component, the panel would show a continuous graph with the temperature variations along a week or so, followed by a list of the current weather conditions. 

After the PR #352 , it now appears as the following:
![28947662-f085811c-78a8-11e7-8bd2-869c14095a63](https://user-images.githubusercontent.com/974569/28965171-b2d54226-7907-11e7-9bb2-e1920eea058d.png)

**Comment by balloob** [comment]
The problem is that no one has ever taken ownership of the weather component, driving it to a solid implementation and representation in the UI.

Should it be forecasts? should it be graphs? We need to pick one and stick with it.

In this case the icons are not shown, that's bad. We should also probably limit the forecasts to 7 days. Or maybe drop forecasts completely and move that into the more info card.

**Comment by abmantis** [comment]
@balloob Its not only the icons. The min/max temperatures are wrong (instead of 4 - 17.2 it should be something like 18 - 27). 
I liked the old hour/temp forecast graph :( Would it be too hard to support having both day bars and hourly graph, and specify which to use on the config?
Also, what does "Visual" mean? And 0.53? 

I'm not really into web frontend dev, so I'll probably not able to help much here.

**Comment by balloob** [comment]
We will not support having both in the card.

I do agree that a graph is more visual. If people want exact data, we can move that into the more info card.

We should revert the PR.

Pinging @fanthos so he is in the loop.

**Comment by fanthos** [comment]
I think just replace the table with chart for now. I am trying to replace the table with new chart.
This page is using emoji for weather icon, it shows good on my device.

Just want to make sure the following emoji display correctly on device.
```
"cloudy":"☁️",
"fog":"🌫️",
"hail":"Hail",
"lightning":"🌩️",
"lightning-rainy":"⛈️",
"partlycloudy":"⛅️",
"pouring":"💧️",
"rainy":"🌧️",
"snowy":"🌨️",
"snowy-rainy":"🌨️",
"sunny":"☀️",
"windy":"🌬️",
"windy-variant":"🌬️",
"exceptional":"⭕️"
```

**Comment by fabaff** [comment]
I created the weather categories according the available icons from [Material Design Icons](https://materialdesignicons.com/). The initial idea was to later use those icons to provide an unified user experience for the UI.

Just some background information...

**Comment by fanthos** [comment]
Sounds good.
Emoji is easiest way to show some common icons for now, but it isn't the best way. Icons should works better than emoji in most cases.

**Comment by mjj4791** [comment]
All,

can we make a clear decision on how the weather card is going to look like and stick to that decision?
I have now spent time to adapt the buienradar component to the new card, to discover we are reverting this again...

(see my post in https://github.com/home-assistant/home-assistant-polymer/pull/375)

**Comment by balloob** [comment]
Fixed
