### ISSUE TITLE
Person editor - show message if no device trackers

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3731]
**Home Assistant release with the issue:**
0.99b1

**Description of problem:**
The new user experience could use some work in the Person editor. Here it is instructing me to select a device, when I don't actually have any device trackers inside of Home Assistant yet. 

Instead of asking the user to do the impossible, this should check if `device_tracker` entities = 0 and then display a helpful message guiding the user to the Integrations panel where they can add their very first device. 

Current screen:

![nodevices](https://i.imgur.com/uOQJ50x.png)

Rough idea, wording and design can be better:

![mockup](https://i.imgur.com/lwu8UTb.png)

This same message should probably be added to more-info of Person too. 

Home Assistant creates a new person by default, which will be in an "Unknown" state until the user adds a device. This results in a horrible looking badge that says "UNK" on the auto-generated layout, and the user is given no indication what that's even for or how to fix it. 

I plan to create another issue for the more-info of Person later on, just wanted to post that here before I forget since it's very much related.

**Comment by iantrich** [comment]
I believe this is just our entity picker in general when a domain-filter is applied.
