### ISSUE TITLE
Light card unavailable text cut off when in horizontal stack

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3745]
**Home Assistant release with the issue:**
0.99b03

**Description of problem:**
This is in regards to the new unavailable lights overlay warning thing that @iantrich added in https://github.com/home-assistant/home-assistant-polymer/pull/3549 . 

It looks fine when there's a light card by itself, but if there's two light cards in a horizontal-stack some letters get cut off, see screenshot below. 

Purely a minor visual / styling thing so not a huge deal... But maybe the text could be tweaked to be a little smaller or something?

![image](https://i.imgur.com/63dXpx8.jpg)

**Comment by iantrich** [comment]
Or scale better with the card size

**Comment by iantrich** [comment]
Also, fix your lights :stuck_out_tongue_winking_eye:

**Comment by iantrich** [comment]
I'm tired, so just lowered it to 24px. Should work with 3 cards in a stack on a normal resolution :tada:
