### ISSUE TITLE
Lovelace: Light card dimming slide not shown anymore

### ISSUE THREAD

**Issue by Scrounger** [home-assistant/home-assistant-polymer#3758]
Since the #3542 light card not shown dimming slide anymore.
Think it would be better to add an option like 'show_slider' to the light cards.

**Comment by iantrich** [comment]
better in what sense?

**Comment by Scrounger** [comment]
so the user has the ability to deactivate the slider, if its not a dimm light.

**Comment by iantrich** [comment]
...? if the light doesn't support brightness, the slider is not shown. That's the whole point.

**Comment by iantrich** [comment]
Your dimmers must not be properly integrated. What integration are you using?

**Comment by iantrich** [comment]
Also, what is your `supported_features` for the light on the STATES tab in developer tools?

**Comment by Scrounger** [comment]
ah ok my mistake, i need the attribute supported_features = 1 not supported_brightness = 1.
Now it works, thanks!
