### ISSUE TITLE
Home Assistant Cast does not open camera view

### ISSUE THREAD

**Issue by radovanbauer** [home-assistant/home-assistant-polymer#3760]
**Home Assistant release with the issue:**
0.99.0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Google Home Hub

**Description of problem:**
Home Assistant Cast correctly shows camera stream in picture-glance, but when I click on the camera entity, nothing happens. In regular browser  a large panel opens showing the camera stream.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Dialogues are not supported in cast
