### ISSUE TITLE
Add support of MDI 4.4.95 

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/home-assistant-polymer#3764]
**Home Assistant release with the issue:**

HASSio 0.98.5

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Opera/Chrome/MacOS

**Description of problem:**

Please, add support to HA of the latest MDI icons set - 4.4.95. Great thanks!

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
Iris in 0.99

**Comment by Spirituss** [comment]
@iantrich Thanks! At last it is there!

**Comment by iantrich** [comment]
It's been out only 9 days 🤔
