### ISSUE TITLE
Triggers without text in device automation editor

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-polymer#3765]
**Home Assistant release with the issue:**

0.99.0

**Last working Home Assistant release (if known):** 

None

**UI (States or Lovelace UI?):** 

Lovelace

**Browser and Operating System:**

Firefox / Linux

**Description of problem:**

There are blank fields when selecting a trigger for device automations. 
This can be reproduced as follows:
1. Go to Settings -> Automations -> New Automation
2. Choose Device as type
3. Choose any area as device
4. Try to choose a trigger

This works for all rooms, but for other devices as well.

**Additional information:**
![grafik](https://user-images.githubusercontent.com/15657682/65241918-13703f00-dae5-11e9-98c9-2a38315f5db2.png)

**Comment by bramkragten** [comment]
There are some translations missing in the latest release, they will be part of the next release.
