### ISSUE TITLE
Devices Page Theming

### ISSUE THREAD

**Issue by acordill** [home-assistant/home-assistant-polymer#3772]
**Home Assistant release with the issue:**

0.99.0
**Last working Home Assistant release (if known):**
N/A
**UI (States or Lovelace UI?):**

Lovelace UI
**Browser and Operating System:**

Chrome Version 77.0.3865.75 (Official Build) (64-bit)
**Description of problem:**

New Devices screen does not follow theme.  If on a dark theme the page shows up as all white so you cant see the devices.
![Selection_001](https://user-images.githubusercontent.com/1455624/65285623-06664680-db0b-11e9-8fb9-6a93c335dc4d.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by rpitera** [comment]
Same here, a little better than OP's though:

![Clipboard01](https://user-images.githubusercontent.com/19910294/65286317-1da63380-db0d-11e9-9ad9-4f70a529c893.png)

**Comment by dshokouhi** [comment]
Can you guys try adding this to your theme and see if it fixes it?

https://community.home-assistant.io/t/0-99-withings-device-automations-launch-home-assistant-cast-from-python/137960/98?u=dshokouhi

**Comment by rpitera** [comment]
I just had to add 

`card-background-color: "var(--paper-card-background-color)"`

and then reloaded the theme via a service call and it's working great now; thanks!

**Comment by acordill** [comment]
Worked for me too, just have to let the theme developers know for the future.
