### ISSUE TITLE
UI issue adding discovered devices.

### ISSUE THREAD

**Issue by morozsm** [home-assistant/home-assistant-polymer#3777]
**Home Assistant release with the issue:**
0.99.2

**Last working Home Assistant release (if known):**
0.98.5

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io

**Component/platform:**

**Description of problem:**
When trying to configure discovered integration, clicking `configure` button, nothing happens. The following being added to log:

`2019-09-20 12:11:15 ERROR (MainThread) [frontend.js.latest.201909181] https://hass.msmsoft.com/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:164 Uncaught TypeError: Cannot read property 'item' of undefined`

**Additional information:**
![discovered](https://user-images.githubusercontent.com/4393731/65342315-7c68bd00-dba0-11e9-8000-12f7dc98ee7b.png)
![error](https://user-images.githubusercontent.com/4393731/65342323-7ffc4400-dba0-11e9-800e-9db295f2b8ec.png)

**Comment by bramkragten** [comment]
Please try reloading your UI, this should be fixed.

**Comment by morozsm** [comment]
Thank you. Fixed. I confirm.

**Comment by gnaeser** [comment]
I get the same error and it does not go away when reloading the UI, restarting the server, or restarting the client. Any suggestion on what to do? (Server run in docker.)

**Comment by bramkragten** [comment]
@gnaeser what version of ha are you running? You should update to 0.99.2 or higher.
