### ISSUE TITLE
gui remains initializing in kiosk browser

### ISSUE THREAD

**Issue by RonaldHiemstra** [home-assistant/home-assistant-polymer#3781]
**Home Assistant release with the issue:**
0.99.0 and 0.99.2

**Last working Home Assistant release (if known):**
0.98.?

**UI (States or Lovelace UI?):**
lovelace, but states give the same result

**Browser and Operating System:**
* android version: 6.0.1
* browser: A lightweight browser that relies on the System Webview, for low-end devices, also known as Jelly - comes with LineageOS 13.0
* kiosk app: wallpanel (which I suppose uses the Jelly browser)
* Note: google chrome works fine...

**Description of problem:**

The kiosk app does shows "Initializing" remains in that state
![2019-09-21 15 50 47](https://user-images.githubusercontent.com/17012831/65374297-bca36a80-dc88-11e9-98b9-3ee9e11284ad.jpg)

The default browser only shows the blue navigation bar without any info
![2019-09-21 15 53 16](https://user-images.githubusercontent.com/17012831/65374300-c62cd280-dc88-11e9-9d26-074bfefd5a54.jpg)

**Javascript errors shown in the web inspector (if applicable):**
don't know how to get it :(

**Additional information:**
Similar issue is reported here: https://community.home-assistant.io/t/problem-with-0-99-and-fully-kiosk-fire-tablets

**Comment by lukastillmann** [comment]
I have exactly the same issue on a Fire Tablet 7. Don't know how to debug this or find any more information

**Comment by iantrich** [comment]
@balloob could this be because we removed babel?

**Comment by ccmacaluso** [comment]
This is also happening in fully kiosk when using tablets with the same above reported outdated webviews.

**Comment by DeviousPenguin** [comment]
I'm not using Fully but I get the exact same behaviour on an old iPad with iOs 9.3.5

I'm unable to login due to it just saying 'Initializing'. If this is unrelated however I can post as a seperate issue.

I used to be able to login OK with older versions in the past.

**Comment by bramkragten** [comment]
If someone could get the javascript errors from the console that would be helpful, and if someone could tell what path the js files are loaded from, `frontend_es5` or `frontend_latest`

**Comment by DeviousPenguin** [comment]
Hi @bramkragten my files appear to be loading from the `frontend_es5` folder on my device, I got a screenshot showing the errors in console, hopefully this helps.

![Screenshot 2019-09-20 at 01 00 36](https://user-images.githubusercontent.com/11376139/65380706-95748980-dcd8-11e9-98e6-7cab7648722b.png)

**Comment by balloob** [comment]
I just downloaded the latest frontend release from PyPI and it looks indeed that we're not transpiling things down to ES5. That implies that this flag is not working properly:

https://github.com/home-assistant/home-assistant-polymer/blob/9a92ed31f631307bb74b7220a9ba9a7d0a02413e/build-scripts/webpack.js#L49-L53

**Comment by ccmacaluso** [comment]
Thanks for looking into this balloob! If any of us with the issue can help you test a dev release let us know.

**Comment by balloob** [comment]
Bram and I figured out the cause and Bram is on the case. Will publish a hot fix today/tomorrow when fixed.

**Comment by ccmacaluso** [comment]
Thanks!

**Comment by bramkragten** [comment]
Should be fixed with 0.99.3

**Comment by ccmacaluso** [comment]
Confirmed to be resolved in 0.99.3 for me. Great job guys.

**Comment by N-l1** [comment]
I am on 110.1 and this issue seems to be back?

**Comment by balloob** [comment]
Please open a new issue.
