### ISSUE TITLE
Allow YAML as input for fields that currently require JSON

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#3784]
**Home Assistant release with the issue:** 0.99
All our config is in YAML, yet the frontend is somehow stuck in this JSON world.

Since JSON is a subset of YAML, we should allow all the fields that take in JSON, also take in YAML. This aligns config <> frontend.

- [x] dev tool - services data
- [x] dev tool - state attributes
- [x] dev tool - event data
- [x] automation editor - trigger - event
- [x] automation/script editor - action - service: service data
- [x] automation/script editor - action - event event data

**Comment by frenck** [comment]
Trick question, does this also apply to Hass.io add-on configurations?

**Comment by balloob** [comment]
Ah good one, yes that too.

**Comment by elupus** [comment]
Does this apply to manifest.json ;)

**Comment by frenck** [comment]
@elupus I would say: No.

Mainly because it is "data" and not user "configuration" (which kinda is the goal difference between YAML & JSON).

**Comment by balloob** [comment]
Going to close issue, thanks Bram !
