### ISSUE TITLE
0.99.2 Automation > Device > List showing blank entities

### ISSUE THREAD

**Issue by petemagnusson** [home-assistant/home-assistant-polymer#3785]
**Home Assistant release with the issue:**

0.99.2

**Last working Home Assistant release (if known):**
xxx

**UI (States or Lovelace UI?):**

resources | 3
views | 16

**Browser and Operating System:**

Chrome 76.0.3809.132 (64Bit)
Windows 10 1809

**Description of problem:**

When going in to Automations and selecting Device as Trigger.
The names of the devices aret showing up for allot of them. it looks like there is a break before the name almost. Looking in the "Entity" field, you can see the top of the letters of the selected device.
![Automation_Device](https://user-images.githubusercontent.com/8865134/65385003-7ce08f80-dd29-11e9-8388-cd6d7970a983.png)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by iantrich** [comment]
still an issue?

**Comment by bramkragten** [comment]
Should be fixed
