### ISSUE TITLE
Unused Entiteis not displaying

### ISSUE THREAD

**Issue by Beaker1969** [home-assistant/home-assistant-polymer#3794]
Updated to 0.99.1 and went to the new Unused entities page but all I am getting is ablank white page with some icons on it. If I do a search it appears to wrok but cannot see a thing.
![Unused entities](https://user-images.githubusercontent.com/52863518/65415887-91d32680-ddee-11e9-923d-cb59561b6993.png)

**Comment by bramkragten** [comment]
Your theme misses the variable `--card-background-color`, please add that to your theme.
