### ISSUE TITLE
Additing discovered esphome device is broken

### ISSUE THREAD

**Issue by tribut** [home-assistant/home-assistant-polymer#3795]
**Home Assistant release with the issue:** 0.99.1

**Last working Home Assistant release (if known):** 0.98

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Firefox 69 (Linux)

**Description of problem:** Adding a newly discovered esphome node by going to settings and clicking on configure no longer works. Instead, nothing happens and the error below is logged in the dev tools.
A similiar error appears in the home assistant logs:

    ERROR (MainThread) [frontend.js.latest.201909181] https://MY_DOMAIN/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:141 TypeError: e.model is undefined

**Javascript errors shown in the web inspector (if applicable):**

    TypeError: e.model is undefined
        _continueFlow ha-config-entries-dashboard.ts:170
        handleEvent parts.js:434
        __boundHandleEvent parts.js:400

**Additional information:** Manually adding the device works (by clicking Add > Esphome > "hostname.local" > Submit).

**Comment by bramkragten** [comment]
This is fixed in 0.99.2

**Comment by tribut** [comment]
Thanks. I specifically made sure to check for updates before submitting this bug report, but apparently the docker image is not yet updated.

**Comment by bramkragten** [comment]
The image was release 3 days ago

**Comment by tribut** [comment]
homeassistant/home-assistant:stable still points to 0.99.1

**Comment by bramkragten** [comment]
They where released about the same time, the build of 0.99.2 was done sooner than 0.99.1 maybe?

**Comment by tribut** [comment]
Maybe. I've opened a bug against [hassio-homeassistant](https://github.com/home-assistant/hassio-homeassistant), which I hope is the right place to discuss this.

**Comment by frenck** [comment]
For reference: home-assistant/home-assistant#26764
