### ISSUE TITLE
Missing question mark on prompt when deleting user

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3801]
**Home Assistant release with the issue:**
0.99.2

**Description of problem:**
When deleting a user, there "Are you sure" prompt is missing a question mark at the end. Easy issue for Hacktoberfest.

![delete-user](https://i.imgur.com/ABYxEFr.png)

**Comment by shmooey** [comment]
Hi! I'd like to work on this issue for Hacktoberfest

**Comment by iantrich** [comment]
If you run into issues hit us up on [Discord](https://discord.gg/XVcx2KX)

**Comment by shmooey** [comment]
Hi, after setting everything up unfortunately it looks like someone already fixed this issue: https://github.com/home-assistant/home-assistant-polymer/pull/3869

**Comment by iantrich** [comment]
Well you're setup now, so that's awesome! Take a look at other Hacktoberfest issues. Most are pretty good for newcomers and if a bit too much others always willing to help with suggestions.
