### ISSUE TITLE
Navigation bar broken in Edge

### ISSUE THREAD

**Issue by d1vanloon** [home-assistant/home-assistant-polymer#381]
The navigation bar does not work properly in the Edge browser, often requiring multiple clicks in separate locations to trigger navigation.

Steps to reproduce
=============

1. Open Home Assistant web interface in Edge
2. Click on the hamburger menu
3. Click on any large navigation item (e.g. Configuration)

Observed behavior
=============
The configuration navigation item drops behind the **Developer Tools** text. Navigation does not occur.

Expected behavior
============
Navigation should occur to the Configuration page.

Workaround
=========
After step 3 above, click on the whitespace below the Developer Tools buttons, then click on the blue header to the right of the Configuration text.

Environment
=========
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063
Home Assistant 0.49.1

Illustration
=======
![hass_nav](https://user-images.githubusercontent.com/9598082/29052841-2bc88934-7bb2-11e7-807a-3fbbc0eed002.gif)

**Comment by d1vanloon** [comment]
Also see #307

**Comment by balloob** [comment]
We just upgraded to Polymer 2, might have been fixed. Test if it still persists after the next release.

**Comment by d1vanloon** [comment]
After updating to Home Assistant 0.51.2, the issue is worse: the UI does not appear at all once the page is loaded. A blue bar (what will become the navigation bar) briefly appears at the top of the screen before disappearing.

**Comment by balloob** [comment]
Please provide the errors in the JavaScript console, if any.

**Comment by d1vanloon** [comment]
Whatever is going on seems to crash the JavaScript console in Edge. I haven't been able to get it to load when viewing Home Assistant.

**Comment by dnperfors** [comment]
I was able to get some error message when loading Home Assistant in Edge:
```
SCRIPT5007: Unable to get property '__catchall' of undefined or null reference
webcomponents-lite.js (134,346)
```
I am not sure if this error is causing this problem or not...

**Comment by d1vanloon** [comment]
I was able to get the console to load and display this error:

`SCRIPT438: Object doesn't support property or method 'byKey'`

In this dynamic code block:

`!function(){"use strict";var n=0,e=0,i=[],t=0,o=document.createTextNode("");new window.MutationObserver(function(){for(var n=i.length,t=0;t<n;t++){var o=i[t];if(o)try{o()}catch(n){setTimeout(function(){throw n})}}i.splice(0,n),e+=n}).observe(o,{characterData:!0}),Polymer.Async={timeOut:{after:function(n){return{run:function(e){return setTimeout(e,n)},cancel:window.clearTimeout.bind(window)}},run:window.setTimeout.bind(window),cancel:window.clearTimeout.bind(window)},animationFrame:{run:window.requestAnimationFrame.bind(window),cancel:window.cancelAnimationFrame.bind(window)},idlePeriod:{run:function(n){return window.requestIdleCallback?window.requestIdleCallback(n):window.setTimeout(n,16)},cancel:function(n){window.cancelIdleCallback?window.cancelIdleCallback(n):window.clearTimeout(n)}},microTask:{run:function(e){return o.textContent=t++,i.push(e),n++},cancel:function(n){var t=n-e;if(t>=0){if(!i[t])throw new Error("invalid async handle: "+n);i[t]=null}}}}}();`

I will try updating Home Assistant (as I see an update is available) and test again.

**Comment by balloob** [comment]
This has been fixed by https://github.com/home-assistant/home-assistant/pull/9438
