### ISSUE TITLE
Unused entities blank with dark background/theme

### ISSUE THREAD

**Issue by msuguy71** [home-assistant/home-assistant-polymer#3814]
**Home Assistant release with the issue:**
0.99.3, 0.99.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Worked prior to change in how unused entities page was displayed

**Browser and Operating System:**

Windows 10 Version 1903 Build 18362.356
Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Description of problem:**

Unused entities page is blank when using dark background/theme.  Unused entities page will work when changing back to default theme.
![Capture](https://user-images.githubusercontent.com/7312961/65717581-b68a0100-e06f-11e9-8dda-595764c17a5e.JPG)
![Capture1](https://user-images.githubusercontent.com/7312961/65718180-04ebcf80-e071-11e9-9a9a-7373427cc4c0.JPG)

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
Your theme uses the wrong variables.

Add the variable `card-background-color` to your theme.
