### ISSUE TITLE
Italian states translation on "Alarm Panel Card"

### ISSUE THREAD

**Issue by mike829** [home-assistant/home-assistant-polymer#3817]
Home Assistant release with the issue: 0.99.3

Lovelace UI

Browser and Operating System: CHROME & Hassio Raspberry pi3 b+

Description of problem:
States translation issue on alarm component "Alarm Panel Card".
![alarm_states](https://user-images.githubusercontent.com/54367803/65754197-cf96be80-e110-11e9-8f1d-3ef632c625de.png)
 
I set Italian language but it seems the alarm states remaining in english.

There is also a translation issue on the code input "Alarm Code" in Italian should be "Codice Allarme"

**Comment by iantrich** [comment]
Needs general localization, not just Italian.
Closing in favor of generic https://github.com/home-assistant/home-assistant-polymer/issues/3429
