### ISSUE TITLE
Theme support in Hassio dialogs

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3821]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
The dialogs inside Hassio panel do not currently seem to respect the users theme choice. 

To reproduce, use a non-default community theme and then visit any of the following areas:
1. "Changelog" link in add-on details page
2. The info badges on add-on details page (security rating, apparmor, etc)
3. "Hardware" button on System tab
4. "Available snapshots" dialogs

All of them will show up white (default theme) rather than using your themes colors, as you can see in this picture below:

![hassio-themes](https://i.imgur.com/5PEN44E.png)

**Comment by bramkragten** [comment]
Fixed! https://github.com/home-assistant/home-assistant-polymer/pull/4758
