### ISSUE TITLE
Adjust CSS on System Options dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3823]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
There should be a little bit more spacing between the toggle and the text on the System Options dialog. You can find this dialog in the top right corner of Integrations page after clicking through to a device (aka device details).

It's so close that it's practically touching on desktop (Chrome):
![desktop](https://i.imgur.com/Ypb76EN.png)

And on mobile devices (iPhone 11 Pro here) the toggle switch is overlapping the first word:
![mobile](https://i.imgur.com/4ZY9ABU.jpg)

Maybe the toggle switch would be better positioned on the right instead? Then the text on the left would line up and the text could use more of the card width. The user is going to read the option anyway before performing a toggle.

Probably an easy one for Hacktoberfest.

**Comment by cgarwood** [comment]
Looks like this has been fixed already? Looks fine on my system (Chrome):

![image](https://user-images.githubusercontent.com/7545841/66145309-9068e180-e5d8-11e9-9fc2-fe998beb9156.png)

**Comment by iantrich** [comment]
Yeah, bram did put out a change for this. https://github.com/home-assistant/home-assistant-polymer/pull/3842

**Comment by SeanPM5** [comment]
Although it did fix this particular issue, it kinda introduced another one?

The "Enable newly added entities" title is no longer on its own line. Makes that prompt look like one paragraph of text rather than an option and descriptive text.

**Comment by bramkragten** [comment]
![image](https://user-images.githubusercontent.com/5662298/66155595-528fab80-e620-11e9-92b6-f67511494d8c.png)
