### ISSUE TITLE
Remove redundant text in Cloud panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3824]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
The Alexa and Google Assistant cards in Cloud panel contain some redundant text (red rectangles in pic below). You can see where the arrows are pointing that this information is already mentioned above.

![cloud-panel](https://i.imgur.com/dORP5PV.png)

The italicized text in the red rectangles should be removed to clean up the cards a little, unless there are any objections? This would be an easy one for Hacktoberfest.

**Comment by shmooey** [comment]
Hey! It looks like I can do this issue :)
