### ISSUE TITLE
mdc-data-table background color

### ISSUE THREAD

**Issue by Strixx76** [home-assistant/home-assistant-polymer#3826]
**Home Assistant release with the issue:**
0.99.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
All

**Description of problem:**
Background color for the mdc-data-table seems to be set to white (#ffffff), and not inherited. But text-colors are.
This makes the table unreadable when you use a theme with dark background and white text.

**Javascript errors shown in the web inspector (if applicable):**
```
N/A
```

**Additional information:**

**Comment by SeanPM5** [comment]
The unused entities page uses a variable `ha-card-background` which most older community themes do not have defined, and so it falls back to the color from the default theme (white) in that case. 

Add this line to your theme(s) and restart, and you should be good:

`card-background-color: "var(--paper-card-background-color)"`

**Comment by Strixx76** [comment]
Thanks!

That did the trick.
