### ISSUE TITLE
History graph in more-info doesn't expand in Firefox

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#3827]
**Home Assistant release with the issue:**
0.99.3

**Last working Home Assistant release (if known):**
Not sure, and to lazy to downgrade. :-)

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox 69.0.1 on Ubuntu 18.04 

**Description of problem:**
Clicking on the Header of a more-info dialog doesn't expand the graph in Firefox.
![20190930_13:52:13_001](https://user-images.githubusercontent.com/26381449/65877031-f6f8c000-e38a-11e9-8431-83e160c7376e.png)

in Chrome, it works.
![20190930_13:52:59_001](https://user-images.githubusercontent.com/26381449/65877172-42ab6980-e38b-11e9-8abb-c79cfc337442.png)

**Comment by R0nd** [comment]
Unable to reproduce (Firefox 70.0, HA 0.100.1)
![image](https://user-images.githubusercontent.com/12497155/67638897-c446d680-f8fa-11e9-9aa0-0e2e81c250d0.png)

**Comment by VDRainer** [comment]
Yeah, seems like it's fixed.
FF 70.0, HA 0.101.0b2
Thanks for the hint.
