### ISSUE TITLE
Remove "pick script to edit" heading on Script Panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3829]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
![heading](https://i.imgur.com/cdq8NVg.png)

The "Pick script to edit" heading has been around since Script Editor was first introduced, but I think it's time to get rid of it. There are a couple of reasons why:

1. YAML users cannot edit scripts, so this heading combined with the issue https://github.com/home-assistant/home-assistant-polymer/issues/3563 (edit pencil icons not being disabled) causes confusion.
2. You can create scripts from here too
3. You can run scripts from here too
4. No other panel contains a heading like this, so it's inconsistent

Would be a good issue for Hacktoberfest I think.

**Comment by tomraithel** [comment]
I would take care of that
