### ISSUE TITLE
Cannot load UI on older iOS devices

### ISSUE THREAD

**Issue by trimethia** [home-assistant/home-assistant-polymer#3830]
**Home Assistant release with the issue:**
~0.99.3~ 0.99

**Last working Home Assistant release (if known):**
~0.84 (found this issue after updating from 0.84 to 0.99.3)~ 0.98.5 is the most recent one working

**Operating environment (Hass.io/Docker/Windows/etc.):**
HA running on Raspberry Pi, Hassbian
Client using iPhone 6s running iOS 10.3.3

**Description of problem:**
Found some UI issues (see screenshots below) when displaying 0.99.3 HA with Safari on iOS 10.3.3. Loading screen after log-in gets stuck loading forever and dashboard does not show at all. Left side menu seems to work but styles seem messed up. Login UI displays fine and I can log in with no issues.

![IMG_1211](https://user-images.githubusercontent.com/16490054/65890153-68f9f500-e3dd-11e9-8e8e-8fef3aabe37e.PNG)
![IMG_1212](https://user-images.githubusercontent.com/16490054/65890154-68f9f500-e3dd-11e9-9ef6-e129fcff476f.PNG)
![IMG_1213](https://user-images.githubusercontent.com/16490054/65890157-69928b80-e3dd-11e9-9129-71fcfcd60093.PNG)

**Additional information:**
Not using lovelace, only default states UI.

**Comment by jojitb** [comment]
same issue. ipad2 with safari

**Comment by trimethia** [comment]
Just downgraded to 0.98.5 and UI works perfectly fine in older iOS devices.
I believe some change in 0.99 is breaking the UI in such devices.

**Comment by bramkragten** [comment]
Do you have errors in the console?

**Comment by trimethia** [comment]
@bramkragten Just updated again to 0.99.3 and checked the output of web inspector for my iOS device using a mac.

When opening the states page I get the following console errors:

<img width="1027" alt="Screen Shot 2019-10-04 at 9 32 33" src="https://user-images.githubusercontent.com/16490054/66173297-6c65d880-e68a-11e9-991a-73c7f2e700bb.png">

When opening the configuration page, I get the following errors:

<img width="1024" alt="Screen Shot 2019-10-04 at 9 33 24" src="https://user-images.githubusercontent.com/16490054/66173311-830c2f80-e68a-11e9-8f69-29da01f4a6fd.png">
