### ISSUE TITLE
Adjust CSS for help icon in Z-Wave panel on mobile devices

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3834]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
The help icon in the Z-Wave panel overlaps the heading on mobile devices (screenshot from an iPhone 11 Pro). 

Not a huge deal since the icon can still be tapped and is fully functional - but stuff like this does makes the UI look and feel a little unpolished. Maybe someone can fix it as part of Hacktoberfest?

![zwave-panel](https://i.imgur.com/DefvpEX.jpg)

**Comment by iantrich** [comment]
Not sure what the best option is, but that heading may be even longer in some localizations

**Comment by bramkragten** [comment]
It should wrap to the next line if the header is even longer.
