### ISSUE TITLE
weblinks are opening new tabs by duplicate when clicking the text link

### ISSUE THREAD

**Issue by azogue** [home-assistant/home-assistant-polymer#388]
With **v.0.51.1**, in **Safari for macOS** and **Chrome**, when clicking on a `weblink`, it opens 2 tabs. It should be only one ;-)

**The problem is appearing only when clicking the text link, when clicking around (in the entity card) there is no problem**

**Comment by azogue** [comment]
This is happening when clicking the link. If you press around it (in the card), it opens only one window.

Not a JS guy, but this old code now it's failing, isn't it?
```javascript
onTap: function (ev) {
    ev.stopPropagation();
    if (ev.target === this.$.link) {
      // Only open window if we clicked on card but not the link
      return;
    }
    window.open(this.stateObj.state, '_blank');
  },
```

**Comment by fanaticDavid** [comment]
This issue already existed prior to 0.51.x : home-assistant/home-assistant#7257

**Comment by azogue** [comment]
wow, it's old!, but I would have sworn that it worked properly in 0.49, at least for me, and in Safari...

I'm not closing this for now, because I think the issue is here, but I could be wrong. I'll edit the title anyway. Thanks @fanaticDavid!

**Comment by azogue** [comment]
As I'm seeing after adding some `console.log()` points in `src/state-summary/state-card-weblink.html`, when clicking the link (`<a href$='[[stateObj.state]]' target='_blank' class='name' id='link'>[[computeStateName(stateObj)]]</a>`), **the received event in the `onTab` function is the same as when clicking the icon or in the card space**, so the condition `if (ev.target === this.$.link)` is never true, and so, **two windows are opened** (one for the click in the link and the other one for clicking the card).

First idea to fix this is setting **`href='#'`**, or even substituting the link for a simple `<span>` tag. 

@balloob, what's the best way to fix this? I can make a PR with your instructions.

**Comment by balloob** [comment]
I think that we should be able to call `ev.preventDefault()` to stop the link from opening. Don't have to check if it's the link at all.

**Comment by azogue** [comment]
Adding a simple `on-tap="onTap"` attribute to the `<a>` link fixes it, I'm testing it now
(forget about the bad ideas from above)

**Comment by azogue** [comment]
@balloob, your solution also works ;-)

If calling `ev.preventDefault();` after `ev.stopPropagation();`, only one window opens.

But that way, the old code is not necessary, is it? `onTap` could be simply:
```javascript
onTap: function (ev) {
    ev.stopPropagation();
    ev.preventDefault();
    window.open(this.stateObj.state, '_blank');
  },
```
So, what solution do you prefer for the PR?
