### ISSUE TITLE
Support globbing in excluded_entities

### ISSUE THREAD

**Issue by postlund** [home-assistant/home-assistant-polymer#3887]
I would like to keep my "Unused entities" as clean as possible, but it is know cluttered with various automations, scripts and other things that i will never add to the UI. So I would like to ignore them. Since especially scripts and automations will vary over time depending on what I do, it would be convenient if I could remove them with a wildcard (or at least exclude domains).

**Comment by iantrich** [comment]
I don't see this being all that useful to spend time on especially with the unused redesign. As thomas noted, this is a view that is likely not viewed all that often
