### ISSUE TITLE
Thermostat Card showing <null> when ECO mode is on

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant-polymer#3889]
Hello,
the thermostat card shows `null` string (instead of `blank`) when my Nest Learning Thermostat is in ECO mode (because home away).

This climate entity `state` is **eco** and state attributes are:
```
current_temperature: 18
min_temp: 9
max_temp: 32
temperature: null
operation_mode: eco
operation_list: off,heat,eco
away_mode: on
friendly_name: Family Room
supported_features: 1153
```

The `null` string is displayed above the state label:
![mobile_vertical](https://user-images.githubusercontent.com/25845078/51029881-f4a1cc00-1597-11e9-96ec-85265a583b3f.png)

**Comment by elupus** [comment]
Eco is a profile isnt it. So it shouldnt even have that mode.

**Comment by elupus** [comment]
Oh, issue is old. So likely not relevent anymore.
