### ISSUE TITLE
Permissions / Multiple users

### ISSUE THREAD

**Issue by TheFlyingCorpse** [home-assistant/home-assistant-polymer#3899]
Awesome work on the new UI, it looks fresh 👍 

Any thoughts on implementing permissions in the new UI? It would be really awesome if it became possible to grant different users different access in this.

**Comment by Misiu** [comment]
I'm still new to HA, but can't agree more - each user should have their own UI (files).
I'd like to suggest an improvement that I commented [here](https://github.com/home-assistant/home-assistant-polymer/issues/3895).
There should be an option to create pre-configured cards, this way a user will be able to add a pre-configured card to his views.
This way admin will declare all the cards, users will have the freedom to add them (if they want) and if that card needs a change then admin only need to change in one place.

**Comment by Misiu** [comment]
@iantrich why this got closed?

**Comment by iantrich** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/3811

**Comment by Misiu** [comment]
it wasn't linked, sorry for that.
Awesome feature 👍
