### ISSUE TITLE
Allow setting read-only property for entities

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant-polymer#3933]
**Home Assistant release with the issue:** 0.95.4

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):** Lovelace UI

**Browser and Operating System:** Chrome 77 WIndows 10

**Description of the feature request:**
Sometimes you want to show the status of a switch or other entries in Lovelace UI. A simple use case can be a read-only view for a non-admin user or showing the status of switches that are changed via automation.
The current workaround is to create a template entity, but if You have 30 switches then You must create 30 templates.
If we would be able to add read-only: true to the entity then the problem would be solved.

this is already used for example in toggle switch - https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/entity/ha-entity-toggle.ts#L34

Please consider adding this property.

**Comment by iantrich** [comment]
You can already do this

`type: custom:hui-text-entity-row`

**Comment by Misiu** [comment]
@iantrich I didn't know about `custom:hui-text-entity-row`. Thank You for this!
Are there any other types that might be helpful? Are they documented somewhere?

**Comment by iantrich** [comment]
I see what you're after, I guess, but we're not architected for that. Just use a template sensor if you don't want control

**Comment by Misiu** [comment]
@iantrich I've tried using a template, but I can't change the icon color and I get no history, so a read-only property would be ideal. Where should I address this? Here or in other repo?

**Comment by Misiu** [comment]
@iantrich can we reopen this issue and add `feature request` label?
I've opened an issue in architecture repo and hopefully, it will get some attention and approval.
