### ISSUE TITLE
Chrome Type-ahead-find breaks login page

### ISSUE THREAD

**Issue by mikromCZ** [home-assistant/home-assistant-polymer#394]
Trivial bug

I am using this Chrome extension (https://chrome.google.com/webstore/detail/type-ahead-find/cpecbmjeidppdiampimghndkikcmoadk) and on the login page is not possible to type pasword.

For now I have disable the extension, but it is strange behavior, right?

It is simple impossible write in the password field, because extension "search" what you type.

**Comment by balloob** [comment]
We are not supporting this extension and so can't help you.

Also, please refrain from using the word "trivial".
