### ISSUE TITLE
Add default text to Markdown card editor

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3943]
**Home Assistant release with the issue:**
0.100b

**Description of problem:**
The Markdown card editor assumes the user already knows Markdown. But most normal people won't. When they click on the card they will just see two text fields with no idea of what to do, what Markdown even means, etc. 

This should have some type of default text (in Markdown format) so the user knows how this works. Could even add a Markdown link to [Markdown Reference](https://commonmark.org/help/). 

![markdown-card](https://i.imgur.com/vd1ycCI.png)

Better yet would be a WYSIWYG editor if possible, but this is probably easier for now.

**Comment by bramkragten** [comment]
Can simply be added here: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-markdown-card.ts#L29

**Comment by SeanPM5** [comment]
Closed via https://github.com/home-assistant/home-assistant-polymer/pull/3960
