### ISSUE TITLE
Theming of entity switches doesn't work anymore in beta

### ISSUE THREAD

**Issue by markus-pixel** [home-assistant/home-assistant-polymer#3946]
**Home Assistant release with the issue:**
0.100.0b1

**Last working Home Assistant release (if known):**
0.99.3

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome and Windows 10

**Description of problem:**
The checked-button-color variables doesn't apply anymore to entity switches with the new beta. The unchecked-button-color variables still work as intended.
```
  paper-toggle-button-checked-button-color: 'var(--accent-color)'
  paper-toggle-button-checked-bar-color: 'var(--accent-color)'
  paper-toggle-button-checked-ink-color: 'var(--accent-color)'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
```
The checked switches use primary-color instead.

**Javascript errors shown in the web inspector (if applicable):**
none
```

```

**Additional information:**
none

**Comment by iantrich** [comment]
`var(--primary-color)` is used for checked switches

**Comment by ThirteenTX** [comment]
> 
> 
> `var(--primary-color)` is used for checked switches

So we are no longer able to change the color to the accent color?

**Comment by Merwenus** [comment]
What Why?
