### ISSUE TITLE
De-emphasize States UI button on Info panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3947]
**Home Assistant release with the issue:**
0.100b1

**Description of problem:**
Lovelace has been the default UI for nearly a year now. New users have no reason to switch back to the old States UI they've never used, and existing users have now had plenty of time to transition over to Lovelace. 

Yet on the Info page, "SET STATES AS DEFAULT PAGE ON THIS DEVICE" is the focal point of the page. A huge blue button in all-caps practically begging to be clicked on. 

![states-button](https://i.imgur.com/3JiVueJ.jpg)

Here is some confusion in Discord from a new Home Assistant user who unknowingly did this: https://i.imgur.com/F25JCdn.png

This button should be de-emphasized. Make it a regular text link instead, just like the "Go to the states UI" link right above it is.

**Comment by iantrich** [comment]
I would probably also emphasize it is the old UI that is no longer supported/enhanced

**Comment by SeanPM5** [comment]
Good idea on a disclaimer type thing.

Though, are there any downsides to removing this option altogether? Allow the user to view States UI but not set it as default? I don't think users should be given the option to make an old and unsupported UI the default.

**Comment by iantrich** [comment]
That's a much bigger decision/discussion

**Comment by SeanPM5** [comment]
Closed via https://github.com/home-assistant/home-assistant-polymer/pull/3959
