### ISSUE TITLE
Add integration name to System Options dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3948]
**Home Assistant release with the issue:**
0.100b1

**Description of problem:**
On the Integrations pages there's a button in top right corner where you can disable newly discovered entities from being added to HA. 

The heading just has a generic "System Options" text regardless of integration. I think adding the integration name to the heading and maybe the descriptive text too would add some clarity and look nicer.

"System Options for **[integration name]**
If disabled, newly discovered entities for **[integration name]** will not be automatically added to Home Assistant."

mockup (ignore styling, that was fixed already - this is only about added integration name):

![system-options](https://i.imgur.com/3sWV18G.png)

**Comment by springstan** [comment]
@SeanPM5 please close this issue :)

**Comment by SeanPM5** [comment]
Closed via https://github.com/home-assistant/home-assistant-polymer/pull/3996
