### ISSUE TITLE
Swiping between group tabs

### ISSUE THREAD

**Issue by mikromCZ** [home-assistant/home-assistant-polymer#395]
Trivial enhacement

It is possible to add this little feature? It would be nice on mobile devices.

I mean this:
`default_view:
  view: yes        
system_view:
  name: Systém
  view: yes`

make two tabs, and on mobile device I need to do horizontal scroll on the tabs..

**Comment by balloob** [comment]
We have to satisfy both desktop and mobile phone users, both mouse and touch. We're not planning on implementing this trivial enhancement.
