### ISSUE TITLE
Make thermostat history graph localizable

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant-polymer#3952]
**Home Assistant release with the issue:** 0.9.9.3

**Last working Home Assistant release (if known):** NA

**UI (States or Lovelace UI?):** Lovelace UI

**Browser and Operating System:** Chrome 77, Windows 10 x64

**Description of problem:**
Currently, when viewing thermostat history (click on the thermostat) You get a popup with the history graph, like this:
![image](https://user-images.githubusercontent.com/1741838/66350176-ee8c2080-e95a-11e9-9867-26a1ff331275.png)

or this:

![image](https://user-images.githubusercontent.com/1741838/66350280-33b05280-e95b-11e9-8e46-5656ee99859e.png)

Unfortunately the strings: `target temperature`, `current temperature` , `heating` aren't translated.

I've checked https://lokalise.com but I didn't found those strings there. If possible please allow localizing them.

**Comment by springstan** [comment]
I would like to take this issue, unfortunately I do not own a thermostat which I could use for testing.
@bramkragten Can I utilize the demo climate platform in any way for testing this?

**Comment by bramkragten** [comment]
Yes, add `demo:` to your dev `configuration.yaml` and you will a get a bunch of demo entities, including thermostats. Or use:
```
climate:
    - platform: demo
```
https://www.home-assistant.io/integrations/demo/

**Comment by springstan** [comment]
@bramkragten thanks for the quick response! 
Should I add the translation to the climate section:
https://github.com/home-assistant/home-assistant-polymer/blob/f9b0a0fc139d3965de474e30bf89e4ac374fe237/src/translations/en.json#L401
or to the lovelace thermostat card?
https://github.com/home-assistant/home-assistant-polymer/blob/f9b0a0fc139d3965de474e30bf89e4ac374fe237/src/translations/en.json#L1513-L1515

**Comment by bramkragten** [comment]
The history graph is not part of lovelace, so I would say `climate`

**Comment by springstan** [comment]
Fixed with #4004 :) Please close this issue.
