### ISSUE TITLE
Unnecessary Line Wrapping in Lovelace Light Card

### ISSUE THREAD

**Issue by shbatm** [home-assistant/home-assistant-polymer#3964]
**Home Assistant release with the issue:**

Hass: v0.100.0b1
Frontend: 20191002.0 

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Chrome / Windows 10

**Description of problem:**

For longer entity friendly names, the Light entity card is wrapping the name when there is plenty of room in the card to display the whole thing.  It appears that there is no `'width'` setting set on the `name` class.  Adding something like `width: 90%;` or `width: fit-content;` in Chrome DevTools corrects the issue.

### Before:
![image](https://user-images.githubusercontent.com/18057952/66399552-7434be00-e9a5-11e9-9a49-a457b0b00d49.png)

### After:
![image](https://user-images.githubusercontent.com/18057952/66399570-7d258f80-e9a5-11e9-9095-6310382f540b.png)

**Javascript errors shown in the web inspector (if applicable):**
```
N/A
```

**Additional information:**
Suggest adding `width: 90%;` at [this line](https://github.com/home-assistant/home-assistant-polymer/blob/0f7a3887a78b9354025d16189a1dc7069d0e52b6/src/panels/lovelace/cards/hui-light-card.ts#L219)

**Comment by shbatm** [comment]
Thought this might be because I am using the Light card inside a Horizontal Stack, but I confirmed the same issue occurs with a longer name on the full Light Card using the demo site:
![image](https://user-images.githubusercontent.com/18057952/66400791-bfe86700-e9a7-11e9-9ebc-32eebe0147f7.png)

**Comment by iantrich** [comment]
Sounds like an easy hacktoberfest issue if you want to take a stab at it

**Comment by iantrich** [comment]
I think that's fine. Others might chime in when you submit a PR (css is not my forte either 😄 )

**Comment by JeroenGoddijn** [comment]
You can also just set 
`max-width: 90%;`
Might make it more responsive..

**Comment by shbatm** [comment]
@JeroenGoddijn -- Tried this in DevTools and it had no effect.

**Comment by JeroenGoddijn** [comment]
Sorry, was just going off by what I saw in here... haven't had a chance to change my light dimmers to these cards yet..

Need to make some time to set up new clean dev environment and knock out some Hacktoberfest issues too... ;o)

**Comment by shbatm** [comment]
NP. I went with @bramkragten's suggestion in the PR (#3972)... Trying to knock out as many of my backlog issues for Hacktoberfest too

**Comment by iantrich** [comment]
@shbatm there's no shortage of them :)
