### ISSUE TITLE
History graph disappears on more-info after editing entity

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#3966]
**Home Assistant release with the issue:**
0.100b1

**Description of problem:**
Steps to reproduce bug:

Open more-info dialog for any entity that has a history graph and can be edited:
![image](https://i.imgur.com/ALkyOjm.png)

Click on the edit cog in top right to begin editing it. Rather than saving it just press the back arrow to cancel. 
![image](https://i.imgur.com/l1RPdqe.png)

When it returns you to the screen, the history graph does not appear and is just a blank empty space.
![image](https://i.imgur.com/hrHKQ1N.png)

**Comment by SeanPM5** [comment]
Still an issue in 0.104.3

**Comment by bramkragten** [comment]
The edit dialog is changed in 0.105, I think this should fix it. If not, please create a new issue.
