### ISSUE TITLE
Poor card placement versus available screen space

### ISSUE THREAD

**Issue by decairn** [home-assistant/home-assistant-polymer#3976]
**Home Assistant release with the issue:**
Frontend version: 20190919.1 - latest
HA 99.3

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Firefox 67.0 (64-bit)
Windows 10, 1920x1080 display

**Description of problem:**
1. 10 cards to display, plenty of space on entire screen to show all 10, yet UI is choosing to show 5 of them vertically on left hand side with the lowest one a partial display causing a scroll of the screen (Chrome).  Similar issue on Firefox but it crams 6 on left, with one partial view and another out of view.

2. Then, when entering configure UI mode, the cards move around again (due to edit footer added to each card I guess), still not perfect placement with vertical scroll evident. Closing configure without change leaves the cards in that order in the example leaves them using the whole display.

Expectation is that it can be smarter about moving the cards to use all the display space before forcing a vertical scroll, and that the display on going straight to the Overview Home Page by URL is the same as that displayed after exiting Configure UI.

Examples:
![1FirstOpen](https://user-images.githubusercontent.com/15806011/66527128-d974d600-eaaf-11e9-9de6-9d191b87adec.PNG)
![2ConfigureUI](https://user-images.githubusercontent.com/15806011/66527129-da0d6c80-eaaf-11e9-9b4a-7bb62212d736.PNG)
![3AfterConfigureUI](https://user-images.githubusercontent.com/15806011/66527131-da0d6c80-eaaf-11e9-919f-5d5ccdd214f5.PNG)

**Comment by balloob** [comment]
We count artificial rows to measure for distribution. If a column has 5 rows, we'll move to the next one. One row is ~height of an entity row.

**Comment by iantrich** [comment]
I'm not sure what to do with this issue; it is quite vague/subjective. To be "more smart" can mean very different things to different people. While I do agree that the layout mechanism could be improved, I don't feel like anything of value is here. If you want more granularity in defining your layout, use stacks or layout-card

As for point 2; no way around this unless we implement drag/drop layout editing which I believe we already have a ticket open for

**Comment by decairn** [comment]
I don't know what limitations there are in the UI technology.  Ideas I have are - 1) allow user to define number of artificial cards on the vertical rather than the static 5, 2) allow placement to be horizontal first rather than vertical, 3) allow card to define number of rows it should be deemed to take up, 4) use a pixel-space based algorithm to fit cards into canvas space.
Any of those could be an improvement on the core usability problem of vertical scrolling is poor.
