### ISSUE TITLE
Cast demo no longer launches

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#3983]
Launching the Cast demo from both https://demo.home-assistant.io or https://cast.home-assistant.io no longer seems to work. It opens the launcher but it shows up as "Not Connected".

**Comment by bramkragten** [comment]
Works for me on both places...?

**Comment by frenck** [comment]
Tested as well, both works as expected on my end.

**Comment by SeanPM5** [comment]
When this was first posted I tested it and also got the "Not Connected" message but now it appears to work perfectly fine in both places.

**Comment by balloob** [comment]
No longer able to reproduce 🤷‍♂  weird
