### ISSUE TITLE
Z-Wave config TODO list

### ISSUE THREAD

**Issue by andrey-git** [home-assistant/home-assistant-polymer#399]
* Make OZW log screen-wide
* Add `tail -f` like mode for OZW log
* Allow adding / removing instances to a group (and not just "whole" nodes).
* Show instance label instead of just instance number in group config.

**Comment by balloob** [comment]
We might want to move the logs for Z-Wave to a new page, like we did for Hass.io

**Comment by gogitgo** [comment]
>> We might want to move the logs for Z-Wave to a new page, like we did for Hass.io

This would be helpful as it could be moved to a separate window for monitoring "tail -f" mode while making changes. If not a new page, there could be a link to pop out to a new window.

**Comment by cgarwood** [comment]
First 2 items on the list are done now:

- Make OZW log screen-wide
- Add tail -f like mode for OZW log
