### ISSUE TITLE
iFrame card not working in demo

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4013]
**Home Assistant release with the issue:**
[Demo](https://demo.home-assistant.io/)

**Description of problem:**
I don't think this is a problem with the frontend, rather a server configuration thing. But this seemed like the most relevant place to report since it causes issues with demo. 

When adding an iFrame card on the demo, the default pre-filled URL is `home-assistant.io` and this no longer displays in the preview.  I suspect this might have been due to https://github.com/home-assistant/home-assistant-polymer/pull/3982 

![iframe-card](https://i.imgur.com/GrcVwMf.png)

If you change the URL to a subdomain, like `demo.home-assistant.io` or `developers.home-assistant.io` etc it will work fine. Just not the main HA site. cc @balloob @frenck

**Comment by frenck** [comment]
Aaah yes, our website has now got security headers that prevent framing.

Easy to remove, however, I would only advised doing that if it serves a purpose...

**Comment by frenck** [comment]
PR that addresses this in: home-assistant/home-assistant.io#10803

Please note, that this will remove a header from our website that is considered good practice in general.

**Comment by frenck** [comment]
Merged and this resolved (after the build of the site finished).

🎉
