### ISSUE TITLE
Show view name when editing a view

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4025]
**Home Assistant release with the issue:**
0.100.2

**Description of problem:**
Currently when you're editing a view it always has a generic "View Configuration" title.  It would look nicer and be more helpful if it displayed the actual view name up there such as "Lights View Configuration" for example.

![view-titles](https://i.imgur.com/qGEma3I.png)

This would prevent mistakes of the user accidentally editing the wrong view, and would ensure the user never loses their place. Especially because on the Badges tab for example you wouldn't see the fields for title, icon, url path that the above "Settings" tab screenshot has.

This was done for the Card editors recently (https://github.com/home-assistant/home-assistant-polymer/issues/3658), and I think it would make sense here too.

**Comment by iantrich** [comment]
cc @timmo001

**Comment by drakeloud** [comment]
I think I can handle this! I'll work on it and see if I can find a fix!

**Comment by drakeloud** [comment]
Well I figured out my issue. I had to run the project with node --max-old-space-size=2000 so that the heap didn't run out of memory.

Regardless, I have finished this up and will be submitting a PR in a moment!

**Comment by ludeeus** [comment]
Added by #4037, should be closed
