### ISSUE TITLE
View Configuration - change delete icon to text button 

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4027]
**Home Assistant release with the issue:**
0.100.2

**Description of problem:**
On the View Configuration panel, there is just a trash can icon for delete view. This is inconsistent with the other buttons in that same row which are text-based.  And there's no real good reason for it being this way as far as I can tell? It's not like that area is lacking room, even on mobile.

It's also inconsistent with pretty much every other area of Home Assistant. Go to the Users panel, the Person editor, the Entity Registry, Area Registry and try to delete something there. They all use red text.

Lastly, when you navigate to the Badges tab, it becomes less clear what action that trash can icon performs when you don't have a text label. The user could mistakenly think it's deleting their badges for example. Even the tooltip isn't too helpful and simply says "Delete" rather than "Delete view".

With it being text based (and red to indicate it's performing a destructive action) you have extra context, no confusion, and consistency with everything else.

![delete-view](https://i.imgur.com/nJHDnAi.jpg)

**Comment by drakeloud** [comment]
I'm blocked because I don't think there are any translations currently for 'Delete View'. Not really sure how to proceed on this.

**Comment by bramkragten** [comment]
@drakeloud You can add new translations to `src/translations/en.json`

**Comment by drakeloud** [comment]
@bramkragten Ah, okay. I wasn't sure if I could touch those or not. Okay, i'll update accordingly.
