### ISSUE TITLE
Tweak heading of Lovelace Add Card picker

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4029]
**Home Assistant release with the issue:**
0.100.2

**Description of problem:**
Here is how the add card picker screen looks. It has "Card Configuration" as the main heading, even though you're not actually configuring a card on this screen, just picking one. The heading doesn't really make sense.

![add-card](https://i.imgur.com/y96K1Yx.png)

I think that it would be cleaner if that first heading was removed, and the subheading was put in its place. Here is option 1. This is the easiest as it's basically deleting one heading, and changing an H3 to an H2.

![image](https://i.imgur.com/zq8yR60.png)

Option 2 which I prefer, is a little more informative. It tells the user which view the card will be added to (basically whatever view they were currently on when pressing the orange "add card" button). This ensures the user doesn't lose track of what they were doing after reading two dozen card titles. And it helps new users get more accustomed to the difference between views and cards.

![image](https://i.imgur.com/BcKutp1.png)

Option 3 is sort of a hybrid approach. Similar style to how it currently looks (with two headings), but text is tweaked and it includes the improvement from above.

![image](https://i.imgur.com/EGQTSgj.png)

Not sure which is best, and maybe someone else will have other ideas... But the "Card Configuration" heading is definitely not needed here.

**Comment by iantrich** [comment]
👍 #2

**Comment by SeanPM5** [comment]
That's my fav option as well. 

Though now that I think about it, views can have no title. Probably a rare scenario, but that's something that should be accounted for.  

I think "Unnamed view" view sounds clunky, so in the case of no view title I think the heading should just say "Which card would you like to add?"

**Comment by springstan** [comment]
> 👍 #2

I really like this option too and would like to implement it, I have already found where I need to make make modifications:
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/panels/lovelace/editor/card-editor/hui-card-picker.ts#L53

and:
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/translations/en.json#L1403

However, I am not sure how to access the current `LovelaceViewConfig` to get its `title` and pass it on to the translation. Can anyone give me a hint? 😁

**Comment by bramkragten** [comment]
You should pass the config or title to `hui-card-picker` from `hui-dialog-edit-card`:
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts#L84-L87

We currently don't store the view config, but it is available in `hui-dialog-edit-card`:
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts#L49
`params.lovelace.config.views[view]`

**Comment by springstan** [comment]
@bramkragten thanks for the input! With your help I figured it out and it works now, however I think I have a better solution.

Instead of passing the config to `hui-card-picker` from `hui-dialog-edit-card` I could modify the following lines where the main heading is created:
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts#L65-L74
e.g in this case "Card Configuration":
https://github.com/home-assistant/home-assistant-polymer/blob/c437cd386546a3dbeba8d766000016c31b838bb7/src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts#L70-L74
Therefore, we do not need to pass on the config since we use it only in this file. 
What do you think?

**Comment by springstan** [comment]
I have implemented my suggested changes in #4083
