### ISSUE TITLE
Changing primary-color through theming doesn't work when referenced in another variable

### ISSUE THREAD

**Issue by mweinelt** [home-assistant/home-assistant-polymer#403]
I've set the primary color through

```yaml
frontend:
  themes:
    test:
      primary-color: "#A71680"
```

According to https://github.com/home-assistant/home-assistant-polymer/blob/master/src/resources/ha-style.html this should affect:

```css
    --paper-slider-knob-color: var(--primary-color);
    --paper-slider-knob-start-color: var(--primary-color);
    --paper-slider-pin-color: var(--primary-color);
    --paper-slider-active-color: var(--primary-color);
```

But they stay at the default blue, while the header correctly changes color.

I'm on 0.51.2.

**Comment by andrey-git** [comment]
Which browser?

**Comment by mweinelt** [comment]
Firefox 55 and Chromium 60

**Comment by andrey-git** [comment]
This is because theming is set on <home-assistant> and `--paper-slider-knob-color: var(--primary-color);` is set on <body>

We could *also* set theming on <html> and <body> (or just <html> and <body> and not <home-assistant>)

Paulus, WDYT?

**Comment by balloob** [comment]
I'm surprised, I would expect us setting it on `<home-assistant>` would overwrite anything that is defined above it?

**Comment by NovapaX** [comment]
This is quite an old issue, but I took a look at it nonetheless.

We assign `--paper-slider-knob-color: var(--primary-color);` on <html>. 
On that level `--primary color` is set to the default blue color.... so `--paper-slider-knob-color` will get that default value and then propagate down into the dom-tree.

possible solutions:
- we set the theme variables at the html element
- the theme (that currently gets set on <home-assistant> needs to override all the variables that propagate down from html element level
