### ISSUE TITLE
More descriptive menu item text for cards in configure UI

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4030]
**Home Assistant release with the issue:**
0.100.2

**Description of problem:**
Very small adjustment to the menu option text for cards when in Configure UI mode that makes things a little bit more clear. Especially for beginners and demo users to wrap their heads around differences between cards and views.

Before (left) and after (right). 

![card-text](https://i.imgur.com/LYeFCWm.jpg)

I don't think "Move" is descriptive enough on its own, because there's already icons to move cards up and down. What makes this "Move" different than the other "Move"? This one is moving to a view. So it should actually say that rather than making the user guess or be surprised after they click. 

And "Delete" becomes "Delete Card" with red text so it's consistent with the rest of HA. It might be possible to change the text for these in Lokalise, but the red text requires a frontend change so I posted it here.

**Comment by rahuldkjain** [comment]
@SeanPM5 I would love to work on this. Please assign this issue to me

**Comment by ludeeus** [comment]
Added by #4145, should be closed
