### ISSUE TITLE
 Theming of entity switches doesn't work anymore in beta 

### ISSUE THREAD

**Issue by Merwenus** [home-assistant/home-assistant-polymer#4034]
Home Assistant release with the issue:
0.100.0b1

Last working Home Assistant release (if known):
0.99.3

UI (States or Lovelace UI?):
Lovelace

Browser and Operating System:
Chrome/Firefox and Windows 10

Description of problem:
The checked-button-color variables doesn't apply anymore to entity switches with the new beta. The unchecked-button-color variables still work as intended.

  paper-toggle-button-checked-button-color: 'var(--accent-color)'
  paper-toggle-button-checked-bar-color: 'var(--accent-color)'
  paper-toggle-button-checked-ink-color: 'var(--accent-color)'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

The checked switches use primary-color instead.

Additional information:
**Dark themes are useless now, active toggles look like inactive.**

**Comment by bramkragten** [comment]
Why do you create a new exactly the same issue?
