### ISSUE TITLE
Reorder items in Configuration panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4040]
**Home Assistant release with the issue:**
0.100.2

**Description of problem:**
I think Configuration panel could use some minor re-arranging to surface the more frequently used sections higher in the list.

Basically this boils down to moving "Users" down near the bottom and "Automation" and "Script" near the top. Here is a before (left) and after (right) screenshot, with the reasoning below.

![config-panel-arrangement](https://i.imgur.com/5euDm1h.jpg)

**Reasoning**:
Users is currently placed near the top, yet it's probably the _least_ visited section if you think about it. An owner/admin account is created during onboarding and many users will never need to create another one. Even those who do create user accounts for each family member, it's a one-time process. Not something that you are doing regularly like the other sections here. So it should be demoted a bit.

Automation and Script Editors are probably the most visited sections inside this panel. Yet these are listed towards the bottom pretty much, meaning you have to scroll to see them on certain devices (my phone and laptop). Would make navigation easier and more convenient if these frequently used sections were higher up in the list.

These changes put the most frequently used items together near the top, so users won't have to read or scroll as much in order to access them.

**Comment by Mariusthvdb** [comment]
if it were up to me, add move the server control up as far as possible, since this is the button used most frequently on this end. 
Got to add I use yaml mode, so don't need any of the other tasks at all, and have advanced mode activated.

Maybe you could change the order based on yaml mode or not?

thanks for considering my 2ct..

**Comment by bramkragten** [comment]
@Mariusthvdb We can't see how you configured your system, with `yaml` or through the UI. So we can't change the UI based on that.
