### ISSUE TITLE
Climate Card Issue - MQTT

### ISSUE THREAD

**Issue by kuchel77** [home-assistant/home-assistant-polymer#4042]
**Home Assistant release with the issue:**
0.100.0.dev0

and 0.100.1

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Firefox 69.0.3

**Description of problem:**

This error is due to me changing the code to tell me list of modes - It isn't an error just a debug setting.

2019-10-18 00:01:03 ERROR (MainThread) [homeassistant.components.mqtt.climate] mode_list ['off', 'auto', 'cool', 'heat', 'dry']

As you can see these are all lowercase modes.

The Climate card seems to introduce First Letter Capitalization (as is Cool vs cool) which then gives invalid modes error messages.

2019-10-18 00:04:04 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: Cool
2019-10-18 00:06:44 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: Dry

When I click on the Dry icon for instance, it gives "Dry" and the error message above and sets the MQTT cmnd to Dry and the card disables it self. Since this is being done via MQTT discovery, I can set the cmnd item to "dry" and the card starts to work again. 

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

<img width="249" alt="Screen Shot 2019-10-18 at 11 15 11 am" src="https://user-images.githubusercontent.com/52343790/67056628-980fb500-f198-11e9-8c77-fccf02548a17.png">
<img width="224" alt="Screen Shot 2019-10-18 at 11 14 55 am" src="https://user-images.githubusercontent.com/52343790/67056629-98a84b80-f198-11e9-8229-4cd89617cf63.png">
<img width="501" alt="Screen Shot 2019-10-18 at 11 14 23 am" src="https://user-images.githubusercontent.com/52343790/67056630-98a84b80-f198-11e9-93e1-4717d88fbdd0.png">
<img width="508" alt="Screen Shot 2019-10-18 at 11 14 04 am" src="https://user-images.githubusercontent.com/52343790/67056631-98a84b80-f198-11e9-96ea-19cc6e9829a5.png">

Hopefully these screenshots show the MQTT that works when I set it manually to "cool", and the MQTT that doesn't work once a button has been pressed and it gets set to "Cool".

If this is the wrong spot, can you let me know, but it seems it is the climate front end messing things up.

**Comment by bramkragten** [comment]
We don't do capitalization, we just send back the modes the same way we get them from the component.
![image](https://user-images.githubusercontent.com/5662298/67109388-b5607580-f1d0-11e9-922f-b0691f7aafde.png)

**Comment by bramkragten** [comment]
Might be an issue with the MQTT climate component?
