### ISSUE TITLE
Page automatically jumps to changed switch

### ISSUE THREAD

**Issue by thrust15** [home-assistant/home-assistant-polymer#406]
Hi,

Whenever a switch changes (due to automation or someone pushing a button) and I have the UI open, the page jumps to the changed switch. For me this is very annoying. Most of the time I want to monitor a specific element in the UI and then the page jumps. 

I started noticing this behaviour from the current 0.51 release of home assistant so I assume this has something to do with the upgrade to the new polymer version.

Browsers tested: Safari 10.1.2 on MacOS 10.12.6 and the Home-assistant iOS App

**Comment by andrey-git** [comment]
This is caused by #387

**Comment by aequitas** [comment]
I experience this issue as well. It's especially prominent on mobile where it scrolls the entire page.

**Comment by pixeye33** [comment]
More than a month since the bug appeared, i wonder why there is not more people complaining ?

Here on latest versions of Firefox, Chrome and Chrome mobile i have the issue.

@balloob would you please take a look at this ?

**Comment by pixeye33** [comment]
Wow thumbed down by balloob himself <3

Well, i'm pretty sure we're not the only have automations or groups on our setup ?
And on my end the switch or automation can be triggered on page or externally : i've got a page jump.

**Comment by pelson** [comment]
I have the same issue. If the behaviour is desirable, it would be useful to be able to toggle it (as it really doesn't work when you have multiple groups containing the same switches).

Not sure if related, but I also get an issue where a group fails to completely toggle all of its s witches when I toggle the group - I have a few groups which overlap and it could be that the switch that fail to toggle is also in another group as well. Anybody else seeing that? I was wondering if it was related to the interface jumping around - but perhaps that is just an entirely different issue...
