### ISSUE TITLE
Allow reloading Automations and Scripts from their respective panels

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4065]
Home Assistant already allows you to reload automations and scripts without restarting. You either have to do this in Configuration > Server Control, or from Services panel > `automation.reload` etc. This is not as convenient as it could be. 

The panels for Automation and Script allow you to view, create, edit, and trigger them. So why not allow reloading them too? Right now you either have to open a second browser window or navigate around when you want to reload. With this idea, you'd be able to do it all in one convenient spot.

I was thinking of maybe having a refresh icon in top right corner for the Automation and Script panels. This is already familiar to users, since the Logbook panel and Hass.io panel (snapshots/add-on store) have these refresh buttons.

![reload-automations](https://i.imgur.com/Q4Qmqvg.jpg)

The tooltip would read "Reload Automations" and "Reload Scripts" (text is already localized for the buttons on Server Control panel, so could just be re-used?). This would add a useful feature without changing the UI much at all.

Like the Server Control panel, this should only be displayed when "Advanced mode" is toggled on.

**Comment by iantrich** [comment]
you would only need to reload these if you are editing them via yaml, correct? in which case, i don't think we need this.

**Comment by SeanPM5** [comment]
I believe that's correct.  I still think it's useful, however. I edit most of my automations via yaml still, but use the Automation panel to trigger and test them.

If the automation is not working 100% I have to tweak my yaml and then reload automations, but there's no way to do this from the actual automations page. Would either need to navigate to config > server control or dev tools > services, _or_ keep one of those pages open in another tab just to press a reload button.

Feels more elegant to just have it here as a shortcut, so you never have to leave the page? And since this would be tied to advanced mode it would only be shown to the proper target audience. But I realize my usage might be an edge case so i'm cool with whatever gets decided here.

**Comment by bramkragten** [comment]
I think this will add to the confusion for people that they need to refresh/reload after a change in the UI.

**Comment by ProLoser** [comment]
I'd really like this too and do it the same way. Can we at least allow this to be configured on? Can we bury "Reload YAML Automations" underneath a More menu?
