### ISSUE TITLE
Missing title attributes in Configure UI mode

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4066]
Configure UI mode is lacking a few tooltips in the following places:

* The "3 dots" icon that you have to click to enter Configure UI mode in the first place
* The "X" button in the far left to exit Configure UI mode
* The edit/pencil icon next to the Lovelace title

These should be added.

**Comment by springstan** [comment]
Would not it make more sense to add the `title` attribute instead of a tooltip?
Since other elements have this attribute set, e.g. help icon, edit view title, move view, add card and so on.

**Comment by SeanPM5** [comment]
Yeah, that's what I meant - to make it consistent with the other elements that you listed. Was a wrong choice of words on my part.

**Comment by springstan** [comment]
Oh okay great, then I will get right to it. No worries about that, both terms mean very similar things after all.

**Comment by springstan** [comment]
Done with #4148 :)
