### ISSUE TITLE
Thermostat card doesn't support well RTL languages

### ISSUE THREAD

**Issue by ofirm93** [home-assistant/home-assistant-polymer#4069]
**Checklist:**

- [v ] I updated to the latest version available
- [ v] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** 20191002.2 - latest

**Browser and Operating System:** Chrome version 77.0.3865.120, Windows 10x64

**Description of problem:**

While using Right-To-Left languages (such as Hebrew which I use), the thermostat card displays the round slider completely messed-up. I am not that much skilled with frontend, but I found that the origin of it is in the library that is used for rounded sliders, which doesn't handle rtl in html correctly. I tested the GUI in developer mode of chrome and added to the containing div tag a dir="ltr" attribute and it fixed the issue. As I'm not sure it is the best solution for such a problem (again not a frontend dev) I just taged in this issue the line I think the attribute dir="ltr" can be added to solve it.

Some images of the error and solution:
![image](https://user-images.githubusercontent.com/20561642/67150561-9a216300-f2c1-11e9-9534-091fbe2c93dc.png)
![image](https://user-images.githubusercontent.com/20561642/67150576-f84e4600-f2c1-11e9-9782-b6c26dfa6fac.png)

**Additional information:**
Link to the possible line in which the issue can be fixed: https://github.com/home-assistant/home-assistant-polymer/blob/f5e3a9ad403a5199ae27247df978000e82bbd58a/src/panels/lovelace/cards/hui-thermostat-card.ts#L130

**Comment by bramkragten** [comment]
@iantrich as promised, assigning you ;-)

**Comment by bramkragten** [comment]
The thermostat card was rewritten for the next release, this might be fixed already.

**Comment by ofirm93** [comment]
I will follow up on next release.

**Comment by iantrich** [comment]
![image](https://user-images.githubusercontent.com/1287159/67232056-1fae2b80-f406-11e9-90bf-ee1777875f7e.png)
slider looks fine in the new release but unit of measurement gets bumped to the line below. Where should it be?

**Comment by ofirm93** [comment]
I guess to the right of the teperature number. Also the "degrees" sign should be closer to the number than the units. For example I took this from google forecast: 
![image](https://user-images.githubusercontent.com/20561642/67238564-0df47480-f456-11e9-9b99-6144d0ad580a.png)

**Comment by thomasloven** [comment]
Do I understand correctly that the "correct" way to display the temperature is still with the unit to the right?

What would be the appropriate behavior of the slider itself?
Should it move from right to left as well, with the lower temperatures to the right?

What about the light slider card, where the slider adjusts the brightness of a lamp. Would that be better to have from right to left or would that be confusing to people used to RTL languages?
I assume physical dimmers and volume knobs and such increase clockwise even in countries where RTL writing is the norm?
Please forgive my ignorance. I just want to get it right.
