### ISSUE TITLE
Kiosk returns 404

### ISSUE THREAD

**Issue by thrust15** [home-assistant/home-assistant-polymer#407]
Hi,

When going to my instance of home-assistant https://192.168.1.20:8123/kiosk/ it returns a 404 error. I've not set up an explicit default_view in my configuration. If there is more information you need, i'm happy to provide, not sure if you can reproduce this.

**Comment by balloob** [comment]
Try removing the slash at the end.

**Comment by thrust15** [comment]
Hi @balloob that works :) when i enlarge my screen I still can see the sidebar while the hamburger button is removed. Do I need to raise a new issue on that?

**Comment by andrey-git** [comment]
sidebar status is sticky, so if you go to `/states`, open the sidebar and then got to `/kiosk` you will see the sidebar. If you close it - you shouldn't be able to open it again.

**Comment by thrust15** [comment]
Ok, this seems to be intended behaviour then. I was under the assumption that the kiosk would remove the sidebar no matter what.
