### ISSUE TITLE
Device Automation device picklist seems empty but entries are hidden below empty lines

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/home-assistant-polymer#4082]
**Home Assistant release with the issue:**

0.100.2

**Last working Home Assistant release (if known):**
Never worked

**Operating environment (Hass.io/Docker/Windows/etc.):**

**Integration:**

Device Automation

**Description of problem:**
When I try to create a new automation in the GUI Automation creator and I choose the new trigger type Device, the pick list below contains an entry that says "No Device" and nothing below even though I have more than 100 devices

At first I thought the feature just did not work at all but then I see a scroll bar and when I scroll down 54 empty positions, my devices start showing.

See picture

![image](https://user-images.githubusercontent.com/8373419/67161948-a0661c80-f35f-11e9-9321-901c38e28745.png)

I cannot say what these are. If I try to make an automation with an empty pick item I cannot save it as I cannot create a valid automation

But I have a theory. I think it is all the Unifi device tracker items because none of these have a name and there would be around 50+ of them.

So the bug seems to be that the pick list is generated including devices that should be excluded as they have no name

The same pick list behaviour is seen down the automation creator in actions and conditions

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

Here is a picture where I scrolled down and the devices show up

![image](https://user-images.githubusercontent.com/8373419/67162024-8f69db00-f360-11e9-8021-81fe4a873c77.png)

**Comment by bramkragten** [comment]
Why should devices with no name not be shown? I just think we need to do a better job getting a name. What do you see in `/config/devices` for these devices?

**Comment by KennethLavrsen** [comment]
Thanks for the speedy action
