### ISSUE TITLE
When choose alternative theme - the page with unused devices page look bad and no chance to correct it right

### ISSUE THREAD

**Issue by konstantin-teplitzky** [home-assistant/home-assistant-polymer#4087]
**Home Assistant release with the issue:** 100.2

**Last working Home Assistant release (if known):** never

**Operating environment (Hass.io/Docker/Windows/etc.):** Arch Linux

**Integration:** themes

**Description of problem:** If select other theme than default,on the page with unused devices, cant see table because font color is the same as background. it's unpossible to set different color in theme - because this table not nave own style/id.

**Comment by SeanPM5** [comment]
Add this to your theme(s), then restart Home Assistant, and it should fix the issue you are seeing.

`card-background-color: "var(--paper-card-background-color)"`
