### ISSUE TITLE
Failed to call service timer/start. unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'

### ISSUE THREAD

**Issue by dgtal1** [home-assistant/home-assistant-polymer#4088]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Windows Chrome 77

**Description of problem:**
The newly introduced frontend timer control raises errors for a timer with initial duration (not supplied in configuration.yaml).
Failed to call service timer/start. unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'
I was extremly excited with the new feature as now to control any timer I need an input_boolean and an input_datetime additionally.
The thing is that I do not use any default value for my timers, but I made it configurable in the frontend with input_datetime and set the duration dynamically by calling the timer.start service and passing my input_datetime value as timer duration.

The first thing I propose to fix is to remove this error when duration is not given in configuration.yaml as it brings confusion to the user (I thought the new frontend START button doesn't work, and later realized it may be because initial duration).
And the second thing - even more important - please implement a field to set the duration for the timer before one presses the START button! This will only give the full control to the user.
I bet that many people use dynamic duration setting and the new buttons won't help much.
As an alternative a new timer service would be useful like timer.set_duration, so then I could perhaps make an automation to set the duration before triggering the timer from the GUI.

**Traceback**
```
unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/timer/__init__.py", line 175, in async_start
    self._end = start + self._duration
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'NoneType'
```
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Bram - thanks for your great work on Lovelace and please implement this function as only this will complement this functionality

**Comment by bramkragten** [comment]
This is actually a bug in the backend, the default for `duration` should be 0 and never `None`, not a python/voluptuous expert, but I think `default=` is missing here.

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/timer/__init__.py#L52

**Comment by bramkragten** [comment]
For the other thing, please create a new feature request issue
