### ISSUE TITLE
Chrome shows copy menu on buttons long press

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4092]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):**
0.99.3

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome, Firefox is OK

**Description of problem:**
On a tablet with touchscreen, all buttons that have hold_action configured show a copy menu in chrome on long press.
![Auswahl_211](https://user-images.githubusercontent.com/26381449/67234099-c5808b00-f444-11e9-8725-0b1bbe0bf572.png)
Chrome on Desktop is OK.
Reverting back to 0.99.3 fixes this.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by bramkragten** [comment]
Wonder if we can do something similar to the tap that showed the search action on chrome?

**Comment by iantrich** [comment]
assuming this this is an Android tablet, you should not be able to select text.
@VDRainer are you able to grab the user agent string for your device?

**Comment by VDRainer** [comment]
This is in latest chrome on Ubuntu 18.04.
The problem is the touchpad. If i try a long press over a vnc session, everything works as expected.

https://www.whoishostingthis.com/tools/user-agent/ shows:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
```
Hope that helps.
Thanks for looking at this.

**Comment by iantrich** [comment]
Okay, I am able to replicate on the touchscreen on my laptop. Mouse clicks are being handled by long-press and not presenting the copy, but touch events are.

**Comment by iantrich** [comment]
First thoughts; revert the ability to copy text or just remove it from Chrome as it likes to be difficult?

**Comment by iantrich** [comment]
For reference https://github.com/home-assistant/home-assistant-polymer/pull/3605

**Comment by SeanPM5** [comment]
I have the same behavior on mobile Safari (iOS 13.1.3) in 0.100.2 although with the custom button card (can test core button later). The hold_actions are still working fine but it's also selecting the button text.

So I don't think it's limited to just Chrome.

**Comment by iantrich** [comment]
I think maybe it makes sense to just revert my change and only make notifications selectable. Can you guys think of a good reason to need to select text on anything else?

**Comment by SeanPM5** [comment]
I think it's fine to make just notifications selectable. You'd want that to copy PIN codes and API keys and stuff that sometimes come in notification form when setting up integrations.

But for other things, I can't really think of a reason why you'd need to select text? Especially for the button example in OP, button text is usually kept intentionally short anyway. Wouldn't be much of an inconvenience to retype it if need be.
