### ISSUE TITLE
Link to manual setup configurations need styling and open in new tab

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4096]
![image](https://user-images.githubusercontent.com/1444314/67251241-462e8f80-f423-11e9-8711-22100d5483c4.png)

This link should:
 - be colored with primary color
 - should have `target="_blank"` so it opens in new window
 - should only be visible in advanced mode

**Comment by balloob** [comment]
Also needs some padding in case the list is empty

![image](https://user-images.githubusercontent.com/1444314/67251397-dff63c80-f423-11e9-8abd-e82f4d2af107.png)

**Comment by balloob** [comment]
And the period should not be part of the link.

**Comment by pdong** [comment]
I started taking a peek at this but I'm unfamiliar with how passing of the showAdvanced works.

I noticed `src\panels\config\ha-panel-config.ts` is setting showAdvanced on the pageEl so I added the property to `ha-config-integrations` and set pageEl showAdvanced property when the page is dashboard (`pageEl.showAdvanced = this.showAdvanced;`)

From here I added the property to `src\panels\config\integrations\ha-config-entries-dashboard.ts` which gave me access to showAdvanced but it looks like that page is opening the dialog by firing a `"show-dialog"` event.  

I tracked that down to make-dialog-manager but it looks like the dialogElement isn't receiving props passed down by the view but being provided by the root element (`element.provideHass(dialogEl)`).  At this point I've kind of hit a dead end and I'm starting to question if I'm headed in the right direction 😬 

Any input would be appreciated. Thanks

**Comment by bramkragten** [comment]
You can give parameters to the dialog with the `showConfigFlowDialog` function:

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/dialogs/config-flow/show-dialog-config-flow.ts#L19

Here is the interface for the parameters:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/dialogs/config-flow/show-dialog-data-entry-flow.ts#L73

**Comment by bramkragten** [comment]
@pdong are you working on this, or should I pick this up? I would like it in the release of tomorrow.

**Comment by pdong** [comment]
@bramkragten You can take care of it :) I won't be able to get back to it until late tonight.
