### ISSUE TITLE
Inconsistent column width

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant-polymer#4125]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.0b0

0.100.3
**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

latest just d/l after beta Frontend version: 20191023.0 - latest
**Browser and Operating System:**
debian/hass.io

chrome on PC and iOS and iOS app
**Description of problem:**
Column widths are variable depending on data on card. Some cards are getting cut off down the side.
Examples:
![image](https://user-images.githubusercontent.com/36390762/67455631-f1388680-f679-11e9-93bd-f27b8eb18b3f.png)
Different widths... the V6 IP address is expanded whereas previously all 3 columns would be same width.
![image](https://user-images.githubusercontent.com/36390762/67455683-1c22da80-f67a-11e9-9a4c-96c57c4a6d55.png)
ipad image - totally different width
![image](https://user-images.githubusercontent.com/36390762/67455709-30ff6e00-f67a-11e9-9ae8-165a2958b4b8.png)
also ipad but display is cut off on both sides.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by DavidFW1960** [comment]
Note also...
![image](https://user-images.githubusercontent.com/36390762/67455900-bf73ef80-f67a-11e9-8c52-2fe56c3b58e4.png)
The theme used is the same but the switches are now using different variables I think?

**Comment by DavidFW1960** [comment]
If I display the console, the very left column totally collapses
![image](https://user-images.githubusercontent.com/36390762/67456931-fdbede00-f67d-11e9-92a7-646a47793bf4.png)

**Comment by DavidFW1960** [comment]
![FBF992BE-52D5-46C0-AF5E-FBFA9096AADC](https://user-images.githubusercontent.com/36390762/67465756-81ce9100-f691-11e9-9c12-c977dc229ca2.png)

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/4127

**Comment by DavidFW1960** [comment]
@bramkragten the PR didn't fix this. Better on PC Chrome but still really bad on iOS mobile app and chrome.

**Comment by iantrich** [comment]
A new frontend release has not been cut since the first beta so you shouldn't have seen any improvement

**Comment by DavidFW1960** [comment]
Thanks Ian. I thought 0.101.0.b1 would fix it (incorrectly of course)
Is there any way I can manually update that file in the container? I can't find that file anywhere in the homeassistant container (using Portainer)

**Comment by iantrich** [comment]
No, it is not editable
