### ISSUE TITLE
Delete View button in View Configuration not red

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4126]
**Home Assistant release with the issue**:
0.101.0b0

![del-view](https://i.imgur.com/qx3h6S7.jpg)

The "Delete View" button added in https://github.com/home-assistant/home-assistant-polymer/pull/4067 is not red (despite screenshot showing it in red) and appears to be using secondary text color instead.

So I suspect it might have something to do with the Panel mode descriptive text (which uses secondary text color and appears directly above it) from https://github.com/home-assistant/home-assistant-polymer/pull/4043 overflowing into it somehow? Just guessing. Either way, should be red text.

**Comment by bramkragten** [comment]
It is actually because the icon used to be grey. I remember when I made it, it was red, but Paulus didn't wanted it to stand out and wanted it grey 🙂
