### ISSUE TITLE
Long names don't wrap in dialogs on Entity Registry

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4130]
**Home Assistant release with the issue:**
0.100.b0

Long device names don't wrap in the dialogs on Entity Registry, they get truncated instead. This is a Z-Wave sensor using the default name, it shows the overly long manufacturer name but cuts off the most important part - that it's a door sensor. 

So even if the user wanted to rename / shorten this, the name being truncated makes that a lot more difficult.. Should wrap to a second line I think.

![image](https://i.imgur.com/0F8YuhF.png)

Here are some names that can be tested with:
`Linear (Nortek Security Control LLC) WADWAZ-1 Door/Window Sensor`
`Linear (Nortek Security Control LLC) WADWAZ-1 Door/Window Sensor Alarm Level`
`Linear (Nortek Security Control LLC) WADWAZ-1 Door/Window Sensor Battery Level`

Possibly related issue: https://github.com/home-assistant/home-assistant-polymer/issues/4118 (that one only occurs on mobile, this particular issue happens on desktop too).

**Comment by joshmcrty** [comment]
This and #4118 could be solved by updating the ha-paper-dialog component to modify the white-space style for the title. This would potentially affect a lot of other parts of the UI that use ha-paper-dialog too, for better or worse.

```
export class HaPaperDialog
  extends mixinBehaviors([haTabFixBehaviorImpl], paperDialogClass)
  implements PaperDialogElement {
  static get template() {
    return html`
      <style include="paper-dialog-shared-styles">
        :host {
          --paper-font-title_-_white-space: normal;
        }
      </style>
      <slot></slot>
    `;
  }
}
```
Would this approach be preferable or should we just update the styles for specific uses where the text is likely to need to wrap like this issue and #4118?

**Comment by joshmcrty** [comment]
For now I can submit a PR to wrap the title in this specific use-case. I think it makes sense here to show the full entity name so users see it all for reference when renaming an entity.
