### ISSUE TITLE
Move save login prompt as it overlaps certain UI features such as add integration

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#4138]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
Been around for a while but I only really notice this in my dev instance, probably started when new auth system was put in place?

**Last working Home Assistant release (if known):**
Before new auth as the prompt did not exist
**UI (States or Lovelace UI?):**
Neither, Configuration -> Integrations

**Browser and Operating System:**

Chrome on Desktop and also mobile, probably impacts all devices and browsers as both buttons are in the same location
**Description of problem:**
When a user navigates to Configuration and selects Integration without saving the login prompt or dismissing it the Add Integration icon is hidden behind it.  

![image](https://user-images.githubusercontent.com/1634145/67597226-7b86f600-f71f-11e9-98ae-eba9049d953b.png)

![image](https://user-images.githubusercontent.com/1634145/67597247-8b063f00-f71f-11e9-88d4-aa56a3a4a6b9.png)

**Javascript errors shown in the web inspector (if applicable):**

```
n/a
```

**Additional information:**
We should probably move this or allow the button to be above if its shown, either way not good to have it hidden.  Maybe a better location is in the header since its completely out of the way?

**Comment by dshokouhi** [comment]
Looks like Person, Area registry, Script/Automation editor all have this issue too.

**Comment by balloob** [comment]
This is not an issue. Just press one of the buttons to dismiss it.
