### ISSUE TITLE
frontend.reload_themes service doesn't work for packages

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4153]
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.0b2

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
The `frontend.reload_themes` service does not seem to work when using [packages](https://www.home-assistant.io/docs/configuration/packages/).

I have all of my themes located in `/config/system/ui/themes.yaml` rather than inside of `configuration.yaml`

After I call service, the themes get removed from the dropdown on the profile page, but they never load back in. Will just say "No themes" or something. No errors appear in the logs as far as I can tell.

When I have the theme(s) inside of `configuration.yaml` the service works as expected. The other "reload" services like automations and scripts work with packages, but not this one.

**Comment by Mariusthvdb** [comment]
just to be sure, you have set the full path to the themes in the package itself:

```
frontend:
  themes:
    happy:
```
in the file themes.yaml, and have pointed the packages: to the correct folder?

**Comment by Dino-Tech** [comment]
I can confirm the same results using path: `/config/packages/theme_control.yaml` and `packages: !include_dir_named packages` with structure:
```yaml
frontend:
  themes:
    Dark-N-Clear:
```

**Comment by iantrich** [comment]
@bramkragten this would be related to the backend service, correct?

**Comment by bramkragten** [comment]
Yes
