### ISSUE TITLE
Thermostat Card Title Size

### ISSUE THREAD

**Issue by mynameisdaniel32** [home-assistant/home-assistant-polymer#4156]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.0

**Last working Home Assistant release (if known):**
0.100 (at least I didn't notice it)

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome (latest)

**Description of problem:**
See screenshot below, my two thermostat cards have different title font sizes. The 'Bedroom AC' one is too large and interferes with the slider. Resizing the frame changes it and seems to fix it at almost all other ratios, however this default one (full screen on a 1920x1080) seems a bit tight. Happens on all views.

![image](https://user-images.githubusercontent.com/24840952/67911222-c13b3700-fbd5-11e9-87da-d688103f0216.png)

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

**Comment by niccolobusato** [comment]
same here

**Comment by kvvoff** [comment]
Same with my ha 0.101.3

**Comment by kvvoff** [comment]
Same with my ha 0.101.3
Pc:
![IMG_20191111_181751](https://user-images.githubusercontent.com/38342171/68598357-b030d680-04af-11ea-8c40-5af152661d76.jpg)

Phone:
![Screenshot_20191111-181556](https://user-images.githubusercontent.com/38342171/68598368-b6bf4e00-04af-11ea-8c91-5b736d6c6ced.jpg)
