### ISSUE TITLE
First tab user has "visibility" to should load up instead of default

### ISSUE THREAD

**Issue by D3nnisd** [home-assistant/home-assistant-polymer#4158]
The visible setting , introduced in 0.101, on tabs always opens the default tab on reload.  even if the user has no visibility on it. I use HomeAssistant on a tablet and i want to use it only on 1 screen . It still goes to the default path. 

I feel it should go to the first tab it has visibility on.

**Comment by iantrich** [comment]
See explanation here: https://github.com/home-assistant/home-assistant-polymer/issues/4330
