### ISSUE TITLE
Add tabindex to Lovelace elements

### ISSUE THREAD

**Issue by iantrich** [home-assistant/home-assistant-polymer#4159]
- [ ] thermostat-card: slider (not sure if interaction with it is possible yet, but should be able to use arrow keys)
- [x] thermostat-card: mode icons
- [ ] light-card: slider
- [x] light-card: icon
- [x] glance-card: state-badges
- [x] entity-button: button
- [ ] media-player: (want to do a rewrite before we tackle this)
- [x] picture-elements: all the elements
- [x] picture-glance: image
- [x] picture-glance: icons
- [x] picture-entity: image
- [x] plant-status: haven't verified as it is not on the demo, but assume no values are tabbable
- [x] shopping-list-card: clear items icon
- [x] sensor-card: card itself
- [x] weather-forecast: card itself
- [x] state-label-badge

**Comment by iantrich** [comment]
@balloob @bramkragten 
should we be considering hold/double_tap actions via keyboard?

**Comment by dshokouhi** [comment]
@iantrich according to WCAG everything that has user interaction must be keyboard accessible.  You have to consider users who can't use a mouse or can't see the screen.

https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation.html

We did a lot of accessibility improvements and the WCAG rules are what you should base it all off.

**Comment by dshokouhi** [comment]
I also just checked out the demo site and we should ensure that when any dialog is open the user cannot tab behind the dialog.  They must stay within the dialog until it is closed.  This might be in scope here but not 100% on that.

![image](https://user-images.githubusercontent.com/1634145/67985463-26972400-fbe6-11e9-82e6-740da58777dd.png)

**Comment by iantrich** [comment]
I believe round-slider will need to add focus on the handles https://github.com/thomasloven/round-slider/issues/9

**Comment by iantrich** [comment]
Thinking that it would be nice to add paper-ripple on our focused items, rather than the current boxy outline

**Comment by iantrich** [comment]
Last commit added this to picture-glance icons
![image](https://user-images.githubusercontent.com/1287159/68001360-bf06c600-fc31-11e9-8530-90e47cdbc542.png)
Versus this
![image](https://user-images.githubusercontent.com/1287159/68001377-d645b380-fc31-11e9-87e1-0fa2966a8d0c.png)

I think it looks a lot better. Color should probably be part of the theme vars. Trying to determine where this should all apply; mostly inner element, I think. e.g. doing this to the entity-button doesn't make sense

**Comment by thomasloven** [comment]
The slider has been fixed in version 0.3.2. Thanks for the push - I've been meaning to do that.
There's been some other changes too since 0.2.0, but I believe it should still work as a drop-in replacement for us.

**Comment by iantrich** [comment]
Thanks @thomasloven !
