### ISSUE TITLE
Shortcut to edit automations and scripts from more-info dialogs

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4162]
I think it'd be useful to have an edit icon on the more-info dialogs for Automations and Scripts. This would open it inside of Script Editor or Automation Editor where the user can easily rename it, tweak the actions, etc.

It's a small convenience feature that makes sense imo. Saves a few clicks and makes everything feel more interconnected. Mockup below - the pencil icon in the top right would open the script inside of Script Editor.

![edit-script](https://i.imgur.com/7Nsbjsv.jpg)

Edit:

Also would be useful on Scenes, and Zones now.

**Comment by bramkragten** [comment]
Implemented
