### ISSUE TITLE
Ecobee / generic thermostat ring broken in idle mode

### ISSUE THREAD

**Issue by ronaldheft-usds** [home-assistant/home-assistant-polymer#4175]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

.101

**Last working Home Assistant release (if known):**

.100.3

**UI (States or Lovelace UI?):**

**Browser and Operating System:**

iOS 13

**Description of problem:**

When the thermostat is idle mode, the ring extends past the ring boundaries.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

![5E96FA98-DBC7-4CBD-8E8B-9C7F1D24341D](https://user-images.githubusercontent.com/52176593/68070045-f616cd80-fd3e-11e9-9957-a47c73ea53b2.png)

**Comment by bramkragten** [comment]
@thomasloven any idea why this would happen?

**Comment by thomasloven** [comment]
Does it only happen in idle mode? Only at that exact position (400 degrees? Really?)?

Could you show me the attributes of your climate device while in idle mode?
I.e. this:
![Skärmavbild 2019-11-02 kl  13 40 47](https://user-images.githubusercontent.com/1299821/68071061-71e03c80-fd76-11e9-9ee5-0b6fc736e4f4.png)

**Comment by thomasloven** [comment]
I can reproduce the problem when `temperature` is much higher than `max_temp`. Sounds like a backend problem if that is possible...

@iantrich There's a check if `temperature` is finite. Could that have to do with this?

**Comment by ronaldheft** [comment]
I’ve always seen 400-degrees from my ecobee when in vacation mode. When not in idle/vacation mode, everything looks okay.

![EAAFCBF8-4E51-4654-8749-CC399373F88D](https://user-images.githubusercontent.com/1143112/68071276-46962700-fd4f-11e9-8722-6603ad1ab63d.png)
![74FA8B9E-3AD6-4343-B99C-5B4FC8C0B378](https://user-images.githubusercontent.com/1143112/68071277-46962700-fd4f-11e9-84b5-f9c5337a44aa.png)
![A68BBED1-E0A2-411B-B1E4-F4B49BBA9EE1](https://user-images.githubusercontent.com/1143112/68071278-46962700-fd4f-11e9-90d8-fc19b7427e68.png)

**Comment by ronaldheft** [comment]
Vacation settings if this helps:

![D7122189-F633-4352-B8AC-0CEAC2F0D219](https://user-images.githubusercontent.com/1143112/68071347-26b33300-fd50-11e9-820d-207a8b56a23a.png)

**Comment by ronaldheft** [comment]
Btw, myself and OP are the same person. Accidentally logged this under my work account. 🤦‍♂️

**Comment by bramkragten** [comment]
Yeah the 400 degrees seems like a backend issue, is a bit hot...
