### ISSUE TITLE
Using the Rename option in ZHA Integration to rename Entity renames all sensors associated with it

### ISSUE THREAD

**Issue by stratplayer** [home-assistant/home-assistant-polymer#4177]
Please see attached PDF for steps to replicate and images

**Home Assistant release with the issue:**
v0.101.2

**Browser and Operating System:**
Firefox v70.0
Hassio O/S running on VirtualBox VM

**Description of problem:**
Renaming an entity in ZHA integration prompts to rename the entity_ids. Clicking Ok or Cancel renames them regardlessly (see PDF)
[Add new device into ZHA integration.pdf](https://github.com/home-assistant/home-assistant-polymer/files/3800523/Add.new.device.into.ZHA.integration.pdf)

**Comment by bramkragten** [comment]
It asks if you want to rename the entity ids. We will always rename the names of the entities if it contains the device name you where changing. (And this has nothing to do with ZHA)
