### ISSUE TITLE
Device Automation - no trigger and list not showing properly

### ISSUE THREAD

**Issue by boojew** [home-assistant/home-assistant-polymer#4178]
**Home Assistant release with the issue:**
0.100.0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

I am running hassio 0.100.0. 
 
**Integration:**

**Description of problem:**
The new device automation options do not get sorted properly on FF or Chrome (OSX). Additionally, any supported entity I choose (e.g. a Light) shows "unknown type" for trigger and "unknown action" for action. The entity I chose to show in the demo is a light.
![Screen Recording 2019-10-31 at 11 24 54 PM](https://user-images.githubusercontent.com/1015566/68000465-9df4a400-fc36-11e9-938e-4b869950a8a5.gif)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
Please update before reporting an issue, the device picker was updated in the last release.
