### ISSUE TITLE
Mobile app moves entire card when switching on/off

### ISSUE THREAD

**Issue by alexmuntean** [home-assistant/home-assistant-polymer#4179]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.2

**Last working Home Assistant release (if known):**
0.100.x
**UI (States or Lovelace UI?):**
lovelace ui

**Browser and Operating System:**
safari latest, ios

**Description of problem:**
when I'm toggling the switches on/off on any theme included default Lovelace UI (the white and blue one) it moves the cards completely

**Javascript errors shown in the web inspector (if applicable):**
can't see in mobile
```

```

**Additional information:**

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2796003/68090001-82c4a700-fe77-11e9-9508-a9eb6c0dd778.png">

**Comment by alexmuntean** [comment]
this is happening on any theme... this theme is more visible because probably it helps you see what's going on. it looks like the card gets a left position when slider of switch is going left. when clicking on it to go to right (meaning on state) it's coming to normal state and it looks good

**Comment by Mossi777** [comment]
Personally I find it annoying. I’m interested in the outcome of this issue.

**Comment by bramkragten** [comment]
Is this only in Safari? Does it work in Chrome on the desktop in mobile device view?

**Comment by SeanPM5** [comment]
I can reproduce this in the iOS 2.0b app, happens whenever any switch is toggled off. Screen recording: https://streamable.com/2p17h

Doesn't seem to occur on the demo website in mobile Safari, and doesn't seem to happen in the 1.5 app either (though I haven't tested extensively there).

**Comment by iantrich** [comment]
potentially related to this? https://github.com/home-assistant/home-assistant-polymer/pull/3842

**Comment by bramkragten** [comment]
Is it just in the app not in mobile Safari on the same page?

**Comment by SeanPM5** [comment]
Just tested, same issue occurs in mobile Safari too on my setup. So it’s not just the app but Safari in general. I am on iOS 13.2.

**Comment by rgruyters** [comment]
Here same issue here. See https://streamable.com/9ceos

Running hass.io version 0.102.2. Tried to disable all custom resources, but issue still exists.
