### ISSUE TITLE
Add entity picker to automation editor call service action

### ISSUE THREAD

**Issue by Bergasha** [home-assistant/home-assistant-polymer#4180]
**Is your feature request related to a problem? Please describe.**
It would be great to have entity_id as a dropdown option in the Automation ui editor under Actions,

**Describe the solution you'd like**
This dropdown could go between Call service and Service data

**Additional context**
After creating an Automation in the ui I then have to navigate to developer tools- States just to find the name of the entity I want to use then go back to Automations and add it.

**Comment by bramkragten** [comment]
We should add the functions of `developer-tools/service` to the automation editor service call.
