### ISSUE TITLE
Unable to login using HA Auth on iOs Safari 9.3.5 using HA 0.101.2

### ISSUE THREAD

**Issue by DeviousPenguin** [home-assistant/home-assistant-polymer#4182]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

Home Assistant 0.101.2

**Last working Home Assistant release (if known):**

Home Assistant 0.99.x I think

**UI (States or Lovelace UI?):**

States

**Browser and Operating System:**

An iPad 3rd gen running iOs 9.3.5, I'm using Tileboard as a UI to control Home Assistant, and I'm using HA's Auth system to provide access.

**Description of problem:**

On older versions of HA I was able to Login with the iPad, however with the latest version there is are no form fields to put a username and password in. Screenshot here:

![ipad_login_fail](https://user-images.githubusercontent.com/11376139/68105978-11691080-fed8-11e9-98ab-821136c6542b.png)

**Javascript errors shown in the web inspector (if applicable):**

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
in
custom-elements-es5-adapter.js
```

**Additional information:**

I have the cable needed to do remote debug in safari if needed.

**Comment by Sloth-on-meth** [comment]
Same issue here. Wanting to put an ipad on the wall, can't do it without the login :)

**Comment by Sloth-on-meth** [comment]
confirmed to be broken on every imaginable browser running on 9.3.5 because they all use the same webview. there go my plans for a wallmounted ipad :(

**Comment by bramkragten** [comment]
I'm planning to look in to this shortly.

**Comment by Sloth-on-meth** [comment]
im sorry for pinging you about this but i am not sure how to do it properly; how can i edit my polymer to include this new commit? thank you for fixing it so quickly

**Comment by iantrich** [comment]
@Sloth-on-meth it will be in the next release

**Comment by DeviousPenguin** [comment]
> it will be in the next release

That's great, thanks very much for fixing this :)
