### ISSUE TITLE
Thermostat card decimals different

### ISSUE THREAD

**Issue by kmlucy** [home-assistant/home-assistant-polymer#4209]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
101.3

**Last working Home Assistant release (if known):**
N/A

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 78/Docker

**Description of problem:**
The current temperature is displayed without a decimal value, but the set temperature is displayed with a decimal. They should be consistent within the same card. I'd personally prefer just the integer, but I'd be happy as long as they are consistent.

![image](https://user-images.githubusercontent.com/13952475/68690007-511aa280-053f-11ea-872b-bbbb57dba696.png)
![image](https://user-images.githubusercontent.com/13952475/68690033-5d066480-053f-11ea-9c4f-d6dd117d4eab.png)

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
N/A

**Comment by Molodax** [comment]
My thermostat cards display decimals for the current temperature when the decimal is not equal to 0. I believe that decimals are important especially if it is in Celsius.

**Comment by kmlucy** [comment]
I'm fine with that behavior, I'd just like it to be consistent. So if the decimal is hidden if zero for the current temperature, it should be the same for the set temperature(s).

**Comment by Molodax** [comment]
> I'm fine with that behavior, I'd just like it to be consistent. So if the decimal is hidden if zero for the current temperature, it should be the same for the set temperature(s).

I like consistency too but do not see the issue in this particular case.
What if the current temperature will show a decimal, e.g. 22.5°C, but your set temperature would be 23°C, still would be inconsistent.

**Comment by kmlucy** [comment]
I don't see that as inconsistent; it would just be showing as many places as are needed. It would also improve the function for °F, where most thermostats do not report past the integer, so there is no need to show the decimal at all (as is the case with my screenshots above).

**Comment by kmlucy** [comment]
It looks like pull request #4221 would fix this.

**Comment by bannhead** [comment]
My PR relies on thermostat specifications: if it declares whole integer as temperature step, then the card report current and set temperatures consistently. If it is not declared, uses the default logic.

**Comment by kmlucy** [comment]
That's a better solution than just hiding/showing depending on the value.

**Comment by Molodax** [comment]
> That's a better solution than just hiding/showing depending on the value.

I disagree that it is better solution, it will worsen  the interface.
I don't see the point to show a decimal in the current temperature when it is equal to 0. You might want to not show a 0 decimal in set temperature if it is so important.

**Comment by Molodax** [comment]
> My PR relies on thermostat specifications: if it declares whole integer as temperature step, then the card report current and set temperatures consistently. If it is not declared, uses the default logic.

Even if thermostat cannot be set using a decimal, e.g. 0.5°C, it doesn't mean that not displaying it in the current temperature is correct.
22°C, 22.5°C and 23°C are three differences in temperature.

**Comment by bannhead** [comment]
> > My PR relies on thermostat specifications: if it declares whole integer as temperature step, then the card report current and set temperatures consistently. If it is not declared, uses the default logic.
> 
> Even if thermostat cannot be set using a decimal, e.g. 0.5°C, it doesn't mean that not displaying it in the current temperature is correct.
> 22°C, 22.5°C and 23°C are three differences in temperature.

I did not express myself clearly. The behavior of the "current temperature" parameter is in no way modified by my code.
I simply took the interval value, already used in the slider, to consistently show the "set temperature" parameter. Therefore, if the thermostat has one-degree steps, the value shown will be integer.

**Comment by Molodax** [comment]
Thank you for explanation,  @bannhead 
Now it sounds much better and makes sense :)

**Comment by bannhead** [comment]
If you like it could you remove the downvote please? 🙂

**Comment by kmlucy** [comment]
Closed by #4221 in 0.103
