### ISSUE TITLE
Deleting Entity from Entities card causes

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant-polymer#4211]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 101.3

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** Lovelace, Entities card.  Removing entities from card through ui by using the x (delete) button.

**Browser and Operating System:** All.  Verified by using the demo site to replicate bug.

**Description of problem:**

When you delete an item from entities list through the ui, the X button on the item that shifts up (to replace it) will not work.  The x button will no longer capture delete events and will now only expand the menu.  To replicate:

1.  Go to https://demo.home-assistant.io/#/lovelace/0
2.  Configure the UI
3.  Edit any Entities card.
4.  Delete top item by using X button next to the down arrow on the right side of the ComboBox.
5.  Attempt to delete the item that is now the top item.  You'll notice that a combobox dropdown will appear instead of removing the item.

**Javascript errors shown in the web inspector (if applicable):**  No errors.
**Additional information:** None

**Comment by bramkragten** [comment]
Is already fixed
