### ISSUE TITLE
Scrollbars on Toggle off in entity cards

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4212]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
since 0.101.x i think, but also on 0.102.0b0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
LL

**Browser and Operating System:**
Firefox, Chrome, iOS app

**Description of problem:**
On toogle something (switch, input_boolen, automation) off, scrollbars show up for a short time.
![scrollbars](https://user-images.githubusercontent.com/26381449/68804109-4fe19680-0661-11ea-962f-8491043fefcd.gif)
BUT only if the card with the toogle is on the right side of the browser window.
On the left or in the middle, everthing is ok.

This happens in the iOS app on every toogle (all on the right side here)

Also when i toogle in the iOS app, i see it in the browser and vice versa. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
https://community.home-assistant.io/t/cards-shrink-when-turning-devices-off-ios-app-version-1-5-1-hass-io-version-0-101-3/147938?u=vdrainer

**Comment by deluxestyle** [comment]
I have the same issue

**Comment by csouers** [comment]
Same issue here. Hassio on Ubuntu 18.04.2. HA version 101.3. Using latest version of iOS beta app 2.0 on latest stable iOS for iPhone X. 

![46CB69B9-E31A-4815-A09C-2F1229B83728](https://user-images.githubusercontent.com/16481750/68828610-4281d780-0674-11ea-83b2-cb58beb259cc.gif)

**Comment by zakariajado** [comment]
I have the same issue here, wondering if right side scrolling bar can be disabled!?

**Comment by mspiridakis** [comment]
Same here
