### ISSUE TITLE
History showing an empty page when gui_language != English

### ISSUE THREAD

**Issue by onkelbeh** [home-assistant/home-assistant-polymer#4229]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.102.0_beta1 / 20191114.0

**Last working Home Assistant release (if known):**
0.102.0_beta0 / 20191108.0

**UI (States or Lovelace UI?):**
Frontend version: 20191114.0 - Lovelace autogen

**Browser and Operating System:**
Firefox 70.0.1 on OS X, also tried actual Chrome and Safari

**Description of problem:**

History only shows an empty white page if frontend language is set to any language but english.
**When set to english, everything works fine.**

**Javascript errors shown in the web inspector (if applicable):**
No Errors in Browser, but
```
2019-11-16 20:40:43 ERROR (MainThread) [frontend.js.latest.201911140] https://hass.edevau.net:8443/frontend_latest/app.1db108b5.js:899:12481 uncaught exception: SyntaxError: Expected "=", "\\#", "\\\\", "\\u", "\\{", "\\}", "offset:" or [^{}\\\0-\x1F\x7f \t\n\r] but "\\" found.
```
appears in **server.log**

**Additional information:**

**Comment by VDRainer** [comment]
Will be fixed in next beta. https://github.com/home-assistant/home-assistant-polymer/pull/4225

**Comment by onkelbeh** [comment]
Can confirm it's OK again in Home Assistant 0.102.0b2 with Frontend-Version: 20191118.0.
Thanks a lot!
