### ISSUE TITLE
Default icon for light groups

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4242]
Below screenshot is of a brand new install, uncustomized using autogenerated layout. This is what every new user will see. Two of these entities are light groups, and two are singular bulbs. You wouldn't know this based on the icons though, since they're identical.

![image](https://i.imgur.com/l6T6RO7.png)

Home Assistant already knows which ones are groups ("is hue group: true" in more-info dialogs etc).  If it's a light group, I think it should default to one of the below icons instead for better clarity.

| `mdi:lightbulb-multiple` | ![mdi-multiple](https://i.imgur.com/P1hD98k.png) |
|--------------|---|
| `mdi:lightbulb-group`  | ![mdi-group](https://i.imgur.com/DtbbENx.png) |

**Comment by sophof** [comment]
Nice idea. By chance I just wanted to add these icons manually, but it looks like they aren't even working in Home Assistant at the moment? Are they really new maybe?

**Comment by Mariusthvdb** [comment]
+1, and not only for hue groups, Tradfri also creates these (if one allows)

and yes, these icons aren't yet imported, but are released on materialdesignicons, wo soon will be available in HA.

**Comment by iantrich** [comment]
This does not look to be a standard attribute of groups; Hue/Tradfri may be exceptions, but even our own [light group](https://www.home-assistant.io/integrations/light.group/) gives no indication that it is a group.
I think this would have to be an arch issue first to settle on a standard for representing a group in the schema
