### ISSUE TITLE
Light card icon and slider

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4251]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.102.0b3

**Last working Home Assistant release (if known):**
0.102.0b2
**UI (States or Lovelace UI?):**
LL

**Browser and Operating System:**
FF and Chrome

**Description of problem:**
Since the last beta the icon of the light card is a little to big and the knob of the slider is missing.

b2
![20191120_15:17:14_001](https://user-images.githubusercontent.com/26381449/69246363-e43f8200-0ba8-11ea-9d54-9495a011bc18.png)

b3
![20191120_15:10:41_001](https://user-images.githubusercontent.com/26381449/69246176-81e68180-0ba8-11ea-9506-523f5f778946.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
cc @thomasloven

**Comment by bramkragten** [comment]
I think we should give the thermostat a max width too like the light and the text should be a little smaller as it nearly touches the slider:

![image](https://user-images.githubusercontent.com/5662298/69253107-5e293880-0bb4-11ea-82f1-d14c56611f8a.png)

**Comment by bramkragten** [comment]
The knob is only missing when the light is off right? It still functions by clicking the icon to turn the light on and then sliding?

**Comment by bramkragten** [comment]
And while we are at it, it also bothers me that the circle stays after you clicked on the icon.
![image](https://user-images.githubusercontent.com/5662298/69254038-e2c88680-0bb5-11ea-8307-b2f63d481297.png)

**Comment by VDRainer** [comment]
I think the light card without the slider looks a little poor.

**Comment by bramkragten** [comment]
> I think the light card without the slider looks a little poor.

Was just checking if it was still functional, was not even aware it was changed before you mentioned it :-)

**Comment by iantrich** [comment]
@VDRainer It the light doesn't support brightness, there is no slider rendered, but there would still be a more-info button...which makes me think this is not the light-card that you are showing?

**Comment by bramkragten** [comment]
No, I can confirm the issue @iantrich

**Comment by VDRainer** [comment]
:smile: It's a screenshot from the [docs](https://www.home-assistant.io/lovelace/light/) where i painted the slider away.

**Comment by iantrich** [comment]
I'm so lost...? @bramkragten what issue? @VDRainer what was the point of editing a screenshot from the docs?

**Comment by VDRainer** [comment]
Well, i had the fear that Bram wanted to remove the slider when the light is off.
> And while we are at it, it also bothers me that the circle stays after you clicked on the icon.

and i wanted to show him that the card looks poor without a slider.
He edited his comment after that.

**Comment by bramkragten** [comment]
> I'm so lost...? @bramkragten what issue? @VDRainer what was the point of editing a screenshot from the docs?

Ok we are all lost, with the circle I didn't mean the slider, but the focus circle behind the icon.

And I misread things with the issue @iantrich...

**Comment by iantrich** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by iantrich** [comment]
@bramkragten why do you think paper-icon-button will fix it? It appears to be an issue with not releasing focus

**Comment by bramkragten** [comment]
It will not fix it, was just a side note...

**Comment by thomasloven** [comment]
> I think we should give the thermostat a max width too like the light and the text should be a little smaller as it nearly touches the slider:

🤦‍♂ I never tested it with non-integer temperatures... 

About the nomenclature, the *Slider* consists of a *Bar* and a *Handle*. The Handle is hidden when the light is off.

The ripple (shadow circle) is still visible because the button is still focused after clicking, indicating that you can activate it with Enter. I just noticed that problem after commiting the final changes...
