### ISSUE TITLE
[0.102.0b3] Thermostat card does not respect theme font color

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/home-assistant-polymer#4254]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.102.0b3

**Last working Home Assistant release (if known):** 0.102.0b2

**UI (States or Lovelace UI?):** Lovelace UI

**Browser and Operating System:** Chrome, Windows 10 1909

**Description of problem:**
Since the last update, the thermostat card does not respect the theme font color:
![Screenshot_2019 11 20_23h57m08s_008_](https://user-images.githubusercontent.com/1368405/69285569-7cf9f000-0bf1-11ea-8d68-40400c1eee85.png)

Also the font of the current temperature seems a little bit to big

**Comment by gary-reyes** [comment]
I see this too.
I am using the amoled theme and cannot see anything since the theme is black.
