### ISSUE TITLE
Light card broken

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-polymer#4256]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.102.0

**Last working Home Assistant release (if known):** 0.102.0b2

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Android / Chrome, Linux / Firefox

**Description of problem:**
Light cards without a slider are not displayed properly anymore. New they are just boxes with text but without icon.
![grafik](https://user-images.githubusercontent.com/15657682/69315728-75f5d080-0c37-11ea-9c28-9a5d98cfb473.png)

**Javascript errors shown in the web inspector (if applicable):**

```
No error
```

**Additional information:**

**Comment by gary-reyes** [comment]
I see this too. 
The light entity I am using does not support brightness. I had to go to into the customize menu and manually set supported features to 1 to have the card show up properly

**Comment by Santobert** [comment]
Additional information: all broken cards represent esphome devices. I don't know if that's relevant.

**Comment by homeassistanthomegear** [comment]
Seem to apply only for lights based on switches:
`  - platform: switch
    name: MagicMirror
    entity_id: switch.magicmirror`

**Comment by bramkragten** [comment]
It applies to every light that doesn't support brightness. Fixes by https://github.com/home-assistant/home-assistant-polymer/pull/4257
