### ISSUE TITLE
Generic Thermostat font color issue

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant-polymer#4261]
> **Checklist:**
> 
> * [x]  I updated to the latest version available
> * [x]  I cleared the cache of my browser
> 
> **Home Assistant release with the issue:**
> 0.102.0
> 
> **Last working Home Assistant release (if known):**
> 0.101
> 
> **UI (States or Lovelace UI?):**
> Lovelace
> 
> **Browser and Operating System:**
> Chrome 78/Docker
> 
> **Description of problem:**
> 

thermostat temperature font is now black, no care about the theme used.
please fix

![Screenshot_20191121-165550](https://user-images.githubusercontent.com/4722227/69357363-3fdf3d80-0c85-11ea-8764-d2617b89a7a4.jpg)

**Comment by niccolobusato** [comment]
same here..
<img width="341" alt="Schermata 2019-11-21 alle 17 55 51" src="https://user-images.githubusercontent.com/44100360/69359105-47541600-0c88-11ea-8e2a-70f0b317baab.png">

**Comment by bramkragten** [comment]
Fixed by https://github.com/home-assistant/home-assistant-polymer/pull/4258

**Comment by sblantipodi** [comment]
Will we see this fix on 0.102.1?

**Comment by bramkragten** [comment]
Yes

**Comment by 3ative** [comment]
Excellent work, here's hoping for a fast turn-a-round for the 0.102.1 update.
I'm using a temp theme to be able to see the display(s) atm.

**Comment by bramkragten** [comment]
0.102.1 including this fix is already released.

**Comment by 3ative** [comment]
@bramkragten 
Oh yeah... Thanks for the info - updating now. #sweet :)
