### ISSUE TITLE
0.102.0 - Netatmo indoor sensors lost.

### ISSUE THREAD

**Issue by antro31** [home-assistant/home-assistant-polymer#4262]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.102.0

**Last working Home Assistant release (if known):**
0.101.3

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Firefox, MacOS
Safari, MacOS
Chrome, MacOS
Firefox, Android

**Description of problem:**

Netatmo integration lost all the indoor sensors. 
This was working in 0.101.3.
I tried to change the name of the indoor sensors, tried to change the API keys. 
Without success..

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

N/A

**Comment by iantrich** [comment]
This sounds like an issue with the integration, not the frontend

**Comment by antro31** [comment]
0.102.0 integrated a new version of pyatmo (3.0.1). Maybe this is the issue. 
I reverted back to 0.101.3. This version works without issue. Maybe then need to integrate pyatmo 3.1.0 instead?

**Comment by bramkragten** [comment]
There is a fix for Netamo in 0.102.1

**Comment by LCerebo** [comment]
I'm using home assistant docker 0.102.1 but the issue is still there, I can't see any Netatmo entities. Am I missing something ?

**Comment by bramkragten** [comment]
They where renamed I believe, maybe search in states?
