### ISSUE TITLE
Problem with light card in iOS app and safari browser

### ISSUE THREAD

**Issue by koles142** [home-assistant/home-assistant-polymer#4273]
**Home Assistant release with the issue:**

0.102.x

**Last working Home Assistant release (if known):**
0.101.x

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io/Docker
**Integration:**

**Description of problem:**
I have problem with light card after update Home Assistant. When light is off, card is not displayed correctly in iOS app and safari browser on macOS. Here is an example: https://drive.google.com/file/d/1zly4GhBqfOcS7qDPnsYLU0gAZ7uywGeH/view?usp=sharing

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by SeanPM5** [comment]
A fix for this should be included in 0.102.2 which was released a few hours ago.

**Comment by koles142** [comment]
I have the latest version of HA - 0.102.2 and unfortunately problem is still active.

**Comment by koles142** [comment]
After reset whole RPi - not only home Assistant server, problem is gone. Issue could be closed.

**Comment by Trefex** [comment]
@SeanPM5 please see issue #523 linked above. Which fix was introduced to solve this issue and how can i see the fix ? I am running 0.103.4

**Comment by SeanPM5** [comment]
@Trefex the issue was https://github.com/home-assistant/home-assistant-polymer/issues/4265 and the fix was https://github.com/home-assistant/home-assistant-polymer/pull/4266 . 

But it's preferable that you create a new issue (and add those links as reference) rather than commenting on the closed/merged ones.
