### ISSUE TITLE
Missing attributes in SCENE_SAVED_ATTRIBUTES 

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-polymer#4279]
**Description of problem:**

The following attributes are missing here:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/data/scene.ts#L21-L51

I'll look up the strings soon

### Counter
-  ATTR_INITIAL - `initial`
-  ATTR_MAXIMUM - `maximum`
-   ATTR_MINIMUM - `minimum`
-   ATTR_STEP - `step`

### Cover
-  ATTR_CURRENT_POSITION - `current_position`
-  ATTR_CURRENT_TILT_POSITION - `current_tilt_position`

### Fan
-  ATTR_OSCILLATING - `oscillating`

### Input datetime
-  CONF_HAS_DATE - `has_date`
-  CONF_HAS_TIME - `has_time`

### Input select
-  ATTR_OPTION - `option`
-  ATTR_OPTIONS - `options`

### Timer
-  ATTR_DURATION - `duration`

### Vacuum
-  ATTR_FAN_SPEED - `fan_speed`
-  `cleaning_mode` is not supported by base vacuum devices

### Water Heater
-  ATTR_AWAY_MODE - `away_mode`
- Be aware that `operation_mode` is equal to `state`, isn't it ?

**Comment by Santobert** [comment]
Should water_heater - `operation_mode` be removed? `reproduce_state` won't use this attribute since it's equal to the state

**Comment by Santobert** [comment]
I'm not aware that there is a `cleaning_mode` for vacuum devices. We only know the `fan_speed`

https://github.com/home-assistant/home-assistant/blob/8933540950cb755b041535bd628710abb122dde5/homeassistant/components/vacuum/__init__.py#L363

https://github.com/home-assistant/home-assistant/blob/8933540950cb755b041535bd628710abb122dde5/homeassistant/components/vacuum/__init__.py#L289

**Comment by bramkragten** [comment]
I used the docs... <https://developers.home-assistant.io/docs/en/entity_vacuum.html>

**Comment by Santobert** [comment]
Hm. I'm afraid they are wrong. I can't find a vacuum that uses this attribute. `reproduce_state` won't use it as well.
