### ISSUE TITLE
Google Assistant after exactly 1 month replies "... that mode isn't available..."

### ISSUE THREAD

**Issue by RRR97** [home-assistant/home-assistant-polymer#4288]
The product itself has worked flawlessly for a month. I have several smart devices controlled through the SmartLife app and Google Assistant Voice Commands with my smart phone. However, one month to the day, this Smart Garage Door Opener no longer is working with Google Assistant. After saying the magic words... "Ok Google, Turn On Garage Door" I am receiving back... "Sorry, that mode isn't available for the Garage Door." which would seem it doesn't know what the command means for this device. Like asking it something like... "... Activate Garage Door". The Smart Life is able to control the door opener still.  However, Google Assistant does reply to the status of the door being either open or closed.
So, I suspect some update for either SmartLife or Google Home around November 14th, 2019.  Upon some investigating observed in Google Assistant the Opener is recognized as a 'SENSOR' but I am not sure if it was always that way or not.

**Comment by frenck** [comment]
I think you are confusing us with Google or Tuya/Smartlife.

Home Assistant is none of them. We are an open-source project for hobbyists that like to build their own private systems.

Please contact SmartLife or Google for these matters. 👍
