### ISSUE TITLE
Light card bug on small screen device when light switched off

### ISSUE THREAD

**Issue by bobvmierlo** [home-assistant/home-assistant-polymer#4291]
**Home Assistant release with the issue: 102.1**

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.): Docker on Synology**

**Integration: Ikea tradfri lights**

**Description of problem: When using the Light card on lovelace UI, there is a strange bug showing a blue overlay when the light is off. This only occurs on small screen devices (iPad, iPhone, Google Home Hub). See [screenshot](https://imgur.com/a/2uWePea).**

**Comment by bramkragten** [comment]
Please update to 0.102.2 this is fixed.
