### ISSUE TITLE
Smoke Detector HomematicIP HmIP-SWSD - Service for Triggering Alarm

### ISSUE THREAD

**Issue by JeWi81** [home-assistant/home-assistant-polymer#4298]
Hello all

I have got seven somke detectors (Type HmIP-SWSD) present in home assistant.
I would like to group them. If one device detects smoke and makes noise, all other six devices should also make noise.

Can anybody describe how to trigger an alarm (smoke detector makes noise)?

In my HA the HmIP-SWSD detector is listed in entity list twice:
> sensor.living_room_smoke_alarm_status and
> binary_sensor.living_room_battery_status

For entities of type "light", I can call a service to switch them on and off, thats clear.
But for entities of type "sensor" or "binary_sensor" I assume there is no service available (what is somehow understandable, since it is a sensor)

Is there any other way of triggering the alarm? Is there an entity missing?

Thank you very much for help. In case this forums is not the right one for this issue, please advice me to the appropriate one.

Jens

**Comment by bramkragten** [comment]
Hi, this place is for issues with the code (bugs) and feature requests for the frontend of Home Assistant. You should ask your question on the forum of on discord:

https://www.home-assistant.io/help/#communication-channels
