### ISSUE TITLE
Language Request

### ISSUE THREAD

**Issue by LiScythe** [home-assistant/home-assistant-polymer#4303]
English Name : Iban Language
Native Name : Iban Language

**Comment by bramkragten** [comment]
Shouldn't the native name be `jaku Iban`?

**Comment by LiScythe** [comment]
Yes. The native is Jaku Iban
Sent from Yahoo Mail on Android 
 
  On Mon, Dec 2, 2019 at 4:14 PM, Bram Kragten<notifications@github.com> wrote:   
Shouldn't the native name be jaku Iban?

**Comment by bramkragten** [comment]
What is your username of Lokalise so I can add you?
