### ISSUE TITLE
Don't use CodeMirror on mobile devices

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant-polymer#4314]
**Is your feature request related to a problem? Please describe.**

Selecting all, deleting everything that is selected and navigation on mobile is PAINFUL with CodeMirror.

Selecting all does not work depending on where you are in the field.

Deleting when any chunk of text that is selected un-selects the chunk and only deletes the last character.

Pressing and holding the delete button only deletes a single letter, it does not delete an entire word after the deletion 'ramps up'.  In fact, it slows down acting like it's deleting whole words but does not.

**Describe the solution you'd like**
Anything but this abomination that is CodeMirror for mobile devices.

**Describe alternatives you've considered**
Use what we had prior to 0.101.

**Comment by iantrich** [comment]
Closing in favor of https://github.com/home-assistant/home-assistant-polymer/issues/4482
