### ISSUE TITLE
Lovelace view: invisible for certain users

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#4316]
**Is your feature request related to a problem? Please describe.**
I use [this](https://github.com/akasma74/Hass-Custom-Alarm) custom alarm integration in my HA and access its view from a tablet running WallPanel for Android app.
It opens the alarm view (http://hassio.local:8123/alarm), but a user can swipe the screen from the left edge and access the sidebar even though it's set to "always hide" (I access HA from the tablet as a normal user).

I would like to allow this user to access only the alarm view for security reasons.

**Describe the solution you'd like**
There is a [visible](https://www.home-assistant.io/lovelace/views/#visible) variable for Lovelace views that accepts `user` variable, i.e users who can access this view.
It would be great to have the `invisible` variable to `view` that acts opposite to `visible`?
Or have another variable (`not_users`?) that lists users who **cannot** access this view. 

**Describe alternatives you've considered**
Using current visible/user variables I need to list all users who can acces every single view (which is a lot) and should not forget to update these lists when creating new users. 

**Additional context**
Based on [this](https://community.home-assistant.io/t/is-it-possible-to-allow-user-to-access-only-one-lovelace-view/152472) conversation

**Comment by iantrich** [comment]
While potentially more initial setup, we determined it to be the better solution so that you don't add a new user and forget to add them to your `invisible` list and now they have access to something they shouldn't. So while it may be more configuration, it is the safer approach.

**Comment by akasma74** [comment]
> While potentially more initial setup, we determined it to be the better solution so that you don't add a new user and forget to add them to your `invisible` list and now they have access to something they shouldn't. So while it may be more configuration, it is the safer approach.

According to this logik, every view should NOT be visible to any user, but that's how it is now because the default value is true. 

I reckon you're a bit overthinking the situation and creating artificial barriers for users that leads to them using custom cards/solutions that are possibly much less safe so lost-lost situation.

**Comment by iantrich** [comment]
Yes, default is true, which implies you do not wish to restrict the view

**Comment by akasma74** [comment]
Ok, and then why it's wrong to say "I want this particular view to be accessible to anyone but users A and B"? What makes it not safe considering the initial unrestricted access?

**Comment by iantrich** [comment]
Because at that point you have said that you do want restrictions on the view and if you were to forget about those restrictions when creating a new user, you would expose the view to them that you didn't intend.
Regardless, there are custom solutions to do this now; e.g. compact-custom-header which also has kiosk mode which would further restrict it to a single view.

All this being said, this is me saying that the core team won't be working on this, but PRs are always welcome.

**Comment by johan149** [comment]
I was also looking for this, it comes really handy to hide some stuff from your children, they like to play with the tablet on the living room, making the house going crazy, also guesses, it would be awesome to give permissions to views independently, so children will only have access to one view to their stuff only.

**Comment by VajraCool** [comment]
I am looking for this feature and found this page, this request has been closed, has it been implemented?

**Comment by pwrsoft** [comment]
You can use the tab's properties as for now:
![image](https://user-images.githubusercontent.com/2362805/151052282-c6372fa4-8464-442d-8695-e28eff9ca5fd.png)
