### ISSUE TITLE
Key displayed instead of translation in French

### ISSUE THREAD

**Issue by royto** [home-assistant/home-assistant-polymer#4325]
**Home Assistant release with the issue:**
Ha Version: 0.102.2
Front end version: 20191119.6

**Browser and Operating System:**

All

**Description of problem:**

In French, for binary state on, instead of displaying the translation (Actif) in french, [%key_id:state::default::on%]  is displayed 

![image](https://user-images.githubusercontent.com/6990995/70275539-9fbe0400-17ae-11ea-942b-8947f76fe8c4.png)

If I switch to English, it is OK

![image](https://user-images.githubusercontent.com/6990995/70275590-bebc9600-17ae-11ea-8ae3-fa314382baf0.png)

Here is the translation in Lokalize for french:

![image](https://user-images.githubusercontent.com/6990995/70275949-7d78b600-17af-11ea-9e47-d30c4d48d743.png)

**Expected behaviour:**

It should display the french translation

**Comment by bramkragten** [comment]
See https://github.com/home-assistant/home-assistant-polymer/issues/4181
