### ISSUE TITLE
New scene button missing on iOS in portrait

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-polymer#4333]
**Home Assistant release with the issue:**

0.103.0b0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

**Integration:**

Frontend: Settings Ui: Scenes

**Description of problem:**
The scenes UI in settings has no + button in portrait but hitting the bottom right corner will open the create new scene dialog.
Works in landscape.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
![7949E64C-6A7F-490F-8D09-51E1E0FD1616](https://user-images.githubusercontent.com/43749346/70373950-ccc50080-18ed-11ea-8b4c-7b33c1707320.png)
![906FBA23-1117-4414-8DB0-54840B0614C4](https://user-images.githubusercontent.com/43749346/70373952-d51d3b80-18ed-11ea-8b53-3ade03a96b0c.png)

**Comment by bramkragten** [comment]
Seems to be fixed on 0.105
