### ISSUE TITLE
No UI shown in Edge

### ISSUE THREAD

**Issue by d1vanloon** [home-assistant/home-assistant-polymer#434]
The UI does not appear in the desktop version of the Edge web browser.

# Steps to reproduce

1. Load Home Assistant in Microsoft Edge
2. Stare into the white abyss

# Comments

The (empty) blue header bar at the top of the screen briefly appears.

# Workaround

Use a different browser. Not always an option.

# Environment

Microsoft Edge 41.16288.1.0
Microsoft EdgeHTML 16.16288
Home Assistant 0.54.0

Browser Extensions:
* uBlock Origin
* LastPass

# Details

Error:

`SCRIPT438: SCRIPT438: Object doesn't support property or method 'byKey'`

Code:
`!function(){"use strict";var n=0,e=0,i=[],t=0,o=document.createTextNode("");new window.MutationObserver(function(){for(var n=i.length,t=0;t<n;t++){var o=i[t];if(o)try{o()}catch(n){setTimeout(function(){throw n})}}i.splice(0,n),e+=n}).observe(o,{characterData:!0}),Polymer.Async={timeOut:{after:function(n){return{run:function(e){return setTimeout(e,n)},cancel:window.clearTimeout.bind(window)}},run:window.setTimeout.bind(window),cancel:window.clearTimeout.bind(window)},animationFrame:{run:window.requestAnimationFrame.bind(window),cancel:window.cancelAnimationFrame.bind(window)},idlePeriod:{run:function(n){return window.requestIdleCallback?window.requestIdleCallback(n):window.setTimeout(n,16)},cancel:function(n){window.cancelIdleCallback?window.cancelIdleCallback(n):window.clearTimeout(n)}},microTask:{run:function(e){return o.textContent=t++,i.push(e),n++},cancel:function(n){var t=n-e;if(t>=0){if(!i[t])throw new Error("invalid async handle: "+n);i[t]=null}}}}}();`

**Comment by d1vanloon** [comment]
Issue persists in new environment:

Microsoft Edge 41.16296.0.0
Microsoft EdgeHTML 16.16296

**Comment by d1vanloon** [comment]
The same error occurs in the new version of Edge:

Microsoft Edge 41.16299.0.0
Microsoft EdgeHTML 16.16299

**Comment by corneyl** [comment]
Can you try with 0.55? For me this solved the same problem in FireFox.

**Comment by d1vanloon** [comment]
Disabling the LastPass extension allows the UI to display (as suggested in #448). Disabling the extension is just a workaround; Home Assistant should work with LastPass enabled.

**Comment by balloob** [comment]
This is not a problem of Home Assistant. We are responsible and are shipping a working frontend, we control exactly what we ship so that we know it works. It is not up to us to try to work around flaws in every extension for every browser ever. Instead,  extensions in browsers need to good citizens and should not break websites.

**Comment by d1vanloon** [comment]
I appreciate your perspective. I'll try to bring this up with LastPass and/or further narrow down the issue.
