### ISSUE TITLE
Menu button not visible in /hassio if width > 870px

### ISSUE THREAD

**Issue by bonanitech** [home-assistant/home-assistant-polymer#4343]
I have the option "Always hide the sidebar" enabled and noticed that the menu button won't be visible in `/hassio` when the width > 870px

<img width="870" alt="Screen Shot 2019-12-10 at 7 35 39 PM" src="https://user-images.githubusercontent.com/29807944/70581865-a241a480-1b86-11ea-8009-fab8dec886ad.png">

<img width="870" alt="Screen Shot 2019-12-10 at 7 35 54 PM" src="https://user-images.githubusercontent.com/29807944/70581870-a5d52b80-1b86-11ea-8d4f-1315a7f7381e.png">

**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

0.102.3

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Safari 13.0.4 and Chrome 79.0.3945.79 on macOS 10.15.2

**Description of problem:**

Described above

**Expected behaviour:**

Menu button always visible

**Relevant config:**

**Steps to reproduce this problem:**

1. Enable "Always hide the sidebar" in the user profile
1. Open the sidebar and click on Hass.io
1. Resize the window

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by bonanitech** [comment]
It also happens when rotating the screen on the mobile app.

![IMG_7253](https://user-images.githubusercontent.com/29807944/70729975-2fdddb00-1cd2-11ea-81ea-75bebdc37a84.PNG)

![IMG_7254](https://user-images.githubusercontent.com/29807944/70729986-33716200-1cd2-11ea-9aa9-cc11569aef3c.PNG)

**Comment by ludeeus** [comment]
I tested that on a fresh dev branch no, it looks like this one is fixed.

**Comment by bonanitech** [comment]
Thanks @ludeeus and @bramkragten

**Comment by bonanitech** [comment]
@ludeeus just to be sure, the solution is not in the current version (20200108.0), right?

**Comment by ludeeus** [comment]
Hassio does not follow Home Assistant frontend releases.

**Comment by bonanitech** [comment]
Oops, my bad. Version 195.
