### ISSUE TITLE
app-header-background-color seems to be overriden by primary-color

### ISSUE THREAD

**Issue by mammuth** [home-assistant/home-assistant-polymer#4348]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
- HA 0.103
- Frontend 20191204.1 - latest

**Last working Home Assistant release (if known):**
Not applicable, since the new variable was just introduced.

**UI (States or Lovelace UI?):**
Lovelace UI / storage mode

**Browser and Operating System:**
- Chrome 81 on macOS
- Chrome 80 on Android

**Description of problem:**

The latest release includes #4269 which introduced new variables for styling the app toolbar background and text color.

This works fine on some views (eg. dev tools), but not for the main lovelace views and for example the settings. 
After reloading, the header colors are correct for a fraction of a second and then seem to be set to `primary-color` (the old behavior).

The chrome dev tools also show that the style definition is overridden with inline styles:
![image](https://user-images.githubusercontent.com/3121306/70699512-8e528b80-1cc9-11ea-9aa4-b93dfcd975c4.png)

**Expected behaviour:**
Theme variables should actually be used.

**Relevant config:**

Theme:
```css
  primary-color: "black"
  app-header-background-color: "white"
  app-header-text-color: "black"
```
The full theme I was experimenting with: https://gist.github.com/mammuth/1ae7d1658b9b0837e7d772d380191c75

**Steps to reproduce this problem:**
1. Create theme
2. Set the two new variables `app-header-background-color` and `app-header-text-color`.
3. Apply theme

**Javascript errors shown in the web inspector (if applicable):**
No JS errors.

**Additional information:**
Related issue: #2709
Related PR: #4269

**Comment by Knapoc** [comment]
Did you install custom header by any chance? I experience the same issue and as soon as I disable custom header the defined app-header-background-color works.

**Comment by mammuth** [comment]
Yes! It didn't came to my mind that I still have it installed, because I was never using it. 

I'll close this issue then.
