### ISSUE TITLE
Lovelace card editor, preview not updating

### ISSUE THREAD

**Issue by stave1989** [home-assistant/home-assistant-polymer#4364]
**Home Assistant release with the issue:**

Home Assistant 0.103.0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**

Raspberry pi 3, with hassio
**Integration:**

**Description of problem:**
When i create a manual card in the Lovelace UI, for example a picture element card. The preview on the right side does not update when i preforme a change. For example moving around a "State-Label" I then have to save, close, and edit again, en then the preview is updated. 
This worked before. 

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by bramkragten** [comment]
Just tested and works for me, got more info or maybe errors in the console?

**Comment by stave1989** [comment]
Her is an example from one of my cards. 
If i for example change the position of the "settings" icon, nothing changes on the preview, i have to save, close and edit again to see the change. 
Only error is: "No visual editor available for: vertical-stack"
![Skjermbilde](https://user-images.githubusercontent.com/57415182/71081520-a45fc080-218f-11ea-9ed6-d64303702d2b.JPG)

**Comment by stave1989** [comment]
It seems that if i cut the vertical-stack, the preview works, but this worked before, and the error is still present "No visual editor available for: picture-elements"

![image](https://user-images.githubusercontent.com/57415182/71081927-76c74700-2190-11ea-833e-1138e36ba852.png)

**Comment by iantrich** [comment]
There is no visual editor for picture-elements, it is not an error, just the truth
