### ISSUE TITLE
Default to "device" for new scripts and automations

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4367]
Currently when you create a brand new script or automation, the action type defaults to "Call service" (it is like this on both simple and advanced mode):

![defaults](https://i.imgur.com/cDiiJRL.png)

Now that device automations are a thing, I think that "Device" would be a more sensible default as that's a lot more beginner friendly.

**Comment by bramkragten** [comment]
I was waiting for more device automations before doing this, but we might do it already :-)
