### ISSUE TITLE
Translation: Add Esperanto to Lokalise

### ISSUE THREAD

**Issue by teslasmoustache** [home-assistant/home-assistant-polymer#4371]
**Is your feature request related to a problem? Please describe.**
There is no Esperanto translation, and I would like to work on one.

**Describe the solution you'd like**
I would like someone to add the Esperanto language to Lokalise so that I can start working on Esperanto translation.

**Describe alternatives you've considered**
Yes, I have considered learning a "useful" language. I decided I didn't want to. I like Esperanto. :stuck_out_tongue_winking_eye: 

**Additional context**
Home Assistant - Polymer Frontend has 50 translation projects in the works on Lokalise, but Esperanto is not one of them.

**Comment by bramkragten** [comment]
What is your user account on Lokalise?

**Comment by teslasmoustache** [comment]
> What is your user account on Lokalise?
Thanks!
Teslasmoustache

**Comment by bramkragten** [comment]
Add you to Esperanto! Happy translating!
