### ISSUE TITLE
Multiple triggers lack spacing between each card in Automation editor

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4389]
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103.4

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
macOS High Sierra / Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Description of problem:**
Triggers no longer seem to have spacing between the cards in the latest (stable) HA. Wasn't sure if this was an intentional change, but there is still spacing between the cards on Conditions and Actions, it's just Triggers that behave like this.

Screenshot below, looks like one tall card rather than two separate ones.

![spacing](https://i.imgur.com/VRykf8t.png)

**Expected behaviour:**
Space between cards (like Conditions and Actions).

**Steps to reproduce this problem:**
1. Go to Configuration -> Automation and add a trigger
2. Now add a second trigger

**Comment by bramkragten** [comment]
This is fixed in dev
