### ISSUE TITLE
Primary-color used erroneously (listicon, saveicon, and hyperlink in logbook)

### ISSUE THREAD

**Issue by krissen** [home-assistant/home-assistant-polymer#4394]
Apologies if I'm off base. Not used to polymer, but been dabbling in theming.

Been running into some elements, that have proven difficult to theme because -- I think -- they are using `primary-color` though there ought to be better alternatives. In short, it renders them invisible.

For instance, `listicon` and `saveicon`. Currently their color is defined by `primary-color`. But wouldn't, say, `paper-item-icon` be a better alternative?

Another element is `a` in the logbook. It also uses `primary-color` for text. Shouldn't it rather be primary/secondary _text_ color, accent, or some such?

**Comment by ludeeus** [comment]
Where did you see list/save? I searched through the codebase and they are not defined anywhere I could find.

As for links, there is a discussion going on here <https://github.com/home-assistant/home-assistant-polymer/pull/3412>

**Comment by krissen** [comment]
Links; perfect, thanks. I'll follow that discussion.

Listicon & saveicon is used in HACS. However, I didn't see it themed in HACS’ code so assumed it to be based on something at a more foundational level -- polymer. That was the case with similar, previous issues I had with HACS. If I'm in the wrong about that, the issue can be closed as links is covered by #3412!

**Comment by ludeeus** [comment]
HACS is a custom component that has a different set of theme options, and it's not on topic here :) 
I don't have the power to close this, but you do.
