### ISSUE TITLE
Reordering automation actions doesn't move the service data

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#4395]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.103.5

**Last working Home Assistant release (if known):** N/A

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Chrome 79, Ubuntu 19.10

**Description of problem:**

Since 0.103, it is possible to reorder actions when you create an automation, but it only moves the "Action type" and "Service" fields, but not the "Service data" fields.

**Expected behaviour:**
Move the whole action-block up/down.

**Steps to reproduce this problem:**

1. Create an automation.
2. Add an action.
3. Fill in the "service details" field (when action type is call service).
4. Click the arrow button to move it up/down.
5. Notice only the type and service move.

**Javascript errors shown in the web inspector (if applicable):** None

**Additional information:** None

**Comment by ludeeus** [comment]
The action data is actually moved to, it's just not rendered so it looks like it stayed there.
If you open the YAML editor on the moved row you will see that it has the correct data.
Going back will force a rerender of that row, and that makes it show the correct data again.

![bug](https://user-images.githubusercontent.com/15093472/71556126-a6017200-2a34-11ea-91bf-813c0c71b356.gif)
