### ISSUE TITLE
Lovelace UI: Group control does not reflect correct state when 'all:true' option is used

### ISSUE THREAD

**Issue by f0ggy987** [home-assistant/home-assistant-polymer#4400]
**Checklist:

- [ X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Home Assistant release with the issue: Home Assistant 0.103.5

**Last working Home Assistant release (if known): Unknown

**UI (States or Lovelace UI?): Lovelace UI

**Browser and Operating System: Chrome & Edge on Windows 10 . Home Assistant Android App

**Description of problem:

Lovelace UI shows incorrect group state.

Using the `all: true` option should require all members of a group to be 'on' for the group to be 'on'. (see: https://www.home-assistant.io/integrations/group/ )

However, the Lovelace UI group control will show 'on' when just a single group member is 'on'.

Checking **developer tools > states** shows the group is 'off' , which is the correct and expected behavior.

I have tested multiple groups containing a mix of switches and lights and see the same (incorrect) behavior.

I am using the default/auto generated Lovelace UI and `group: !include groups.yaml` in my configuration file.

See attached screenshots:

![home_assistant](https://user-images.githubusercontent.com/56989711/71571207-3082b980-2aa7-11ea-95d3-41cc42d4df88.jpg)
![home_assistant_2](https://user-images.githubusercontent.com/56989711/71571208-3082b980-2aa7-11ea-894a-0c480201a7b5.jpg)

**Expected behaviour:**

Lovelace UI group control should reflect the same state as **developer tools > states** and should require all group members to be 'on' to show 'on'

**Relevant config:

Example group:

```
deck_lights:
  name: 'Deck Lights'
  icon: mdi:string-lights
  all: true
  entities:
    - switch.outdoor_switch_1
    - switch.outdoor_switch_2
```

**Steps to reproduce this problem:

1. Create group , include `all: true` option
2. Ensure at least one group member is off
3. Observe the group control in Lovelace UI (will show 'on')

**Javascript errors shown in the web inspector (if applicable): None

**Additional information: None

**Comment by bramkragten** [comment]
Lovelace doesn't use groups like the states UI did, we create a Entity Card https://www.home-assistant.io/lovelace/entities/ that doesn't support this feature.

**Comment by iantrich** [comment]
The docs do not indicate it is not used in Lovelace while other options clearly say they are only for States UI. Could be a nice addition to the entities card IMO

**Comment by Mariusthvdb** [comment]
Since you mention this option only valid for states, please also have a look at hidden: true.
Is kind of confusing this is not indicated in the docs, and then see the entities appear in Lovelace anyhow._

**Comment by ludeeus** [comment]
It will only show hidden entities if you have taken control of the UI, if you are in auto-mode, they will not show.

**Comment by f0ggy987** [comment]
Thanks for the responses.

Apologies in advance as I am new to HA and only a couple of weeks in (transitioning from a different z-wave centric software controller). I am getting everything setup, tested and working 100% before I start customizing the UI.

Are you saying the feature is not supported by lovelace at all, or just not in the auto-generated UI?

Is there an alternative solution/work around? controlling the on/off status of an entire group seems like a common thing to do.

In the entities documentation I see:

**show_header_toggle
(boolean)(Optional)
Button to turn on/off all entities.**

This sounds similar, but it's not clear what states the button will reflect if some entities are 'on' and some are 'off'.

Thanks

**Comment by iantrich** [comment]
@f0ggy987 the header toggle shows "on" if any one of the entities in the card are active and allows for controlling the full group from the toggle.
e.g. using your initial example

| entity  | state |
| ------------- | ------------- |
|switch.outdoor_switch_1|on|
|switch.outdoor_switch_2|off|
|group.deck_lights|on|

**Comment by iantrich** [comment]
Closing as I believe this has been cleared up
