### ISSUE TITLE
Sensor w/ latitude/longitude attributes showing up on the map

### ISSUE THREAD

**Issue by bachya** [home-assistant/home-assistant-polymer#441]
**Home Assistant release (`hass --version`):**
0.54.0

**Python release (`python3 --version`):**
3.5.2

**Component/platform:**
Map/Device Tracker

**Description of problem:**
The [AirVisual platform](https://home-assistant.io/components/sensor.airvisual/) produces sensors that have latitude/longitude attributes. While testing today, I happened to notice that the map was displaying a strange entity; when I clicked on it, it showed the modal window for the AirVisual sensor.

I'm thinking that the issue occurs because of the `drawEntities` function's logic; lines 102-108 of [home-assistant-polymer/panels/map/ha-panel-map.html](https://github.com/home-assistant/home-assistant-polymer/blob/master/panels/map/ha-panel-map.html) show this:

```javascript
if ((entity.attributes.hidden &&
      window.hassUtil.computeDomain(entity) !== 'zone') ||
     entity.state === 'home' ||
     !('latitude' in entity.attributes) ||
     !('longitude' in entity.attributes)) {
   return;
}
```

I'm not sure how to appropriately change this logic, but it seems like a good place to start.

**Expected:**
The sensor shouldn't show up on the map.

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
N/A

**Traceback (if applicable):**
N/A

**Additional info:**
<img width="1280" alt="screen shot 2017-09-26 at 4 43 37 pm" src="https://user-images.githubusercontent.com/47216/30887786-2e0a97e2-a2da-11e7-87f3-0910eb631d2c.png">
<img width="1280" alt="screen shot 2017-09-26 at 4 43 40 pm" src="https://user-images.githubusercontent.com/47216/30887788-30339758-a2da-11e7-8e82-25fe4487932e.png">

**Comment by balloob** [comment]
This is by design. Anything that has a latitude/longitude will be shown on the map.
