### ISSUE TITLE
'Lat' is not showing up

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant-polymer#442]
The [ISS](https://home-assistant.io/components/binary_sensor.iss/) sensor supports the showing of the position on the map and just the coordinates in the frontend

```yaml
binary_sensor:
  - platform: iss
    show_on_map: False
```
It seems that `lat` is only available in **States** but not in the more info dialog.

![iss-1](https://user-images.githubusercontent.com/116184/31115406-79d70a28-a822-11e7-8f0f-70efc4a21bfa.png)

![iss-2](https://user-images.githubusercontent.com/116184/31115413-83589012-a822-11e7-85f1-7157eb4478fb.png)

This is also recognizable with [#9654](https://github.com/home-assistant/home-assistant/pull/9654).

**Comment by c727** [comment]
fixed for me in 0.57.2
