### ISSUE TITLE
secondary_info: last-triggered doesn't show  'never' when not yet triggered

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant-polymer#4428]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
never
**UI (States or Lovelace UI?):**
Lovelace

103.5
**Browser and Operating System:**
Hassio, all browsers

**Description of problem:**
now that https://github.com/home-assistant/home-assistant-polymer/pull/4222 was merged, we can show 
`secondary_info: last-triggered` for entities, which is great. We don't see the line display a 'never' though on entities that aren't triggered yet (automations and scripts)

is this a bug, or should an extra guard be added to the code in https://github.com/home-assistant/home-assistant-polymer/blob/2ed6d0e73cb46f97a76ed57da6ace8e373ffcdb0/src/panels/lovelace/components/hui-generic-entity-row.ts#L116

and changed in `: "never"}`

**Expected behaviour:**
have `secondary_info: last-triggered` show 'never' in case of not yet triggered

**Relevant config:**

```
  - type: entities
    entities:
      - entity: automation.any_automation_or_script
        secondary_info: last-triggered
```
**Steps to reproduce this problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
<img width="454" alt="Schermafbeelding 2020-01-07 om 10 32 47" src="https://user-images.githubusercontent.com/33354141/71884690-16954680-3139-11ea-8c8b-502fee322522.png">

**Comment by iantrich** [comment]
Did you not add the `last-triggered` option? i.e. wouldn't it be your decision if it is a bug or not?

**Comment by Mariusthvdb** [comment]
Yes I did, and suppose it isn't a bug in the true sense, more of an oversight...

would like to create a new Pr on it now, so might I ask if my suggestion would be the right solution for this? It's a catch really, to simply state 'never' if none of the conditions are met.

**Comment by iantrich** [comment]
fixed in https://github.com/home-assistant/home-assistant-polymer/pull/4442
