### ISSUE TITLE
Automation Editor not able to rearrange  ACTIONS, TRIGGERS , ETC

### ISSUE THREAD

**Issue by dynamichvac** [home-assistant/home-assistant-polymer#4429]
Unable to rearrange the ordering of ACTIONS, TRIGGERS, ETC in Animations ..  it just moves the ENTITY ID as per attached images:

![1](https://user-images.githubusercontent.com/59604597/71889913-4ffc9f00-3197-11ea-98f2-4d40262a9d36.JPG)
![2](https://user-images.githubusercontent.com/59604597/71889925-53902600-3197-11ea-8783-c59530d38de7.JPG)

**Comment by bramkragten** [comment]
Duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/4395
