### ISSUE TITLE
Can't enter a device when adding a new automation using the natural language wizard

### ISSUE THREAD

**Issue by mcinnes01** [home-assistant/home-assistant-polymer#4433]
**Home Assistant release with the issue:**
103.5

**Last working Home Assistant release (if known):**
unknown

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hassio running directly on up to date ubuntu 18.04

**Description of problem:**
I've just been trying to use the new Automation wizard with natural language recognition
I select on of the standard examples "Turn the lights on when the sun is set"
It displays a popup:
![image](https://user-images.githubusercontent.com/877512/71820546-53a10080-3087-11ea-9d2f-4bf177663fc9.png)
Regardless of what I type "light.porch_light", "Porch Light", etc nothing is populating and I can't move on to the next stage.
Nothing is in the console and I cannot see any requests on the network tab in the browser, so it doesn't appear to be posting back to search light entities, nor does it seem to be loading any light entities in to a list to select from.

I am using chrome 79.0.3945.88, also tried on chrome on my android mobile and edge

**Comment by balloob** [comment]
Do you have any integrations that have added light devices ?

**Comment by mcinnes01** [comment]
@balloob I don't have any lights from integrations no, most of the lights I have come from the built in platforms such as yeelight and sonoff.

**Comment by bramkragten** [comment]
This only works with device automations, so it will need an integration that provides devices.
