### ISSUE TITLE
Lovelace UI loses connection and reloads frequently

### ISSUE THREAD

**Issue by bdunlay** [home-assistant/home-assistant-polymer#4434]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**

* 0.103.6

**Last working Home Assistant release (if known):**

* n/a -- I am a new user. However, this issue occurred on 0.103.5 as well. I upgraded before filing this issue and it persisted.

**UI (States or Lovelace UI?):**

* Lovelace UI

**Browser and Operating System:**

* Firefox 72.0 
* OS X 10.14.6

**Description of problem:**

* The UI loses connection with the backend  periodically. A toast stating "Connection lost. Reconnecting..." pops up for a brief moment, the page flashes (as if reloading), and a new websocket connection is made.

![Screen Shot 2020-01-07 at 7 23 53 PM](https://user-images.githubusercontent.com/420197/71947999-787a9e00-3183-11ea-80d7-0f496ac56c45.png)

**Expected behaviour:**

* The page does not lose connection and reload. This causes any unsaved work (e.g. editing an automation) to be lost.

**Relevant config:**

* n/a

**Steps to reproduce this problem:**

1. Open Lovelace UI
2. Wait 1-2 minutes
3. Page reloads

**Javascript errors shown in the web inspector (if applicable):**

* I don't think any of the following are relevant to this issue, but pasting here for completeness. I am on the configuration page (https://hass.example.com/config/dashboard) as these logs are produced.

```
TypeError: this.cloudStatus is undefined
4 chunk.82858443d26cf004db28.js:277:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2. (Reason: CORS request did not succeed).

The resource at “<URL>” was blocked because content blocking is enabled. 2
downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:2): bad URI or cross-site access not allowed source: https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2. (Reason: CORS request did not succeed).

downloadable font: download failed (font-family: "Roboto" style:normal weight:500 stretch:100 src index:2): bad URI or cross-site access not allowed source: https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
TypeError: this.cloudStatus is undefined
3 chunk.82858443d26cf004db28.js:277:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! dashboard
TypeError: this.cloudStatus is undefined
4 chunk.82858443d26cf004db28.js:277:1
TypeError: this.cloudStatus is undefined
3 chunk.82858443d26cf004db28.js:277:1
TypeError: this.cloudStatus is undefined
2 chunk.82858443d26cf004db28.js:277:1
TypeError: this.cloudStatus is undefined
4 chunk.82858443d26cf004db28.js:277:1
TypeError: this.cloudStatus is undefined
3 chunk.82858443d26cf004db28.js:277:1
TypeError: this.cloudStatus is undefined
3 chunk.82858443d26cf004db28.js:277:1
```

**Additional information:**

* Hass backend reports:

```
Jan 09 03:09:21 raspberrypi hass[1270]: 2020-01-09 03:09:21 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1646752464] Connection closed by client
```

* Using HAProxy to access the frontend.

**Comment by bdunlay** [comment]
Digging in more, this looks like HAProxy is involved. I increased the [tunnel timeout](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-timeout%20tunnel) in HAProxy to  60 seconds, and that seems to have addressed the issue.

**Comment by bdunlay** [comment]
Likely the same issue: https://github.com/home-assistant/home-assistant/issues/28219

**Comment by bramkragten** [comment]
Thanks for digging in and good you got it fixed. I'll close this now.
