### ISSUE TITLE
Wrong translation in Hungarian language pack

### ISSUE THREAD

**Issue by vargatamas86** [home-assistant/home-assistant-polymer#4436]
Translation is wrong in Hungarian language pack at
https://github.com/home-assistant/home-assistant-polymer/blob/dev/translations/hu.json#L1577

The placeholder {idő} should be reverted to the English original {time}

**Comment by bramkragten** [comment]
You can fix this on Lokalize https://developers.home-assistant.io/docs/en/internationalization_translation.html
