### ISSUE TITLE
No custom cards work with MS Edge

### ISSUE THREAD

**Issue by i00** [home-assistant/home-assistant-polymer#4446]
**Home Assistant release with the issue:**
0.103.6

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Integration:**
Lovelace?

**Description of problem:**
Custom cards do not work at all in edge see: https://github.com/thomasloven/lovelace-auto-entities/issues/48
They just show massive red boxes stating that the "Custom element doesn't exist"

I have tested with:
- lovelace-card-tools
- vertical-stack-in-card
- auto-entities

**Comment by bramkragten** [comment]
That would be an issue of the custom card? What errors do you get in the console? And what version of Edge?

**Comment by i00** [comment]
> That would be an issue of the custom card? What errors do you get in the console? And what version of Edge?

I just checked .. version is 44.18362.449.0 (latest)
... but since last time I have installed the mini-graph-card and it works ... but I imagine it can be fixed in HA to increase compatibility?
All state:
>Custom element doesn't exist {{custom card name}}
{{the yaml i use in the card}}

**Comment by bramkragten** [comment]
No, Home Assistant can't fix compatibility for custom cards, please create an issue for the cards in question
