### ISSUE TITLE
Onboarding should allow elevation input in feet OR meters

### ISSUE THREAD

**Issue by waded** [home-assistant/home-assistant-polymer#4452]
When onboarding to Home Assistant, one of the first things I'm asked to do is set location/elevation. I don't know my location's elevation in meters (I know it in feet) but it doesn't let me choose to input anything but meters.

Ordinarily I'd do the math, but the question immediately following is "Unit System." That gives you a bad taste when you just did a conversion because of inflexibility about unit system.

![image](https://user-images.githubusercontent.com/1535656/72210479-69446a80-3479-11ea-8cea-a5383a72e8fe.png)

What I'd like to see changed is for unit system to be asked first on this screen. Then location/elevation can be asked, with meters/feet as a dropdown, defaulted perhaps by unit system but able to be changed separately from that setting in case one size does not fit all.

It seems OK to me if feet input is converted to meters for internal use if needed, but the choice of elevation unit and the value you typed should not be lost, and shown on the "General Configuration" page that looks similar to this part of onboarding.

**Comment by iantrich** [comment]
I fairly certain your input will be the same unit as selected. Feet in your case, and it is just a display bug
