### ISSUE TITLE
Theme Not Applying Properly in <app-header> on the "Frontend -> Hass.io" Tab

### ISSUE THREAD

**Issue by sirlashelot** [home-assistant/home-assistant-polymer#4457]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103.6

**Last working Home Assistant release (if known):**
unknown

**UI (States or Lovelace UI?):** 
_Frontend -> Hass.io_

**Browser and Operating System:**
Windows 10, Firefox 72.0.1 (64-bit)
Windows 10, Microsoft Edge 44.18362.449.0
iOS 13.3, Home Assistant app

**Description of problem:**
At _Frontend -> Hass.io_, the theme does not apply to the <app-header> element properly. Specifically, at least the `background-color` and `color` styles are not set to the same values as they are on _Frontend -> Developer Tools_ and _Frontend -> Configuration_.

Firefox and the iOS Home Assistant App apply the `--primary-color` and `--text-primary-color` instead of the `--app-header-background-color` and `--app-header-text-color ` respectively.
![image](https://user-images.githubusercontent.com/59674135/72226494-b3b50c80-3589-11ea-9098-d5120026efc0.png)
![image](https://user-images.githubusercontent.com/59674135/72226606-de539500-358a-11ea-8008-f6e184c66921.png)

Edge does something different where it does not apply the colors of the theme at all, but uses the default theme's colors.
![image](https://user-images.githubusercontent.com/59674135/72226536-07275a80-358a-11ea-9ec8-d76c73532458.png)

**Current behaviour**:
CSS:
```
app-header, app-toolbar {
    background-color: var(--primary-color);
    font-weight: 400;
    color: var(--text-primary-color, white);
}
```

**Expected behaviour:**
CSS:
```
app-header, app-toolbar {
    background-color: var(--app-header-background-color);
    font-weight: 400;
    color: var(--app-header-text-color, white);
}
```
As exemplified on the _Frontend -> Developer Tools_ page, the theme is applied to the `app-header` properly:
![image](https://user-images.githubusercontent.com/59674135/72226549-3a69e980-358a-11ea-9a8f-77b6167d78c3.png)

**Relevant config:**
N/A

**Steps to reproduce this problem:**
1. Download the "Google Home Theme" theme from: [https://github.com/liri/lovelace-themes](https://github.com/liri/lovelace-themes)
2. Apply the "Google - Light" Theme at _Profile -> Theme_
3. In Firefox, navigate to _Frontend -> Hass.io_.

**Javascript errors shown in the web inspector (if applicable):**

```
None
```

**Additional information:**
I am not sure this is the right spot for this Bug report, or if this is indeed a feature instead of a bug, so I do apologize if I am wasting your time. I am happy to resubmit it at the proper location if needed.

**Comment by bramkragten** [comment]
Hass.io builds of the frontend don't follow the same schedule as Home Assistant, so this will be fixed when a new Hass.io supervisor is released with a new version of its frontend.
