### ISSUE TITLE
Deprecate old states UI

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4459]
Lovelace has been the default UI for a year ([announcement](https://www.home-assistant.io/blog/2019/01/23/lovelace-released/)). It's time we drop the old UI and any Polymer element that is only being used there.

Let's deprecate the old states UI and then remove it in a month or two. Let's start by adding a button in the upper right corner labeled "DEPRECATED" that links to this issue.

**Comment by tjorim** [comment]
Is there already a issue to track missing features from the states in lovelace?

**Comment by bramkragten** [comment]
That should be an issue for every missing feature, and there have been several.

**Comment by osokthedevil** [comment]
I'm having this issue as of yesterday, when I didn't the update

**Comment by iantrich** [comment]
@osokthedevil this isn't an issue to "have"...?

**Comment by osokthedevil** [comment]
@iantrich well since i had updated HA lovelace UI doesn't function anymore, it just come up as a blank white screen. i don't know how else to describe this issue or problem or what ever it is but it broke lovelace ui

**Comment by osokthedevil** [comment]
![image](https://user-images.githubusercontent.com/32919961/73994998-f82f9000-491c-11ea-9940-a3f590ee3cb3.png)

**Comment by iantrich** [comment]
Have you tried clearing your browser cache?

**Comment by osokthedevil** [comment]
No I haven't, I will give that a try this evening

**Comment by JozimarHM** [comment]
Para mim funcionou deletando "default_config:" do meu configuration.yaml.

**Comment by rarroyo6** [comment]
The states UI is great for debugging. I don't use it for a front end, but I use it for viewing the state of ALL the entities when doing things like automations. It lets me view things like boolian inputs that I use to store states for the automation. Plus it lets me see the value of a sensor which might not be directly displayed on the front end, but it's used to trigger events.
The states UI, or something equivalent, should remain available under the development menu or as an advanced option.

**Comment by pilot1981** [comment]
so if I understood well: every entities present in states page with deprecated button in the upper right corner labeled "DEPRECATED" will not be available in next versions?

how I can use this page?

why states page is default page now? If I would have lovelace default page, what I can do?

**Comment by sirs2k** [comment]
Please don't take it away, I love seeing absolutely everything while trying to debug and connect new devices etc...

**Comment by bramkragten** [comment]
Locking this, you can continue to discuss the functions you would like to see from state UI here: #4784
