### ISSUE TITLE
Detect button in onboarding no longer sets location

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4460]
Running latest dev. If I hit "detect" during onboarding, it detects timezone + units but it is not detecting/setting the location. Pressing "Next" results in this screen:

![image](https://user-images.githubusercontent.com/1444314/72235735-acd9ca00-3588-11ea-8b6e-78c905b5153c.png)

**Comment by balloob** [comment]
If I press anywhere on the map it will set latitude/longitude and I can continue.

**Comment by bramkragten** [comment]
Works here, what does `config/core/detect` gives back?

**Comment by bramkragten** [comment]
At least show the error: https://github.com/home-assistant/home-assistant-polymer/pull/4462

**Comment by balloob** [comment]
It looks like latitude and longitude are not set initially and when I press detect. So it fails because not all data present. I'll try again today, but I thought I already had latest code and dependencies installed.
