### ISSUE TITLE
Unable to confirm card deletion.

### ISSUE THREAD

**Issue by aptonline** [home-assistant/home-assistant-polymer#4468]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Home Assistant release with the issue:**

Home Assistant 0.103.6

**Last working Home Assistant release (if known):**

Unknown 

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Safari and HA app on iOS/iPadOS 13.3.
Works ok on desktop.

**Description of problem:**

When deleting a card from the UI the confirmation dialog box is unable to be actioned , I cannot click cancel or OK. Dialog will not dismiss leaving the only option to force quick the app.

![8A8B63F3-F364-4EF7-B720-0E50904DE579](https://user-images.githubusercontent.com/190136/72336195-2e7c4580-36b8-11ea-9daf-12ff459ce029.jpeg)

**Expected behaviour:**

To be able to confirm the deletion.

**Relevant config:**

Any card, not specific to a config.

**Steps to reproduce this problem:**

Go into Configure UI
Click the ellipses for the card you want to remove.
Choose delete card
Attempt to confirm

**Javascript errors shown in the web inspector (if applicable):**

No errors

**Additional information:**

Cleared cache and tried multiple hardware. Issue remaining.

**Comment by SeanPM5** [comment]
I'm also able to reproduce this on the demo site on my iPhone 11 and iOS 13.3.

Other similar confirmation dialogs like deleting a view don't have this issue. So it appears to be an issue with this specific confirmation dialog, and not a general or OS-level issue.

**Comment by aptonline** [comment]
Issue still present in HA 0.104.0.

**Comment by iantrich** [comment]
Unless closed, no need to reaffirm

**Comment by aptonline** [comment]
If it was fixed after the update it makes sense that the issue should be closed... it also makes sense to update the issue if it wasn’t.

**Comment by iantrich** [comment]
If someone works on this, they will close the issue

**Comment by aptonline** [comment]
After the update to 0.104.2 which includes this fix I can no longer select ANY of the menu items in edit UI mode on my cards (Move to view, Delete Card) when editing on iOS/iPadOS:

![DD3D2DE9-4EA5-450C-857B-DAF622D9E164](https://user-images.githubusercontent.com/190136/72661389-27fc0f80-39d1-11ea-9976-085170e596fe.gif)

**Comment by aptonline** [comment]
Raised a separate issues: https://github.com/home-assistant/home-assistant-polymer/issues/4515
