### ISSUE TITLE
picture glance card bug  with camera_view?

### ISSUE THREAD

**Issue by vMeph** [home-assistant/home-assistant-polymer#4478]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103.6

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
chrome

**Description of problem:**
using storage mode it seems picture glance card has a bug using with camera_view: 
in options, if you set to live and exit config it will always show auto in GUI card settings and on raw config will show live.
if then you change back to auto it  will always stay live the only way to get back to auto mode back is to go into raw editor and write the code to auto
in GUI card will always show auto, wont matter what sets you put
can anyone confirm this?

**Comment by aptonline** [comment]
I can confirm this issue, happens to me as well.
