### ISSUE TITLE
null values displayed instead of None

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant-polymer#4492]
**Home Assistant release with the issue:**
0.103.0

**Last working Home Assistant release (if known):**
don't know

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 79.0.3945.117 (Official Build) (64-bit)/OS X 10.11.6

**Description of problem:**
Today I received a [new issue](https://github.com/akasma74/Hass-Custom-Alarm/issues/71#issuecomment-575288386) with a custom component I support.
When I checked it out, I noticed that even if I return `None` from the [python function](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/alarm_control_panel.py#L706), it is displayed as `null` in Developer -> States, but I get `None` in template editor.
I can also see plenty of automations with `last_triggered: null`.
That all makes me think that something wrong happens to those `None` values in the frontend.

**Expected behaviour:**
In UI `None` should be `None`.

**Relevant config:**

**Steps to reproduce this problem:**
1. Restart HA
2. Go to Devloper Tools - > States
3. Filter to see automations - all automations that didn't trigger after the restart will have `last_triggered` with `null`

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
`None` is Python's equivalent of a `null` value. What the template editor shows is a representation of Jinja2

**Comment by akasma74** [comment]
Ian, that's great but how about this example - I can clearly seen `None` here?
![Screen Shot 2020-01-17 at 15 38 38 (2)](https://user-images.githubusercontent.com/13675855/72625053-e53e2700-393f-11ea-9c66-3c1d64a7316f.png)

**Comment by bramkragten** [comment]
If you send `None` as a string it will display None. If you send the python `None`, it will be `null`

**Comment by akasma74** [comment]
Good point. The timer integration converts its properties to strings upon returning whereas my one returns them as they are.
Do you have an idea why they convert it to string as it seems like not every standard integration does it at the moment?

**Comment by iantrich** [comment]
Good question for the [backend devs](https://discord.gg/TQhvzjB)
