### ISSUE TITLE
Seeking capabilities for media player card

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#4493]
**Is your feature request related to a problem? Please describe.**

Our media players entities can implement seek capabilities as part of their supported features, as seen by the small yellow/orange/ish bar in the media player card:

![image](https://user-images.githubusercontent.com/195327/72563764-a9a74c80-38ae-11ea-95c4-83e4b34bb67b.png)

However, there is no way to seek 🤷‍♂ 

There is a service call, but that feels rather useless (unless you want a song to start on a specific timestamp from an automation or something).

**Describe the solution you'd like**

My wish for this card would be that the yellow/orange/ish bar is clickable like a media player, allowing me to seek through the media.

**Describe alternatives you've considered**

🤷‍♂

**Additional context**

I've been reworking the Spotify integration in:
<https://github.com/home-assistant/home-assistant/pull/30717>

I've managed to implement the current playing position and seeking capabilities.
When I finally implemented it... I was like, wait uh? Does it work? 😂

**Comment by zsarnett** [comment]
[![Screenshot from Gyazo](https://gyazo.com/dda60d4a5f078bd6ce43cd2c7fd5f3c1/raw)](https://gyazo.com/dda60d4a5f078bd6ce43cd2c7fd5f3c1)

SoonTM 👀
