### ISSUE TITLE
Fan Icon doesn't change colors when turned on

### ISSUE THREAD

**Issue by randellhodges** [home-assistant/home-assistant-polymer#450]
https://github.com/home-assistant/home-assistant-polymer/blob/91c8b4eb239a52b7c709c7ca8065cbfb4ce57663/src/components/entity/state-badge.html#L28

Not sure when it changed, but the state of a fan is not just off/on, but now, at least as of 0.55 the state of a fan will be the speed. In a lot of cases, this is off/low/medium/high

This line probably needs to be something like data-state != 'off'

Or, is the fan component broken and the state should be off/on?

**Comment by andrey-git** [comment]
Current code looks at brightness attribute. I'm not sure it makes sense to set fan color in the same way.

**Comment by randellhodges** [comment]
Some color is better than none :)

I think the ISY994 fan is just messed up. I don't have any other fan types to check against, but I'm suspecting the "state" should be "on" with the speed reflecting the actual speed. This is more in line with how a light works. It is "on" with a brightness attribute.

**Comment by balloob** [comment]
This is not an issue with the frontend. Instead it is an issue with the ISY994 overwriting the state attribute which is not allowed. Closing this and we should remove that functionality from the ISY994 fan.
