### ISSUE TITLE
Unexpected resize media player card on media_content_type change

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#4502]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.105dev
**Last working Home Assistant release (if known):** ?
**UI (States or Lovelace UI?):** 20200108.0
**Browser and Operating System:** Not relevant

**Description of problem:**

The media player card will adjust its size based on value of the `media_content_type` provided by the media player.

It will even resize during playback if the `media_content_type` changes, just cutting off part of the cover art.

Screen recording:

![2020-01-17 09 46 22](https://user-images.githubusercontent.com/195327/72597569-5238c900-390e-11ea-9470-df542de2476c.gif)

The first view seconds of the clip, there is music playing, which just a Spotify track, the `media_content_type` set to playlist.

As soon as I switch to playing an album, instead of a playlist, it changes. In this case, the `media_content_tupe` is set to music. (Playlist name is None/empty at this point).

**Expected behaviour:**

For the resizing, I would expect the card to respect the aspect ratio of the provided cover art.

**Additional information:**

Discovered while rewriting our Spotify integration: 

<https://github.com/home-assistant/home-assistant/pull/30717>

**Comment by frenck** [comment]
I realize now I wrote to separate issues in this single issue. Let me split it.

**Comment by iantrich** [comment]
Potential redesign could help with this: https://github.com/home-assistant/home-assistant-polymer/issues/2095#issuecomment-542713141

**Comment by zsarnett** [comment]
#4850 - The media card has been redesigned. Cover Art is now set to be a standard 16:9 ratio

**Comment by glyndon** [comment]
It seems to be clipping the top edge of art supplied by a Chromecast. This is new as of about a week ago (~ 2/24/2020)

**Comment by zsarnett** [comment]
@frenck This is not an issue anymore as the card's ratio is set correct?

**Comment by glyndon** [comment]
I wish that were true, but I updated to and prior to 106.x it displayed the whole image. Now it clips the top portion, about 1/4 of it. It's not scaling the image to fit the 16:9 aspect ratio - it's clipping whatever is across the top of the album art. I could attach a screenshot. 
Adding the aspect_ratio param - even with some extreme percentages - to the card had no effect.
Perhaps it's something that only happens if the source is a Chromecast playing Pandora - that's what I routinely use.

**Comment by zsarnett** [comment]
It is scaling to fit the ratio. The issue is that the image is a square and therefore will be cut off. This is to reduce the jumping of sizes in your Lovelace dashboard

**Comment by zsarnett** [comment]
I am going to be building a new Media Card very soon. Completely different form the current version
