### ISSUE TITLE
Card options when editing UI not selectable

### ISSUE THREAD

**Issue by aptonline** [home-assistant/home-assistant-polymer#4515]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**

0.104.2

**Last working Home Assistant release (if known):**

0.104.1

**UI (States or Lovelace UI?):**

Lovelace UI

**Browser and Operating System:**

Safari iOS/iPadOS 13.3

**Description of problem:**

Unable to select ‘move to view’ or ‘delete card’ from card options (eclipses).

![F0EB81DF-E3EE-4682-A853-C7C6D11D9570](https://user-images.githubusercontent.com/190136/72663299-09097780-39e9-11ea-81db-721319f22d1b.gif)

**Expected behaviour:**

To be able to select an option from the drop down menu.

**Relevant config:**

N/A

**Steps to reproduce this problem:**

Choose edit UI
Choose a menu item from a card using the eclipses. (...)

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

**Comment by iantrich** [comment]
Confirmed

**Comment by ludeeus** [comment]
if you click the same option twice, does it work?

**Comment by aptonline** [comment]
No, I have however noticed in some situation that for some menu items you need to select it twice for it to action but in this situation it does not work.

As a side note I have noticed the auto complete for menu for entities selection in automation/scripts is also broken. It don't not keep the auto complete selection in the menu long enough for you to select, it jumps to another items almost straight away.

**Comment by iantrich** [comment]
@aptonline separate issues should not be conflated in the same ticket

**Comment by aptonline** [comment]
> ~@aptonline separate issues should not be conflated in the same ticket~ you know what, that very well may be related, actually. apologies

It does seem connected which is why I mentioned it. Happy to raise another issue if needed however.

**Comment by aptonline** [comment]
Here’s another example I found of the same issue with regard to not being able to select an option from the menu.  Also note that the service data is deleted if I re-organise an item in the flow.

![EDA26D36-6234-402A-8A6C-E2FB40894247](https://user-images.githubusercontent.com/190136/72670153-1eef5a80-3a32-11ea-8262-4bfb81f6dd42.gif)

**Comment by aptonline** [comment]
Any update on this issue?
