### ISSUE TITLE
Regex rename of entities

### ISSUE THREAD

**Issue by jaimevisser** [home-assistant/home-assistant-polymer#4517]
When entities were still stored on disk with all configuration it was easy to use regex to rename them. Because Z-wave devices each have a non-trivial number of entities, renaming them (or keeping names that group them well) is very tedious. It would be nice to have a regex rename for entity id's in the entity registry. Other option is a rename for all entities under a device in the integrations page. This way a user could rename a device and all entities would rename into something like "sensor.new_name_of_the_device_motion" (example for a motion entity on a multisensor).

**Comment by bramkragten** [comment]
If you rename the device name we will rename the entities if they contain the same name.
