### ISSUE TITLE
Customized icon for sensor isn't honored when posting new sensor value via API

### ISSUE THREAD

**Issue by richrd** [home-assistant/home-assistant-polymer#452]
I'm not sure what exactly is causing this so I've described my situation in detail. I tried to search for similar cases but didn't find anything.

I have a sensor monitoring the voltage of a battery. The device is an ESP8266 based devboard, and it sends the battery state to HA via the HTTP API every 30 minutes.
The `POST` request is sent to `/api/states/sensor.huzzah_power` with the following contents:
```
{
    "state": "3.449",
    "attributes": {
        "friendly_name": "Huzzah Power",
        "unit_of_measurement": "V"
    }
}
```
I have this in my `customize.yaml`:
```
   sensor.huzzah_power:
     icon: mdi:flash
```
If I go to the Customize settings in the HA UI, select `Huzzah Power` and save it the customized icon is correctly shown in the UI. Then as soon as a new value comes in via the API the icon in the UI reverts to `mdi:eye`. The customize settings never change and I can see that the icon is correctly set to `mdi:flash`.
I realize I could probably just include `"icon": "mdi:flash"` in the attributes that are sent, but do I really need to do that?

I was expecting the icon from `customize.yaml` to be used since I haven't specified it in the request.
Is this a feature or a bug? I could try and fix this and send a PR but I'm not sure what the best approach would be.

EDIT: I'm guessing this should take into account whatever is specified in customize.yaml: https://github.com/home-assistant/home-assistant-polymer/blob/bc0d44ca81dce48961c81bf2d1cc268d9c99d2df/src/util/hass-util.html#L403
EDIT2: Actually seems like this might be an issue with HA itself.

**Comment by andrey-git** [comment]
This API overrides the state machine.
An alternative would be to have a template or some other backend type of sensor and call a service that changes state.

**Comment by richrd** [comment]
Couldn't it check whether a custom icon has been defined, and use that if no icon is explicitly specified in the API request? Not sure what the best place would be to do this but maybe somewhere in here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/api.py#L205

**Comment by balloob** [comment]
Customize is only used when entities post state. When you write to the state machine directly, you bypass this mechanism. This is by design.

**Comment by richrd** [comment]
Ok, thats mostly fine for me. But OTOH couldn't an icon fallback be used. I mean, what (negative) impact would it have? Or is it mainly by design because it keeps the implementation more simple 
and robust?

Is there any way to post a sensor value without having this issue? I think a restful sensor could be used, but my situation doesn't require polling. The point of my device is actually to monitor a door sensor. I usually only need to post the state when it changes and I'd like to avoid polling since polling will run down the battery faster.

If not, I'll just have to send the icon attribute every time the battery level is sent.

Thanks!

**Comment by balloob** [comment]
The state machine is a core part of Home Assistant. The customization is part of the entity component and sits on a layer above it in the architecture. We should not conflate concerns 👍 

If you want to use customize, make an http sensor that takes API requests.

If you want to set them via the HTTP API directly on the state machine, you will have to add the icon attribute.

**Comment by richrd** [comment]
Thanks for clarification and tips!
