### ISSUE TITLE
Missing image in onboarding config flow

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/home-assistant-polymer#4534]
![image](https://user-images.githubusercontent.com/5662298/72739440-eb344200-3ba3-11ea-8609-54fdb76f78aa.png)

**Comment by frenck** [comment]
Translation issue:

![image](https://user-images.githubusercontent.com/195327/72740056-3569f300-3ba5-11ea-9f0c-dd1352cd45d9.png)


Fixed it in Lokalise.

**Comment by frenck** [comment]
This was actually broken in 7 different languages (in many different ways).

Adjusted them all.
