### ISSUE TITLE
HA form layout issue if 3 boolean values rendered in a row

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4539]
Home Assistant 0.104

![image](https://user-images.githubusercontent.com/1444314/72750686-5f55f200-3b72-11ea-9c49-dcd543722fdd.png)

**Comment by iantrich** [comment]
I would opt for never having more than one in a row. Easier to work with and will work much better on mobile.

**Comment by dmulcahey** [comment]
> I would opt for never having more than one in a row. Easier to work with and will work much better on mobile.

I agree. I was experimenting with config entry options and I had the same thought.

**Comment by balloob** [comment]
Sorry, that was what I meant. Each input should be its own row !

**Comment by VDRainer** [comment]
Is this a new input_* feature in 0.104?
Can't find anything in the Release Notes.

**Comment by bramkragten** [comment]
No this is the settings dialog of an integration.
