### ISSUE TITLE
UI inaccessible in Firefox: TypeError: this._meta.byKey is not a function

### ISSUE THREAD

**Issue by fortinj1354** [home-assistant/home-assistant-polymer#454]
This issue https://github.com/home-assistant/home-assistant-polymer/issues/428 was marked as closed however I'm still experiencing this issue on a clean install of Firefox and the latest version (0.55) of home assistant. Other people in the original thread have also mentioned that this does not seem to be resolved.

**Comment by balloob** [comment]
Duplicate of https://github.com/home-assistant/home-assistant-polymer/issues/448 …
