### ISSUE TITLE
Content gets cut off if using pictures when moving to a room

### ISSUE THREAD

**Issue by riemers** [home-assistant/home-assistant-polymer#456]
This is how it shows when i just clicked on that particular room:

![image](https://user-images.githubusercontent.com/682041/27120689-dd8beb28-50e4-11e7-931f-1b091f87a740.png)

But when i try to scroll down:

![image](https://user-images.githubusercontent.com/682041/27120706-ede6e2c0-50e4-11e7-8be1-8071c15cdb3f.png)

It does not show the full image, it cuts it off. Going to another room and then back resolves the issue though. This happens in the app and the front end (chrome tested)

**Comment by zsarnett** [comment]
Is this still an issue? @riemers

**Comment by riemers** [comment]
Seems resolved, have not been able to reproduce anymore.
