### ISSUE TITLE
Improve Lovelace debugging

### ISSUE THREAD

**Issue by chaptergy** [home-assistant/home-assistant-polymer#4566]
Currently there does not seem to be a way to debug custom Lovelace cards.

For example, I currently have the problem, that my custom card works on my home assistant, but on a different home assistant the `render()` function of the `LitElement` is just never called, while other methods, like the `getConfig()` are called perfectly fine. and there is nothing to help me understand why this happens, not in the home assistant logs, not in the browser logs, nowhere. And I can't imagine that Lovelace isn't logging anything, I'm assuming it is just not available for the end user / developer.

**Comment by bramkragten** [comment]
We don't log anything, you can add your own log statements to see what is happening.

`console.log()`
