### ISSUE TITLE
Allow specifying multiple lights for a light card

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4578]
## The request

_This could work for other places in Lovelace too, especially entity rows would be great for this, but let's start small!_

I would like to be able to have a light card control multiple lights. The light card should work as a virtual group that is frontend only. If any light is on: show light card as on. Don't try to mangle the colors, just normal yellow. If all cards are off, show icon as off. If any light is on, tapping it will turn all off. 

## The alternatives

Group in YAML.

**Comment by iantrich** [comment]
Additional alternative is the actual [light group](https://www.home-assistant.io/integrations/light.group/).

You'll also have to contend with what to show for more-info

**Comment by balloob** [comment]
MVP will be no more info.

**Comment by SeanPM5** [comment]
Perhaps my idea in #4242 (which wasn't possible due to missing backend info) could be implemented in a different way here. If the card contains more than one entity (and the user hasn't specified an icon override yet), change the icon to `mdi:lightbulb-multiple`. Would make it a little more clear that it's controlling multiple lights.

**Comment by iantrich** [comment]
How should we have display of brightness? Should one light be the master for current value?

**Comment by bramkragten** [comment]
The same as Light group I guess? 
It seems to grab the brightness from the first entity that has a brightness.
https://github.com/home-assistant/home-assistant/blob/30249d14282eec04356da8a335f5478a66d0dfa5/homeassistant/components/group/light.py#L332

**Comment by balloob** [comment]
For implementation, implement a `getInfo` function that normalizes the info from 1 or multiple bulbs into an object that contains brightness, color etc.

**Comment by balloob** [comment]
We use light groups instead.

**Comment by iantrich** [comment]
@balloob anyone working on light group helpers like inputs?

**Comment by balloob** [comment]
Not yet.
