### ISSUE TITLE
Advanced Mode toggle not working

### ISSUE THREAD

**Issue by iantrich** [home-assistant/home-assistant-polymer#4586]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The advanced mode toggle does not change the available options in the Configuration panel anymore

## Expected behavior
If not enabled, advanced configuration items should not be shown

## Steps to reproduce
1. Go to Configuration panel and take note of the available options
1. Go to Profile and toggle Advanced Mode
2. Go back to Configuration panel and notice that the available options have not changed

**Comment by bramkragten** [comment]
Works here, customize is gone and a note about advanced mode shows up.

**Comment by iantrich** [comment]
I could have sworn more disappeared? Shouldn't they?

**Comment by bramkragten** [comment]
Nope, don't think so
