### ISSUE TITLE
Removal of entities not possible

### ISSUE THREAD

**Issue by svh1985** [home-assistant/home-assistant-polymer#4588]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I want to remove one or multiple entities the remove dialog shows delete 0 
<img width="770" alt="Screenshot 2020-01-24 at 11 42 17" src="https://user-images.githubusercontent.com/5213210/73063848-0ce14200-3ea0-11ea-94ff-a569d5cff345.png">

## Expected behavior

Removal of entities.

## Environment

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.104.3
virtualenv | false

- Home Assistant release with the issue: 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79.0.3945.130 and Safari Version 13.0.4 (15608.4.9.1.3)
- Operating system: macOS 10.15.2

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

When I click the remove button anyway.
```txt

  | value | @ | ha-data-table.ts:362
-- | -- | -- | --
  | setRowCheckboxCheckedAtIndex | @ | ha-data-table.ts:329
  | (anonymous) | @ | foundation.ts:131
  | value | @ | ha-data-table.ts:121
  | value | @ | ha-config-entity-registry.ts:476
  | confirm | @ | ha-config-entity-registry.ts:470
  | value | @ | dialog-confirmation.ts:71
  | handleEvent | @ | parts.ts:505
  | __boundHandleEvent | @ | parts.ts:463


```

**Comment by bramkragten** [comment]
You can only remove entities that are no longer provided. You should disable them, or remove the integration.

**Comment by svh1985** [comment]
@bramkragten ok, thanks for the clarification 😄 But this is still a usability issue, the remove option should not be possible or the message should be different. Can we change this bug to a request for UI improvement?

**Comment by bramkragten** [comment]
Please create a new issue with a suggestion (maybe we can show in the dialog that some of the entities can not be removed)
