### ISSUE TITLE
Entity registry modal buttons are not in the right place

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4595]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://user-images.githubusercontent.com/1444314/73112851-6c9e1400-3ec5-11ea-9cb9-9d003349554d.png)

## Environment
Current dev

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is weird, it works with adopted stylesheets but not without, the styles are not available at all... not sure what I'm missing here... 🤔

**Comment by balloob** [comment]
since adopted stylesheets means shared stylesheets, are you by any chance tweaking the CSS in another place?

**Comment by bramkragten** [comment]
Then that would show in the style inspector right? Crossed out style? I don't see it at all... Going to check the source of Lit what could be the reason tonight.
