### ISSUE TITLE
Dimmer slider turning off light for MQTT but not other dimmers

### ISSUE THREAD

**Issue by will-l-h** [home-assistant/home-assistant-polymer#4609]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem
The dimmer slider for MQTT lights behaves differently than my z-wave light dimmers. When the slider is moved all the way to the left, the zwave dimmers will remain on (the toggle in the upper right of the lovelace card stays on) and the dimmer gets the lowest value possible. This is preferable as I’d like to dim the lights as low as possible.

With the MQTT lights, however, moving the slider all the way to the left turns the dimmer value to 0 and turns the toggle off.

I noticed this merged PR where there a turn_off was removed from slider. Not sure why MQTT is different

https://github.com/home-assistant/home-assistant-polymer/pull/1715

## Expected behavior
Consistent behavior with other dimmers: sliding to the left turn the light to the lowest value and leaves the light on.

## Environment

- Home Assistant release with the issue: 103 (or earlier) -104 
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): lovelace
- Browser and browser version: Chrome 79, Firefox 71
- Operating system: Windows

## Problem-relevant configuration

Tasmota v8.1 dimming white bulb
```
- platform: mqtt
  unique_id: lr_reading_light
  name: "Reading light"
  command_topic: "cmnd/DVES_DE8C7D/POWER"
  state_topic: "tele/DVES_DE8C7D/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/DVES_DE8C7D/LWT"
  brightness_command_topic: "cmnd/DVES_DE8C7D/Dimmer"
  brightness_state_topic: "tele/DVES_DE8C7D/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

```

**Comment by iantrich** [comment]
What happens when you call light.turn_on with brightness of 1?

**Comment by will-l-h** [comment]
Brightness 1 leaves the light off in lovelace, and this is published so it seems that is getting rounded down to 0

stat/DVES_DE8C7D/RESULT = {"POWER":"OFF","Dimmer":0}

Just in case you meant brightness_pct, I tried that, too, and it works as expected. Light turns on in lovelace and:

stat/DVES_DE8C7D/RESULT = {"POWER":"ON","Dimmer":1}

**Comment by iantrich** [comment]
No, it makes the call with `brightness` as the slider goes from 1 - 255. So yeah, doesn't seem like a frontend issue after all

**Comment by will-l-h** [comment]
Right, so the 1-255 would get converted to 1 - [brightness_scale] and the value 1 is getting rounded to 0. You're saying this would be an issue for https://github.com/home-assistant/home-assistant ?
