### ISSUE TITLE
Add error message when shopping list integration is missing

### ISSUE THREAD

**Issue by musterknabe** [home-assistant/home-assistant-polymer#4616]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Adding items to shopping list card does not work.

## Expected behavior
Items are added.

## Steps to reproduce
1. Add Shopping List Widget
2. Try to add item

## Environment
- Home Assistant release with the issue: 0.104.3
- Last working Home Assistant release (if known): ?
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox, Chrome, latest
- Operating system: MacOS

## Problem-relevant configuration

-
```yaml
-
```

## Javascript errors shown in your browser console/inspector

When clicking + Button or hitting Enter the following JS error occurs:
```txt
hui-shopping-list-card.ts:284 
Uncaught (in promise) 
{code: "unknown_command", message: "Unknown command."}
code: "unknown_command"
message: "Unknown command."

```

## Additional information
-

**Comment by ludeeus** [comment]
You need to add the shopping list integration for it to work.

**Comment by musterknabe** [comment]
Thanks for the quick response. Works fine now.

Maybe add that as an error message for newbies like me?

**Comment by ludeeus** [comment]
AFAIK that is already added, it's just not released yet

**Comment by musterknabe** [comment]
👍

**Comment by ludeeus** [comment]
For reference https://github.com/home-assistant/home-assistant-polymer/pull/4523
