### ISSUE TITLE
cosmetic: more-info-card for groups has "useless" information

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#462]
![more-group](https://user-images.githubusercontent.com/11984118/31587532-baddd360-b1e3-11e7-830c-abab0ed7b262.PNG)

**Comment by andrey-git** [comment]
Groups that contain switches have on/off state. I agree that for other groups the last-updated and state is useless.

**Comment by balloob** [comment]
Groups also group home/not_home, open/closed, locked/unlocked, problem/ok.

**Comment by c727** [comment]
the current groups will be removed from the frontend
