### ISSUE TITLE
Links to add-ons are broken

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-polymer#4623]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

All links to the external add-on pages are broken, an additional `"` is on the end of the URL.

![image](https://user-images.githubusercontent.com/195327/73220247-447d1200-415e-11ea-9c92-eb76acb1da98.png)

⚠️ Additionally, the space character after the link text seems to be linked as well (really minor, but 🤷‍♂)

## Expected behavior

Working links 😄 

## Steps to reproduce

Open up any add-on, click on the add-on link right under the add-on description.

## Environment

- Home Assistant release with the issue: 0.104.3 / Supervisor 196 (dev)
- Last working Home Assistant release (if known): Supervisor 195
- UI Type (States or Lovelace): n/a
- Browser and browser version: Version 79.0.3945.117 (Official Build) (64-bit)
- Operating system: macOS Mojave

## Problem-relevant configuration

```yaml
n/a
```

## Javascript errors shown in your browser console/inspector

```txt
Nothing.
```

**Comment by ludeeus** [comment]
Wait.... You want _working_ links? 🤔
