### ISSUE TITLE
Two weather cards on a view will attempt to load Google visualization twice

### ISSUE THREAD

**Issue by armills** [home-assistant/home-assistant-polymer#464]
This creates a race condition that results in the following error on this line:

`TypeError: window.google.visualization is undefined`

https://github.com/home-assistant/home-assistant-polymer/blob/f24cb3eed50136551d648ed0f272c367e0239f36/src/cards/ha-weather-card.html#L156

**Comment by balloob** [comment]
I'm surprised that Google doesn't catch this inside their loading scripts.

**Comment by armills** [comment]
Agreed. Not immediately pressing since it seems to end up displaying OK at the end. Just wanted to document it here so it doesn't get lost. It's reproducible with the demo weather platform.

**Comment by NovapaX** [comment]
this can probably be closed since we moved to chart.js

**Comment by balloob** [comment]
I think that we still need to migrate the weather component
