### ISSUE TITLE
Related Entities don't show, error in console

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4657]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I click on any related entities, they do not appear for me, I get an error in console.

![image](https://i.imgur.com/2j4IlrR.png)

## Steps to reproduce

1. Open a more info dialog
2. Press settings cog in top right
3. Click "Related" tab

## Environment

- Home Assistant release with the issue: 0.105.0b
- Last working Home Assistant release (if known): n/a 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome stable 
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
ha-related-items.ts:274 Uncaught (in promise) {code: "unknown_error", message: "Unknown error"}
value @ ha-related-items.ts:274
async function (async)
value @ ha-related-items.ts:272
value @ ha-related-items.ts:63
performUpdate @ updating-element.ts:720
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
initialize @ updating-element.ts:449
initialize @ lit-element.ts:146
O @ updating-element.ts:438
V @ lit-element.ts:61
i @ subscribe-mixin.ts:13
i @ ha-related-items.ts:29
_clone @ template-instance.ts:99
__commitTemplateResult @ parts.ts:276
commit @ parts.ts:218
update @ template-instance.ts:53
__commitTemplateResult @ parts.ts:268
commit @ parts.ts:218
s @ render.ts:55
V.render @ shady-render.ts:277
update @ lit-element.ts:220
performUpdate @ updating-element.ts:704
_enqueueUpdate @ updating-element.ts:653
async function (async)
_enqueueUpdate @ updating-element.ts:640
_requestUpdate @ updating-element.ts:605
set @ updating-element.ts:313
value @ dialog-entity-registry-detail.ts:131
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
j @ property-effects.js:299
C @ property-effects.js:324
w @ property-effects.js:155
(anonymous) @ property-effects.js:242
_propertiesChanged @ property-effects.js:1657
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
t.<computed> @ property-effects.js:2015
_selectionChange @ iron-multi-selectable.js:139
_applySelection @ iron-selectable.js:355
_applySelection @ iron-menu-behavior.js:274
setItemSelected @ iron-selection.js:77
select @ iron-selection.js:95
_selectSelected @ iron-selectable.js:292
_updateSelected @ iron-multi-selectable.js:102
I @ property-effects.js:811
w @ property-effects.js:155
v @ property-effects.js:121
_propertiesChanged @ property-effects.js:1654
_flushProperties @ properties-changed.js:352
_flushProperties @ property-effects.js:1502
_invalidateProperties @ property-effects.js:1474
_setProperty @ property-effects.js:1459
Object.defineProperty.set @ properties-changed.js:152
select @ iron-multi-selectable.js:66
select @ iron-menu-behavior.js:125
_itemActivate @ iron-selectable.js:395
_activateHandler @ iron-selectable.js:383
_activateHandler @ iron-menu-behavior.js:415
_activateHandler @ paper-tabs.js:407
(anonymous) @ template-stamp.js:87
M @ gestures.js:662
q @ gestures.js:1058
click @ gestures.js:1017
N @ gestures.js:450
Show 37 more frames

```

**Comment by balloob** [comment]
That's weird, it means you don't have the search integration loaded, which is marked as a dependency of the frontend and so should always be there. Are you sure you have pulled the latest beta?

**Comment by SeanPM5** [comment]
I'm on 0.105.0b in ~~Hass.io~~ Home Assistant (not dev). I see all the other new stuff and have been playing with it but this doesn't appear to be working at all even after a restart.

Just noticed the new automations, scripts, and scenes cards that are under Device Info page also aren't functioning correctly. They all just say "no automations" even though I definitely have a bunch of existing ones in YAML and created a brand new one using the UI editor. I assume that uses the search integration also then.

![image](https://i.imgur.com/bseBleK.png)

**Comment by TheZoker** [comment]
I have the same issue

**Comment by bramkragten** [comment]
If you would like to test it before it is fixed, you can add this to your configuration.yaml:
```yaml
search:
```

**Comment by balloob** [comment]
any errors in your backend log

**Comment by bramkragten** [comment]
It probably is a backend thing, I see:
![image](https://user-images.githubusercontent.com/5662298/73470864-d49e9f80-4388-11ea-99ae-3395ba9ee417.png)

**Comment by iantrich** [comment]
I see the same error after adding `search:` to my configuration

**Comment by balloob** [comment]
@SeanPM5 please also check the backend error logs next time 👍
