### ISSUE TITLE
Inconsistent coloring of icons in Map and Zones panels

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4660]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Basically same problem as https://github.com/home-assistant/home-assistant-polymer/issues/3409 which was fixed for the Map panel during Hacktoberfest and should be applied to Zones too. Text and icons should be hardcoded to black on the map because the map tiles are white. Otherwise users of dark themes will have issues.

Map panel, hardcoded to black (good):
![map](https://i.imgur.com/dpWzqy4.png)

Zones panel, uses primary text color which will be white on darker themes. White text on white map tiles will be pretty much illegible most of the time (bad):
![zone](https://i.imgur.com/RC18FQy.png)

## Expected behavior

Use same behavior as Map panel to ensure zone icons and names are always legible regardless of theme

## Steps to reproduce

1. Switch to a dark theme like [Slate](https://community.home-assistant.io/t/slate-a-new-dark-theme-updated/86410) for example
2. Open Zones panel

## Environment

- Home Assistant release with the issue: 0.105.0b
- Last working Home Assistant release (if known): n/a 
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version: chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
Who knew hardcoding colors was a good thing 👍
