### ISSUE TITLE
Media Control 0.105b0

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-polymer#4669]
In new version beta show me this bug. Why ?
![media_control](https://user-images.githubusercontent.com/16692223/73448650-a22d7c00-4361-11ea-87d9-f7dffd6ba5d7.jpg)

**Comment by bramkragten** [comment]
There is no entity row `media-control`, there is a card `media-control` but it can not be inside `entities` (well it can, but not officially) replace it with `custom:mini-media-player`

**Comment by pepeEL** [comment]
But in version 0.104 it works ok with no problem.

**Comment by iantrich** [comment]
@pepeEL if it did before, it was a fluke, it should not have. If you want the media-control card in a row use `type: custom:hui-media-control-card`. If you just want the standard media player row, no type is required.
