### ISSUE TITLE
State cards: problem with arrangement in page

### ISSUE THREAD

**Issue by covrig** [home-assistant/home-assistant-polymer#467]
**Home Assistant release (hass --version):** 0.55.1
**Python release (python3 --version):** Python 3.4.2
**Component/platform:** frontend

**Description of problem:**
State cards don't use properly the available space. The distribution on page is far from perfect. The picture is self explanatory.
Also I think the number of columns is limited to 3. On a 4K monitor the number of columns should be higher.

**Demo here:**
<img width="447" alt="test" src="https://user-images.githubusercontent.com/8059190/31625739-6e20d436-b2a7-11e7-9b59-ef18c6c177be.png">

**Comment by andrey-git** [comment]
It's 3 columns with sidebar open or 4 without.

Entities not in groups are autogrouped by domain, so all the weather cards are a single block.

You can partially work around that by placing cards in groups, but then you will get group titles.

**Comment by covrig** [comment]
@andrey-git In this case even if I close the sidebar I still have 3 columns. I can provide a picture if needed.
Two questions:
- Why should entities group by domain and not by the order defined in the list? (I assume there is no way to customize the arrangement of entities and groups... and if not, why?)
- Why do we need a group title? In some cases this is not desired and there should be an option to hide it (e.g. for your history_chart component).

**Comment by andrey-git** [comment]
Order in which list? Only entities not in groups are autogrouped.

**Comment by covrig** [comment]
Sorry for not being clear. By list I wanted to say a view group list (e.g. the components of the default_view group). 
In the end, a view is a group no? :) Why should we have a different rule (auto group) for views compared to normal groups? The same thing applies for badges. I simply can't arrange them the way I want.

Having the possibility to disable or enable the "auto group" feature or/and the group title would be a nice bonus to have. I should get to decide what information should be more accessible/important.

**Comment by balloob** [comment]
We can only provide so much customization. If you need more than we offer, there is always the option to write a custom panel. We just can't and won't support every wish out there.

Number of columns are based on the size of cards. We fill up each column up to 5 "rows" before going to the next column. Things that are in 1 group will obviously be shown in 1 column.

**Comment by covrig** [comment]
@balloob Thank you for your reply. I fully understand that we need to stop somewhere with the customization. Indeed, the custom panels help but these are not for everyone.

However, my print screen shows that the auto-group feature is failing. The extra long column in my example is not a group - the group by domain creates this.

This is not a pure customization annoyance, it's also about prioritizing the information I need.

The auto-group/group by domain feature creates more problems instead of helping. It should be optional. The order specified in the group's entity list should be sufficient.

**Comment by andrey-git** [comment]
I think we should cancel auto grouping for domains with cards (like weather)

**Comment by covrig** [comment]
@andrey-git For me canceling the auto-group feature should be an option for everything, including badges. For large setups this is incredible problematic. 

e.g. I want to see a camera and I need to scroll all over the place to get to it; I have some badges showing temperatures, humidity, power etc. and they are mixed/ arranged alphabetically.

**Comment by cgarwood** [comment]
Closing as the Lovelace UI will take care of most of this now.
