### ISSUE TITLE
 Entity management card changing sizes

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-polymer#4678]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The last card row in the Exposed Entities and Not Exposed Entities sections of Alexa or Google Assistant span the width of the browser and change size when the browser is resized. 

![resizing](https://user-images.githubusercontent.com/2456810/73473265-b49bbb80-4349-11ea-9815-0babcec3d6d3.gif)

## Expected behavior

Cards should remain same size as the others.

## Steps to reproduce

Gif provided above

## Environment

- Home Assistant release with the issue: 0.105.0b0
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: Chrome/FF/Edge (new)
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/4674
