### ISSUE TITLE
Inconsistent naming for Core/General configuration page

### ISSUE THREAD

**Issue by joshmcrty** [home-assistant/home-assistant-polymer#469]
I would recommend two changes for consistency:

1. Change the title in the app header for the General configuration page from "Core" to "General"
2. Change the header at the top of this page from "Server Management" to "General" or something with "General" in it.

Rationale:

"Core" isn't used anywhere else in the UI that I'm aware of, and this pattern would be more consistent with how the other configuration pages are titled. Also, there is a "Server Management" card at the bottom of the "General" page, so the header for that page should necessarily have a wider scope and I think "General" works fine as a page header.

All of the configuration page titles and headers could be made more consistent here (e.g. the link to a page is singular, but the title in the app header is plural, and the page header is even more descriptive).

**Comment by balloob** [comment]
Fixed in #505
