### ISSUE TITLE
[0.105.0b1] Devices entities entries margin is off

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/home-assistant-polymer#4693]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The entries on the device page have a unequal maring:
![Screenshot_2020 01 31_00h26m44s_003_](https://user-images.githubusercontent.com/1368405/73499746-3975ec00-43c1-11ea-8d2a-d4e430c84b8b.png)

The issue is, that the whole element has a margin of 8px and the icon has margin as well. This leads to a bigger space on the left than on the right. 
This can be fixed by 
1. Remove the margin on the left site (`margin: 8px 8px 8px 0`):
![Screenshot_2020 01 31_00h28m45s_004_](https://user-images.githubusercontent.com/1368405/73499971-d89ae380-43c1-11ea-880e-a2999c8434db.png)
2. Or add extra margin on the right (`margin: 8px 20px 8px 8px`)
![Screenshot_2020 01 31_00h39m10s_006_](https://user-images.githubusercontent.com/1368405/73500240-6ecf0980-43c2-11ea-9842-627ac48b7bba.png)

Both fix the problem, personally I prefer the second one

## Expected behavior

Have equal space on the right and the left side

## Steps to reproduce

Go to `Configuration`, `Integration`, select a device, have look at the entities panel. 

## Environment

- Home Assistant release with the issue: 0.105.0b1
- Last working Home Assistant release (if known): none
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80
- Operating system: Windows 10

## Problem-relevant configuration

```yaml
none
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/4684
