### ISSUE TITLE
Scenes created in UI editor not appearing in Scenes panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4698]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In 0.105.0b1 I have created scenes using the Scene editor, these get saved without any errors and they do appear in the `scenes.yaml` file. However they  **do not** appear in the Scenes panel. And they do not appear in States either.

I've reloaded scenes and then also restarted Home Assistant, still doesn't show. Reproduced on two different installs.

Nothing is in the logs file regarding scenes, don't see anything related to this in browser console either.

## Expected behavior

Have newly created scenes appear in scenes panel

## Steps to reproduce

1. Configuration > Scenes
2. Create a scene and save it with name of "Test" or something
3. It saves without error, it's visible in the `scenes.yaml` file, but it does not appear in the Scenes panel

## Environment

- Home Assistant release with the issue: 0.105.0b1
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml
scene:
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Have you imported the scene.yaml in your configuration.yaml?

**Comment by SeanPM5** [comment]
Ah, that was it, thanks. User error on my part.

I had just `scene:` in my configuration.yaml and it was writing to the file, but Scenes Editor panel wasn't showing them because I was lacking the `!include scenes.yaml` part. Should've read the instructions, my bad 😄
