### ISSUE TITLE
Can't create More Info card

### ISSUE THREAD

**Issue by mamartins** [home-assistant/home-assistant-polymer#4709]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem
I'm trying to create a new more info card but I'm getting an error extending `Polymer.Element`, If I past the script on the browser console, it works, but when I'm loading the component I get `Uncaught TypeError: Class extends value undefined is not a constructor or null` 

## Expected behavior
Not having the error

## Environment

- Home Assistant release with the issue:  0.104.3
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79.0.3945.130 
- Operating system: OSX

## Problem-relevant configuration
```js
<dom-module id='more-info-plant'>
  <template>
    <style>

    </style>
    <textarea>[[_toStr(stateObj)]]</textarea>
  </template>
</dom-module>

<script>
  class MoreInfoPlant extends Polymer.Element {
    static get is() { return 'more-info-plant'; }

    static get properties() {
      return {
        // Home Assistant object
        hass: Object,
        // inDialog is true if shown as more-info-card
        inDialog: {
          type: Boolean,
          value: true,
        },
        // includes state, config and more information of the entity
        stateObj: Object,
      };
    }

    _toStr(obj) {
      return JSON.stringify(obj, null, 2);
    }
  }

  customElements.define(MoreInfoPlant.is, MoreInfoPlant);
</script>
```
```yaml
customize:
  plant.monstera_deliciosa:
    custom_ui_more_info: more-info-my-plant

frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/more-info-my-plant.html
```

## Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at more-info-my-plant.html:14
```

**Comment by balloob** [comment]
This repository is only for bugs with our frontend. It's not for support with custom cards.

**Comment by mamartins** [comment]
Isn't this a feature, allowing to create custom cards?

**Comment by iantrich** [comment]
You can chat with devs in discord but it is not an issue for the project

**Comment by balloob** [comment]
`custom_ui_more_info` is no longer a supported feature.

**Comment by mamartins** [comment]
> `custom_ui_more_info` is no longer a supported feature.

How so? Documentation still shows it, and code too. I was able to create the more info card if I add a timeout of 100ms to the script. This looks like a load order issue.
