### ISSUE TITLE
Lovelace Markdown card, entity_id not working

### ISSUE THREAD

**Issue by noppo** [home-assistant/home-assistant-polymer#4732]
I have a rather complex script to display some text in av Markdown Card. However, it does not get updated when values change.
The documentaiton says I can used the "entity_id" parameter "so a template in content: only reacts to the state changes of these entities"

However, if I write "entity_id:" in the config editor I get an error saying. "Expected a value of type `undefined` for `entity_id` but received `null`." So either there is documentation is wrong og there is an error in the Markdown card.
Version 0.104.3

**Comment by iantrich** [comment]
You need to specify the relevant entity ids

**Comment by noppo** [comment]
Yes I have now specified the id's as a list and now the markdown is updating as descibed.

However I still get the error message in the UI. So this should be corrected.

I also noticed the "config" example in the documentation is wrong. I changed it like below and it is working (see escpecially the content part.)
`type: markdown
entity_id:
  - sensor.entur_royken_stasjon_platform_1
  - sensor.entur_royken_stasjon_platform_28309
  - sensor.entur_royken_stasjon_platform_28311
title: Avganger Røyken Stasjon
content: |
  {% for e in config.entity_id -%}
  {{ e }}
  {%- endfor %}`

**Comment by iantrich** [comment]
Please submit a PR to the docs

**Comment by zsarnett** [comment]
Issue is open in Doc Repo

**Comment by mikepan-ovoenergy** [comment]
This one is still reproducible.

**Comment by fabiopedrosa** [comment]
@zsarnett this is still happening.
