### ISSUE TITLE
More Info - hide "Related" tab if nothing is related

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4734]
## The request

When clicking on the settings cog in more info dialogs, it has a Related tab. But often when you click it there's nothing inside that tab, like in the below screenshots of an input_boolean. 

![related](https://i.imgur.com/ICUVy1Q.png)

This tab should be hidden if there's nothing related. If users click on this and end up empty handed with a blank tab half the time, it's a bit frustrating and they will stop trying after a while.

## The alternatives

Display text that says "Nothing related to this entity" or something, so that at least it's not blank. But would be best to just hide the tab completely if there's nothing related.

**Comment by balloob** [comment]
When the dialog opens we haven't fetched related info. Right now it's only fetched if you click on related. 

If the user has to wait to see the whole dialog before we know related -> bad, slows down dialog.
If the user sees the related appear a bit later, that's also bad.

I think I would prefer the empty state.

**Comment by balloob** [comment]
Also, once we have input booleans admin UI, this screen will go away. 

Also, if your input boolean is not related to anything, why have it ?

**Comment by SeanPM5** [comment]
That explanation makes sense and I agree with the choice.

My input boolean _is_ used in automations, but it's not showing on related tab yet. I see now that entities within automation conditions and triggers aren't supported by related at the moment which explains why. Most of my 133 (!!) input booleans are used in that way.

Once support for that gets added in the backend, this will be a non-issue as related tab will rarely be blank. So I will close this.
