### ISSUE TITLE
Active icon states color options

### ISSUE THREAD

**Issue by olbjan** [home-assistant/home-assistant-polymer#4741]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

With 0.105 new icon state color options were introduced for many more types of entities. Whilst I welcome this change I take issue with two of the domains:
On media player and alarm_control_panel the choice seems nonsensical:

Media player: this equals any state other than off to active. I believe in the most commonly used integrations these entities are never truly off (Sonos eg is either playing or paused).
To me it makes more sense to visually differentiate playing and any other state.

Alarm_control_panel:
State disarmed looks active (yellow). Maybe better differentiate between armed_home, armed_away and triggered.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
I agree with the media player. Only playing should be considered active.

No real opinion on alarm control panel. Maybe just no color at all ?

**Comment by starkillerOG** [comment]
Sorry did not see this issue when I created mine.

I do like and use the icon color on alarm_control_panels to see in a glance card if and which alarms are turned on/off.
Would be greath if at least the colors could be inverted.

_Now:_
disarmed = yellow
armed = blue
_expected:_
disarmed = blue
armed = yellow

Could indeed also use other colors if that would make it more clear.
We could match the colors of the alarm-panel card:
disarmed = green
pending = yellow
armed = red

**Comment by iantrich** [comment]
@starkillerOG I like the idea of matching the alarm-panel card. I'll look into that change soon 👍
