### ISSUE TITLE
Theme list is cut off at the top when list is long

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/home-assistant-polymer#475]
When the theme list is very long (long enough to need to scroll), the top entry (Backend-selected) gets cut off and can't be selected by clicking/tapping.

![image](https://user-images.githubusercontent.com/1326315/31967867-d325c62e-b8d4-11e7-9736-ae4d639ee20c.png)

**Comment by balloob** [comment]
Would you want to write a blog post for the Home Assistant blog showcasing some of your favourite themes?

**Comment by tboyce021** [comment]
Most of these are just **really** basic themes (i.e. only change the primary colors). I only just realized there were themes a couple days ago. Plus, I probably won't have time for awhile, getting married in two days! 😄

**Comment by balloob** [comment]
Congratulations!
