### ISSUE TITLE
Add administrative rights to Lovelace UI

### ISSUE THREAD

**Issue by Joebuckeye123** [home-assistant/home-assistant-polymer#4754]
Excellent work with Home Assistant companion.  I plan to make Home Assistant Companion (Android app) the front-end of a tablet that will be used by family members to navigate Lovelace UI.  Have one concern: The only person that should have access to the Home Assistant back-end is the Administrator.  
Can a login/logoff be added to the Lovelace UI (Upper right-side) toolbar.  If you are not the Admin the Home Assistant (left-side) toolbar will not be available.  If you log in as Admin the toolbar will remain available until you log out.  This should only apply to the Home Assistant Companion device that will be used by family members.
I would take care of this myself.  Don’t have the technical skill set yet to make this happen.  It’s a long road.  Working my way there.

**Comment by iantrich** [comment]
If I understand correctly, you want the sidebar to be hidden for non-admins. This is not something we will implement. You can explore custom solutions like custom-header that provides a kiosk-mode if you wish.

**Comment by Joebuckeye123** [comment]
Thank you for the response.  I will look into kiosk-mode.
