### ISSUE TITLE
HA remains in "Initializing" when launching through Fully Kiosk/Wallpanel

### ISSUE THREAD

**Issue by whattheschnell** [home-assistant/home-assistant-polymer#4767]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

The kiosk app does shows "Initializing" remains in that state

## Expected behavior

Launch HA through Wallpanel/Fully Kiosk Browser

## Environment

Home Assistant release with the issue:
0.104.x

Last working Home Assistant release (if known):
N/A

UI (States or Lovelace UI?):
lovelace

Browser and Operating System:

android version: 6.0.1
browser: unknown
kiosk app:  Fully Kiosk Browser & wallpanel 
Note: google chrome works fine.
Description of problem:

Same as https://github.com/home-assistant/home-assistant-polymer/issues/3781.  Just present in 0.104.x

**Comment by bramkragten** [comment]
The webview that they use is not supported by Home Assistant, try: https://github.com/thanksmister/wallpanel-android-legacy

**Comment by marronedamian** [comment]
Install Opera worked for my android 4.2

**Comment by krisxnlx** [comment]
On my old Samsung tablet, under developer options, I could choose WebView Deployment. Set this to Google WebView instead of AOSP WebView. Works perfect, Initializing problem is gone now.
