### ISSUE TITLE
Allow enabling/disabling automation from edit screen

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4778]
## The request

Because it's possible now to go an automation editor page from the device info, it would be great if we can see if an automation is enabled/disabled on the device info page and be able to turn it on/off from either the automation editor page or on the device info page.

**Comment by escoand** [comment]
I would like to have the "TRIGGER" button as well.

And maybe also every trigger and condition could show there current state. I had something like the "Function Arguments" dialog from Excel in mind: https://www.teachucomp.com/wp-content/uploads/Slide62.jpg

**Comment by escoand** [comment]
OK, my second request is already existing at #4685.
