### ISSUE TITLE
Hide battery sensors from the generated UI

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4780]
## The request

We should exclude battery sensors from the generated UI. People can check their battery status on the device tab or device info page.

**Comment by iantrich** [comment]
It could also be a great secondary-info addition. Could reference the device registry to see if an entity has a battery and display that?

**Comment by balloob** [comment]
Yeah, longer term I want to be able to allow users to set a "low battery threshold" for each device (with sensible defaults), and if an entity has a low battery add a badge to the icon.

**Comment by iantrich** [comment]
Love that idea!
