### ISSUE TITLE
Only serve transpiled assets for old browsers

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#479]
Transpiled code is obfuscating the intention of our JavaScript code. This leads to a bigger file size and to JavaScript engines not being able to optimize as much.

Approach taken from https://philipwalton.com/articles/deploying-es2015-code-in-production-today/ (found it via talk from Chrome Dev Summit)

```html
<!-- Browsers with ES module support load this file. -->
<script type="module" src="main.js"></script>

<!-- Older browsers load this file (and module-supporting -->
<!-- browsers know *not* to load this file). -->
<script nomodule src="main-legacy.js"></script>
```

For frontend.html, this saves us almost 100kb ! 

## File sizes with transpilation:

![image](https://user-images.githubusercontent.com/1444314/32032901-4474a2ac-b9be-11e7-8959-a0918e517933.png)

![image](https://user-images.githubusercontent.com/1444314/32032906-4f7d5f90-b9be-11e7-9ea6-81b9e7f8e3ae.png)

## File sizes without transpilation

![image](https://user-images.githubusercontent.com/1444314/32032978-b69d59be-b9be-11e7-8589-d4edf84becf2.png)

![image](https://user-images.githubusercontent.com/1444314/32032990-c16fe546-b9be-11e7-9c30-4b93412773f8.png)

**Comment by balloob** [comment]
Note, minification was done with babel-preset-minify because uglifyjs doesn't support ES2015. Running that preset on transpiled code will result in bigger files than uglifyjs:

## Transpiled and minified with babel-preset-minify

![image](https://user-images.githubusercontent.com/1444314/32033113-8b660380-b9bf-11e7-8c97-4ab134bb1c76.png)

![image](https://user-images.githubusercontent.com/1444314/32033116-9213c4ba-b9bf-11e7-9285-5ebc8b4b8e3c.png)

**Comment by balloob** [comment]
When we start to distinguish between transpiled / not transpiled, it will also be easy to start adding polyfills by default to the transpiled version but keeping the ES2015 version lean.

**Comment by andrey-git** [comment]
There is uglify-es for es6
The article says to special-case Safari10

**Comment by andrey-git** [comment]
Btw according to caniuse - type="module" is not supported by FF: http://caniuse.com/#feat=es6-module
Maybe use a traditional useragent-based approach?

**Comment by balloob** [comment]
Yeah I would be fine with that too.

**Comment by balloob** [comment]
This has been implemented by Andrey.
