### ISSUE TITLE
​ Expected a value of type `undefined` for state_color in Entities Card Configuration

### ISSUE THREAD

**Issue by reefland** [home-assistant/home-assistant-polymer#4797]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Per instructions in 0.105.0, to get entity icon colors based on state within Entities Card I added "state_color: true".  The functionality is working (I get colors), however I get the warning message:

```Expected a value of type "undefined" for "state_color" but received "true"```

## Expected behavior

Should not get this warning message.

## Steps to reproduce

1. Click Configure UI
2. Click [EDIT] on Entities card
3. Click [SHOW CODE EDITOR]
4. Add line ```state_color: true```

Warning message is shown.

5. Click [SAVE]

## Environment

- Home Assistant release with the issue: 0.105.0
- Last working Home Assistant release (if known): 0.104.3
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chromium Version 79.0.3945.130
- Operating system: 
os_name: FreeBSD
os_version: 11.2-STABLE
python_version: 3.7.5

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is not supported in the UI editor, that's why we only show the YAML editor.

**Comment by davidkmcgowan** [comment]
Is there a better way to turn state on for certain cards and not disable the UI?  Seems like a feature got turned off, makes sense why, then a way to turn it back on when needed was posted, great, but then you lose the UI editor
