### ISSUE TITLE
Add theme picker row to Lovelace

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#4813]
## The request

People are using `frontend.set_theme` to change the theme on their frontend. Since this is changing the default for all users, it's going to require admin access in 106 (via https://github.com/home-assistant/home-assistant/pull/31654). **Update:** This is not an issue because it's called from an automation. 

To allow users to pick themes from the UI, we should implement a theme picker row that renders the available themes and fires a `settheme` event to change the theme. That will then be stored in the browser.

We should be able to reuse the row from the preferences: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/profile/ha-pick-theme-row.js

**Comment by bramkragten** [comment]
Why shouldn't they use the theme picker in preferences? That does exactly this?

**Comment by basnijholt** [comment]
@bramkragten, see [this](https://www.reddit.com/r/homeassistant/comments/ex7mve/after_a_lot_of_love_a_muchrequested_feature_more/) post I made.

It's mainly to have an easy way to switch between "light" and "dark" mode.

**Comment by bramkragten** [comment]
This would not include the dark mode switch, so you would get the same as in preferences, double the number of thems you have in your current drop down.

**Comment by basnijholt** [comment]
I understand how it works, I am just explaining why someone might want to switch themes inside their frontend.

**Comment by balloob** [comment]
I thought that making it admin access would be a bigger issue than it actually is. It is not as the automation is fired with admin access, so it can still change the default theme for all users. It might be unexpected though if someone else in your house is using the app and their UI changes 😆
