### ISSUE TITLE
Logger screen scrolling problem on iOS 

### ISSUE THREAD

**Issue by jazzmonger** [home-assistant/home-assistant-polymer#4814]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

  iOS 12.4.1 browser chrome or safari. Logger window scrolling only goes one line at a time. Not able to smooth scroll with finger swipe like on other versions.  Not a show stopper but Very annoying. 

## Expected behavior

  Drag a finger on the window and the page should scroll like in other versions up to this point. 

## Steps to reproduce
    1. Log in. 
    2. Navigate to Lovelace
    3. Click logger
    4. Try to scroll the page

## Environment
- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): .102 (I think, but any prior version)
- UI Type (Lovelace): 
- Browser and browser version: iOS iPad, or iPhone. 
- Operating system: iOS 12.4.1
- safari or chrome. Both exhibit the same problem. 
## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by KapJI** [comment]
It looks like this is related to #4450 which introduced `lit-virtualizer`.

cc @bramkragten

**Comment by KapJI** [comment]
I can see exact the same problem with `lit-virtualizer` [examples](https://polymerlabs.github.io/uni-virtualizer/) on  iOS. But with Chrome on Android it works fine.

**Comment by KapJI** [comment]
This is actually should be merged with https://github.com/home-assistant/home-assistant-polymer/issues/4791

**Comment by jazzmonger** [comment]
This issue remains and has since it was reported. I just tried it on the latest release

raspberrypi3-homeassistant tag 0.106.2.

No change. Log only scrolls one line at a time..

**Comment by bramkragten** [comment]
This is not released yet. Will be in 0.107
