### ISSUE TITLE
alarm_control_panel: icon color inverted in glance card

### ISSUE THREAD

**Issue by starkillerOG** [home-assistant/home-assistant-polymer#4820]
## The problem

If you add an alarm control panel to a glance card (alarm_control_panel.home_alarm), the icon is yellow when the alarm is off and standard blue when the alarm is armed, this is inverted compared to every other enitity that shows up yellow when 'on' and blue when 'off'. This happens for multiple diffrent alarm_control_panel integrations.

Note: I think this was not the case in HomeAssistant 0.104.x, updating to 0.105.2 made the colors invert. HomeAssistant 0.105.2 also made changes to the way colors are used in icons.

Expected behavior:
Armed/on = yellow icon
disarmed/off = blue icon

## Environment

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): 0.104.x
- Operating environment (Hass.io/Docker/Windows/etc.): Linux
- Integration causing this issue: alarm_control_panel
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bramkragten** [comment]
Duplicated of https://github.com/home-assistant/home-assistant-polymer/issues/4741
