### ISSUE TITLE
Can not add Integrations, Automations or access Notifications

### ISSUE THREAD

**Issue by cdk222** [home-assistant/home-assistant-polymer#4823]
Following recent update of Home Assistant 0.105.2 I am now unable to do the following from the UI:

- Notifications do not open (but does show unread notifications icon)
- Cant press “configure” to install a discovered integration
- Cant press “+” in the Integrations menu to add a new integration
- Cant press “+” in the Automations menu to add a new integration
- Receive a spinning disc when trying to open “states” or “entities” in developer tab

The only other thing I did following the upgrade with remove MQTT addon but dont see how this could cause the above.

Tried to roll back my config using previous snapshot but these issues remained once rollback complete.

**Comment by bramkragten** [comment]
Please don't remove the issue template.

Try clearing your cache and check for error in your console.  If it doesn't solve it, recreate the issue following the template.
