### ISSUE TITLE
Mikrotik integration since 0.105 doesn't allow to disable auto-adding

### ISSUE THREAD

**Issue by Aesculapius** [home-assistant/home-assistant-polymer#4830]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Since latest HA 0.105.2, the new mikrotik device tracker integration is live. I disabled the config in configuration.yaml and added the integration via front UI. Took a few restarts to see devices being collected by the integration, but it adds far too many of them (all of them), which results in endless devices being added that I have no interest in to track.

So I want to disable adding new devices, but the toggle button for that in the UI doesn't save its state. Once toggled, if I click elsewhere and go back to the setting, its value is restored...

## Expected behavior

Would expect either a save button, or the latest value to be respected.

## Steps to reproduce

1. add mikrotik integration
2. go to second option menu in the top-right
3. change the value from enabled (default) to disabled
4. Click elsewhere to remove the lightbox popup
5. Go back to the settings menu to see its value unchanged.

![image](https://user-images.githubusercontent.com/617061/74188726-52975c00-4c4f-11ea-9338-cdb5e4ca4234.png)

## Environment

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): 0.104
- UI Type (States or Lovelace): lovelace
- Browser and browser version: latest chrome 
- Operating system: virtualenv on ubuntu

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

no console errors
```txt

```

**Comment by bramkragten** [comment]
There is a button in the bottom right, but the translation is wrong. I'll fix that.

If you go to the bottom right of the dialog you'll your cursor changes to a pointer. That's the button.
