### ISSUE TITLE
Support state_color:false to disable icon coloring based on state in all cards

### ISSUE THREAD

**Issue by TazUk** [home-assistant/home-assistant-polymer#4838]
## The request
Regarding the 0.105.x introduction of additional domain icon colouring based on states that are determined to be appropriate (e.g. alarm_control_panel state of 'disarmed', input_boolean state 'on) and the default disabling of state_color in the entity card with the option to enable at card or entity level using `state_color: true`.
I would request that cards that do show icon coloring on state implement `state_color: false` at entity or card level to enable users to adjust this feature according to their requirements.

Recent discussions in the forums have been quite animated on this change, e.g. [this thread](https://community.home-assistant.io/t/how-to-make-state-color-true-global/169556) and this change would provide additional flexibility without impacting the default interface for new users.

Cards such as the entity-button already support the display of non-default icons for entities, and this change would effectively reinforce this user choice.

## The alternatives
 My situation is that I use a large set of entity-button cards conditionally displayed with custom icons based on state. The icons indicate the current state of the entity without requiring state-color, and the users of my system are used to this arrangement.

Suggested alternatives include a custom button card, e.g. [this one](https://github.com/custom-cards/button-card).
This will require the addition of non-standard components to my somewhat standard system and additional UI rework in place of an existing standard card that did exactly what I wanted until 0.105.x changes.

**Comment by SeanPM5** [comment]
IMO this makes a lot of sense and is a reasonable request. 

If you could set `state_color: true` to override the default behavior on Entities card, you should be able to do the same thing for other cards by setting `state_color: false`.

Keep the exact same behavior as now, but allow people to override the default if they wish.

**Comment by Mariusthvdb** [comment]
let me second that request indeed, please revert this logic at least to have the user select false if so desired. 
truly wonder how many people would do so..
would like to extend it to be a global setting even, since now we are forced to do my per card settings. see https://github.com/home-assistant/home-assistant-polymer/issues/4821#issuecomment-584199072 for more on that request.

**Comment by iantrich** [comment]
@TazUk  I'll add this option to glance and button card

**Comment by TazUk** [comment]
> @TazUk I'll add this option to glance and button card

Thank you.

**Comment by CaptTom9** [comment]
I also support this request.

I was somewhat shocked when this change happened. I don't do much UI modification and so I don't follow planned changes. Until now, it's worked well, looked good and was always improving.

This is a huge step back for me. I have some cards with things like switches and sensors on them. It looks really dull if everything is "grayed out." It's difficult to see at a glace which devices are on or off.

I don't find it too complicated if lots of, say, lights are shown with colored icons when they're on. Isn't that what we want to know at a glance? My page is all lit up when my house is all lit up. Makes perfect sense. Likewise, when one of my heating zones, or my boiler is running, I want that to show up in color. If all zones are on, I get more color. Again, that's the desired result.

**Comment by frenck** [comment]
@CaptTom9 This issue is closed already, a change has been made 6 days ago...

**Comment by CaptTom9** [comment]
Oops! OK, thanks!!
