### ISSUE TITLE
Media player card doesn't check supported features

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/home-assistant-polymer#4844]
With the conversion of the media player to Lit (#4761), the checks for supported features where removed.

There is a class for media player entities that has all the logic:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/util/hass-media-player-model.js

**Comment by iantrich** [comment]
I would not use the model and just extract the features to consts and then just call supportsFeature as necessary
