### ISSUE TITLE
Card Editors - cancel button return to Add Card Picker instead of closing dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4869]
## The request

Currently when you are inside of a card and press the cancel button, it closes the entire dialog. 

I think that it might be a little nicer if it brought you back to the "Add Card" picker instead, here is why.

1. **Many cards are named kinda similarly, and so it's easy to make mistakes**. Entities, Entity Button, Entity Filter. And then there's Picture, Picture Elements, Picture Entity, Picture Glance. Users that are not familiar with the differences are going to be selecting the wrong ones at times. When this happens you wanna cancel out and quickly select the correct one, but it closes the whole dialog. 

2. **Demo users trying Lovelace for first time**. If you are playing with all two dozen(!!) cards, you will be encountering cards that have no UI editor yet, and want to cancel out of it and quickly move on to the next card. But instead it closes the whole dialog, have to launch everything again from the FAB in the bottom right.

Bringing the user back to Add Card picker screen would be just a little nicer imo. Does require one additional click if you fully want to cancel out, but it saves a click in the above examples which I think are much more common scenarios.

**Comment by iantrich** [comment]
Adding a back button, maybe, but I think cancel should remain as is

**Comment by SeanPM5** [comment]
Yeah I had thought of that initially, but I like how all the text lines up on the left side of the card editors - a button would ruin that clean look.

And on second thought, not sure it's a good idea to change the behavior of this cancel button either, will rethink this later.
