### ISSUE TITLE
Text Correction: "Read our founders vision for the perfect home automation."

### ISSUE THREAD

**Issue by antoniodowling** [home-assistant/home-assistant-polymer#4889]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem
Text does not use possessive for of "founders".

## Expected behavior

Text should read: "Read our founder's vision for the perfect home automation."

## Steps to reproduce

This is present on the "Setting up Home Assistant" screen.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
uhm… ?

**Comment by antoniodowling** [comment]
@balloob Apologies...forgot to uncomment some stuff.
