### ISSUE TITLE
Toggles are hard to tap on mobile device

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#49]
The polymer toggles are quite hard to tap when used on a mobile. I'm never able to tap them the first time, and the popup always opens.

Is it possible to add some padding around them so it's easier to tap with your fingers?

**Comment by michaelarnauts** [comment]
It seems there is an issue with the padding/margin anyway, as the "ripple effect" seems to be cut off.
![image](https://cloud.githubusercontent.com/assets/1193779/14490079/f223d63c-0170-11e6-8ae2-e7e3c04f2f70.png)

This doesn't happen on the demo pages: https://elements.polymer-project.org/elements/paper-toggle-button?view=demo:demo/index.html&active=paper-toggle-button

**Comment by balloob** [comment]
The passing has been increased in 0.17. You removed the issue template so I
don't know which version you're running. The cutting off is only in the
more info which doesn't have any side effects.

**Comment by michaelarnauts** [comment]
There is no issue template in this repo :)

Anyway, I just upgraded to 0.17, and the padding around the toggle seems to be `padding: 9px 0;`. If I change this to `padding: 9px;`, it's a lot better to click on the icon, and the layout doesn't seem to change.

**Comment by balloob** [comment]
Ah my bad, I thought this was an issue on the main repo.

I did explore this when I decided to just add a padding on top + bottom. Adding a padding on the right would make the switch not align with control for other entities. And since we can't have a padding on the right we also can't have a padding on the left or else it's not symmetrical.

**Comment by happyleavesaoc** [comment]
I have about a 50% success rate when toggling a switch on mobile. Too easy to accidentally open the graph.

**Comment by justweb1** [comment]
@balloob Can this issue be closed or should we still look into it.?

**Comment by michaelarnauts** [comment]
I still have the same remark as @happyleavesaoc . On mobile, I accidentally open the dialog a lot instead of toggling the switch.

**Comment by andrey-git** [comment]
This can be solved by increasing padding (Google recommends at least 48x48: https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately)
and compensating for it with negative margin. This way it doesn't move the element and doesn't affect parent size.
