### ISSUE TITLE
Inconsistent state_color:true behavior for covers and alarms

### ISSUE THREAD

**Issue by TheNr1Guest** [home-assistant/home-assistant-polymer#4902]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Inconsistent state_color:true behavior for covers and alarms:
- For covers; an open cover results in a colored icon while a closed does not.
- For alarms; a disabled alarm results in a colored icon while an armed does not.

## Expected behavior

If we take a look at very binary controls like lights and switches; an active state will color the icon. 
From that I take away that an entity is active when colored, therefor the state_color:true logic should be reversed for covers and alarms.

**Covers**
An active cover is one that is not in the default position. Default position for covers is open. If I look at my house, I have covers for privacy and I have awnings to block the sun. I expect the icon to be colored when they are both closed since that is when they are actively used.

**Alarms**
I expect an armed alarm to have a colored icon since that is the active state. And alarm that is disabled is not active and therefore should not have a colored icon.

## Steps to reproduce

1. Add a cover
2. Add an alarm
3. Add an entities card in Lovelace with both cover and alarm
4. Add the state_color:true option to the entities card
5. Notice that both icons will be colored when the cover is open and the alarm is disabled.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
The default for covers is closed. You have to remember that garage doors are also covers. 

Alarm panel will have different coloring scheme in 0.106

**Comment by TheNr1Guest** [comment]
> The default for covers is closed. You have to remember that garage doors are also covers.
> 
> Alarm panel will have different coloring scheme in 0.106

Ok I understand that the default state is closed when you look at it from a door perspective. But if you look at it from the perspective of an actual cover or awning, don't you agree that open should be the default state?

Since covers can be used for more than actual covers I would expect an additional property like state_active_on_close:false or something like that.

Good to here about the alarms.

**Comment by iantrich** [comment]
Perhaps but I think this would then fall under a feature request to support device-class and not be a bug. I'm going to close this, but feel free to open a FR with the details on how you think that should work.
