### ISSUE TITLE
Entity-Button card stays highlighted after click/touch

### ISSUE THREAD

**Issue by mikenabhan** [home-assistant/home-assistant-polymer#4913]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When clicking on lovelace buttons, the card stays highlighted as if I am holding down the button.  This happens across browsers, (tested in firefox and chrome on desktop, safari and the official home assistant companion app on iOS on mobile).  This issue is happening on the entity-button card natively in home assistant.  Until I click on deadspace in the ui, the button will still stay highlighted.

This started as of HA version .105.0 and stops upon a revert to .104.x

## Expected behavior

I would expect the button to immediately unpress after releasing the click or touch when on a mobile device. 

## Steps to reproduce

1. Press a button in the UI
2. Release button in the UI
3. Button stays highlighted

## Environment

This started as of HA version .105.0 and stops upon a revert to .104.x

- Home Assistant release with the issue: .105.5
- Last working Home Assistant release (if known): .104.x
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox/Safari/Chrome (Desktop), Safari/Home Assistant Companion (iOS)
- Operating system: Generic Linux Hass.io install on Ubuntu 18.04

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | America/Denver
version | 0.105.5
virtualenv | false

## Problem-relevant configuration

```yaml

entity: light.kitchen_light
hold_action:
  action: more-info
show_icon: true
show_name: true
tap_action:
  action: toggle
type: entity-button


```

## Javascript errors shown in your browser console/inspector

```txt

```
No error logs in console :(

## Additional information

![behaviour1](https://user-images.githubusercontent.com/13139061/74759675-67b75080-5236-11ea-8901-0fc18c77c321.png)
![behaviour2](https://user-images.githubusercontent.com/13139061/74759682-6a19aa80-5236-11ea-9769-62257fbb7156.png)

I have tried removing all custom lovelace cards and this does not fix the issue.  I am not running any custom theme.

**Comment by mikenabhan** [comment]
Now that I am looking at other parts of the UI, this issue is happening in other UI elements.  Here is an example in the entities card.

![image](https://user-images.githubusercontent.com/13139061/74760992-7d2d7a00-5238-11ea-904e-515d670331f2.png)

**Comment by mikenabhan** [comment]
Duplicate of #4788 

But that bug report doesn't document this behavior in other lovelace elements.

**Comment by iantrich** [comment]
this is an artifact of us implementing tabindex. We'd have to track if tab or mouse is used in each interaction and apply focus only on a tab key interaction. Simple enough for a single element, but messy to do on all. Not sure if this could be handled somehow in the action-handler, @bramkragten?

**Comment by zsarnett** [comment]
Closing. The conversation should be continued on original report. I have updated to include all elements. Added this as supporting details
