### ISSUE TITLE
Card editors semi-broken on 0.106.0 - visual editors blank

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant-polymer#4925]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

**EDIT**: reproduced the same issue on many cards, so updated title... Everything in the issue that is written below also applies to the following cards.

1. iFrame
2. Markdown
3. Map
4. Picture
5. Picture Elements
6. Picture Entity
7. Picture Glance
8. Plant
9. Shopping List

<hr>

iFrame card visual editor is (kinda, sorta?) broken on 0.106.0b0.

When first opening it, it defaults to the code editor with just a single line, `iframe:` despite it having a visual editor. See screenshot:

![image](https://i.imgur.com/6UK0AT7.png)

Tapping show visual editor button here brings you to this empty screen with nothing there. So it's not loading the expected fields (url, title, aspect ratio) or preview on the right for visual editor.

![image](https://i.imgur.com/86d3HY0.png)

If I switch back to the code editor and add some YAML code there:

```
type: iframe
url: https://home-assistant.io
aspect_ratio: 75%
```

I am then finally able to switch back to visual editor and see all of the fields there. And from then on, it appears to work normally as expected **until restarting Home Assistant which is when it breaks again like above**. Experienced this first on my setup but also reproduced on the [demo site](https://demo.home-assistant.io/#/lovelace/0).

## Expected behavior

Show a working visual editor by default as it did before

## Steps to reproduce

1. Go to [demo site](https://demo.home-assistant.io/#/lovelace/0), enter Configure UI Mode
2. Add new card
3. Choose iFrame Card

## Environment

- Home Assistant release with the issue: 0.106.0b0
- Last working Home Assistant release (if known): 0.105.X
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
Common theme seems to be that there are all in the lazy load section: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/create-element/create-card-element.ts#L32
