### ISSUE TITLE
High CPU usage in backend when using history-graph card

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant-polymer#4926]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The CPU usage of the HA server raises when using a history-graph card in LL

## Steps to reproduce

After adding on history-graph to a view, CPU fan gets louder.
docker stats shows
```
CONTAINER ID        NAME                    CPU % 
bfc796dc6cfc        homeassistant           93.12% 
5cdf2eea383e        addon_a0d7b954_ssh      0.01%
ca24717c50aa        addon_a0d7b954_vscode   16.11%
41b2d2c909ea        addon_core_mosquitto    0.23%
0236958263c0        addon_core_mariadb      7.73%
1bfd2e78add9        hassio_dns              0.00%
4dee01e63d18        hassio_supervisor       0.00% 
```
after removing the card and reload browser, all is good.
```
CONTAINER ID        NAME                    CPU %
bfc796dc6cfc        homeassistant           0.27%
```

## Environment

- Home Assistant release with the issue: 0.106.0b0
- Last working Home Assistant release (if known): 0.105.5
- UI Type (States or Lovelace): LL
- Browser and browser version: FF and Chrome
- Operating system: VirtualBox VM, ubuntu 16.04, HA supervised

## Problem-relevant configuration

```yaml
type: history-graph
entities:
  - entity: sensor.test_temperature
hours_to_show: 24
refresh_interval: 0
```
I assume related to https://github.com/home-assistant/home-assistant-polymer/pull/4882

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by VDRainer** [comment]
Update:
CPU on server raises also when i only add a new card, select the history-graph and click 'CANCEL'
After that, CTRL-F5, and the CPU is normal again.

**Comment by zsarnett** [comment]
I will take a look at the issue later today. Assuming it has something to do with the interval being set if the refresh interval is set to Zero. Meaning it refreshes all the time (not good)
