### ISSUE TITLE
Tab RELATED is empty when opened from lovelace card in 0.106.0b0 

### ISSUE THREAD

**Issue by SukramJ** [home-assistant/home-assistant-polymer#4938]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The tab related is empty when opened from lovelace card.

![grafik](https://user-images.githubusercontent.com/5650106/74922248-3920ad80-53cf-11ea-998e-799b34b01f61.png)

This is a problem with entities of all used integrations.
It's no problem when opening tab from device or entity registry.
![grafik](https://user-images.githubusercontent.com/5650106/74922588-b8ae7c80-53cf-11ea-8b9b-20c330bf5d65.png)

## Steps to reproduce

1. open an entity from a lovelace entity card
2. click on settings
3. open related tab

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration
I tried:
- Firefox 68 / 73 on Windows 10
- Chrome 80 on Mac
- Firefox 73 on Mac

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Berlin
version | 0.106.0b0 
virtualenv | false

Last working on 0.105.5

```yaml
entities:
  - entity: switch.schalter_har_2
  - entity: switch.schalter_carport_1
state_color: true
title: Aussenbeleuchtung
type: entities
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is fixed in 0.107
