### ISSUE TITLE
MDI icon mdi:christmas-lights doesn't show in lovelace

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/home-assistant-polymer#4939]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The icon mdi:christmas-lights doesn;t show in lovelace, despite HA has been updated.

## Expected behavior

The icon is visible in lovelace.

## Steps to reproduce

Just use mdi:christmas-lights icon for any lovelace entity.

## Environment

- Home Assistant release with the issue: Home Assistant 105.4
- Last working Home Assistant release (if known): None
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Opera 66.0.3515.72
- Operating system: DSM 6.2.2-24922 Update 4

## Problem-relevant configuration

```

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
That's not an actual icon. Where are you seeing that as valid?

**Comment by iantrich** [comment]
found it via its alias. we don't support aliases. use `mdi:string-lights`

**Comment by Spirituss** [comment]
Thanks! It works.
