### ISSUE TITLE
Type "entity-button" shows wrong state

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant-polymer#4943]
## The problem

```- cards:
      - entity: group.grp_watchwinder_power
        hold_action:
          action: more-info
        icon_height: 119px
        show_icon: true
        show_name: false
        type: entity-button
```

Type entity button shows wrong state.
It's off even if the state of the entity is on

```
type: entities
entities:
  - entity: group.grp_watchwinder_power
```

Same entity works well on a different type like the one above

Please fix

## Environment
* Home Assistant release with the issue: 0.105.4
* Last working Home Assistant release (if known): none
* Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
* Integration causing this issue: Scripts
* Link to integration documentation on our website: https://www.home-assistant.io/integrations/script/

**Comment by iantrich** [comment]
The `group` domain does not change state color

**Comment by sblantipodi** [comment]
@iantrich isn't this a bug a glitch or something that we don't want?

**Comment by iantrich** [comment]
As it stands currently, no. You'd have to come up with a pretty complete feature request to support groups. They are not just on/off. They are the majority state of the group. Which can be mixed between domains. 

You can find the current implementation here: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/common/style/icon_color_css.ts
