### ISSUE TITLE
group issue

### ISSUE THREAD

**Issue by toze1619** [home-assistant/home-assistant-polymer#4949]
## Checklist

- [check] I have updated to the latest available Home Assistant version.
- [check] I have cleared the cache of my browser.
- [check] I have tried a different browser to see if it is related to my browser.

## The problem

in one update my group didnt apear anymore with all ententies, for example if i creat a small window the list off group dont ajuste anymore to see all enteties with scroll down or slider up/down in android.
https://ibb.co/B36Vbdf

## Expected behavior

before i can scroll down or slide down to see all enteties

## Steps to reproduce

https://ibb.co/Xyy8Q0y

## Environment

System | HassOS 3.11
Published under the Apache 2.0 license
Source: servidor — frontend-ui
Construído com Python 3, Polymer, Ícones por Google and MaterialDesignIcons.com.
Frontend version: 20200130.3 - latest
Ir para a UI states (DEPRECATED)
Definir states (DEPRECATED) as default page on this device

- Home Assistant release with the issue: 
- Last working Home Assistant release: i think 3 realease below 
- UI Type (States or Lovelace): 
- Browser and browser version: google chrome and avast secure brower
- Operating system: i try in android and windows 7 

## Problem-relevant configuration
https://paste.ubuntu.com/p/msTysCDDP8/
  alarm_4:
    name: Alarm Clock4
    icon: 'mdi:alarm'
    entities:
      - input_select.chromecast_radio_alarm4
      - input_number.volume_radio_alarm4
      - input_select.radio_station_alarm4
      - input_boolean.alarm4_weekday_enabled
      - sensor.alarm4_weekday_time
      - input_number.alarm4_weekday_hour
      - input_number.alarm4_weekday_minutes
      - input_boolean.alarm4_weekend_enabled
      - sensor.alarm4_weekend_time
      - input_number.alarm4_weekend_hour
      - input_number.alarm4_weekend_minutes
      - sensor.time

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is fixed in 0.106
