### ISSUE TITLE
Visual editor - Error Unknown Type

### ISSUE THREAD

**Issue by GP920** [home-assistant/home-assistant-polymer#4955]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When using Visual updater to edit previously created cards in lovelace, it is showing: "Error: Unknown type: glance". Seeing same error for horizontal-stack as well ("Error: Unknown type: horizontal-stack"). Can't save any edits as the save button remains greyed-out. 

Also cannot create any lovelace cards that are an unrecognized type. Glance, Horizontal stack, etc.

## Expected behavior

Should be able to create and edit lovelace cards that are  specified types

## Steps to reproduce

1. "Configure UI"
2. Try to add Card, type: "Glance" (Can't seem to add cards that are not recognizable types.)

1. "Configure UI"
2. Edit pre-existing "glance" card. 
3. Visual editor shows "Error: Unknown type: glance" and save button is disabled.

## Environment

- Home Assistant release with the issue: 0.106.0b1
- Last working Home Assistant release (if known): 0.105.4
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79.0.3945.130 (Official Build) (64-bit) also Microsoft Edge 44.18362.449.0
- Operating system: Windows 10

## Problem-relevant configuration

```type: glance
   columns: 2
   entities:
     - entity: sensor.dark_sky_temperature
       name: Outside
     - entity: sensor.dark_sky_apparent_temperature
       name: Feels Like
     - entity: sensor.downstairs_thermostat_temperature
       name: Downstairs
       icon: mdi:stairs-down
     - entity: sensor.samjin_button
       name: Upstairs
       icon: mdi:stairs-up

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

edit: changed 0.105.3 to 0.105.4 for last working version.
edit2: changed 0.106b1 to 0.106.0b1

**Comment by Tediore** [comment]
Having the same issue. Seems to happen for button, entities, glance, horizontal and vertical stack, and sensor cards. I see many instances of this (and similar) in the Chrome browser console:
```
Uncaught (in promise) Error: Unknown type: horizontal-stack
    at u (create-element-base.ts:202)
    at Bt (create-card-element.ts:64)
    at HTMLElement.value (hui-card-picker.ts:100)
    at y.handleEvent (parts.ts:505)
    at HTMLElement.__boundHandleEvent (parts.ts:463)
```

**Comment by iantrich** [comment]
Should be fixed in 0.106.0b2

**Comment by Cabalforces** [comment]
In the meantime the [YAML mode](https://www.home-assistant.io/lovelace/yaml-mode/) can be a suitable workaround.

**Comment by iantrich** [comment]
YAML mode is not necessary. Use manual card option or raw config editor

**Comment by GP920** [comment]
Unfortunately can't use the manual card option. It throws the same error (unknown type) and won't let you save it. 

Raw config works tho.

**Comment by Tediore** [comment]
Can confirm it's working again in 0.106.0b2. Thanks!
