### ISSUE TITLE
Glance card activation marker stuck after tap

### ISSUE THREAD

**Issue by meinarsson** [home-assistant/home-assistant-polymer#4960]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When i tap an icon in a glance card the icon is highlighted with a grey square bakground. This highlight stays until i tap somewhere else in the page.
This occurs in Safari on iOS, Chrome on android, Chrome on windows and the HA companion on Android and iOS.

## Expected behavior

The icon should return to its previous state after the tap

## Steps to reproduce

Tap (or click on windows) any icon in a glance card

## Environment

- Home Assistant release with the issue: 105.5
- Last working Home Assistant release (if known): 104.x
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version: Safari on iOS 13.3.1
- Operating system: iOS 13.3.1

## Problem-relevant configuration

```yaml


```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![0D2DFD12-3BC7-4F66-A8F1-1CBEBA13F589](https://user-images.githubusercontent.com/27996200/75098725-0dade680-55ba-11ea-9e32-b5b3ac314e29.png)

**Comment by eggman0131** [comment]
Is this a duplicate?

https://github.com/home-assistant/home-assistant-polymer/issues/4788

**Comment by meinarsson** [comment]
> Is this a duplicate of #4788 ?

Yes, it seems to be the the same problem as #4788

**Comment by meinarsson** [comment]
Closing this since it is a duplicate of #4788
