### ISSUE TITLE
Lokalise Translate Project Reviewer permission Application

### ISSUE THREAD

**Issue by w27** [home-assistant/home-assistant-polymer#4961]
## The request

I would like to apply for ''reviewer'' permission of project 
**Home Assistant - Backend**
and
**Home Assistant - Polymer frontend**.
in language **Chinese Simplified**.

This is because the former reviewer haven't been active for a long time(about 2 years). Some entries were locked before while it requires unlocking for modify now. And some entries should be locked to prevent casually edits. 

I have been using Home Assistant since 2017 and translated half of entries of the Home Assistant project. So I am capable of it. My Lokalise account is 1902457591 (at) qq.com .

Thank you for your consideration. I look forward to your reply.

**Comment by bramkragten** [comment]
What is your email address for Lokalise?

**Comment by w27** [comment]
@bramkragten 

> What is your email address for Lokalise?

1902457591@qq.com

**Comment by bramkragten** [comment]
Done!
