### ISSUE TITLE
Updated to Home Assistant 0.106.0 new Custom Cards not working

### ISSUE THREAD

**Issue by Joebuckeye123** [home-assistant/home-assistant-polymer#5004]
Hello - Reporting a new issue that occurred with update to 0.106.0.  Checked my current Home Assistant to verify there would be no issues with an update to 0.106.0.  This check was OK.  Updated to 0.106.0 and restarted.  I checked all of my Lovelace tabs and found the the custom: canvas-gauge-car and the custom: button-entity-row cards are no longer working.  I download the most recent files canvas-gauge-card.js and gauge.min.js.  Verified correct path for url: /local/custom_cards/canvas-gauge-card.js

I've had both of these cards working for more than 2 months.  See attachments: 

Please advise on any changes required.  Thanks.

![custom button error](https://user-images.githubusercontent.com/49767800/75398022-7fda4000-58c6-11ea-879c-568ce22bb1a5.png)
![custom canvas card error](https://user-images.githubusercontent.com/49767800/75398026-8072d680-58c6-11ea-8df8-2d6d33d1e760.png)

**Comment by bramkragten** [comment]
Create issues for the custom cards in question

**Comment by Joebuckeye123** [comment]
OK

**Comment by Joebuckeye123** [comment]
Unable to locate the custom: canvas-gauge-car and the custom: button-entity-row cards
to submit these issues  Please provide a link for both.  Thanks

**Comment by Joebuckeye123** [comment]
Separated these 2 issues and re-posted them in home-assistant-polymer

**Comment by iantrich** [comment]
You installed these cards, you should know where you got them from?
