### ISSUE TITLE
Custom canvas gauge card stopped working with Home Assistant 0.106.0

### ISSUE THREAD

**Issue by Joebuckeye123** [home-assistant/home-assistant-polymer#5005]
custom: canvas-gauge-card
Reporting a new issue that occurred with update to 0.106.0. Checked my current Home Assistant to verify there would be no issues with an update to 0.106.0. This check was OK. Updated to 0.106.0 and restarted. I checked all of my Lovelace tabs and found the custom: canvas-gauge-card is no longer working. I download the most recent files canvas-gauge-card.js and gauge.min.js. Verified correct path for url: /local/custom_cards/canvas-gauge-card.js
I've had this card working for more than 2 months. See attachments:
Please advise on any changes required. Thanks.

![custom canvas card error](https://user-images.githubusercontent.com/49767800/75409004-6e546080-58e5-11ea-8033-8b73dc37f402.png)

**Comment by iantrich** [comment]
log the issue on the custom card repo
