### ISSUE TITLE
Custom HACS button-entity-row card stopped working with Home Assistant 0.106.0

### ISSUE THREAD

**Issue by Joebuckeye123** [home-assistant/home-assistant-polymer#5006]
custom: button-entity-row card
Reporting a new issue that occurred with update to 0.106.0. Checked my current Home Assistant to verify there would be no issues with an update to 0.106.0. This check was OK. Updated to 0.106.0 and restarted. I checked all of my Lovelace tabs and found the custom: button-entity-row card is no longer working. 
I've had this card working for more than 2 months. See attachments:
Please advise on any changes required. Thanks.

![custom button error](https://user-images.githubusercontent.com/49767800/75409192-00f4ff80-58e6-11ea-9fc9-047fed84b75b.png)

**Comment by iantrich** [comment]
We don't support custom cards. Issues should be raised on the card's repo
