### ISSUE TITLE
Climate component issue after updating to Lovelace

### ISSUE THREAD

**Issue by wangyt123ng** [home-assistant/home-assistant-polymer#5008]
Since HA using Lovelace as frontend, Climate component appears problem which is the component often doesn't get feedback from HVAC stat. But sometime after reboot, it will work for a while. The climate component is zhonghong. It used work when frontend is not Lovelace, it appears a common problem which I also found in Chinese HA forum.

**Comment by dshokouhi** [comment]
Hey there @wangyt123ng please do not delete the issue template.  All requested information is important to help out with this issue.  You can find the template again here: https://github.com/home-assistant/home-assistant-polymer/issues/new?labels=bug&template=BUG_REPORT.md

**Comment by wangyt123ng** [comment]
![微信图片_20200228184856](https://user-images.githubusercontent.com/47052753/75542542-fe67e680-5a5a-11ea-9a0a-7e03ff4e0446.png)
This is the screenshot of HVAC component while it's not working. When it's working it will display current temperature.
Also I can open the AC but couldn't turning it off when it's not working, and no log error reported.

**Comment by zsarnett** [comment]
Please create a new issue with the template filled out
