### ISSUE TITLE
broadlink SC1 devices stopped working on version 0.106.0

### ISSUE THREAD

**Issue by abouelric** [home-assistant/home-assistant-polymer#5011]
I have problems with my broadlink SC1 devices, after latest hassio upgrade to 0.106.0 all my broadlink switches are no longer working. did anyone encounter this issue? I have around 8 switches working normally before the upgrade.
any solution for this?
they are configure as sp2

**Comment by zsarnett** [comment]
Hey there @abouelric please do not delete the issue template. All requested information is important to help out with this issue. You can find the template again here: https://github.com/home-assistant/home-assistant-polymer/issues/new?labels=bug&template=BUG_REPORT.md
