### ISSUE TITLE
Sensor card improvements

### ISSUE THREAD

**Issue by sgttrs** [home-assistant/home-assistant-polymer#5017]
## The request

At the moment, the sensor card shows a beautiful chart. But looking at it you can only roughly understand how the values changed. I would like to see labels on the graph with minimum and maximum values, as implemented in mini-graph-card.

Example:
![example](https://user-images.githubusercontent.com/457678/52573150-cbd05900-2e19-11e9-9e01-740753169093.png)

**Comment by bramkragten** [comment]
Why don't you use `mini-graph-card` then?

**Comment by bramkragten** [comment]
We will not add all those features.
