### ISSUE TITLE
Move push notifications from sidebar to config

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#512]
The push notification configuration in the sidebar is from a time before the config panel was introduced. We should move it to the general config panel.

**Comment by mkyral** [comment]
I think it's already moved by commit https://github.com/home-assistant/home-assistant-polymer/commit/7303e55f631cec56bed434db3018124ed28d605b ;-)

**Comment by fanaticDavid** [comment]
Correct, it's been moved.

**Comment by balloob** [comment]
💃
