### ISSUE TITLE
timeline chart tooltip title is not readable in mobile

### ISSUE THREAD

**Issue by roidayan** [home-assistant/home-assistant-polymer#52]
the tooltip is style top -29px on my view and the title is hidden and can't scroll more to read it.

![screenshot_1](https://cloud.githubusercontent.com/assets/660126/14781331/850954c2-0aea-11e6-8c19-ee727b0d75fa.png)

A suggestion is changing the top of the tooltip to 0. the bottom part can be read with scrolling.
![screenshot_2](https://cloud.githubusercontent.com/assets/660126/14781343/9c1e62f6-0aea-11e6-8dbd-8af153527140.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/660126/14781347/a5526e08-0aea-11e6-9e79-fd497294ffb4.png)

**Comment by balloob** [comment]
The problem is that the tooltip is rendered by the chart api

**Comment by roidayan** [comment]
I understand but is a css override considered good approach for a fix here?
I used this:
```
state-history-chart-timeline
.google-visualization-tooltip {
    top: 0px !important;
}
```

**Comment by roidayan** [comment]
Seems fixed in latest version.
