### ISSUE TITLE
Icon usage for sensors of the "energy" class is confusing

### ISSUE THREAD

**Issue by echox** [home-assistant/home-assistant-polymer#550]
First of all: More of a minor minor issue, if theres another place for this, please point me to it :)

I'm using the binary_sensor with the custom device class "power": https://home-assistant.io/components/binary_sensor/

"Power off" uses a "everything ok" icon.
"Power On" uses a warning icon.
<img width="106" alt="screen shot 2017-11-02 at 17 32 16" src="https://user-images.githubusercontent.com/146484/32338007-d62137ac-bff3-11e7-8f55-049e1fa1d434.png">

While I can understand the viewpoint for this ("Danger! Electricity is on!") most of my use cases are "device is powered, everything is fine!".

If the state of "on" is dangerous, I would expect people to use the "safety" device class?

Or did I not understand the correct use of the classes? :)

**Comment by andrey-git** [comment]
The example the doc uses for `power` is over-current, so "on" is indeed danger.
You can propose a new category with a pair of on/off icons :)

**Comment by echox** [comment]
Thanks you!

Created a pull request for that.
If it gets accepted, I would add it also to the documentation of home-assistant.github.io via another pull-request.

Did I miss anything else? :)

**Comment by echox** [comment]
Thanks for your support during the whole pull-request/merge process 👍 
Everything is merged and I'm looking forward to the next update, so I'm closing this :)
