### ISSUE TITLE
Inconsistent capitalization in menu (0.57)

### ISSUE THREAD

**Issue by tleegaard** [home-assistant/home-assistant-polymer#557]
![screenshot](https://user-images.githubusercontent.com/5439041/32404626-599922b0-c153-11e7-888c-c4a60bb6b248.png)

**Comment by namadori** [comment]
I think you are seeing the unlocalized placemarks. What happens if you go to Configuration -> General and choose English language?

**Comment by marvinroger** [comment]
I also experience this. Indeed, it seems the new translations framework is not perfectly bulletproof yet.

If I go to the configuration panel, the language dropdown is not filled with any language. Selecting a language does solve this for the current session, but as soon as you reload the page, the issue comes back. (My language is french)

**Comment by arsaboo** [comment]
Try CTRL+F5 or CTRL+SHIFT+R to clear cache. I had the same problem, but clearing cache fixed it.

**Comment by marvinroger** [comment]
First thing I did, still the same issue!

**Comment by balloob** [comment]
This is a problem with your service worker not serving the latest frontend yet. These are indeed the placeholders. Try refreshing harder 😉

**Comment by marvinroger** [comment]
That’s what I was thinking, so I cleared everything and I cannot even type
the password anymore, I am stuck on “Connection lost. Reconnecting”. That’s
another issue, maybe I’ll fill an issue if I can reproduce on multiple
devices.

Anyway, the service worker should compare its hash against the latest hash
available to avoid that kind of issue. Isn’t there a system like this
embedded? Where the service worker would refresh itself after an update?

Le sam. 4 nov. 2017 à 20:14, Paulus Schoutsen <notifications@github.com> a
écrit :

**Comment by marvinroger** [comment]
https://github.com/home-assistant/home-assistant-polymer/pull/564

So I’ll be able to test and report as soon as the hot fix is pushed 😉

**Comment by tleegaard** [comment]
Ctrl+F5 did the job for me, thanks! :-) (Configuration -> General didn't show the language dropdown before that)

Still thinking the placeholders should be with similar capitalization though ;-)
