### ISSUE TITLE
Chinese Traditional: blurry font

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#560]
![blurry](https://user-images.githubusercontent.com/11984118/32405863-e639c7b4-c16d-11e7-84a0-cafedcf8ff82.PNG)

Simplified is OK

**Comment by balloob** [comment]
That seems like a computer/browser issue

**Comment by c727** [comment]
You are right. I thought the signs are also included in Roboto but it uses local fonts
