### ISSUE TITLE
Only admins can download translations from Lokalise

### ISSUE THREAD

**Issue by armills** [home-assistant/home-assistant-polymer#562]
We'll need to decide what our plan is for distributing translations, since we want to have the JSON exports be publicly available.

Options:
1. Check in to home-assistant-polymer repo
2. Distribute as a secondary PyPI project
3. Check in to a new git repo
4. Check in a read-only token for translation downloading.

My preference right now is 2. The immutability guarantees of PyPI are nice. It ensures that anyone can run old versions as they existed back then.

**Comment by bachya** [comment]
I'm running into this when trying to build the frontend (per the new instructions) – is there a way to bypass Lokalise entirely for the time being?

**Comment by balloob** [comment]
I wouldn't mind just going for 1. With 2 we have to make the main repo translation aware. It's also the easiest short term solution 👍

**Comment by armills** [comment]
WFM
