### ISSUE TITLE
Spanish Frontend Translation

### ISSUE THREAD

**Issue by SirMartin** [home-assistant/home-assistant-polymer#569]
Hi, I just installed today the home assistant in my Raspberry, and I am noted that is not in Spanish, but there are translations in a lot of languages, I added my self to the translations project in Lokalise, but I can´t see a Spanish project for translation, and I want to collaborate in that. How can I create that, I want to help in that, and I am pretty sure, that some more people are involved in the project, that can collaborate in the translation.

Thank you so much, for so amazing work.

**Comment by balloob** [comment]
I just added Spanish.
