### ISSUE TITLE
Open a hebrew translation in lokalise

### ISSUE THREAD

**Issue by ohadbenita** [home-assistant/home-assistant-polymer#577]
I want to start writing the Hebrew localization for hass, for that I need to have the Hebrew language in Lokalise, the language name as written natively is "עברית"

Thanks

**Comment by ohadbenita** [comment]
I want to start writing the Hebrew localization for hass, for that I need to have the Hebrew language in Lokalise

**Comment by c727** [comment]
Should be available now

**Comment by ohadbenita** [comment]
Thanks @c727, closing the issue
