### ISSUE TITLE
Language Request - Swiss German

### ISSUE THREAD

**Issue by schmidiij** [home-assistant/home-assistant-polymer#586]
English Name: Swiss German
Native Name: Schweizerdeutsch

**Comment by c727** [comment]
Please tell me your lokalise.co user name.

Whats the output of `javascript:alert(navigator.languages)` in your browsers address bar?

**Comment by schmidiij** [comment]
kevin.schmid@outlook.com
javascript:alert(navigator.languages) = de

inital for swiss German -> de-ch

**Comment by c727** [comment]
You can start translating. You will have to select `Schweizerdeutsch` in Home Assistant settings later because auto detecting will lead to `de`.

https://en.wikipedia.org/wiki/Swiss_German
> The dialects of Swiss German must not be confused with Swiss Standard German, the variety of Standard German used in Switzerland

**Comment by c727** [comment]
whats the better name?
Schwizerdütsch or Schwiizertüütsch?

**Comment by schmidiij** [comment]
haha :-) 
best name is "Schwiizerdütsch"
