### ISSUE TITLE
Translation to Serbian 

### ISSUE THREAD

**Issue by ilijakamenko** [home-assistant/home-assistant-polymer#588]
I would like to help to translate in my Serbian language. In Serbian language are used two alphabets cyrillic and latin. Please add new language in two variants:
Serbian latin
English Name: Serbian
Native Name: Srpski

Serbian cyrillic 
English Name: Serbian
Native Name: Српски

**Comment by c727** [comment]
Please tell me your loaklise.co user name.

Whats the output of `javascript:alert(navigator.languages)` in your browsers address bar?

**Comment by ilijakamenko** [comment]
My  loaklise.co user name is ilija@kamenko.rs
The output is sr,en,sr-RS

**Comment by c727** [comment]
You can start translating.
Is `српски језик` or `српски` the correct name?

**Comment by ilijakamenko** [comment]
српски means Serbian

језик means language

Both are correct.

2017-11-07 10:22 GMT+01:00 c727 <notifications@github.com>:
