### ISSUE TITLE
Wrong case on sensor units

### ISSUE THREAD

**Issue by arnoo** [home-assistant/home-assistant-polymer#59]
The first letter of measurement units for sensors seems to get transformed to uppercase at some point, I'm not sure where. The unit of measurement should be exactly as set in the component code.

For example, the code of the speedtest sensor correctly specifies the unit of measurement for ping in "ms" (miliseconds). The interface displays "Ms" (megaseconds).

**Comment by fabaff** [comment]
There is already an open [story](https://www.pivotaltracker.com/story/show/106537786) for this.

**Comment by arnoo** [comment]
Cool, thanks :)

**Comment by fabaff** [comment]
This doesn't mean that if anybody is working on it.

PR would be welcome.

**Comment by fabaff** [comment]
In the Home Assistant issue tracker: https://github.com/home-assistant/home-assistant/issues/938
