### ISSUE TITLE
en_GB Translation

### ISSUE THREAD

**Issue by phillprice** [home-assistant/home-assistant-polymer#593]
I ask because currently i'm getting some odd strings (logbook, history, config) and I believe it's because en_GB is not defaulting to en_US.

translation should be simple - happy to do it all.
<img width="267" alt="home_assistant" src="https://user-images.githubusercontent.com/320214/32515204-515b4ba4-c3f7-11e7-89fb-da9956be776c.png">

**Comment by c727** [comment]
This seems like a bug. @armills 

`en` is for GB / country of origin. I'll add `en-US` all in all

**Comment by armills** [comment]
No, our root translation is just `en`, which is the final failsafe which is always matched. No need to add new translations. Have you tried clearing your cache?

**Comment by phillprice** [comment]
Hmm a refresh is the right strings, still happy to make it the queen's english if there are any ize to ise etc, or aluminum to aluminium 😄 

Only string I can see at the moment through a quick flick around is Customization which should be Customisation :)

**Comment by armills** [comment]
We can include the region specific translations once we get to that point. 😄 For now though I don't believe there's anything included that warrants it.

Also, Andrey has been working on improving the service worker caching strategy, so hopefully we'll see fewer of these problems going forward.
