### ISSUE TITLE
Superfluous JavaScript text on Snapshot page

### ISSUE THREAD

**Issue by cstuder** [home-assistant/home-assistant-polymer#606]
![image](https://user-images.githubusercontent.com/288493/32595605-cebc004a-c530-11e7-82a9-db5b822bd6cd.png)

If I open the Hass.io-Snapshot page, there is JavaScript source code appearing as text on the page:

    function (){for(var e=arguments.length,t=Array(e),r=0;r<e;r++)t[r]=arguments[r];this._logger("error",t)}

(Wrapped in a `<p class="error">`-element>

Running Hass.io Supervisor 0.74 with Home Assistant 0.57.2. Text appears in Chrome 62 and Firefox 56.

Reported to Hass.io in issue [226](https://github.com/home-assistant/hassio/issues/226), but according to him it's a problem with Polymer.

**Comment by ciotlosm** [comment]
@cstuder I'm running 0.60.0 and I can't reproduce this. Can you check if it was fixed?

**Comment by cstuder** [comment]
Can no longer reproduce this in 0.60.0, looks like it's fixed.
