### ISSUE TITLE
Automatic login when api_password is enabled

### ISSUE THREAD

**Issue by xeor** [home-assistant/home-assistant-polymer#614]
I've been looking around, but I have not found a solution to do an auto-login, when api_password is enabled.

The api for home-assistant, works by using either the `X-HA-Access` header, or the `api_password` query-param. `home-assistant-polymer` wont accept any of these.

I want to expose some api's to 3rd party services like google assistant, while the rest of the interface is protected behind an oauth2 layer.

An easy way to handle setups like that is for `home-assistant-polymer` trigger a login when either of the two options is set.

Is this something any else wants? Is it being left out for a reason? Will a pr for something like this get accepted?

**Comment by balloob** [comment]
Wrong repo. Authentication is handled inside Home Assistant, not the frontend. Some ideas and work was done in https://github.com/home-assistant/home-assistant/pull/9980 but that didn't go anywhere.

**Comment by xeor** [comment]
Sorry, I didn't explain this good enough..

I know that it is the main `home-assistant` repo that takes care of authentication. But the problem is that there are currently no way to automatically authenticate using this web-interface, since there are no way to set `window.localStorage.authToken` without actually pressing the login button. I can only find 1 place that calls `window.createHassConnection(auth)` and thats https://github.com/home-assistant/home-assistant-polymer/blob/fb0b1286d297587e3d80b3ce304ece014338a9be/src/layouts/login-form.html#L155, which is only triggered from a users action (button).

What my question was, is a way to basically call `window.createHassConnection(auth)` based on a query-param or http-header. The goal being able to make the web-ui set authToken, so it acts as if it is logged in, without user actions.

I have tried injecting `x-ha-access` token on every request to the `api`. I also verified that the api sees it as an authenticated request. However, the web-ui won't act as if it is logged in, until you press the `login` button. 

I can make a PR on this, but was curios if a feature like this was left out for a reason..

**Comment by balloob** [comment]
Such functionality should be added here: https://github.com/home-assistant/home-assistant-polymer/blob/master/js/core.js#L25-L31

We used to have it but it got lost in a transition between web tech.

**Comment by xeor** [comment]
Thanks for the input!

I'm not sure what would be the best way to do this for the project. Can you give me some guidance for which one of these would be best for this project?

* Create a new app-route with something like `/authenticate/:token`, and then call `init(token)`
* Parse `?api_password=token`, just like the api from `window.location.href` (can't find an existing lib inside `home-assistant-polymer`, so this might just be an regex.
* Fix the problem @ https://github.com/home-assistant/home-assistant/blob/c8648fbfb824cfa3435d2092803f9c0042e46ef2/homeassistant/components/frontend/__init__.py#L484-L499 instead, proposing a way to for `no_auth` to not be set to `true`, even if `api_password` is set.

I think the latter one is the best for my own (and probably others) usecases, but the 2nd would be best in general..

**Comment by jerrychong25** [comment]
@xeor,

As of now, how do you implement Auto Login for HA frontend?

Is long live access token possible to achieve Auto Login?

Thanks.
