### ISSUE TITLE
paper-textarea in automations editor causing iOS Safari/WKWebView crashes

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-polymer#635]
I've had multiple reports from app users in recent days that they have been unable to edit automations on iOS, whether in Safari or an app that uses [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) (a app-safe Safari-like rendering engine which apps like the official HA iOS app and Chrome use as its the only permitted way to ship a browser in iOS). In Safari attempting to edit a automation causes a crash. In a WKWebView app it produces a white page. Upon investigation I found [this](https://github.com/PolymerElements/paper-input/issues/556) Polymer `paper-input` bug. It's due to the `paper-textarea` used on the automations edit screen.

I'm wondering if it's possible to use one of the mitigation methods in the `paper-input` issue. A second option would be replacing `paper-textarea` with something that doesn't crash. As a worst case fix, we could somehow warn users attempting to visit the automations editor of the crash likelihood if they are using Safari (WKWebView presents the same user agent as Safari).

This affects at least iOS 11 (don't have any iOS 10 devices left around). It does not affect Mac.

See also:

- https://github.com/PolymerElements/paper-input/issues/556
- https://github.com/hotforfeature/origami/issues/38
- https://bugs.webkit.org/show_bug.cgi?id=174629
- https://github.com/home-assistant/home-assistant-iOS/issues/67
- https://community.home-assistant.io/t/can-t-edit-automations-in-ios-app/32756

**Comment by balloob** [comment]
Starting with the next release there will be an option to load an untranspiled version of Home Assistant by navigating to `https://URL/?latest`, this will return the untranspiled version. This _might_ fix it. (you can already test it today in dev)

**Comment by robbiet480** [comment]
Just tested this with latest dev (so 0.58+) and crash is still happening (`NotSupportedError (DOM Exception 9): A newly constructed custom element must not have attributes`).

**Comment by balloob** [comment]
I have an idea what might fix it. We should move this to the ready callback https://github.com/home-assistant/home-assistant-polymer/blob/master/panels/config/automation/ha-automation-editor.html#L168-L172

Will open a PR
