### ISSUE TITLE
Background color gone on 0.58 for "General configuration"

### ISSUE THREAD

**Issue by ksya** [home-assistant/home-assistant-polymer#648]
I use a custom theme and since upgrading to 0.58 the background color is gone on the "Configuration and Server Control" page and script edit page.

The cause is I think the `<app-header-layout>` element that is not present here, which contains the background color.

**Comment by jumpalottahigh** [comment]
I have the same issue when using a custom theme. Here's a screenshot to illustrate the issue. Maybe worth mentioning that the correct background exists for other sub pages in Configuration.

![image](https://user-images.githubusercontent.com/4155121/32991504-8a5e5282-cd45-11e7-9d64-833601b6c7da.png)
