### ISSUE TITLE
Temperature widget is not high enough on mobile 

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant-polymer#65]
Version is 0.20.3

See screenshot 
![screenshot_20160606-192340](https://cloud.githubusercontent.com/assets/1193779/15831122/47bf4498-2c1c-11e6-810d-c63e687b8186.png)

**Comment by balloob** [comment]
Yeah, I'm aware. It's an issue with the scroller inside the paper-dialog
that is causing issues.

On Mon, Jun 6, 2016 at 10:25 AM, Michaël Arnauts <notifications@github.com>
wrote:

> Version is 0.20.3
>
> See screenshot
> [image: screenshot_20160606-192340]
> <https://cloud.githubusercontent.com/assets/1193779/15831122/47bf4498-2c1c-11e6-810d-c63e687b8186.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/home-assistant-polymer/issues/65>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABYJ2qZvrHzOHwO4vTmErvQK9Za33TzEks5qJFgjgaJpZM4IvH_w>
> .
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.

**Comment by balloob** [comment]
Fixed in latest release
