### ISSUE TITLE
Climate: hide "Currently: °C" in case the thermostat doesn't report the current temperature

### ISSUE THREAD

**Issue by tkintscher** [home-assistant/home-assistant-polymer#654]
Hi!

At the moment, the climate card displays the target temperature, followed by the currently measured temperature. There are however thermostats, which do not report the current temperature, such as the Danfoss 014G0013.
The `current_temperature` attribute is always `null` for those devices.
Hence the output is the target temperature, followed by "Currently: °C".

I think it would be best to hide or suppress the second line, in cases where the `current_temperature` attribute is not a number.

This issue was reported here a year ago:
https://github.com/home-assistant/home-assistant/issues/3947

**Comment by ladefoged81** [comment]
I agree. I have the Danfoss LC13.
And since I've upgraded to 0.61.1 theres a big fat text saying "**Unknown**".
That don't look very nice.

**Comment by ciotlosm** [comment]
The code is under `/src/components/ha-climate-state.html`. I think best solution is to add a new supported feature that is enabled by default and can be overwritten in the component that doesn't allow for `current_temperature`.

Another solution would be to use another entity to provide the temperature for that component.

**Comment by tkintscher** [comment]
Unfortunately I didn't have much time since the original pull request and meanwhile things have changed as you pointed out.

With the rewrite of the `ha-climate-state.html` card I didn't manage to fully adapt my originally proposed fix (i.e. when hiding the words "Unknown" and "Currently", how to align the current temperature vertically centered?).

Of course it would be nicer if the Z-wave climate component kept track of the availability of features of different devices. But that's a bigger change and requires someone with a deeper understanding of the inner workings of this component.

For rooms which have separate temperature sensors and thermostats, one could think about having something similar to the "generic thermostat" component to combine the different entities. But looking at the documentation, it seems that currently this component also implies a lot of features such as different heating/cooling modes.

**Comment by ladefoged81** [comment]
Screenshot:
![screenshot-home 386 dk 8123-2018-01-31-14-47-02](https://user-images.githubusercontent.com/26121019/35626345-be5e3b36-0695-11e8-991c-5df59eb76386.png)

**Comment by arsaboo** [comment]
In the meantime, you can always use template sensors so that your UI does not have those `unknown`.

**Comment by ardeus-ua** [comment]
There's a workaround for REMOTEC_ZXT_120 in climate/zwave.py
I guess it would be logical to add the workaround for Danfoss LC13 to have the ability to read the current temperature from the sensor already present in HA in case the sensor name is in configuration or just to rename the sensor according to the rule. For example: sensor.bedroom_heating_1 in case the device is configured to appear climate.bedroom_heating_1
