### ISSUE TITLE
Multiple misplacements of color wheel

### ISSUE THREAD

**Issue by perosb** [home-assistant/home-assistant-polymer#703]
Hass: 0.59
Browser: Version 62.0.3202.94 (Officiell version) (64 bitar)

The color wheel is misplaced.
This could be related to the javascript issue in https://github.com/home-assistant/home-assistant-polymer/issues/702

![screenshot from 2017-12-03 15-28-40](https://user-images.githubusercontent.com/982752/33526307-694ae3da-d83f-11e7-92ca-95775bee84ef.png)

![screenshot from 2017-12-03 15-17-51](https://user-images.githubusercontent.com/982752/33526303-42ed2dba-d83f-11e7-8f98-79c19631759c.png)

**Comment by balloob** [comment]
CC @NovapaX

**Comment by NovapaX** [comment]
found the issue, it's a css overflow thing. never noticed it because it always was the last element in my views and the surrounding container does hide the overflow.
Fix incoming.
