### ISSUE TITLE
Prevent state graph reloading while color is choosen

### ISSUE THREAD

**Issue by janLo** [home-assistant/home-assistant-polymer#710]
If I click on the new color-wheel and move the mouse, there are constantly new colors sent to the Homeassistant. So far, so good. The problem is, that the reload of the state graph above the wheel reloads on very change. This makes the wheel moving up and down as the space used for the "loading wheel" for the graph is not the same as the graph itself. 

This makes the whole thing very flickery.

I suggest to not update the graph as long as the mous is clicked and on the wheel.

**Comment by balloob** [comment]
It's weird it's trying to redraw the graph as we have a 1 minute caching strategy https://github.com/home-assistant/home-assistant-polymer/blob/master/src/data/ha-state-history-data.html#L288-L309

**Comment by NovapaX** [comment]
I have experienced this issue also (before) but not anymore. (I can tell, as it was really annoying)
As far as I can see (and test) we do not redraw the graph anymore with every state change. And while redrawing it should not flicker/trigger the loading message.
I've just tested this to be sure on my (rather slow) hass.io box and it did not cause any issue anymore.
