### ISSUE TITLE
Weather Card Causes frontend in Firefox 56 and 57 to hang

### ISSUE THREAD

**Issue by Cadair** [home-assistant/home-assistant-polymer#713]
My homeassistant `/states` page with the weather card on has been unusable on firefox for a number of weeks, the page would be unresponsive and then I would get a yellow bar with "A page is causing your browser to slow down would you like to kill it". This has been happening with 0.57.x and 0.58.x. (with the latest frontend and without)

The problem appears to be in a call to the google visualisation service, I managed to get the following out of the firefox dev tools: 
![screenshot from 2017-12-05 10-00-20](https://user-images.githubusercontent.com/1391051/33601097-207ba436-d9a3-11e7-90db-9b5a58f7b8e7.png)

I have no experience debugging frontend issues, but I would be happy to follow instructions to help you pin this down. For now removing the weather panel fixes the issue, and the rest of the frontend works fine.

**Comment by andrey-git** [comment]
Could you post the config of the weather card you have? (without api keys)

**Comment by Cadair** [comment]
```yaml
weather:
  - platform: openweathermap
    api_key: ...
    latitude: ...
    longitude: ...
```

**Comment by balloob** [comment]
Are we rendering a graph? If so, I wonder how many data points it's loading.

**Comment by Cadair** [comment]
Yeah, there is a temperature graph on the card.

**Comment by NovapaX** [comment]
Is this still an issue

**Comment by Cadair** [comment]
No this is now fixed. (I assume it was the change in graphing lib). Thanks!
