### ISSUE TITLE
Mobile version: First row of first group covered by Title on first load @stock browser 

### ISSUE THREAD

**Issue by ferdydek** [home-assistant/home-assistant-polymer#720]
When using stock browser (samsung Interent app)  the first row of first group on any view is covered by the title.

![image](https://user-images.githubusercontent.com/5775168/33805070-2a45a8d0-ddaa-11e7-94ea-efa50a50dbf9.png)
![image](https://user-images.githubusercontent.com/5775168/33805077-44df9fca-ddaa-11e7-8c58-03dccc1627d9.png)

Switching views or refreshing does not change this, but opening i.e. logbook and then going back to overview solves the issue.

![image](https://user-images.githubusercontent.com/5775168/33805078-4fc89d10-ddaa-11e7-897f-f00de2f1e5e4.png)

My current version is 0.59.2

**Comment by cgarwood** [comment]
@ferdydek Do you still experience this issue on the latest HA build?

**Comment by cgarwood** [comment]
There was a fix for the header overlapping put in a couple weeks ago. If you still experience problems, please open a new issue. Thanks!
