### ISSUE TITLE
HTML5 push notifications behind secured home assistant

### ISSUE THREAD

**Issue by sweco-secfha** [home-assistant/home-assistant-polymer#729]
Hello!

I have my home assistant secured behind nginx with oauth2 authentication (home assistant builtin auth turned off) and everything is working except subscribing to push notifications. If I look at the request in chrome developer console I can see that the request to manifest.json ends up at my login page.

After some searching I found out that I have to change how the manifest is linked like this `<link rel="manifest" href="/manifest.json" crossOrigin="use-credentials">` to successfully subscribe. That or temporarily disabling my authentication, this is not a permanent fix though... only until I restart home assistant.

Have anyone else stumbled upon this?
Does my "fix" have any side effects?
Would it be possible to commit this to the repository? Maybe configurable?

**Comment by c727** [comment]
Use this https://serverfault.com/questions/477103/how-do-i-verify-site-ownership-on-google-webmaster-tools-through-nginx-conf

**Comment by sweco-secfha** [comment]
@c727 Thanks for trying to help me, unfortunately I don't see how the info in your link would help me. Can you elaborate?
I did try it though, without success.

**Comment by c727** [comment]
Hups I thought you have problems with domain verfication

**Comment by sweco-secfha** [comment]
I ended up just excluding manifest.json from the authentication for now.

**Comment by andriej** [comment]
@sweco-secfha is there any chance you can share your nginx config and oauth2 config without credentials?

**Comment by sweco-secfha** [comment]
@andriej There is really not much to share. I basically set up and followed the examples for the oauth2_proxy.
https://github.com/bitly/oauth2_proxy
