### ISSUE TITLE
Question about Math.pow and ** operator

### ISSUE THREAD

**Issue by fanthos** [home-assistant/home-assistant-polymer#764]
I am trying to use `Math.pow` or `**`, eslint does allow using `Math.pow` and uglify.js refuse to build es5 when using `**`. Should we use `transform-exponentiation-operator` in babel or allow usage of `Math.pow` in eslint, or there is better way to fix this?

**Comment by balloob** [comment]
Please use Math.pow and disable the ESLint rule

**Comment by balloob** [comment]
Example how to disable an ESLint rule: https://github.com/home-assistant/home-assistant-polymer/blob/master/.eslintrc-hound.json#L39
