### ISSUE TITLE
Feature Request: Floorplan view

### ISSUE THREAD

**Issue by torwag** [home-assistant/home-assistant-polymer#77]
Hi,
instead of the current page wise location of different units, I am wondering if it would be possible to have a "floorplan" view. 
That is an image in the background and as an overlay, users can determine location, font formats on top for different units (Actors, Sensors ,etc.). I find this much more intuitive rather then reading columns or rows of node-names to look for the right one. 
E.g. a red or green dot on a floor plan close to a window could indicate the window is open or closed. It would take a second to check whether all windows are closed.
Some text e.g. in the center of the room could indicate the room temperature and humidity.
Colour changes of the rooms floor (redrawn by an overlaid polygone) could indicate the presence of a person.
Thus, what would be needed is the ability to select an image as floorplan and a small set of indicators (circles, rectangles, polygons, text, bar) which could be changed by various parameters (colours, transparency, size, text colour, etc.).
Maybe SVG is a good start. It can be programmatically modified.

**Comment by balloob** [comment]
Please use [our forums](https://community.home-assistant.io/c/feature-requests) for feature requests
