### ISSUE TITLE
Input Select not wokring on ios

### ISSUE THREAD

**Issue by deluxestyle** [home-assistant/home-assistant-polymer#775]
Home Assistant release (hass --version):
0.60

Python release (python3 --version):
Python 3.5.3

Description of problem:
Input Select does not work properly on ios Browsers
I cannot select all items of an input select field. it does not show all values (see screenshot)

There are five entries in the select box but on ios I can only see three. It works on Windows but not on ios

![34460412-5be9be58-ee0d-11e7-9c4a-e37402d6af55](https://user-images.githubusercontent.com/662779/34462041-05197f72-ee3b-11e7-850d-11880cb29552.PNG)

**Comment by balloob** [comment]
did you try dragging the options, iOS hides the scrollbar by default

**Comment by deluxestyle** [comment]
yes I tried.
I found out now, that the input list of the homematic components has the issue
if I create an own intput list, then I can scroll

**Comment by ciotlosm** [comment]
Seems to be duplicate with https://github.com/home-assistant/home-assistant/issues/1043

**Comment by deluxestyle** [comment]
Issue seems to be fixed with version 0.63

**Comment by TH1x11** [comment]
Still an issue with version 0.66 when using iOS app. 

Heating Card - iOS app - 'operation' - can only select the first two items - 'auto' and 'heat'. Cannot select 'off'. On Chrome on MacOS can select all three.

**Comment by NovapaX** [comment]
Can you provide a screenshot of that card with the operation menu opened?

**Comment by TH1x11** [comment]
See attached. 

![file 03-04-2018 8 57 19 am](https://user-images.githubusercontent.com/38029358/38236828-47878ad6-371d-11e8-8a63-e58694132ec3.jpeg)

**Comment by NovapaX** [comment]
Is this on the latest version? v0.66.1
If not, please upgrade and click the refresh button.

**Comment by TH1x11** [comment]
It wasn’t but I’ve now updated to 0.66.1. Issue still there. 

On 3 Apr 2018, at 9:09 am, NovapaX <notifications@github.com> wrote:

Is this on the latest version? v0.66.1
If not, please upgrade and click the refresh button.

**Comment by NovapaX** [comment]
see #1064 for the same issue.
I have a fix for this ready.

**Comment by TH1x11** [comment]
Amazing! Thanks. 


On 3 Apr 2018, at 8:15 pm, NovapaX <notifications@github.com> wrote:

see #1064 for the same issue.
I have a fix for this ready.
