### ISSUE TITLE
Improve UI for input_datetime

### ISSUE THREAD

**Issue by baflo** [home-assistant/home-assistant-polymer#785]
The UI for input_datetime - at least for the time input - is very basic. Especially on mobile devices the experience is not very well. It doesn't even handle jumping from the "hours" field to the "minutes" field when two digits were entered.

Using HTML5 input elements like `<input type="time"/>` would allow the app to use the OS's time input methods, which should be much more elegant.

Alternatively, I found this project: https://www.webcomponents.org/element/fooloomanzoo/datetime-picker

**Comment by raccettura** [comment]
Might be a wider discussion but can there be perhaps a flag to decide when to polyfill vs use native OS input methods?

The reason I mention this is OS input methods don't work as well in all use cases, for example one that always annoys me is passcode for alarm in android pops up the full screen keyboard... hard to use with a wall mounted tablet. An option to reduce that to a polyfilled numeric input would be much more suited.  For wall mount, I think in general the polymer based inputs are actually pretty nice with touch devices.

**Comment by baflo** [comment]
That flag you describe, would you add it as a configuration item? Or how was the flag be set?

**Comment by codeclinic** [comment]
Any progress being made on this?
