### ISSUE TITLE
Custom UI Mobile problem

### ISSUE THREAD

**Issue by JulianMined** [home-assistant/home-assistant-polymer#803]
Hello,
i created a custom state card*, which is working really good.
If i try to open the interface in my mobile browser (Firefox, Chrome, ...), it does not show my custom card.

The desktop browser included the card "<link rel="import" href="/local/custom_ui/state-card-my-custom-remote.html" async>"
In the mobile browser i cannot found this import.

*https://home-assistant.io/developers/frontend_creating_custom_ui/

**Comment by andrey-git** [comment]
Please ask on devs_frontend channel on Discord: https://discordapp.com/channels/330944238910963714/351047592588869643
