### ISSUE TITLE
Tabs on Overview not appearing, no scroll on "dev-state" on Firefox Nightly

### ISSUE THREAD

**Issue by nettosama** [home-assistant/home-assistant-polymer#804]
home-assistant-frontend (20171216.0)
homeassistant (0.60.1)

Tabs on Overview not appearing, no scroll on "dev-state" on Firefox Nightly since around Jan 10 (59.0a1 2018-01-14). In comparison, they work on Chrome.

![34944758-94207aae-f9df-11e7-88aa-d952c12fc85b](https://user-images.githubusercontent.com/8485873/34960968-e53011de-fa1b-11e7-96a9-5811a81c0dc3.png)

**Comment by andrey-git** [comment]
Any JS errors in FF dev console?

**Comment by nettosama** [comment]
just checked, no errors, just a couple of css declarations dropped.

**Comment by balloob** [comment]
Do you have native custom elements enabled? (The `dom.webcomponents.customelements.enabled` pref)

**Comment by nettosama** [comment]
I don't think so, it's mostly an standard installation.

I just checked the styles and computed values of the elements, and the div with class "style-scope partial-cards" seems to have the hidden attribute set for some reason.

Also, I compared Firefox Nightly 59.0a1 (2017-11-23), that works, with (2018-01-15) that doesn't.

```html
<div sticky="" class="style-scope partial-cards" style="transform: translate3d(0px, 0px, 0px);" hidden=""></div>
```

**Comment by nettosama** [comment]
Update: On version 59.0a1 (2018-01-18), it is working correctly again, so it was probably something broken on Nightly, as expected.

Closing.
