### ISSUE TITLE
Graph size does not scale

### ISSUE THREAD

**Issue by Redferne** [home-assistant/home-assistant-polymer#806]
Would it be possible to automatically scale the graph, or configure the rendered size?
I mean, looking at the screenshot, the graph is the size of a stamp :eyeglasses: 
![small_stuff](https://user-images.githubusercontent.com/2379821/34975501-613324da-fa92-11e7-936b-027e6b977dda.png)

**Comment by andrey-git** [comment]
While a lone graph would look better taking most of the screen, many more-info windows include additional data that would look bad if the popup was large.

**Comment by covrig** [comment]
@andrey-git Can't we have an exception for graphs? At least double the size or something.

**Comment by fti7** [comment]
+1 The Graphs are useless if you want more than just a "quick look".
What be nice to be able to resize that window.
Additional Features:
* Snap the Graph to the Buttom (Some kind of split screen), so its full-width
* Add Buttons with preselected Time-Ranges

**Comment by andrey-git** [comment]
If the graph is the main interest you can add a history_graph entity.
That said I think it makes sense to add a button to expand the small graph to full screen
