### ISSUE TITLE
Add interface for controlling loggers

### ISSUE THREAD

**Issue by rytilahti** [home-assistant/home-assistant-polymer#822]
If and when https://github.com/home-assistant/home-assistant/pull/11839 gets merged, it would be nice to have a user-interface for controlling the loggers (both per logger name as well as per entity). This can be useful for both developers (easy access for changing the settings without restarting homeassistant) and for users (it's easier to instruct to click a button and paste the log afterwards).

**Comment by c727** [comment]
Main PR closed
