### ISSUE TITLE
cache somtimes not updating for custom state cards

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#823]
sometimes you need Chrome -> devtools -> network -> disable cache -> CTRL+F5 to get updated cards

on Chrome mobile this is a bit more complicated: you have to install ADB to run the dev tools

**Comment by balloob** [comment]
On Chrome mobile: settings -> Privacy -> Clear browsing data

**Comment by balloob** [comment]
This is btw by design… UI pieces should be cached. If not, the fingerprint should change so the new version is loaded.

**Comment by c727** [comment]
Thanks, this works. I will tell users to clear cache after each update :+1:
