### ISSUE TITLE
input_datetime time format doesn't match everything else

### ISSUE THREAD

**Issue by ve6rah** [home-assistant/home-assistant-polymer#832]
When I look through the UI for Home Assistant pretty much everything is showing for me in 24 hour format. Except the frontend display for my input_datetime settings which show in 12 hour format.

Interestingly enough, you have to enter them in 24 hour format (as there's no am/pm selector) however it then displays it as 12 hour.

For consistency this should use the same time format as the rest of the interface (in my case 24 hour time), and more importantly, the entry box should use the same format as the display format.

![screenshot at 2018-01-24 14-57-41](https://user-images.githubusercontent.com/16531454/35359343-f59bf2fc-0116-11e8-95b4-6ef7a1da9e55.png)
In this screenshot you can see the current setting (upper right) showing 12 hour format (7:00 PM), the history graph showing 24 hour format along the bottom (but 12 hour format within) and the entry box at the bottom left using 24 hour format with no option for AM/PM.

**Comment by flavio20002** [comment]
I would like to note that also the edit text has a non consistent format. The minute is always zero padded, while the hour prior to 12, are not zero padded. This screenshot was obtained after a page refresh. After the edit, also the hour is zero padded for a while.

<img width="363" alt="schermata 2018-04-10 alle 22 47 40" src="https://user-images.githubusercontent.com/10809301/38583887-c9a243ec-3d14-11e8-880e-d98feb5aa61e.png">
