### ISSUE TITLE
more info state history flashes then displays "No state history found."

### ISSUE THREAD

**Issue by posttwo** [home-assistant/home-assistant-polymer#843]
State history in the more info dialog loads then turns into "No state history found"

Video of it happening with a breakpoint set on _computeIsEmpty https://gfycat.com/ImperfectCleanHind

**Comment by andrey-git** [comment]
Which HA version is that?

**Comment by posttwo** [comment]
0.62.0
It didn't happen on 0.61.1

**Comment by bachoo786** [comment]
Same issue here no state history found HA 0.62

**Comment by f0nt4** [comment]
Saw somewhere that this was fixed in 0.62.1.
