### ISSUE TITLE
Chrome + uBlock origin + new hassio panel = broken

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#848]
problem is that you have to disable the add-on in add-on **store** (whitelisting does not work)

```
hassio-app.html:1 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new o (hassio-app.html:1)
```

**Comment by balloob** [comment]
Why would ublock block the polyfill from loading? That makes no sense. It's the same polyfill as we use for the main app.

Look at the network tab and you can see what requests are getting blocked.

Just like with LastPass, an annoying issue but is an issue with uBlock.

**Comment by c727** [comment]
![on](https://user-images.githubusercontent.com/11984118/35491637-ff2f34d4-04a7-11e8-9a64-9998747c5d53.PNG)
![off](https://user-images.githubusercontent.com/11984118/35491638-ff45224e-04a7-11e8-9cd4-cedd2af85f3c.PNG)

**Comment by balloob** [comment]
es5 adapter being loaded too late is what causes the error

**Comment by c727** [comment]
```
frontend:
  javascript_version: es5
```
seems to fix it, it does always send the `es5` hassio panel instead of `latest`

**Comment by balloob** [comment]
Hass.io is fixed to ES5 and runs in an iFrame, isolated from the main frontend. So that shouldn't matter.

**Comment by c727** [comment]
this seems to be fixed with the "new" panel :rabbit:
