### ISSUE TITLE
Rendering Grayed out in Older iOS version ( 9.3.5 on iPad)

### ISSUE THREAD

**Issue by matthieut59** [home-assistant/home-assistant-polymer#851]
Hello,

I m reopening case https://github.com/home-assistant/home-assistant-polymer/issues/780
because it was closed by mistake, the issue is still not fixed on ios 9, using
`frontend: 
  javascript_version: es5`

Is not changing anything :/

Can someone have a look at it ? a lot of users are using Ipad2 wall mounted, that are now useless :/

Thanks in advance guys,

Matt

**Comment by c727** [comment]
Any browser error logs?

**Comment by NovapaX** [comment]
This is being worked on in this PR: https://github.com/home-assistant/home-assistant-polymer/pull/901

**Comment by NovapaX** [comment]
This is fixed with: #901
