### ISSUE TITLE
Problem with decimal comma

### ISSUE THREAD

**Issue by FrenkK** [home-assistant/home-assistant-polymer#86]
Home assistant: 0.25.2
Python: 3.5.2
Browser: Chrome
Platform: Windows 10 x64

I'm using MQTT (Mosquitto) and am sending the temperature data to the broker as text (number only) with decimal commas instead of full-stops (decimal full-stops are incorrect in my country). When I configure sensors (MQTT sensor) to display the temperature, I get correct display with the icon, but the trend graph is rounded up to integer values. Please look at the pictures for more clarity. If the numbers are written with decimal full-stops, everything works correctly.
![untitled-1](https://cloud.githubusercontent.com/assets/10543626/17526060/eac37d0a-5e65-11e6-8064-87fba2ff80cc.png)
![untitled-2](https://cloud.githubusercontent.com/assets/10543626/17526061/eaca0832-5e65-11e6-9f54-1244596faa60.png)
I just wanted to add that this is an awesome project, thank you, you rule!

**Comment by justweb1** [comment]
@FrenkK  Make sure you have this setting in your configuration.yaml
```
homeassistant:
  unit_system: imperial
```

**Comment by justweb1** [comment]
@FrenkK Are you still having issues with this?

**Comment by FrenkK** [comment]
I rewrote my home automation system to just use US units (it should be the most accessible solution for everyone) and can't answer that question anymore. Still, it would be advantageous if the system recognized that there are different ways of writing numbers, mainly because of all the closed-source systems out there.

**Comment by balloob** [comment]
Right now we don't do any internationalization in the UI and thus we get these discrepancies. 

Internally we should always write numbers with decimal full stops because that's how both Python and JSON represent them (and thus this issue can be closed)
