### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by antgwms** [home-assistant/home-assistant-polymer#871]

**Comment by antgwms** [comment]
I'd like to develop home-assistant in the Welsh language as part of my MSc Smart Home Project.  Thanks

English Name: Welsh
Native Name: Cymraeg

**Comment by c727** [comment]
Whats your usename at lokalise.co?

**Comment by antgwms** [comment]
antgwms

**Comment by c727** [comment]
this user does not exist. read here to get started: https://home-assistant.io/developers/frontend_translation/

**Comment by antgwms** [comment]
Apologies, thanks I'm now contributing to the translation.
