### ISSUE TITLE
Customize configurator available states

### ISSUE THREAD

**Issue by wmalgadey** [home-assistant/home-assistant-polymer#876]
Is it possible to manually add new states to the customizer?

I think we have to manipulate the LOGIC_STATE_ATTRIBUTES

I want to add the homebridge_visible attribute to the list of available states/attributes in the customizer.

**Comment by MartinHjelmare** [comment]
Please describe more thoroughly what you want to do, perhaps with screen shots if it's something in the GUI.

Also fill in the issue template that you deleted when you opened the issue, with eg version info etc.

**Comment by wmalgadey** [comment]
NP, I want to add new entries to the selection list in here:
![image](https://user-images.githubusercontent.com/141838/35978295-9b40f890-0ce5-11e8-8ff9-a19f5b24aa3c.png)

This selection list is part of the customizer or config functionality:
![image](https://user-images.githubusercontent.com/141838/35978328-b1966008-0ce5-11e8-8df9-c5c9678bd8ec.png)

Because I changed the default homebridge functionality to always hide every sensor in homebridge/homekit I now want to add the `homebdridge_visible` attribute to the selection list.

I know, that I have to change `LOGIC_STATE_ATTRIBUTES` in here https://github.com/home-assistant/home-assistant-polymer/blob/4379df0d5c7c80944b3c2439b2c09ed91611de06/src/util/hass-attributes-util.html#L49, but how can I do this without modifying the polymer sources?

**Comment by MartinHjelmare** [comment]
If you select Other in the drop down box you can set any attribute you want I think.

I don't think you can add default attributes to the list without changing the source.

**Comment by balloob** [comment]
We're not going to make this configurable. Config options limit our flexibility. Your use case is not convincing since you use a homebridge fork.
