### ISSUE TITLE
Slider not working with Orfox on Android

### ISSUE THREAD

**Issue by flowolf** [home-assistant/home-assistant-polymer#884]
I'm having issues with the UI on Orfox on my Android phone (don't know about any other mobile platform, works with Tor Browser on Linux)

When using the HA-UI with Orfox I'm not able to use sliders. The indicator for the position is highlighted with it's blue shade, but does not move.

Another problem that might be related is that I'm also not able to slide between views (aka tabs) in the HA-UI.

I'm using Orfox (Fennec-52.2.0esr/TorBrowser-7.0-1/Orfox-1.4-RC-3, base is Firefox 52.2.0) on Android 8.0.0

Reproduce:
Install Orbot and Orfox, run a hidden service for HA, start Orbot, connect to address of your HA hidden service with Orfox. Try to move a slider.

**Comment by c727** [comment]
Any JavaScript errors?

**Comment by flowolf** [comment]
how can I get a JS console on Orfox? or a log? NoScript is disabled.

**Comment by c727** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging

Not tested as I'm using chrome

**Comment by flowolf** [comment]
tried to set that up. no success so far... will try later again.

**Comment by andrey-git** [comment]
Unless all JS is broken - JS errors are supposed to propagate to the backend

**Comment by andrey-git** [comment]
Testing this requires open-to-internet HA instance. I don't have one :(

**Comment by andrey-git** [comment]
@Flowolf does it work correctly on FF for you?

**Comment by flowolf** [comment]
yes. normal FF on Android works. but that's a more recent version (58.0.1).

**Comment by c727** [comment]
can you test javascript_version: es5, please?
https://home-assistant.io/components/frontend/#javascript_version

**Comment by flowolf** [comment]
Neither works. Tried auto, es5 and latest.

**Comment by flowolf** [comment]
Neither works. Tried auto, es5 and latest.

**Comment by flowolf** [comment]
The navigation between views seems to work now. Don't know why. Sliders still not working.

**Comment by flowolf** [comment]
Also the view scrolling doesn't work either. Just selecting the available views works. With any of the js versions.

**Comment by flowolf** [comment]
succeeded in remote debugging. There is nothing that indicates an error.

**Comment by flowolf** [comment]
yes. Orfox still has issues. I'm not using it anymore, because of that.

It's very slow, graphics won't load etc. That should not be solely because of the network delay.
Orfox asks for action for an unresponsive Script. I tried v52.9.0.

Firefox 62.0.2 works fine.
Kiwi Browser 69.0.3440.40 works fine as well.
Chrome as well - obviously.

I guess the version of Firefox used as base for Orfox is just too old.

**Comment by cgarwood** [comment]
According to the Orfox site:
> Orfox will be sunsetted by early 2019 when the stable Tor Browser for Android comes out.

At this point I don't believe it would be worth the effort to troubleshoot and fix since they're discontinuing the browser in a few months.
