### ISSUE TITLE
Shopping list complete sends incorrect payload

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/home-assistant-polymer#885]
See home-assistant/home-assistant#12339. When marking a shopping list item as complete, we would **expect** `{"complete": true}` to be sent to the `/api/shopping_list/item` endpoint. However, `{"complete": false}` is sent - thus marking the shopping list item as not complete.

Creating an issue here as I haven't done web development for quite a while and I hope someone with more knowledge will check it out.

<img width="400" alt="screen shot 2018-02-12 at 19 37 24" src="https://user-images.githubusercontent.com/6833237/36113200-57568b0a-102c-11e8-9a5d-dbf7e765b5a9.png">
<img width="403" alt="screen shot 2018-02-12 at 19 37 30" src="https://user-images.githubusercontent.com/6833237/36113204-5a03eb40-102c-11e8-8403-fcec62194aeb.png">

**Comment by OttoWinter** [comment]
This line is probably the culprit:

https://github.com/home-assistant/home-assistant-polymer/blob/e2ff04e40b0a6ed56d744bba332442d359fd0e81/panels/shopping-list/ha-panel-shopping-list.html#L180

Hope it helps!

**Comment by c727** [comment]
you don't want to submit the PR? :smile:

**Comment by OttoWinter** [comment]
I have any development environment set up to test this 😬.

And ... I have no idea whether that's actually the issue here (I guess `item.complete` was negated somewhere else previously and now isn't anymore).

**Comment by OttoWinter** [comment]
(And I really should be working on my (pre-scientific) paper... due date is friday and I'm constantly distracting myself somehow 😄)
