### ISSUE TITLE
Unavailable light shows brightness slider

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/home-assistant-polymer#899]
A light that is `unavailable` shows its more-info card with a brightness slider.

<img width="378" alt="screen shot 2018-02-17 at 21 24 50" src="https://user-images.githubusercontent.com/6833237/36345408-f4ea6782-1429-11e8-9324-06443fa7bed0.png">

**Expected:** Brightness slider is not visible when the light is unavailable.

**How to reproduce:** Working on that, template light doesn't allow the `unavailable` state... 😟 (But if you want to reproduce this, you could use mqtt - that's also how I noticed the issue)

This is probably because we want the brightness slider to be shown when the light is `off`. The following lines would in that case probably be the culprit (+ the if `newVal.state === 'on'`)

https://github.com/home-assistant/home-assistant-polymer/blob/f0f1a565374c69cdbd967609a350afac15fe53c5/src/more-infos/more-info-light.html#L175-L177

Again, I don't know how to develop for the frontend, but the fix should probably be relatively simple. And I can't think of any other component where the same could happen.

**Comment by NovapaX** [comment]
How soon does a light become 'available'
I have some bulbs that I sometimes turn off with the old fashioned power switch, then they become unavailable. When I turn the switch back on the light goes to full brightness... how long will it take for the UI to show the brightness slider so I can turn it down?
We could add a 'refresh' button to let the platform check if it's still unavailable... but this works too ;)
(I'll try to do some behaviour tests tonight with my tradfri bulbs)

**Comment by OttoWinter** [comment]
> How soon does a light become 'available' again?

I don't completely understand the question, but I think it depends a lot on the platform. For example with MQTT, the `available` property is controlled through a subscription to an MQTT, which in the end makes availability reporting pretty much instant for that platform.

> We could add a 'refresh' button to let the platform check if it's still unavailable...

I don't think we should expose a refresh button to users. IMHO the correct thing to do would be to have to back end periodically check the availability for you (and adjust the interval as needed).

**Comment by NovapaX** [comment]
I know we should not.
But I don't want to wait for example a minute before a light to become available again to control it.

I would not expect a platform to poll/connect to unavailable lights every couple of seconds to see if they are available again. But I would expect it to try a connection to the light when I set the brightness (or any service call on that entity)
