### ISSUE TITLE
Chrome Mobile Overflow Issue

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/home-assistant-polymer#902]
## Description:

On the latest dev build of Home Assistant, when using Chrome Mobile and the navigation bar is hidden, there's a white bar at the bottom of the page. Not sure if this is correct, but I believe from my little html/css experience it's something related to `overflow: hidden`. This doesn't happen on my 0.63.2 build, only on the staging build. See screenshot:

<img width="732" alt="screen shot 2018-02-19 at 10 48 41" src="https://user-images.githubusercontent.com/6833237/36371667-1eff485a-1563-11e8-881f-53acb3c8d1d5.png">

I have not been able to replicate this with Chrome for Desktop (using the phone screen size emulator).

Chrome Version: Chrome 64.0.3282.137 on Android 8.1.0

**Comment by balloob** [comment]
Hmm, I did update the bower packages locally. Bower doesn't have a lock file so don't know which it was or if that caused it 🤔 

Just add it to your desktop and the address bar will never hide 😉

**Comment by OttoWinter** [comment]
Yeah, that was also what I did 😀 (Just noticed this will setting up my new staging server and thought that it might be good to report.)

Anyway, do I understand correctly that this is due to some external dependency and that it's fixed with a manual update? Should I then close the issue?

I can also try to write up a way to replicate this using docker.

**Comment by balloob** [comment]
The problem is that bower dependencies are not installed the same on everyone's machine. For NPM dependencies we use Yarn which leverages a lock file to prevent this.

The good news is that with Polymer 3, Bower will be retired.
