### ISSUE TITLE
Unable to view Attributes column when in Mobile view on States tab in Chrome

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-polymer#904]
Using Chrome Mobile stable channel on Android 8.1 when I am on the States tab in mobile view I cannot scroll over to the Attributes column at all, even if I rotate my phone.  The only way I can see that column is when I enable Desktop View but that makes it hard to read as the font size in the Attributes section is larger than the rest of the columns. 

Desktop view:
![screenshot_20180219-170544](https://user-images.githubusercontent.com/1634145/36403117-b516b3c6-1597-11e8-9eec-985c64b40629.png)

Mobile view:
![screenshot_20180219-170518](https://user-images.githubusercontent.com/1634145/36403118-b764e3b4-1597-11e8-91f8-e09bdbdfcaa4.png)

**Comment by balloob** [comment]
That's on purpose. On mobile (or narrow screens in general), there is not enough space for them.

**Comment by SgtBatten** [comment]
@balloob any chance of revisiting this? I do so much on my phone and it would be great to at least have the option.

**Comment by matthiasdebaat** [comment]
We could make it a responsive table, that flips it to a list view. But that still isn't a great experience with a lot of devices.
