### ISSUE TITLE
Snapshots missing method to reload, new snapshot dates appear as "NaN"

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-polymer#917]
New snapshots are created fine (and don't take forever!).
The snapshot list will only show older snapshots that have been copied over after a reboot of the host, as there is no longer a refresh button.

The new snapshots display "in NaN weeks". The older snapshots seem to display their ages properly.
![image](https://user-images.githubusercontent.com/2456810/36609196-4a0d1814-1889-11e8-83b1-974a5d64e992.png)

**Comment by ciotlosm** [comment]
This has been fixed in a recent PR https://github.com/home-assistant/home-assistant-polymer/pull/915
