### ISSUE TITLE
Uncaught TypeError: window.google.visualization.Timeline is not a constructor

### ISSUE THREAD

**Issue by f0nt4** [home-assistant/home-assistant-polymer#919]
Not sure if this is a frontend or backend thing, but here goes.
After pressing the History menu item, it starts loading and after a while it gives a message "System Writer/log called".
The page remains blank at this point.
Viewing the log show the following error:
```
2018-02-19 17:20:59 ERROR (MainThread) [frontend.js.latest.201802090] https://web.address.nl/frontend_latest/frontend-ebcb41952b21503c6a09065b084a638d.html:85:81190 Uncaught TypeError: window.google.visualization.Timeline is not a constructor
```
Element inspector in Chrome shows this error:
https://i.imgur.com/HuY6Sox.png

I've just upgraded to 0.63.3 and the issue persists. I believe it started on 0.62, but might as well be 0.61.

At first I thought that ctrl+f5 fixed the issue, because it popped up the data, but I was just lucky.
So easily said: sometimes when you press ctrl+f5 and wait long enough, the data shows up.
Also tried different databases: mysql and the default sqlite.

**Comment by balloob** [comment]
It's the Google charts that we used to use. They have been removed for 64.

**Comment by f0nt4** [comment]
Dankjewel Paul :)
