### ISSUE TITLE
Bug: Rollershutter arrows disabled reversed test

### ISSUE THREAD

**Issue by Lionel642** [home-assistant/home-assistant-polymer#92]
In src/state-summary/state-card-rollershutter.html

line 28 should be:
          disabled='[[computeIsFullyOpen(stateObj)]]'></paper-icon-button>
which reads as "The up button is disabled when fully open"

 and line 31:
          disabled='[[computeIsFullyClosed(stateObj)]]'></paper-icon-button>
which reads as "The down button is disabled when fully closed".

**Comment by MartinHjelmare** [comment]
In home assistant as it currently stands the rollershutter is fully closed when it is at its highest position. Thus, it can't move more up when it is fully closed.

**Comment by Lionel642** [comment]
ok, then this should be configurable (even if I don't see any case where the roller shutter goes up to close and down to open).

In my case : when I press the down arrow button, the roller shutter goes down and when it reaches its lowest position and is fullly closed (value of 0), then in the web interface it is the up arrow that gets disabled (and reverse when going up and getting fully opened). 

To me this looks like a bug, I can't find in Google Image any case of a roller shutter that goes up to close!

**Comment by MartinHjelmare** [comment]
Home assistant is not redefining how a rollershutter works. It's just a matter of how you define the states open and closed. Home assistant currently sees the rollershutter as closed when the shutter is "inside" the device, ie when you can see through the space that the shutter can cover.

This topic has been discussed a lot, cause many people think it's confusing, and there's an ongoing, but currently closed, PR to revamp both the rollershutter and garage door funtionality and combine them into a cover component.

See:
https://github.com/home-assistant/home-assistant-polymer/pull/54
https://github.com/home-assistant/home-assistant/issues/1949
https://github.com/home-assistant/home-assistant/pull/2392

**Comment by justweb1** [comment]
Rollershutter has been deprecated in favor of the Cover component.
