### ISSUE TITLE
Add IOS Navigation Gestures

### ISSUE THREAD

**Issue by NovapaX** [home-assistant/home-assistant-polymer#931]
In iOS safari:
- Swipe from the edge of the screen is the back-gesture. So it does not work to open the menu.
- Need scroll all the way to the top of the page to 'uncondense' the header to show the menu button.

When adding hass as a web-app to the homescreen on iOS:
- Swipe to open the menu works, but the back-gesture is gone and no navigation buttons are displayed. So the only way to close the more-info is to reach all the way up.

**Comment by balloob** [comment]
If you have multiple views, you can tap the current tab to scroll to the top.

**Comment by balloob** [comment]
I also thought that iOS is very heavy on having close buttons on the top of the screen?

**Comment by NovapaX** [comment]
Yes, but therefore it is also quite heavy on the gestures.
But maybe the last point is the 'worst'. (closing the more-info is a frequent action), and without the back gesture or a dismiss or back button at the bottom it is a far reach.

Will do some research, but as this is pretty low priority I'll probably revisit this once iOS 11.3 comes out and do an optimization to PWA and webapp-manifest... (not planning on doing testing and optimization twice in a short period ;)

**Comment by balloob** [comment]
Actually, I've included a "back" hack so that you can swipe from the left to go back in the browser to close the more info. That's why the Android back button works 👍

**Comment by NovapaX** [comment]
yes, I know... But the navigation gestures do not work when it is added as a webapp in 'standalone' mode (so without the safari interface elements)
