### ISSUE TITLE
History graph card "full screen" button does nothing

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/home-assistant-polymer#935]
The history graph cards have a button that looks like it's supposed to do something like expand the graph to full screen. Clicking this button on desktop (haven't checked on mobile *yet*) chrome 64.0.3282 doesn't do anything and no error or warnings are logged inside the javascript console.

<img width="484" alt="screen shot 2018-02-26 at 21 39 16" src="https://user-images.githubusercontent.com/6833237/36694271-1e435b28-1b3e-11e8-8165-53203f434627.png">

**Expected:** The button does *something* or the button is removed.

**Home Assistant Version:** 0.64.0 + dev build

(Not too related, but the history graph cards + history panel both show "No state history found" while they're still loading; I would expect a spinner or something else there)

<img width="343" alt="screen shot 2018-02-26 at 21 45 11" src="https://user-images.githubusercontent.com/6833237/36694376-79f00e76-1b3e-11e8-9ac0-d744c4fae0ac.png">

**Comment by c727** [comment]
the button resets zoom/pan

**Comment by OttoWinter** [comment]
Ohhhh! Sorry about that; I have to say though that the "zoom out map" icon seems less than ideal to me (the same of the icon is semantically correct for this application, but as a user I would have expected the button to do another thing)

**Comment by c727** [comment]
yes, balloob also suggested to hide the icon in default state

**Comment by fanthos** [comment]
Seems that MDI doesn't have something like 'reset'. Should the button replaced by Emoji 🔄︎🔄️ 1F504 for now?

**Comment by c727** [comment]
What about `image-filter-center-focus`?

**Comment by fanthos** [comment]
seems better

**Comment by c727** [comment]
Feel free to open a PR. I don't like the emoji as it looks different on every OS

**Comment by fanthos** [comment]
I found some other icons with arrow like `replay`, `sync` `backup-restore`.
Which one is better and less confusing in this case?

**Comment by balloob** [comment]
Sync can be confusing because it looks like refresh. backup-restore is nice, so is restart.

What about arrow-expand-horizontal?  ![image](https://user-images.githubusercontent.com/1444314/36767736-a4a5ee08-1bf0-11e8-8dd4-4dc7699ceafd.png)

**Comment by c727** [comment]
`backup-restore` is "ok" but I would prefer one of the `focus` icons

**Comment by balloob** [comment]
Oh, I like focus too.
