### ISSUE TITLE
Locale based time formatting for Chart.js graphs 

### ISSUE THREAD

**Issue by mcspr** [home-assistant/home-assistant-polymer#938]
New Chart.js graphs are no longer using 24 hour style for ru-RU locale as google charts did.
![default](https://user-images.githubusercontent.com/132763/36707245-805689bc-1b7e-11e8-9699-c840a8d4f014.png)
![default](https://user-images.githubusercontent.com/132763/36708433-0f918b22-1b84-11e8-844c-cf0f18f1bd11.png)

At least for tooltip, I noticed that it is using `moment.format` with locale based output. But there are no locales! Maybe this has something to do with packaging? (include `moment-with-locales.js` instead of `moment.js`)
![default](https://user-images.githubusercontent.com/132763/36707532-bde33d2e-1b7f-11e8-8165-9cbb74735e6e.png)
https://github.com/home-assistant/home-assistant-polymer/blob/0ab240c678260e5ec9924407440415e3679f282f/src/components/entity/ha-chart-base.html#L202-L208

Same format spec used inside timeline chart library:
https://github.com/fanthos/chartjs-chart-timeline/blob/82215e441b379c2776f9ab5443db849fc5ffe0bd/timeline.js#L446-L449

**Edit**: referenced chartjs-chart-timeline

**Comment by balloob** [comment]
Moment with locales is too big to include. We should instead use date formatters in hassUtil.

**Comment by matejdro** [comment]
Charts are still displaying AM / PM. Has this regressed?
