### ISSUE TITLE
Add `crossorigin="use-credentials"` to fetch `manifest.json` with cookies

### ISSUE THREAD

**Issue by manutenfruits** [home-assistant/home-assistant-polymer#940]
My setup consists of a server in a DMZ that handles authentication with OAuth, and sets a cookie. Once this cookie is found, requests are proxied to the server that runs hass. Everything runs fine, except when chrome tries to fetch the `manifest.json` it doesn't send the cookie, and thus gets an error.

The solution is to add the following attribute to the `<link>` tag:
`<link rel="manifest" href="/manifest.json" crossorigin="use-credentials">`

Documented here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

I edited manually the compiled html in my setup and it worked fine. 

Thanks!

**Comment by NovapaX** [comment]
This looks fine to me, but I'd like @balloob to chime in and approve before I make the effort of creating PR.

**Comment by balloob** [comment]
Fine with me.

**Comment by manutenfruits** [comment]
Thanks everyone!

**Comment by HolgerJeromin** [comment]
Why is `crossorigin` needed for a relative url? (having the same behaviour in my app).
Is this a bug in the browsers (chrome in my point)?
