### ISSUE TITLE
Zwave Panel: Node Config Options only shows default value

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/home-assistant-polymer#959]
I'm not completely sure if this is a frontend or backend issue (or combination).

On the Zwave panel when you pull up a node to configure the values, it is only showing the default settings, as opposed to the current device settings. This is confusing for new users and prevents you from seeing what the current settings are.

For example, on a couple of my Multisensors there's a Temperature Reporting Unit setting. I changed it to Fahrenheit, and the sensor is reporting temperature in Farenheit, yet the Node config options shows the default Celsius when you pull it up.

**Comment by mf-social** [comment]
Oooooh - I just went on to mine to check if I'm getting the same (I know it was working fine last time I actually used it, maybe a couple of weeks ago) but I can't actually access the dropdown boxes to even look.  The little animation appears in the box itself to acknowledge the click on the arrow, but the dropdown never appears.

**Comment by cgarwood** [comment]
This seems to be working at the moment, going to close this.
