### ISSUE TITLE
Fix climate controls for auto mode

### ISSUE THREAD

**Issue by justweb1** [home-assistant/home-assistant-polymer#97]
Climate controls set in auto mode need to set 2 values, a value to start cooling and a value to start heating. Currently the slider sets a target temperature and pads it with 2 values for heating and cooling. 

Instead, the ```<paper-interval-slider>``` could be implemented to allow the users to set their own min/max values for heating and cooling.

http://ewgenius.github.io/paper-interval-slider/components/paper-interval-slider/

**Comment by arsaboo** [comment]
The Auto mode only means that we don't manually have to change the heating/cooling modes and that the thermostat takes care of it. However, even the Auto mode (like any other mode), requires setting up both the heating and cooling setpoints. Thus, I am not sure if we need the two value slider (even in the auto mode). 

This obviously assumes that you have done the basic scheduling inside the thermostat and only use the HA controls for minor adjustments (which should be the case for most users).

**Comment by justweb1** [comment]
Pull request submitted: https://github.com/home-assistant/home-assistant-polymer/pull/99
