### ISSUE TITLE
History loading icon missing after graph update

### ISSUE THREAD

**Issue by bratanon** [home-assistant/home-assistant-polymer#975]
Home Assistant release (hass --version):
0.64.3

Component/platform:
History

Description of problem:
The spinner/loading icon is missing from the history page.
At first the text "No state history found." is present, then after a while (depending on how much history you have) the graphs will show. In the meantime, there is nothing indicating that the history is loading.

Expected:
An spinner/throbber/loading icon when the history is loaded, just like the Logbook work.

**Comment by NovapaX** [comment]
I noticed the same 'issue'
I'll try to come up with something nice. Don't hold your breath though ;)

**Comment by NovapaX** [comment]
In the next release there will be a textual loading message, please report back how that works for you when it is released so we can close this issue.

**Comment by balloob** [comment]
Let's close it and we can re-open if it still occurs.
