### ISSUE TITLE
Wanting to add new language

### ISSUE THREAD

**Issue by petrepa** [home-assistant/home-assistant-polymer#983]
English Name: Norwegian (nynorsk)
Native Name: Norsk (nynorsk)

Only support for norwegian (bokmål) by now!

**Comment by c727** [comment]
ready, make sure you also join the group for backend translations: https://lokalise.co/signup/130246255a974bd3b5e8a1.51616605/all/

**Comment by petrepa** [comment]
Great! Is it possible to change the other "Norwegian" name to "Norwegian (bokmål)"?

**Comment by c727** [comment]
I don't want to change the name as bokmål has a different ISO code. Also 85-90% use bokmål
